/******************************************************************************/
/*                                                                            */
/* !Layer           : SRV                                                     */
/*                                                                            */
/* !Component       : FAULT                                                   */
/* !Description     :                                                         */
/*                                                                            */
/* !File            : FAULT_FF.c                                              */
/*                                                                            */
/* !Scope           : Public                                                  */
/*                                                                            */
/* !Target          : All                                                     */
/*                                                                            */
/* !Vendor          : invt                                                    */
/*                                                                            */
/* Coding language  : C                                                       */
/*                                                                            */
/* COPYRIGHT 2011 invt                                                        */
/* all rights reserved                                                        */
/*                                                                            */
/******************************************************************************/
/* SVN Information                                                           */
/* $Archive:                                                                 $*/
/* $Revision::            $$Author::                  $$Date::               $*/
/******************************************************************************/
/** 06/16/25, 18:54:33: generated by Genecode v2.6.0.0                               */
/******************************************************************************/

#ifndef FAULT_FF_H
#define FAULT_FF_H

#include "Std_Types.h"
#include "FAULT_FF_Drv.h"


/******************************************************************************/
/* PROTOTYPE DECLARATION                                                      */
/******************************************************************************/

#define FAULT_FF_FREEZEFRAME_LENGTH 350
typedef union
{
   uint32 au32Data[87]; /* !Comment: alignment on 4-byte boundary */
   uint8  au8Data[350];
   struct
   {
      uint16 Item_0xDF20;
      uint16 Item_0xDF21;
      uint16 Item_0xDF23;
      uint8 Item_0xDF29;
      uint8 Item_0xDF2A;
      uint8 Item_0xDF2C;
      uint8 Item_0x0D01;
      uint16 Item_0x0D02;
      uint16 Item_0x0D03;
      uint16 Item_0x0D04;
      uint8 Item_0x0D05;
      uint16 Item_0x0D06;
      uint8 Item_0x0D07;
      uint16 Item_0x0D08;
      uint8 Item_0x0D09;
      uint8 Item_0x0D0A;
      uint8 Item_0x0D0B;
      uint16 Item_0x0D0C;
      uint16 Item_0x0D0C_1;
      uint16 Item_0x0D0C_2;
      uint16 Item_0x0D0D;
      uint16 Item_0x0D0E;
      uint16 Item_0x0D0F;
      uint16 Item_0x0D13;
      uint16 Item_0x0D14;
      uint16 Item_0x0D15;
      uint16 Item_0x0D16;
      uint16 Item_0x0D17;
      uint16 Item_0x0D18;
      uint16 Item_0x0D19;
      uint16 Item_0x0D1A;
      uint16 Item_0x0D1B;
      uint16 Item_0x0D1C;
      uint16 Item_0x0D1D;
      uint16 Item_0x0D1E;
      uint16 Item_0x0D1F;
      uint16 Item_0x0D20;
      uint16 Item_0x0D21;
      uint16 Item_0x0D22;
      uint16 Item_0x0D23;
      uint16 Item_0x0D24;
      uint16 Item_0x0D25;
      uint16 Item_0x0D26;
      uint16 Item_0x0D27;
      uint16 Item_0x0D28;
      uint16 Item_0x0D29;
      uint8 Item_0x1D01;
      uint16 Item_0x1D02;
      uint16 Item_0x1D03;
      uint16 Item_0x1D04;
      uint8 Item_0x1D05;
      uint16 Item_0x1D06;
      uint8 Item_0x1D07;
      uint16 Item_0x1D08;
      uint8 Item_0x1D09;
      uint8 Item_0x1D0A;
      uint8 Item_0x1D0B;
      uint16 Item_0x1D0C;
      uint16 Item_0x1D0C_1;
      uint16 Item_0x1D0C_2;
      uint16 Item_0x1D0D;
      uint16 Item_0x1D0E;
      uint16 Item_0x1D0F;
      uint16 Item_0x1D13;
      uint16 Item_0x1D14;
      uint16 Item_0x1D15;
      uint16 Item_0x1D16;
      uint16 Item_0x1D17;
      uint16 Item_0x1D18;
      uint16 Item_0x1D19;
      uint16 Item_0x1D1A;
      uint16 Item_0x1D1B;
      uint16 Item_0x1D1C;
      uint16 Item_0x1D1D;
      uint16 Item_0x1D1E;
      uint16 Item_0x1D1F;
      uint16 Item_0x1D20;
      uint16 Item_0x1D21;
      uint16 Item_0x1D22;
      uint16 Item_0x1D23;
      uint16 Item_0x1D24;
      uint16 Item_0x1D25;
      uint16 Item_0x1D26;
      uint16 Item_0x1D27;
      uint16 Item_0x1D28;
      uint16 Item_0x1D29;
      uint16 Item_0x2D02;
      uint16 Item_0x2D03;
      uint16 Item_0x2D04;
      uint8 Item_0x2D05;
      uint16 Item_0x2D06;
      uint8 Item_0x2D07;
      uint16 Item_0x2D08;
      uint16 Item_0x2D0E;
      uint16 Item_0x2D13;
      uint16 Item_0x2D14;
      uint16 Item_0x2D15;
      uint16 Item_0x2D1C;
      uint16 Item_0x2D1D;
      uint16 Item_0x2D1E;
      uint16 Item_0x2D1F;
      uint16 Item_0x2D20;
      uint16 Item_0x2D21;
      uint16 Item_0x2D22;
      uint16 Item_0x2D25;
      uint16 Item_0x2D26;
      uint16 Item_0x3D02;
      uint16 Item_0x3D03;
      uint16 Item_0x3D04;
      uint8 Item_0x3D05;
      uint16 Item_0x3D06;
      uint8 Item_0x3D07;
      uint16 Item_0x3D08;
      uint16 Item_0x3D0E;
      uint16 Item_0x3D13;
      uint16 Item_0x3D14;
      uint16 Item_0x3D15;
      uint16 Item_0x3D1C;
      uint16 Item_0x3D1D;
      uint16 Item_0x3D1E;
      uint16 Item_0x3D1F;
      uint16 Item_0x3D20;
      uint16 Item_0x3D21;
      uint16 Item_0x3D22;
      uint16 Item_0x3D25;
      uint16 Item_0x3D26;
      uint16 Item_0x4D27;
      uint16 Item_0x4D28;
      uint16 Item_0x4D29;
      uint16 Item_0x4D2A;
      uint16 Item_0x4D2B;
      uint16 Item_0x4D2C;
      uint16 Item_0x4D2D;
      uint16 Item_0x4D2E;
      uint16 Item_0x4D2F;
      uint16 Item_0x4D30;
      uint16 Item_0x4D31;
      uint16 Item_0x4D32;
      uint8 Item_0x4D33;
      uint16 Item_0x4D34;
      uint8 Item_0x4D35;
      uint16 Item_0x4D36;
      uint8 Item_0x4D37;
      uint16 Item_0x4D38;
      uint8 Item_0x4D39;
      uint16 Item_0x4D3A;
      uint8 Item_0x4D3B;
      uint16 Item_0x4D3C;
      uint8 Item_0x4D3D;
   }Item;
} FAULT_FF_FF1_Typ;



/******************************************************************************/
/* DEFINE                                                                     */
/******************************************************************************/
#define FAULT_FF1_Item_0xDF20_API_COEF_A (1)
#define FAULT_FF1_Item_0xDF20_API_COEF_B (0)
#define FAULT_FF1_Item_0xDF20_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0xDF20_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0xDF21_API_COEF_A (1)
#define FAULT_FF1_Item_0xDF21_API_COEF_B (0)
#define FAULT_FF1_Item_0xDF21_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0xDF21_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0xDF23_API_COEF_A (1)
#define FAULT_FF1_Item_0xDF23_API_COEF_B (0)
#define FAULT_FF1_Item_0xDF23_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0xDF23_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0xDF29_API_COEF_A (1)
#define FAULT_FF1_Item_0xDF29_API_COEF_B (0)
#define FAULT_FF1_Item_0xDF29_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0xDF29_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0xDF2A_API_COEF_A (1)
#define FAULT_FF1_Item_0xDF2A_API_COEF_B (0)
#define FAULT_FF1_Item_0xDF2A_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0xDF2A_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0xDF2C_API_COEF_A (1)
#define FAULT_FF1_Item_0xDF2C_API_COEF_B (0)
#define FAULT_FF1_Item_0xDF2C_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0xDF2C_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x0D01_API_COEF_A (1)
#define FAULT_FF1_Item_0x0D01_API_COEF_B (0)
#define FAULT_FF1_Item_0x0D01_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x0D01_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x0D02_API_COEF_A (1)
#define FAULT_FF1_Item_0x0D02_API_COEF_B (0)
#define FAULT_FF1_Item_0x0D02_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x0D02_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x0D03_API_COEF_A (1)
#define FAULT_FF1_Item_0x0D03_API_COEF_B (0)
#define FAULT_FF1_Item_0x0D03_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x0D03_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x0D04_API_COEF_A (1)
#define FAULT_FF1_Item_0x0D04_API_COEF_B (0)
#define FAULT_FF1_Item_0x0D04_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x0D04_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x0D05_API_COEF_A (1)
#define FAULT_FF1_Item_0x0D05_API_COEF_B (0)
#define FAULT_FF1_Item_0x0D05_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x0D05_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x0D06_API_COEF_A (1)
#define FAULT_FF1_Item_0x0D06_API_COEF_B (0)
#define FAULT_FF1_Item_0x0D06_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x0D06_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x0D07_API_COEF_A (1)
#define FAULT_FF1_Item_0x0D07_API_COEF_B (0)
#define FAULT_FF1_Item_0x0D07_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x0D07_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x0D08_API_COEF_A (1)
#define FAULT_FF1_Item_0x0D08_API_COEF_B (0)
#define FAULT_FF1_Item_0x0D08_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x0D08_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x0D09_API_COEF_A (1)
#define FAULT_FF1_Item_0x0D09_API_COEF_B (0)
#define FAULT_FF1_Item_0x0D09_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x0D09_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x0D0A_API_COEF_A (1)
#define FAULT_FF1_Item_0x0D0A_API_COEF_B (0)
#define FAULT_FF1_Item_0x0D0A_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x0D0A_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x0D0B_API_COEF_A (1)
#define FAULT_FF1_Item_0x0D0B_API_COEF_B (0)
#define FAULT_FF1_Item_0x0D0B_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x0D0B_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x0D0C_API_COEF_A (1)
#define FAULT_FF1_Item_0x0D0C_API_COEF_B (0)
#define FAULT_FF1_Item_0x0D0C_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x0D0C_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x0D0C_1_API_COEF_A (1)
#define FAULT_FF1_Item_0x0D0C_1_API_COEF_B (0)
#define FAULT_FF1_Item_0x0D0C_1_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x0D0C_1_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x0D0C_2_API_COEF_A (1)
#define FAULT_FF1_Item_0x0D0C_2_API_COEF_B (0)
#define FAULT_FF1_Item_0x0D0C_2_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x0D0C_2_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x0D0D_API_COEF_A (1)
#define FAULT_FF1_Item_0x0D0D_API_COEF_B (0)
#define FAULT_FF1_Item_0x0D0D_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x0D0D_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x0D0E_API_COEF_A (1)
#define FAULT_FF1_Item_0x0D0E_API_COEF_B (0)
#define FAULT_FF1_Item_0x0D0E_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x0D0E_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x0D0F_API_COEF_A (1)
#define FAULT_FF1_Item_0x0D0F_API_COEF_B (0)
#define FAULT_FF1_Item_0x0D0F_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x0D0F_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x0D13_API_COEF_A (1)
#define FAULT_FF1_Item_0x0D13_API_COEF_B (0)
#define FAULT_FF1_Item_0x0D13_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x0D13_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x0D14_API_COEF_A (1)
#define FAULT_FF1_Item_0x0D14_API_COEF_B (0)
#define FAULT_FF1_Item_0x0D14_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x0D14_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x0D15_API_COEF_A (1)
#define FAULT_FF1_Item_0x0D15_API_COEF_B (0)
#define FAULT_FF1_Item_0x0D15_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x0D15_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x0D16_API_COEF_A (1)
#define FAULT_FF1_Item_0x0D16_API_COEF_B (0)
#define FAULT_FF1_Item_0x0D16_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x0D16_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x0D17_API_COEF_A (1)
#define FAULT_FF1_Item_0x0D17_API_COEF_B (0)
#define FAULT_FF1_Item_0x0D17_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x0D17_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x0D18_API_COEF_A (1)
#define FAULT_FF1_Item_0x0D18_API_COEF_B (0)
#define FAULT_FF1_Item_0x0D18_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x0D18_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x0D19_API_COEF_A (1)
#define FAULT_FF1_Item_0x0D19_API_COEF_B (0)
#define FAULT_FF1_Item_0x0D19_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x0D19_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x0D1A_API_COEF_A (1)
#define FAULT_FF1_Item_0x0D1A_API_COEF_B (0)
#define FAULT_FF1_Item_0x0D1A_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x0D1A_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x0D1B_API_COEF_A (1)
#define FAULT_FF1_Item_0x0D1B_API_COEF_B (0)
#define FAULT_FF1_Item_0x0D1B_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x0D1B_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x0D1C_API_COEF_A (1)
#define FAULT_FF1_Item_0x0D1C_API_COEF_B (0)
#define FAULT_FF1_Item_0x0D1C_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x0D1C_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x0D1D_API_COEF_A (1)
#define FAULT_FF1_Item_0x0D1D_API_COEF_B (0)
#define FAULT_FF1_Item_0x0D1D_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x0D1D_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x0D1E_API_COEF_A (1)
#define FAULT_FF1_Item_0x0D1E_API_COEF_B (0)
#define FAULT_FF1_Item_0x0D1E_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x0D1E_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x0D1F_API_COEF_A (1)
#define FAULT_FF1_Item_0x0D1F_API_COEF_B (0)
#define FAULT_FF1_Item_0x0D1F_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x0D1F_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x0D20_API_COEF_A (1)
#define FAULT_FF1_Item_0x0D20_API_COEF_B (0)
#define FAULT_FF1_Item_0x0D20_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x0D20_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x0D21_API_COEF_A (1)
#define FAULT_FF1_Item_0x0D21_API_COEF_B (0)
#define FAULT_FF1_Item_0x0D21_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x0D21_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x0D22_API_COEF_A (1)
#define FAULT_FF1_Item_0x0D22_API_COEF_B (0)
#define FAULT_FF1_Item_0x0D22_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x0D22_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x0D23_API_COEF_A (1)
#define FAULT_FF1_Item_0x0D23_API_COEF_B (0)
#define FAULT_FF1_Item_0x0D23_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x0D23_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x0D24_API_COEF_A (1)
#define FAULT_FF1_Item_0x0D24_API_COEF_B (0)
#define FAULT_FF1_Item_0x0D24_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x0D24_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x0D25_API_COEF_A (1)
#define FAULT_FF1_Item_0x0D25_API_COEF_B (0)
#define FAULT_FF1_Item_0x0D25_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x0D25_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x0D26_API_COEF_A (1)
#define FAULT_FF1_Item_0x0D26_API_COEF_B (0)
#define FAULT_FF1_Item_0x0D26_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x0D26_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x0D27_API_COEF_A (1)
#define FAULT_FF1_Item_0x0D27_API_COEF_B (0)
#define FAULT_FF1_Item_0x0D27_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x0D27_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x0D28_API_COEF_A (1)
#define FAULT_FF1_Item_0x0D28_API_COEF_B (0)
#define FAULT_FF1_Item_0x0D28_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x0D28_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x0D29_API_COEF_A (1)
#define FAULT_FF1_Item_0x0D29_API_COEF_B (0)
#define FAULT_FF1_Item_0x0D29_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x0D29_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x1D01_API_COEF_A (1)
#define FAULT_FF1_Item_0x1D01_API_COEF_B (0)
#define FAULT_FF1_Item_0x1D01_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x1D01_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x1D02_API_COEF_A (1)
#define FAULT_FF1_Item_0x1D02_API_COEF_B (0)
#define FAULT_FF1_Item_0x1D02_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x1D02_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x1D03_API_COEF_A (1)
#define FAULT_FF1_Item_0x1D03_API_COEF_B (0)
#define FAULT_FF1_Item_0x1D03_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x1D03_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x1D04_API_COEF_A (1)
#define FAULT_FF1_Item_0x1D04_API_COEF_B (0)
#define FAULT_FF1_Item_0x1D04_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x1D04_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x1D05_API_COEF_A (1)
#define FAULT_FF1_Item_0x1D05_API_COEF_B (0)
#define FAULT_FF1_Item_0x1D05_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x1D05_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x1D06_API_COEF_A (1)
#define FAULT_FF1_Item_0x1D06_API_COEF_B (0)
#define FAULT_FF1_Item_0x1D06_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x1D06_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x1D07_API_COEF_A (1)
#define FAULT_FF1_Item_0x1D07_API_COEF_B (0)
#define FAULT_FF1_Item_0x1D07_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x1D07_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x1D08_API_COEF_A (1)
#define FAULT_FF1_Item_0x1D08_API_COEF_B (0)
#define FAULT_FF1_Item_0x1D08_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x1D08_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x1D09_API_COEF_A (1)
#define FAULT_FF1_Item_0x1D09_API_COEF_B (0)
#define FAULT_FF1_Item_0x1D09_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x1D09_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x1D0A_API_COEF_A (1)
#define FAULT_FF1_Item_0x1D0A_API_COEF_B (0)
#define FAULT_FF1_Item_0x1D0A_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x1D0A_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x1D0B_API_COEF_A (1)
#define FAULT_FF1_Item_0x1D0B_API_COEF_B (0)
#define FAULT_FF1_Item_0x1D0B_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x1D0B_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x1D0C_API_COEF_A (1)
#define FAULT_FF1_Item_0x1D0C_API_COEF_B (0)
#define FAULT_FF1_Item_0x1D0C_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x1D0C_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x1D0C_1_API_COEF_A (1)
#define FAULT_FF1_Item_0x1D0C_1_API_COEF_B (0)
#define FAULT_FF1_Item_0x1D0C_1_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x1D0C_1_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x1D0C_2_API_COEF_A (1)
#define FAULT_FF1_Item_0x1D0C_2_API_COEF_B (0)
#define FAULT_FF1_Item_0x1D0C_2_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x1D0C_2_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x1D0D_API_COEF_A (1)
#define FAULT_FF1_Item_0x1D0D_API_COEF_B (0)
#define FAULT_FF1_Item_0x1D0D_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x1D0D_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x1D0E_API_COEF_A (1)
#define FAULT_FF1_Item_0x1D0E_API_COEF_B (0)
#define FAULT_FF1_Item_0x1D0E_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x1D0E_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x1D0F_API_COEF_A (1)
#define FAULT_FF1_Item_0x1D0F_API_COEF_B (0)
#define FAULT_FF1_Item_0x1D0F_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x1D0F_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x1D13_API_COEF_A (1)
#define FAULT_FF1_Item_0x1D13_API_COEF_B (0)
#define FAULT_FF1_Item_0x1D13_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x1D13_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x1D14_API_COEF_A (1)
#define FAULT_FF1_Item_0x1D14_API_COEF_B (0)
#define FAULT_FF1_Item_0x1D14_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x1D14_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x1D15_API_COEF_A (1)
#define FAULT_FF1_Item_0x1D15_API_COEF_B (0)
#define FAULT_FF1_Item_0x1D15_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x1D15_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x1D16_API_COEF_A (1)
#define FAULT_FF1_Item_0x1D16_API_COEF_B (0)
#define FAULT_FF1_Item_0x1D16_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x1D16_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x1D17_API_COEF_A (1)
#define FAULT_FF1_Item_0x1D17_API_COEF_B (0)
#define FAULT_FF1_Item_0x1D17_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x1D17_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x1D18_API_COEF_A (1)
#define FAULT_FF1_Item_0x1D18_API_COEF_B (0)
#define FAULT_FF1_Item_0x1D18_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x1D18_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x1D19_API_COEF_A (1)
#define FAULT_FF1_Item_0x1D19_API_COEF_B (0)
#define FAULT_FF1_Item_0x1D19_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x1D19_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x1D1A_API_COEF_A (1)
#define FAULT_FF1_Item_0x1D1A_API_COEF_B (0)
#define FAULT_FF1_Item_0x1D1A_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x1D1A_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x1D1B_API_COEF_A (1)
#define FAULT_FF1_Item_0x1D1B_API_COEF_B (0)
#define FAULT_FF1_Item_0x1D1B_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x1D1B_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x1D1C_API_COEF_A (1)
#define FAULT_FF1_Item_0x1D1C_API_COEF_B (0)
#define FAULT_FF1_Item_0x1D1C_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x1D1C_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x1D1D_API_COEF_A (1)
#define FAULT_FF1_Item_0x1D1D_API_COEF_B (0)
#define FAULT_FF1_Item_0x1D1D_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x1D1D_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x1D1E_API_COEF_A (1)
#define FAULT_FF1_Item_0x1D1E_API_COEF_B (0)
#define FAULT_FF1_Item_0x1D1E_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x1D1E_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x1D1F_API_COEF_A (1)
#define FAULT_FF1_Item_0x1D1F_API_COEF_B (0)
#define FAULT_FF1_Item_0x1D1F_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x1D1F_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x1D20_API_COEF_A (1)
#define FAULT_FF1_Item_0x1D20_API_COEF_B (0)
#define FAULT_FF1_Item_0x1D20_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x1D20_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x1D21_API_COEF_A (1)
#define FAULT_FF1_Item_0x1D21_API_COEF_B (0)
#define FAULT_FF1_Item_0x1D21_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x1D21_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x1D22_API_COEF_A (1)
#define FAULT_FF1_Item_0x1D22_API_COEF_B (0)
#define FAULT_FF1_Item_0x1D22_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x1D22_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x1D23_API_COEF_A (1)
#define FAULT_FF1_Item_0x1D23_API_COEF_B (0)
#define FAULT_FF1_Item_0x1D23_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x1D23_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x1D24_API_COEF_A (1)
#define FAULT_FF1_Item_0x1D24_API_COEF_B (0)
#define FAULT_FF1_Item_0x1D24_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x1D24_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x1D25_API_COEF_A (1)
#define FAULT_FF1_Item_0x1D25_API_COEF_B (0)
#define FAULT_FF1_Item_0x1D25_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x1D25_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x1D26_API_COEF_A (1)
#define FAULT_FF1_Item_0x1D26_API_COEF_B (0)
#define FAULT_FF1_Item_0x1D26_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x1D26_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x1D27_API_COEF_A (1)
#define FAULT_FF1_Item_0x1D27_API_COEF_B (0)
#define FAULT_FF1_Item_0x1D27_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x1D27_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x1D28_API_COEF_A (1)
#define FAULT_FF1_Item_0x1D28_API_COEF_B (0)
#define FAULT_FF1_Item_0x1D28_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x1D28_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x1D29_API_COEF_A (1)
#define FAULT_FF1_Item_0x1D29_API_COEF_B (0)
#define FAULT_FF1_Item_0x1D29_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x1D29_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x2D02_API_COEF_A (1)
#define FAULT_FF1_Item_0x2D02_API_COEF_B (0)
#define FAULT_FF1_Item_0x2D02_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x2D02_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x2D03_API_COEF_A (1)
#define FAULT_FF1_Item_0x2D03_API_COEF_B (0)
#define FAULT_FF1_Item_0x2D03_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x2D03_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x2D04_API_COEF_A (1)
#define FAULT_FF1_Item_0x2D04_API_COEF_B (0)
#define FAULT_FF1_Item_0x2D04_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x2D04_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x2D05_API_COEF_A (1)
#define FAULT_FF1_Item_0x2D05_API_COEF_B (0)
#define FAULT_FF1_Item_0x2D05_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x2D05_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x2D06_API_COEF_A (1)
#define FAULT_FF1_Item_0x2D06_API_COEF_B (0)
#define FAULT_FF1_Item_0x2D06_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x2D06_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x2D07_API_COEF_A (1)
#define FAULT_FF1_Item_0x2D07_API_COEF_B (0)
#define FAULT_FF1_Item_0x2D07_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x2D07_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x2D08_API_COEF_A (1)
#define FAULT_FF1_Item_0x2D08_API_COEF_B (0)
#define FAULT_FF1_Item_0x2D08_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x2D08_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x2D0E_API_COEF_A (1)
#define FAULT_FF1_Item_0x2D0E_API_COEF_B (0)
#define FAULT_FF1_Item_0x2D0E_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x2D0E_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x2D13_API_COEF_A (1)
#define FAULT_FF1_Item_0x2D13_API_COEF_B (0)
#define FAULT_FF1_Item_0x2D13_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x2D13_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x2D14_API_COEF_A (1)
#define FAULT_FF1_Item_0x2D14_API_COEF_B (0)
#define FAULT_FF1_Item_0x2D14_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x2D14_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x2D15_API_COEF_A (1)
#define FAULT_FF1_Item_0x2D15_API_COEF_B (0)
#define FAULT_FF1_Item_0x2D15_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x2D15_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x2D1C_API_COEF_A (1)
#define FAULT_FF1_Item_0x2D1C_API_COEF_B (0)
#define FAULT_FF1_Item_0x2D1C_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x2D1C_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x2D1D_API_COEF_A (1)
#define FAULT_FF1_Item_0x2D1D_API_COEF_B (0)
#define FAULT_FF1_Item_0x2D1D_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x2D1D_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x2D1E_API_COEF_A (1)
#define FAULT_FF1_Item_0x2D1E_API_COEF_B (0)
#define FAULT_FF1_Item_0x2D1E_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x2D1E_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x2D1F_API_COEF_A (1)
#define FAULT_FF1_Item_0x2D1F_API_COEF_B (0)
#define FAULT_FF1_Item_0x2D1F_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x2D1F_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x2D20_API_COEF_A (1)
#define FAULT_FF1_Item_0x2D20_API_COEF_B (0)
#define FAULT_FF1_Item_0x2D20_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x2D20_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x2D21_API_COEF_A (1)
#define FAULT_FF1_Item_0x2D21_API_COEF_B (0)
#define FAULT_FF1_Item_0x2D21_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x2D21_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x2D22_API_COEF_A (1)
#define FAULT_FF1_Item_0x2D22_API_COEF_B (0)
#define FAULT_FF1_Item_0x2D22_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x2D22_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x2D25_API_COEF_A (1)
#define FAULT_FF1_Item_0x2D25_API_COEF_B (0)
#define FAULT_FF1_Item_0x2D25_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x2D25_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x2D26_API_COEF_A (1)
#define FAULT_FF1_Item_0x2D26_API_COEF_B (0)
#define FAULT_FF1_Item_0x2D26_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x2D26_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x3D02_API_COEF_A (1)
#define FAULT_FF1_Item_0x3D02_API_COEF_B (0)
#define FAULT_FF1_Item_0x3D02_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x3D02_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x3D03_API_COEF_A (1)
#define FAULT_FF1_Item_0x3D03_API_COEF_B (0)
#define FAULT_FF1_Item_0x3D03_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x3D03_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x3D04_API_COEF_A (1)
#define FAULT_FF1_Item_0x3D04_API_COEF_B (0)
#define FAULT_FF1_Item_0x3D04_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x3D04_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x3D05_API_COEF_A (1)
#define FAULT_FF1_Item_0x3D05_API_COEF_B (0)
#define FAULT_FF1_Item_0x3D05_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x3D05_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x3D06_API_COEF_A (1)
#define FAULT_FF1_Item_0x3D06_API_COEF_B (0)
#define FAULT_FF1_Item_0x3D06_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x3D06_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x3D07_API_COEF_A (1)
#define FAULT_FF1_Item_0x3D07_API_COEF_B (0)
#define FAULT_FF1_Item_0x3D07_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x3D07_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x3D08_API_COEF_A (1)
#define FAULT_FF1_Item_0x3D08_API_COEF_B (0)
#define FAULT_FF1_Item_0x3D08_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x3D08_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x3D0E_API_COEF_A (1)
#define FAULT_FF1_Item_0x3D0E_API_COEF_B (0)
#define FAULT_FF1_Item_0x3D0E_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x3D0E_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x3D13_API_COEF_A (1)
#define FAULT_FF1_Item_0x3D13_API_COEF_B (0)
#define FAULT_FF1_Item_0x3D13_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x3D13_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x3D14_API_COEF_A (1)
#define FAULT_FF1_Item_0x3D14_API_COEF_B (0)
#define FAULT_FF1_Item_0x3D14_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x3D14_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x3D15_API_COEF_A (1)
#define FAULT_FF1_Item_0x3D15_API_COEF_B (0)
#define FAULT_FF1_Item_0x3D15_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x3D15_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x3D1C_API_COEF_A (1)
#define FAULT_FF1_Item_0x3D1C_API_COEF_B (0)
#define FAULT_FF1_Item_0x3D1C_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x3D1C_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x3D1D_API_COEF_A (1)
#define FAULT_FF1_Item_0x3D1D_API_COEF_B (0)
#define FAULT_FF1_Item_0x3D1D_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x3D1D_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x3D1E_API_COEF_A (1)
#define FAULT_FF1_Item_0x3D1E_API_COEF_B (0)
#define FAULT_FF1_Item_0x3D1E_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x3D1E_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x3D1F_API_COEF_A (1)
#define FAULT_FF1_Item_0x3D1F_API_COEF_B (0)
#define FAULT_FF1_Item_0x3D1F_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x3D1F_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x3D20_API_COEF_A (1)
#define FAULT_FF1_Item_0x3D20_API_COEF_B (0)
#define FAULT_FF1_Item_0x3D20_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x3D20_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x3D21_API_COEF_A (1)
#define FAULT_FF1_Item_0x3D21_API_COEF_B (0)
#define FAULT_FF1_Item_0x3D21_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x3D21_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x3D22_API_COEF_A (1)
#define FAULT_FF1_Item_0x3D22_API_COEF_B (0)
#define FAULT_FF1_Item_0x3D22_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x3D22_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x3D25_API_COEF_A (1)
#define FAULT_FF1_Item_0x3D25_API_COEF_B (0)
#define FAULT_FF1_Item_0x3D25_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x3D25_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x3D26_API_COEF_A (1)
#define FAULT_FF1_Item_0x3D26_API_COEF_B (0)
#define FAULT_FF1_Item_0x3D26_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x3D26_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x4D27_API_COEF_A (1)
#define FAULT_FF1_Item_0x4D27_API_COEF_B (0)
#define FAULT_FF1_Item_0x4D27_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x4D27_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x4D28_API_COEF_A (1)
#define FAULT_FF1_Item_0x4D28_API_COEF_B (0)
#define FAULT_FF1_Item_0x4D28_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x4D28_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x4D29_API_COEF_A (1)
#define FAULT_FF1_Item_0x4D29_API_COEF_B (0)
#define FAULT_FF1_Item_0x4D29_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x4D29_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x4D2A_API_COEF_A (1)
#define FAULT_FF1_Item_0x4D2A_API_COEF_B (0)
#define FAULT_FF1_Item_0x4D2A_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x4D2A_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x4D2B_API_COEF_A (1)
#define FAULT_FF1_Item_0x4D2B_API_COEF_B (0)
#define FAULT_FF1_Item_0x4D2B_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x4D2B_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x4D2C_API_COEF_A (1)
#define FAULT_FF1_Item_0x4D2C_API_COEF_B (0)
#define FAULT_FF1_Item_0x4D2C_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x4D2C_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x4D2D_API_COEF_A (1)
#define FAULT_FF1_Item_0x4D2D_API_COEF_B (0)
#define FAULT_FF1_Item_0x4D2D_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x4D2D_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x4D2E_API_COEF_A (1)
#define FAULT_FF1_Item_0x4D2E_API_COEF_B (0)
#define FAULT_FF1_Item_0x4D2E_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x4D2E_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x4D2F_API_COEF_A (1)
#define FAULT_FF1_Item_0x4D2F_API_COEF_B (0)
#define FAULT_FF1_Item_0x4D2F_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x4D2F_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x4D30_API_COEF_A (1)
#define FAULT_FF1_Item_0x4D30_API_COEF_B (0)
#define FAULT_FF1_Item_0x4D30_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x4D30_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x4D31_API_COEF_A (1)
#define FAULT_FF1_Item_0x4D31_API_COEF_B (0)
#define FAULT_FF1_Item_0x4D31_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x4D31_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x4D32_API_COEF_A (1)
#define FAULT_FF1_Item_0x4D32_API_COEF_B (0)
#define FAULT_FF1_Item_0x4D32_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x4D32_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x4D33_API_COEF_A (1)
#define FAULT_FF1_Item_0x4D33_API_COEF_B (0)
#define FAULT_FF1_Item_0x4D33_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x4D33_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x4D34_API_COEF_A (1)
#define FAULT_FF1_Item_0x4D34_API_COEF_B (0)
#define FAULT_FF1_Item_0x4D34_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x4D34_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x4D35_API_COEF_A (1)
#define FAULT_FF1_Item_0x4D35_API_COEF_B (0)
#define FAULT_FF1_Item_0x4D35_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x4D35_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x4D36_API_COEF_A (1)
#define FAULT_FF1_Item_0x4D36_API_COEF_B (0)
#define FAULT_FF1_Item_0x4D36_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x4D36_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x4D37_API_COEF_A (1)
#define FAULT_FF1_Item_0x4D37_API_COEF_B (0)
#define FAULT_FF1_Item_0x4D37_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x4D37_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x4D38_API_COEF_A (1)
#define FAULT_FF1_Item_0x4D38_API_COEF_B (0)
#define FAULT_FF1_Item_0x4D38_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x4D38_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x4D39_API_COEF_A (1)
#define FAULT_FF1_Item_0x4D39_API_COEF_B (0)
#define FAULT_FF1_Item_0x4D39_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x4D39_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x4D3A_API_COEF_A (1)
#define FAULT_FF1_Item_0x4D3A_API_COEF_B (0)
#define FAULT_FF1_Item_0x4D3A_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x4D3A_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x4D3B_API_COEF_A (1)
#define FAULT_FF1_Item_0x4D3B_API_COEF_B (0)
#define FAULT_FF1_Item_0x4D3B_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x4D3B_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x4D3C_API_COEF_A (1)
#define FAULT_FF1_Item_0x4D3C_API_COEF_B (0)
#define FAULT_FF1_Item_0x4D3C_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x4D3C_ITEM_COEF_B (0)
#define FAULT_FF1_Item_0x4D3D_API_COEF_A (1)
#define FAULT_FF1_Item_0x4D3D_API_COEF_B (0)
#define FAULT_FF1_Item_0x4D3D_ITEM_COEF_A (1)
#define FAULT_FF1_Item_0x4D3D_ITEM_COEF_B (0)

/******************************************************************************/
/* DEFINE MACRO FUNCTIONS                                                     */
/******************************************************************************/



/******************************************************************************/
/* DATA DECLARATION                                                           */
/******************************************************************************/

#define FAULT_FF_START_SEC_VAR_UNSPECIFIED
#include "MemMap.h"

extern FAULT_FF_FF1_Typ FAULT_FF_Frame_FF1;

extern boolean FAULT_FF_bFrameLock_FF1;




#define FAULT_FF_STOP_SEC_VAR_UNSPECIFIED
#include "MemMap.h"



/******************************************************************************/
/* FUNCTIONS DECLARATION                                                      */
/******************************************************************************/

#define FAULT_FF_START_SEC_CODE
#include "MemMap.h"

extern void FAULT_vidSetFFItem_FF1_Item_0xDF20(uint16 arg_Item_0xDF20);
extern void FAULT_vidSetFFItem_FF1_Item_0xDF21(uint16 arg_Item_0xDF21);
extern void FAULT_vidSetFFItem_FF1_Item_0xDF23(uint16 arg_Item_0xDF23);
extern void FAULT_vidSetFFItem_FF1_Item_0xDF29(uint8 arg_Item_0xDF29);
extern void FAULT_vidSetFFItem_FF1_Item_0xDF2A(uint8 arg_Item_0xDF2A);
extern void FAULT_vidSetFFItem_FF1_Item_0xDF2C(uint8 arg_Item_0xDF2C);
extern void FAULT_vidSetFFItem_FF1_Item_0x0D01(uint8 arg_Item_0x0D01);
extern void FAULT_vidSetFFItem_FF1_Item_0x0D02(uint16 arg_Item_0x0D02);
extern void FAULT_vidSetFFItem_FF1_Item_0x0D03(uint16 arg_Item_0x0D03);
extern void FAULT_vidSetFFItem_FF1_Item_0x0D04(uint16 arg_Item_0x0D04);
extern void FAULT_vidSetFFItem_FF1_Item_0x0D05(uint8 arg_Item_0x0D05);
extern void FAULT_vidSetFFItem_FF1_Item_0x0D06(uint16 arg_Item_0x0D06);
extern void FAULT_vidSetFFItem_FF1_Item_0x0D07(uint8 arg_Item_0x0D07);
extern void FAULT_vidSetFFItem_FF1_Item_0x0D08(uint16 arg_Item_0x0D08);
extern void FAULT_vidSetFFItem_FF1_Item_0x0D09(uint8 arg_Item_0x0D09);
extern void FAULT_vidSetFFItem_FF1_Item_0x0D0A(uint8 arg_Item_0x0D0A);
extern void FAULT_vidSetFFItem_FF1_Item_0x0D0B(uint8 arg_Item_0x0D0B);
extern void FAULT_vidSetFFItem_FF1_Item_0x0D0C(uint16 arg_Item_0x0D0C);
extern void FAULT_vidSetFFItem_FF1_Item_0x0D0C_1(uint16 arg_Item_0x0D0C_1);
extern void FAULT_vidSetFFItem_FF1_Item_0x0D0C_2(uint16 arg_Item_0x0D0C_2);
extern void FAULT_vidSetFFItem_FF1_Item_0x0D0D(uint16 arg_Item_0x0D0D);
extern void FAULT_vidSetFFItem_FF1_Item_0x0D0E(uint16 arg_Item_0x0D0E);
extern void FAULT_vidSetFFItem_FF1_Item_0x0D0F(uint16 arg_Item_0x0D0F);
extern void FAULT_vidSetFFItem_FF1_Item_0x0D13(uint16 arg_Item_0x0D13);
extern void FAULT_vidSetFFItem_FF1_Item_0x0D14(uint16 arg_Item_0x0D14);
extern void FAULT_vidSetFFItem_FF1_Item_0x0D15(uint16 arg_Item_0x0D15);
extern void FAULT_vidSetFFItem_FF1_Item_0x0D16(uint16 arg_Item_0x0D16);
extern void FAULT_vidSetFFItem_FF1_Item_0x0D17(uint16 arg_Item_0x0D17);
extern void FAULT_vidSetFFItem_FF1_Item_0x0D18(uint16 arg_Item_0x0D18);
extern void FAULT_vidSetFFItem_FF1_Item_0x0D19(uint16 arg_Item_0x0D19);
extern void FAULT_vidSetFFItem_FF1_Item_0x0D1A(uint16 arg_Item_0x0D1A);
extern void FAULT_vidSetFFItem_FF1_Item_0x0D1B(uint16 arg_Item_0x0D1B);
extern void FAULT_vidSetFFItem_FF1_Item_0x0D1C(uint16 arg_Item_0x0D1C);
extern void FAULT_vidSetFFItem_FF1_Item_0x0D1D(uint16 arg_Item_0x0D1D);
extern void FAULT_vidSetFFItem_FF1_Item_0x0D1E(uint16 arg_Item_0x0D1E);
extern void FAULT_vidSetFFItem_FF1_Item_0x0D1F(uint16 arg_Item_0x0D1F);
extern void FAULT_vidSetFFItem_FF1_Item_0x0D20(uint16 arg_Item_0x0D20);
extern void FAULT_vidSetFFItem_FF1_Item_0x0D21(uint16 arg_Item_0x0D21);
extern void FAULT_vidSetFFItem_FF1_Item_0x0D22(uint16 arg_Item_0x0D22);
extern void FAULT_vidSetFFItem_FF1_Item_0x0D23(uint16 arg_Item_0x0D23);
extern void FAULT_vidSetFFItem_FF1_Item_0x0D24(uint16 arg_Item_0x0D24);
extern void FAULT_vidSetFFItem_FF1_Item_0x0D25(uint16 arg_Item_0x0D25);
extern void FAULT_vidSetFFItem_FF1_Item_0x0D26(uint16 arg_Item_0x0D26);
extern void FAULT_vidSetFFItem_FF1_Item_0x0D27(uint16 arg_Item_0x0D27);
extern void FAULT_vidSetFFItem_FF1_Item_0x0D28(uint16 arg_Item_0x0D28);
extern void FAULT_vidSetFFItem_FF1_Item_0x0D29(uint16 arg_Item_0x0D29);
extern void FAULT_vidSetFFItem_FF1_Item_0x1D01(uint8 arg_Item_0x1D01);
extern void FAULT_vidSetFFItem_FF1_Item_0x1D02(uint16 arg_Item_0x1D02);
extern void FAULT_vidSetFFItem_FF1_Item_0x1D03(uint16 arg_Item_0x1D03);
extern void FAULT_vidSetFFItem_FF1_Item_0x1D04(uint16 arg_Item_0x1D04);
extern void FAULT_vidSetFFItem_FF1_Item_0x1D05(uint8 arg_Item_0x1D05);
extern void FAULT_vidSetFFItem_FF1_Item_0x1D06(uint16 arg_Item_0x1D06);
extern void FAULT_vidSetFFItem_FF1_Item_0x1D07(uint8 arg_Item_0x1D07);
extern void FAULT_vidSetFFItem_FF1_Item_0x1D08(uint16 arg_Item_0x1D08);
extern void FAULT_vidSetFFItem_FF1_Item_0x1D09(uint8 arg_Item_0x1D09);
extern void FAULT_vidSetFFItem_FF1_Item_0x1D0A(uint8 arg_Item_0x1D0A);
extern void FAULT_vidSetFFItem_FF1_Item_0x1D0B(uint8 arg_Item_0x1D0B);
extern void FAULT_vidSetFFItem_FF1_Item_0x1D0C(uint16 arg_Item_0x1D0C);
extern void FAULT_vidSetFFItem_FF1_Item_0x1D0C_1(uint16 arg_Item_0x1D0C_1);
extern void FAULT_vidSetFFItem_FF1_Item_0x1D0C_2(uint16 arg_Item_0x1D0C_2);
extern void FAULT_vidSetFFItem_FF1_Item_0x1D0D(uint16 arg_Item_0x1D0D);
extern void FAULT_vidSetFFItem_FF1_Item_0x1D0E(uint16 arg_Item_0x1D0E);
extern void FAULT_vidSetFFItem_FF1_Item_0x1D0F(uint16 arg_Item_0x1D0F);
extern void FAULT_vidSetFFItem_FF1_Item_0x1D13(uint16 arg_Item_0x1D13);
extern void FAULT_vidSetFFItem_FF1_Item_0x1D14(uint16 arg_Item_0x1D14);
extern void FAULT_vidSetFFItem_FF1_Item_0x1D15(uint16 arg_Item_0x1D15);
extern void FAULT_vidSetFFItem_FF1_Item_0x1D16(uint16 arg_Item_0x1D16);
extern void FAULT_vidSetFFItem_FF1_Item_0x1D17(uint16 arg_Item_0x1D17);
extern void FAULT_vidSetFFItem_FF1_Item_0x1D18(uint16 arg_Item_0x1D18);
extern void FAULT_vidSetFFItem_FF1_Item_0x1D19(uint16 arg_Item_0x1D19);
extern void FAULT_vidSetFFItem_FF1_Item_0x1D1A(uint16 arg_Item_0x1D1A);
extern void FAULT_vidSetFFItem_FF1_Item_0x1D1B(uint16 arg_Item_0x1D1B);
extern void FAULT_vidSetFFItem_FF1_Item_0x1D1C(uint16 arg_Item_0x1D1C);
extern void FAULT_vidSetFFItem_FF1_Item_0x1D1D(uint16 arg_Item_0x1D1D);
extern void FAULT_vidSetFFItem_FF1_Item_0x1D1E(uint16 arg_Item_0x1D1E);
extern void FAULT_vidSetFFItem_FF1_Item_0x1D1F(uint16 arg_Item_0x1D1F);
extern void FAULT_vidSetFFItem_FF1_Item_0x1D20(uint16 arg_Item_0x1D20);
extern void FAULT_vidSetFFItem_FF1_Item_0x1D21(uint16 arg_Item_0x1D21);
extern void FAULT_vidSetFFItem_FF1_Item_0x1D22(uint16 arg_Item_0x1D22);
extern void FAULT_vidSetFFItem_FF1_Item_0x1D23(uint16 arg_Item_0x1D23);
extern void FAULT_vidSetFFItem_FF1_Item_0x1D24(uint16 arg_Item_0x1D24);
extern void FAULT_vidSetFFItem_FF1_Item_0x1D25(uint16 arg_Item_0x1D25);
extern void FAULT_vidSetFFItem_FF1_Item_0x1D26(uint16 arg_Item_0x1D26);
extern void FAULT_vidSetFFItem_FF1_Item_0x1D27(uint16 arg_Item_0x1D27);
extern void FAULT_vidSetFFItem_FF1_Item_0x1D28(uint16 arg_Item_0x1D28);
extern void FAULT_vidSetFFItem_FF1_Item_0x1D29(uint16 arg_Item_0x1D29);
extern void FAULT_vidSetFFItem_FF1_Item_0x2D02(uint16 arg_Item_0x2D02);
extern void FAULT_vidSetFFItem_FF1_Item_0x2D03(uint16 arg_Item_0x2D03);
extern void FAULT_vidSetFFItem_FF1_Item_0x2D04(uint16 arg_Item_0x2D04);
extern void FAULT_vidSetFFItem_FF1_Item_0x2D05(uint8 arg_Item_0x2D05);
extern void FAULT_vidSetFFItem_FF1_Item_0x2D06(uint16 arg_Item_0x2D06);
extern void FAULT_vidSetFFItem_FF1_Item_0x2D07(uint8 arg_Item_0x2D07);
extern void FAULT_vidSetFFItem_FF1_Item_0x2D08(uint16 arg_Item_0x2D08);
extern void FAULT_vidSetFFItem_FF1_Item_0x2D0E(uint16 arg_Item_0x2D0E);
extern void FAULT_vidSetFFItem_FF1_Item_0x2D13(uint16 arg_Item_0x2D13);
extern void FAULT_vidSetFFItem_FF1_Item_0x2D14(uint16 arg_Item_0x2D14);
extern void FAULT_vidSetFFItem_FF1_Item_0x2D15(uint16 arg_Item_0x2D15);
extern void FAULT_vidSetFFItem_FF1_Item_0x2D1C(uint16 arg_Item_0x2D1C);
extern void FAULT_vidSetFFItem_FF1_Item_0x2D1D(uint16 arg_Item_0x2D1D);
extern void FAULT_vidSetFFItem_FF1_Item_0x2D1E(uint16 arg_Item_0x2D1E);
extern void FAULT_vidSetFFItem_FF1_Item_0x2D1F(uint16 arg_Item_0x2D1F);
extern void FAULT_vidSetFFItem_FF1_Item_0x2D20(uint16 arg_Item_0x2D20);
extern void FAULT_vidSetFFItem_FF1_Item_0x2D21(uint16 arg_Item_0x2D21);
extern void FAULT_vidSetFFItem_FF1_Item_0x2D22(uint16 arg_Item_0x2D22);
extern void FAULT_vidSetFFItem_FF1_Item_0x2D25(uint16 arg_Item_0x2D25);
extern void FAULT_vidSetFFItem_FF1_Item_0x2D26(uint16 arg_Item_0x2D26);
extern void FAULT_vidSetFFItem_FF1_Item_0x3D02(uint16 arg_Item_0x3D02);
extern void FAULT_vidSetFFItem_FF1_Item_0x3D03(uint16 arg_Item_0x3D03);
extern void FAULT_vidSetFFItem_FF1_Item_0x3D04(uint16 arg_Item_0x3D04);
extern void FAULT_vidSetFFItem_FF1_Item_0x3D05(uint8 arg_Item_0x3D05);
extern void FAULT_vidSetFFItem_FF1_Item_0x3D06(uint16 arg_Item_0x3D06);
extern void FAULT_vidSetFFItem_FF1_Item_0x3D07(uint8 arg_Item_0x3D07);
extern void FAULT_vidSetFFItem_FF1_Item_0x3D08(uint16 arg_Item_0x3D08);
extern void FAULT_vidSetFFItem_FF1_Item_0x3D0E(uint16 arg_Item_0x3D0E);
extern void FAULT_vidSetFFItem_FF1_Item_0x3D13(uint16 arg_Item_0x3D13);
extern void FAULT_vidSetFFItem_FF1_Item_0x3D14(uint16 arg_Item_0x3D14);
extern void FAULT_vidSetFFItem_FF1_Item_0x3D15(uint16 arg_Item_0x3D15);
extern void FAULT_vidSetFFItem_FF1_Item_0x3D1C(uint16 arg_Item_0x3D1C);
extern void FAULT_vidSetFFItem_FF1_Item_0x3D1D(uint16 arg_Item_0x3D1D);
extern void FAULT_vidSetFFItem_FF1_Item_0x3D1E(uint16 arg_Item_0x3D1E);
extern void FAULT_vidSetFFItem_FF1_Item_0x3D1F(uint16 arg_Item_0x3D1F);
extern void FAULT_vidSetFFItem_FF1_Item_0x3D20(uint16 arg_Item_0x3D20);
extern void FAULT_vidSetFFItem_FF1_Item_0x3D21(uint16 arg_Item_0x3D21);
extern void FAULT_vidSetFFItem_FF1_Item_0x3D22(uint16 arg_Item_0x3D22);
extern void FAULT_vidSetFFItem_FF1_Item_0x3D25(uint16 arg_Item_0x3D25);
extern void FAULT_vidSetFFItem_FF1_Item_0x3D26(uint16 arg_Item_0x3D26);
extern void FAULT_vidSetFFItem_FF1_Item_0x4D27(uint16 arg_Item_0x4D27);
extern void FAULT_vidSetFFItem_FF1_Item_0x4D28(uint16 arg_Item_0x4D28);
extern void FAULT_vidSetFFItem_FF1_Item_0x4D29(uint16 arg_Item_0x4D29);
extern void FAULT_vidSetFFItem_FF1_Item_0x4D2A(uint16 arg_Item_0x4D2A);
extern void FAULT_vidSetFFItem_FF1_Item_0x4D2B(uint16 arg_Item_0x4D2B);
extern void FAULT_vidSetFFItem_FF1_Item_0x4D2C(uint16 arg_Item_0x4D2C);
extern void FAULT_vidSetFFItem_FF1_Item_0x4D2D(uint16 arg_Item_0x4D2D);
extern void FAULT_vidSetFFItem_FF1_Item_0x4D2E(uint16 arg_Item_0x4D2E);
extern void FAULT_vidSetFFItem_FF1_Item_0x4D2F(uint16 arg_Item_0x4D2F);
extern void FAULT_vidSetFFItem_FF1_Item_0x4D30(uint16 arg_Item_0x4D30);
extern void FAULT_vidSetFFItem_FF1_Item_0x4D31(uint16 arg_Item_0x4D31);
extern void FAULT_vidSetFFItem_FF1_Item_0x4D32(uint16 arg_Item_0x4D32);
extern void FAULT_vidSetFFItem_FF1_Item_0x4D33(uint8 arg_Item_0x4D33);
extern void FAULT_vidSetFFItem_FF1_Item_0x4D34(uint16 arg_Item_0x4D34);
extern void FAULT_vidSetFFItem_FF1_Item_0x4D35(uint8 arg_Item_0x4D35);
extern void FAULT_vidSetFFItem_FF1_Item_0x4D36(uint16 arg_Item_0x4D36);
extern void FAULT_vidSetFFItem_FF1_Item_0x4D37(uint8 arg_Item_0x4D37);
extern void FAULT_vidSetFFItem_FF1_Item_0x4D38(uint16 arg_Item_0x4D38);
extern void FAULT_vidSetFFItem_FF1_Item_0x4D39(uint8 arg_Item_0x4D39);
extern void FAULT_vidSetFFItem_FF1_Item_0x4D3A(uint16 arg_Item_0x4D3A);
extern void FAULT_vidSetFFItem_FF1_Item_0x4D3B(uint8 arg_Item_0x4D3B);
extern void FAULT_vidSetFFItem_FF1_Item_0x4D3C(uint16 arg_Item_0x4D3C);
extern void FAULT_vidSetFFItem_FF1_Item_0x4D3D(uint8 arg_Item_0x4D3D);


#define FAULT_FF_STOP_SEC_CODE
#include "MemMap.h"

#endif /* FAULT_FF_H */

/*------------------------------- end of file --------------------------------*/
