/******************************************************************************/
/*                                                                            */
/* !Layer           : STD                                                     */
/*                                                                            */
/* !Component       : MEMMAP                                                  */
/* !Description     : MEMMAP Configuration                                    */
/*                                                                            */
/* !File            : FAULT_FF_MEMMAP.H                                          */
/*                                                                            */
/* !Scope           : Public                                                  */
/*                                                                            */
/* !Target          :                                                         */
/*                                                                            */
/* !Vendor          : invt                                                    */
/*                                                                            */
/* Coding language  : C                                                       */
/*                                                                            */
/* COPYRIGHT 2009 invt                                                        */
/* all rights reserved                                                        */
/*                                                                            */
/******************************************************************************/
/* SVN Information                                                           */
/* $Archive::                                                                $*/
/* $Revision::            $$Author::                  $$Date::               $*/
/******************************************************************************/
/* 05/22/24, 11:23:11: generated by Genecode  v2.6.0.0                        */
/* From Source Template : MSN_MEMMAP_H.TPL                                    */
/******************************************************************************/



/******************************************************************************/
/*          MEMMAP selected mode:  SAFE                                       */
/******************************************************************************/
#define MEMMAP_ERROR

/* The following if is used only due to automatic generation */
#if !defined MEMMAP_ERROR

/* Project section mappings */
/* !Comment: FAULT_FF Section allocation */
#elif defined   FAULT_FF_START_SEC_CODE
   #undef  FAULT_FF_START_SEC_CODE
   #define START_CODE_SECTION
#elif defined   FAULT_FF_STOP_SEC_CODE
   #undef  FAULT_FF_STOP_SEC_CODE
   #define STOP_CODE_SECTION

#elif defined   FAULT_FF_START_SEC_VAR_UNSPECIFIED
   #undef  FAULT_FF_START_SEC_VAR_UNSPECIFIED
   #define START_VAR_UNSPECIFIED_SECTION
#elif defined   FAULT_FF_STOP_SEC_VAR_UNSPECIFIED
   #undef  FAULT_FF_STOP_SEC_VAR_UNSPECIFIED
   #define STOP_VAR_UNSPECIFIED_SECTION

#elif defined   FAULT_FF_START_SEC_CONST_UNSPECIFIED
   #undef  FAULT_FF_START_SEC_CONST_UNSPECIFIED
   #define START_CONST_UNSPECIFIED_SECTION
#elif defined   FAULT_FF_STOP_SEC_CONST_UNSPECIFIED
   #undef  FAULT_FF_STOP_SEC_CONST_UNSPECIFIED
   #define STOP_CONST_UNSPECIFIED_SECTION

#elif defined   FAULT_FF_START_SEC_CALIB_UNSPECIFIED
   #undef  FAULT_FF_START_SEC_CALIB_UNSPECIFIED
   #define START_CALIB_UNSPECIFIED_SECTION
#elif defined   FAULT_FF_STOP_SEC_CALIB_UNSPECIFIED
   #undef  FAULT_FF_STOP_SEC_CALIB_UNSPECIFIED
   #define STOP_CALIB_UNSPECIFIED_SECTION


#endif

/* ECU specific section mappings */
#ifndef MEMMAP_START_DONE

/* The following if is used only due to automatic generation */

#if FALSE
/* !Comment: CODE Start Section treatment */
   #elif defined   START_CODE_SECTION
	  

      #pragma section ".text" ax

      #undef  MEMMAP_ERROR
      #define MEMMAP_START_DONE

/* !Comment: VAR_UNSPECIFIED Start Section treatment */
   #elif defined   START_VAR_UNSPECIFIED_SECTION
	  
      #undef  MEMMAP_ERROR
      #define MEMMAP_START_DONE

/* !Comment: CONST_UNSPECIFIED Start Section treatment */
   #elif defined   START_CONST_UNSPECIFIED_SECTION
	  

      #pragma section ".const" a

      #undef  MEMMAP_ERROR
      #define MEMMAP_START_DONE

/* !Comment: CALIB_UNSPECIFIED Start Section treatment */
   #elif defined   START_CALIB_UNSPECIFIED_SECTION
	  

      #pragma section ".calib" a

      #undef  MEMMAP_ERROR
      #define MEMMAP_START_DONE


   #endif

#else   /* if MEMMAP_START_DONE is not defined */

/* The following if is used only due to automatic generation */

#if FALSE
/* !Comment: CODE Stop Section treatment */
   #elif defined   STOP_CODE_SECTION && defined  START_CODE_SECTION
	  

      #pragma section

      #undef START_CODE_SECTION
      #undef STOP_CODE_SECTION
      #undef MEMMAP_ERROR
      #undef MEMMAP_START_DONE

/* !Comment: VAR_UNSPECIFIED Stop Section treatment */
   #elif defined   STOP_VAR_UNSPECIFIED_SECTION && defined  START_VAR_UNSPECIFIED_SECTION
	  
      #undef START_VAR_UNSPECIFIED_SECTION
      #undef STOP_VAR_UNSPECIFIED_SECTION
      #undef MEMMAP_ERROR
      #undef MEMMAP_START_DONE

/* !Comment: CONST_UNSPECIFIED Stop Section treatment */
   #elif defined   STOP_CONST_UNSPECIFIED_SECTION && defined  START_CONST_UNSPECIFIED_SECTION
	  

      #pragma section

      #undef START_CONST_UNSPECIFIED_SECTION
      #undef STOP_CONST_UNSPECIFIED_SECTION
      #undef MEMMAP_ERROR
      #undef MEMMAP_START_DONE

/* !Comment: CALIB_UNSPECIFIED Stop Section treatment */
   #elif defined   STOP_CALIB_UNSPECIFIED_SECTION && defined  START_CALIB_UNSPECIFIED_SECTION
	  

      #pragma section

      #undef START_CALIB_UNSPECIFIED_SECTION
      #undef STOP_CALIB_UNSPECIFIED_SECTION
      #undef MEMMAP_ERROR
      #undef MEMMAP_START_DONE


   #endif
#endif

#if defined MEMMAP_ERROR
   #error MEMMAP-E201 : Bad memory allocation into FAULT_FF_MemMap.h
#endif


/*------------------------------- end of file --------------------------------*/

