/******************************************************************************/
/*                                                                            */
/* !Layer          : BSW                                                      */
/*                                                                            */
/* !Component      : HAL                                                      */
/*                                                                            */
/* !Module         : IOHAL                                                    */
/* !Description    : Configuration of the IOHAL component.                    */
/*                                                                            */
/* !File           : IOHAL_CFG_I.C                                            */
/*                                                                            */
/* !Target         : All                                                      */
/*                                                                            */
/* !Vendor         : invt                                                     */
/*                                                                            */
/* Coding language : C                                                        */
/*                                                                            */
/* COPYRIGHT 2009 invt                                                        */
/* all rights reserved                                                        */
/*                                                                            */
/******************************************************************************/
/* SVN Information                                                           */
/* $Archive::                                                                $*/
/* $Revision::            $$Author::                  $$Date::               $*/
/******************************************************************************/
/** 10/27/22, 09:10:34: generated by Genecode v2.6.0.0                        */
/******************************************************************************/

#include "IcuHal.h"
#include "IOHAL_Cfg_I.h"

#include "Dio.h"
#include "VADC.h"

#include "PortMux.h"

#define IOHAL_START_SEC_CODE
#include "IOHAL_MemMap.h"

/*************************************************************/
/* LOCAL FUNCTION DEFINITION                                 */
/* !LastAuthor:ZZX                                           */
/*************************************************************/

uint16 IOHAL_u16Read_CH_DIO_IN_M_AN_ENABLE_ASC2 (void)
{
   return ((uint16)Dio_ReadChannel(DioConf_DioChannel_M_AN_ENABLE_ASC2));
}
void   IOHAL_vidWrite_CH_DIO_OUT_M_DX1_B (uint16 u16State)
{
   Dio_WriteChannel(DioConf_DioChannel_M_DX1_B, u16State);
}
void   IOHAL_vidWrite_CH_DIO_OUT_M_BACKUP_EN (uint16 u16State)
{
   Dio_WriteChannel(DioConf_DioChannel_M_BACKUP_EN, u16State);
}
void   IOHAL_vidWrite_CH_DIO_OUT_M_RCLK_2 (uint16 u16State)
{
   Dio_WriteChannel(DioConf_DioChannel_M_RCLK_2, u16State);
}
uint16 IOHAL_u16Read_CH_DIO_IN_M_AN_ENABLE_ASC1 (void)
{
   return ((uint16)Dio_ReadChannel(DioConf_DioChannel_M_AN_ENABLE_ASC1));
}
void   IOHAL_vidWrite_CH_DIO_OUT_M_Q6_PTC2 (uint16 u16State)
{
   Dio_WriteChannel(DioConf_DioChannel_M_Q6_PTC2, u16State);
}

uint16 IOHAL_u16Read_CH_DIO_IN_M_HW_OCP_W_2 (void)
{
   return ((uint16)Dio_ReadChannel(DioConf_DioChannel_M_HW_OCP_W_2));
}
void   IOHAL_vidWrite_CH_DIO_OUT_M_DX3_A (uint16 u16State)
{
   Dio_WriteChannel(DioConf_DioChannel_M_DX3_A, u16State);
}
void   IOHAL_vidWrite_CH_DIO_OUT_M_DX3_B (uint16 u16State)
{
   Dio_WriteChannel(DioConf_DioChannel_M_DX3_B, u16State);
}
void   IOHAL_vidWrite_CH_DIO_OUT_M_DX3_C (uint16 u16State)
{
   Dio_WriteChannel(DioConf_DioChannel_M_DX3_C, u16State);
}
void   IOHAL_vidWrite_CH_DIO_OUT_M_DX1_A (uint16 u16State)
{
   Dio_WriteChannel(DioConf_DioChannel_M_DX1_A, u16State);
}

void   IOHAL_vidWrite_CH_DIO_OUT_M_SRCLK_2 (uint16 u16State)
{
   Dio_WriteChannel(DioConf_DioChannel_M_SRCLK_2, u16State);
}
void   IOHAL_vidWrite_CH_DIO_OUT_M_SER_2 (uint16 u16State)
{
   Dio_WriteChannel(DioConf_DioChannel_M_SER_2, u16State);
}
uint16 IOHAL_u16Read_CH_DIO_IN_M_IO_MUX2 (void)
{
   return ((uint16)Dio_ReadChannel(DioConf_DioChannel_M_IO_MUX2));
}
void   IOHAL_vidWrite_CH_DIO_OUT_M_PW_DOWN (uint16 u16State)
{
   Dio_WriteChannel(DioConf_DioChannel_M_PW_DOWN, u16State);
}
void   IOHAL_vidWrite_CH_DIO_OUT_M_KM1_ZQ1 (uint16 u16State)
{
   Dio_WriteChannel(DioConf_DioChannel_M_KM1_ZQ1, u16State);
}
void   IOHAL_vidWrite_CH_DIO_OUT_M_KM2_ZQ2 (uint16 u16State)
{
   Dio_WriteChannel(DioConf_DioChannel_M_KM2_ZQ2, u16State);
}
void   IOHAL_vidWrite_CH_DIO_OUT_M_KM3_ZQ3 (uint16 u16State)
{
   Dio_WriteChannel(DioConf_DioChannel_M_KM3_ZQ3, u16State);
}
void   IOHAL_vidWrite_CH_DIO_OUT_M_KM4_ZQ4 (uint16 u16State)
{
   Dio_WriteChannel(DioConf_DioChannel_M_KM4_ZQ4, u16State);
}

uint16 IOHAL_u16Read_CH_DIO_IN_M_HW_OCP_V_2 (void)
{
   return ((uint16)Dio_ReadChannel(DioConf_DioChannel_M_HW_OCP_V_2));
}

uint16 IOHAL_u16Read_CH_DIO_IN_M_FLT_EXCITATION_2 (void)
{
   return ((uint16)Dio_ReadChannel(DioConf_DioChannel_M_FLT_EXCITATION_2));
}
uint16 IOHAL_u16Read_CH_DIO_IN_M_FLT_EXCITATION_1 (void)
{
   return ((uint16)Dio_ReadChannel(DioConf_DioChannel_M_FLT_EXCITATION_1));
}
uint16 IOHAL_u16Read_CH_DIO_IN_M_DI1_KM_EN (void)
{
   return ((uint16)Dio_ReadChannel(DioConf_DioChannel_M_DI1_KM_EN));
}
void   IOHAL_vidWrite_CH_DIO_OUT_M_SRCLK_3 (uint16 u16State)
{
   Dio_WriteChannel(DioConf_DioChannel_M_SRCLK_3, u16State);
}
void   IOHAL_vidWrite_CH_DIO_OUT_M_SER_3 (uint16 u16State)
{
   Dio_WriteChannel(DioConf_DioChannel_M_SER_3, u16State);
}
uint16 IOHAL_u16Read_CH_DIO_IN_M_HW_OCP_U_2 (void)
{
   return ((uint16)Dio_ReadChannel(DioConf_DioChannel_M_HW_OCP_U_2));
}
void   IOHAL_vidWrite_CH_DIO_OUT_M_YC2_KC3Z_YC (uint16 u16State)
{
   Dio_WriteChannel(DioConf_DioChannel_M_YC2_KC3Z_YC, u16State);
}
void   IOHAL_vidWrite_CH_DIO_OUT_M_ISO_EN1 (uint16 u16State)
{
   Dio_WriteChannel(DioConf_DioChannel_M_ISO_EN1, u16State);
}
void   IOHAL_vidWrite_CH_DIO_OUT_M_ISO_EN2 (uint16 u16State)
{
   Dio_WriteChannel(DioConf_DioChannel_M_ISO_EN2, u16State);
}
void   IOHAL_vidWrite_CH_DIO_OUT_M_ISO_EN3 (uint16 u16State)
{
   Dio_WriteChannel(DioConf_DioChannel_M_ISO_EN3, u16State);
}

uint16 IOHAL_u16Read_CH_DIO_IN_M_HW_OCP_V_1 (void)
{
   return ((uint16)Dio_ReadChannel(DioConf_DioChannel_M_HW_OCP_V_1));
}
void   IOHAL_vidWrite_CH_DIO_OUT_M_KM20_DCJY1 (uint16 u16State)
{
   Dio_WriteChannel(DioConf_DioChannel_M_KM20_DCJY1, u16State);
}
void   IOHAL_vidWrite_CH_DIO_OUT_M_KM21_DCJY2 (uint16 u16State)
{
   Dio_WriteChannel(DioConf_DioChannel_M_KM21_DCJY2, u16State);
}
void   IOHAL_vidWrite_CH_DIO_OUT_M_KM22_DCJY3 (uint16 u16State)
{
   Dio_WriteChannel(DioConf_DioChannel_M_KM22_DCJY3, u16State);
}
void   IOHAL_vidWrite_CH_DIO_OUT_M_KM23_DCJY4 (uint16 u16State)
{
   Dio_WriteChannel(DioConf_DioChannel_M_KM23_DCJY4, u16State);
}
void   IOHAL_vidWrite_CH_DIO_OUT_M_YC5_SZ2_YC (uint16 u16State)
{
   Dio_WriteChannel(DioConf_DioChannel_M_YC5_SZ2_YC, u16State);
}

uint16 IOHAL_u16Read_CH_DIO_IN_M_HW_OCP_U_1 (void)
{
   return ((uint16)Dio_ReadChannel(DioConf_DioChannel_M_HW_OCP_U_1));
}
uint16 IOHAL_u16Read_CH_DIO_IN_M_SUPPLY_WDI (void)
{
   return ((uint16)Dio_ReadChannel(DioConf_DioChannel_M_SUPPLY_WDI));
}
uint16 IOHAL_u16Read_CH_DIO_IN_M_IO_MUX3 (void)
{
   return ((uint16)Dio_ReadChannel(DioConf_DioChannel_M_IO_MUX3));
}
uint16 IOHAL_u16Read_CH_DIO_IN_M_HW_OCP_W_1 (void)
{
   return ((uint16)Dio_ReadChannel(DioConf_DioChannel_M_HW_OCP_W_1));
}

void   IOHAL_vidWrite_CH_DIO_OUT_M_DO2 (uint16 u16State)
{
   Dio_WriteChannel(DioConf_DioChannel_M_DO2, u16State);
}
uint16 IOHAL_u16Read_CH_DIO_IN_M_FAULT_ACM_HS_N (void)
{
   return ((uint16)Dio_ReadChannel(DioConf_DioChannel_M_FAULT_ACM_HS_N));
}
uint16 IOHAL_u16Read_CH_DIO_IN_M_FAULT_EPS_HS_N (void)
{
   return ((uint16)Dio_ReadChannel(DioConf_DioChannel_M_FAULT_EPS_HS_N));
}
void   IOHAL_vidWrite_CH_DIO_OUT_MCU_ASC_STATE (uint16 u16State)
{
   Dio_WriteChannel(DioConf_DioChannel_MCU_ASC_STATE, u16State);
}
void   IOHAL_vidWrite_CH_DIO_OUT_M_YC3_KC4Z_YC (uint16 u16State)
{
   Dio_WriteChannel(DioConf_DioChannel_M_YC3_KC4Z_YC, u16State);
}

uint16 IOHAL_u16Read_CH_DIO_IN_M_FAULT_DRV_HS_N_1 (void)
{
   return ((uint16)Dio_ReadChannel(DioConf_DioChannel_M_FAULT_DRV_HS_N_1));
}
void   IOHAL_vidWrite_CH_DIO_OUT_M_YC7_ZXFZ_YC (uint16 u16State)
{
   Dio_WriteChannel(DioConf_DioChannel_M_YC7_ZXFZ_YC, u16State);
}
void   IOHAL_vidWrite_CH_DIO_OUT_M_YC1_ZQ_YC (uint16 u16State)
{
   Dio_WriteChannel(DioConf_DioChannel_M_YC1_ZQ_YC, u16State);
}
void   IOHAL_vidWrite_CH_DIO_OUT_M_Q1_DCJR1 (uint16 u16State)
{
   Dio_WriteChannel(DioConf_DioChannel_M_Q1_DCJR1, u16State);
}
void   IOHAL_vidWrite_CH_DIO_OUT_M_Q2_DCJR2 (uint16 u16State)
{
   Dio_WriteChannel(DioConf_DioChannel_M_Q2_DCJR2, u16State);
}
void   IOHAL_vidWrite_CH_DIO_OUT_M_Q3_DCJR3 (uint16 u16State)
{
   Dio_WriteChannel(DioConf_DioChannel_M_Q3_DCJR3, u16State);
}
void   IOHAL_vidWrite_CH_DIO_OUT_M_Q4_DCJR4 (uint16 u16State)
{
   Dio_WriteChannel(DioConf_DioChannel_M_Q4_DCJR4, u16State);
}
void   IOHAL_vidWrite_CH_DIO_OUT_M_ENA_KM (uint16 u16State)
{
   Dio_WriteChannel(DioConf_DioChannel_M_ENA_KM, u16State);
}

void   IOHAL_vidWrite_CH_DIO_OUT_M_SRCLK (uint16 u16State)
{
   Dio_WriteChannel(DioConf_DioChannel_M_SRCLK, u16State);
}

void   IOHAL_vidWrite_CH_DIO_OUT_M_RCLK (uint16 u16State)
{
   Dio_WriteChannel(DioConf_DioChannel_M_RCLK, u16State);
}
uint16 IOHAL_u16Read_CH_DIO_IN_M_FAULT_DRV_LS_N_1 (void)
{
   return ((uint16)Dio_ReadChannel(DioConf_DioChannel_M_FAULT_DRV_LS_N_1));
}
uint16 IOHAL_u16Read_CH_DIO_IN_M_FAULT_DRV_LS_N_2 (void)
{
   return ((uint16)Dio_ReadChannel(DioConf_DioChannel_M_FAULT_DRV_LS_N_2));
}
uint16 IOHAL_u16Read_CH_DIO_IN_M_FAULT_DRV_HS_N_2 (void)
{
   return ((uint16)Dio_ReadChannel(DioConf_DioChannel_M_FAULT_DRV_HS_N_2));
}
void   IOHAL_vidWrite_CH_DIO_OUT_M_Q5_PTC1 (uint16 u16State)
{
   Dio_WriteChannel(DioConf_DioChannel_M_Q5_PTC1, u16State);
}
void   IOHAL_vidWrite_CH_DIO_OUT_M_ACM_ENA_PWM (uint16 u16State)
{
   Dio_WriteChannel(DioConf_DioChannel_M_ACM_ENA_PWM, u16State);
}

void   IOHAL_vidWrite_CH_DIO_OUT_M_DX1_C (uint16 u16State)
{
   Dio_WriteChannel(DioConf_DioChannel_M_DX1_C, u16State);
}
void   IOHAL_vidWrite_CH_DIO_OUT_M_YC6_XGLFZ_YC (uint16 u16State)
{
   Dio_WriteChannel(DioConf_DioChannel_M_YC6_XGLFZ_YC, u16State);
}
void   IOHAL_vidWrite_CH_DIO_OUT_M_EPS_ENA_PWM (uint16 u16State)
{
   Dio_WriteChannel(DioConf_DioChannel_M_EPS_ENA_PWM, u16State);
}
/* 
uint16 IOHAL_u16Read_CH_DIO_IN_M_KEY_ON (void)
{
   uint16 u16KeyOnLevel =  ((uint16)Dio_ReadChannel(DioConf_DioChannel_M_KEY_ON));
   uint16 u16ChgOnLevel = ((uint16)Dio_ReadChannel(DioConf_DioChannel_M_CHG_ON));
   uint16 u16Level = 0;
   if (u16KeyOnLevel == 1)
   {
      u16Level = 1;
   }
   else if (u16ChgOnLevel == 1)
   {
      u16Level = 1;
   }
   else
   {
      u16Level = 0;
   } 
   return u16Level;
}

 */

uint16 IOHAL_u16Read_CH_DIO_IN_M_KEY_ON (void)
{
   return ((uint16)Dio_ReadChannel(DioConf_DioChannel_M_KEY_ON));
}
void   IOHAL_vidWrite_CH_DIO_OUT_M_DX2_A (uint16 u16State)
{
   Dio_WriteChannel(DioConf_DioChannel_M_DX2_A, u16State);
}
void   IOHAL_vidWrite_CH_DIO_OUT_M_DX2_B (uint16 u16State)
{
   Dio_WriteChannel(DioConf_DioChannel_M_DX2_B, u16State);
}
void   IOHAL_vidWrite_CH_DIO_OUT_M_DX2_C (uint16 u16State)
{
   Dio_WriteChannel(DioConf_DioChannel_M_DX2_C, u16State);
}
void   IOHAL_vidWrite_CH_DIO_OUT_M_YC4_SZ1_YC (uint16 u16State)
{
   Dio_WriteChannel(DioConf_DioChannel_M_YC4_SZ1_YC, u16State);
}

void   IOHAL_vidWrite_CH_DIO_OUT_MCU_STATE_LED (uint16 u16State)
{
   Dio_WriteChannel(DioConf_DioChannel_MCU_STATE_LED, u16State);
}
void   IOHAL_vidWrite_CH_DIO_OUT_M_SER (uint16 u16State)
{
   Dio_WriteChannel(DioConf_DioChannel_M_SER, u16State);
}
void   IOHAL_vidWrite_CH_DIO_OUT_M_DO1 (uint16 u16State)
{
   Dio_WriteChannel(DioConf_DioChannel_M_DO1, u16State);
}

uint16 IOHAL_u16Read_CH_DIO_IN_M_CHG_ON (void)
{
   return ((uint16)Dio_ReadChannel(DioConf_DioChannel_M_CHG_ON));
}

void   IOHAL_vidWrite_CH_DIO_OUT_M_RCLK_3 (uint16 u16State)
{
   Dio_WriteChannel(DioConf_DioChannel_M_RCLK_3, u16State);
}

uint16 IOHAL_u16Read_CH_ADC_IN_AN_VOL_DCLINK_DRV (void)
{
   return ((uint16)VADC_u16GroupBuffer10[0]);
}
/**********************************************************************************************/
/* !Description: Read function from the ADC channel                                           */
/* !PORT:AN0                                                                                  */
/* !LastAuthor:                                                                               */
/**********************************************************************************************/
uint16 IOHAL_u16Read_CH_ADC_IN_M_AN_MOT_COS_1 (void)
{
   return ((uint16)VADC_u16GroupBuffer0[0]);
}
/**********************************************************************************************/
/* !Description: Read function from the ADC channel                                           */
/* !PORT:AN1                                                                                  */
/* !LastAuthor:                                                                               */
/**********************************************************************************************/
uint16 IOHAL_u16Read_CH_ADC_IN_M_AN_MOT_SIN_1 (void)
{
   return ((uint16)VADC_u16GroupBuffer0[1]);
}
/**********************************************************************************************/
/* !Description: Read function from the ADC channel                                           */
/* !PORT:AN2                                                                                  */
/* !LastAuthor:                                                                               */
/**********************************************************************************************/
uint16 IOHAL_u16Read_CH_ADC_IN_M_AN_KM6_FB_KC1F (void)
{
   return ((uint16)VADC_u16GroupBuffer0[2]);
}
uint16 IOHAL_u16Read_CH_ADC_IN_AN_MON_CURRENT_OCP_MCU1 (void)
{
   return ((uint16)VADC_u16GroupBuffer0[2]);
}
/**********************************************************************************************/
/* !Description: Read function from the ADC channel                                           */
/* !PORT:AN3                                                                                  */
/* !LastAuthor:                                                                               */
/**********************************************************************************************/
uint16 IOHAL_u16Read_CH_ADC_IN_M_AN_KM8_FB_KC2F (void)
{
   return ((uint16)VADC_u16GroupBuffer0[3]);
}
uint16 IOHAL_u16Read_CH_ADC_IN_AN_MON_CURRENT_OCP_MCU2 (void)
{
   return ((uint16)VADC_u16GroupBuffer0[3]);
}

/**********************************************************************************************/
/* !Description: Read function from the ADC channel                                           */
/* !PORT:AN8                                                                                  */
/* !LastAuthor:                                                                               */
/**********************************************************************************************/
uint16 IOHAL_u16Read_CH_ADC_IN_M_AN_CURRENT_U_1 (void)
{
   return ((uint16)VADC_u16GroupBuffer1[0]);
}

/**********************************************************************************************/
/* !Description: Read function from the ADC channel                                           */
/* !PORT:AN10                                                                                 */
/* !LastAuthor:                                                                               */
/**********************************************************************************************/
uint16 IOHAL_u16Read_CH_ADC_IN_M_AN_CURRENT_V_1 (void)
{
   return ((uint16)VADC_u16GroupBuffer1[1]);
}
/**********************************************************************************************/
/* !Description: Read function from the ADC channel                                           */
/* !PORT:AN11                                                                                 */
/* !LastAuthor:                                                                               */
/**********************************************************************************************/
uint16 IOHAL_u16Read_CH_ADC_IN_M_AN_CURRENT_W_1 (void)
{
   return ((uint16)VADC_u16GroupBuffer1[2]);
}
/**********************************************************************************************/
/* !Description: Read function from the ADC channel                                           */
/* !PORT:AN12                                                                                 */
/* !LastAuthor:                                                                               */
/**********************************************************************************************/
uint16 IOHAL_u16Read_CH_ADC_IN_M_AN_DC_LINK_PACK4 (void)
{
   return ((uint16)VADC_u16GroupBuffer1[3]);
}
uint16 IOHAL_u16Read_CH_ADC_IN_M_AN_DIAG_SIN_H_2 (void)
{
   return ((uint16)VADC_u16GroupBuffer1[3]);
}
/**********************************************************************************************/
/* !Description: Read function from the ADC channel                                           */
/* !PORT:AN13                                                                                 */
/* !LastAuthor:                                                                               */
/**********************************************************************************************/
uint16 IOHAL_u16Read_CH_ADC_IN_M_ACM_TEMP_MEAS_MOD_W (void)
{
   return ((uint16)VADC_u16GroupBuffer1[4]);
}
uint16 IOHAL_u16Read_CH_ADC_IN_M_HDW_VERSION (void)
{
   return ((uint16)VADC_u16GroupBuffer1[4]);
}
/**********************************************************************************************/
/* !Description: Read function from the ADC channel                                           */
/* !PORT:AN14                                                                                 */
/* !LastAuthor:                                                                               */
/**********************************************************************************************/
uint16 IOHAL_u16Read_CH_ADC_IN_M_ACM_TEMP_MEAS_MOD_V (void)
{
   return ((uint16)VADC_u16GroupBuffer1[5]);
}
uint16 IOHAL_u16Read_CH_ADC_IN_AN_P5V_AD2S (void)
{
   return ((uint16)VADC_u16GroupBuffer1[5]);
}
/**********************************************************************************************/
/* !Description: Read function from the ADC channel                                           */
/* !PORT:AN16                                                                                 */
/* !LastAuthor:                                                                               */
/**********************************************************************************************/
uint16 IOHAL_u16Read_CH_ADC_IN_M_AN_MOT_COS_2 (void)
{
   return ((uint16)VADC_u16GroupBuffer2[0]);
}
/**********************************************************************************************/
/* !Description: Read function from the ADC channel                                           */
/* !PORT:AN17                                                                                 */
/* !LastAuthor:                                                                               */
/**********************************************************************************************/
uint16 IOHAL_u16Read_CH_ADC_IN_M_AN_MOT_SIN_2 (void)
{
   return ((uint16)VADC_u16GroupBuffer2[1]);
}
/**********************************************************************************************/
/* !Description: Read function from the ADC channel                                           */
/* !PORT:AN20                                                                                 */
/* !LastAuthor:                                                                               */
/**********************************************************************************************/
uint16 IOHAL_u16Read_CH_ADC_IN_M_EPS_TEMP_MEAS_MOD_W (void)
{
   return ((uint16)VADC_u16GroupBuffer2[2]);
}
uint16 IOHAL_u16Read_CH_ADC_IN_AN_15V_RDC (void)
{
   return ((uint16)VADC_u16GroupBuffer2[2]);
}
/**********************************************************************************************/
/* !Description: Read function from the ADC channel                                           */
/* !PORT:AN21                                                                                 */
/* !LastAuthor:                                                                               */
/**********************************************************************************************/
uint16 IOHAL_u16Read_CH_ADC_IN_M_EPS_TEMP_MEAS_MOD_V (void)
{
   return ((uint16)VADC_u16GroupBuffer2[3]);
}
uint16 IOHAL_u16Read_CH_ADC_IN_AN_P5V_REF (void)
{
   return ((uint16)VADC_u16GroupBuffer2[3]);
}
/**********************************************************************************************/
/* !Description: Read function from the ADC channel                                           */
/* !PORT:AN22                                                                                 */
/* !LastAuthor:                                                                               */
/**********************************************************************************************/
uint16 IOHAL_u16Read_CH_ADC_IN_M_AN_DIAG_COS_L_2 (void)
{
   return ((uint16)VADC_u16GroupBuffer2[4]);
}
/**********************************************************************************************/
/* !Description: Read function from the ADC channel                                           */
/* !PORT:AN23                                                                                 */
/* !LastAuthor:                                                                               */
/**********************************************************************************************/
uint16 IOHAL_u16Read_CH_ADC_IN_M_AN_DIAG_COS_H_2 (void)
{
   return ((uint16)VADC_u16GroupBuffer2[5]);
}
/**********************************************************************************************/
/* !Description: Read function from the ADC channel                                           */
/* !PORT:AN24                                                                                 */
/* !LastAuthor:                                                                               */
/**********************************************************************************************/
uint16 IOHAL_u16Read_CH_ADC_IN_M_AN_CURRENT_U_2 (void)
{
   return ((uint16)VADC_u16GroupBuffer3[0]);
}
/**********************************************************************************************/
/* !Description: Read function from the ADC channel                                           */
/* !PORT:AN25                                                                                 */
/* !LastAuthor:                                                                               */
/**********************************************************************************************/
uint16 IOHAL_u16Read_CH_ADC_IN_M_AN_CURRENT_V_2 (void)
{
   return ((uint16)VADC_u16GroupBuffer3[1]);
}
/**********************************************************************************************/
/* !Description: Read function from the ADC channel                                           */
/* !PORT:AN26                                                                                 */
/* !LastAuthor:                                                                               */
/**********************************************************************************************/
uint16 IOHAL_u16Read_CH_ADC_IN_M_AN_CURRENT_W_2 (void)
{
   return ((uint16)VADC_u16GroupBuffer3[2]);
}
/**********************************************************************************************/
/* !Description: Read function from the ADC channel                                           */
/* !PORT:AN27                                                                                 */
/* !LastAuthor:                                                                               */
/**********************************************************************************************/
uint16 IOHAL_u16Read_CH_ADC_IN_M_IO_MUX1 (void)
{
   return ((uint16)VADC_u16GroupBuffer3_1[0]);
}
/**********************************************************************************************/
/* !Description: Read function from the ADC channel                                           */
/* !PORT:AN28                                                                                 */
/* !LastAuthor:                                                                               */
/**********************************************************************************************/
uint16 IOHAL_u16Read_CH_ADC_IN_M_AN_MUX1 (void)
{
   return ((uint16)VADC_u16GroupBuffer3_1[1]);
}
/**********************************************************************************************/
/* !Description: Read function from the ADC channel                                           */
/* !PORT:AN29                                                                                 */
/* !LastAuthor:                                                                               */
/**********************************************************************************************/
uint16 IOHAL_u16Read_CH_ADC_IN_M_AN_MUX2 (void)
{
   return ((uint16)VADC_u16GroupBuffer3_1[2]);
}
/**********************************************************************************************/
/* !Description: Read function from the ADC channel                                           */
/* !PORT:AN30                                                                                 */
/* !LastAuthor:                                                                               */
/**********************************************************************************************/
uint16 IOHAL_u16Read_CH_ADC_IN_M_AN_MUX4 (void)
{
   return ((uint16)VADC_u16GroupBuffer3_1[4]);
}
/**********************************************************************************************/
/* !Description: Read function from the ADC channel                                           */
/* !PORT:AN31                                                                                 */
/* !LastAuthor:                                                                               */
/**********************************************************************************************/
uint16 IOHAL_u16Read_CH_ADC_IN_M_AN_MUX3 (void)
{
   return ((uint16)VADC_u16GroupBuffer3_1[3]);
}
/**********************************************************************************************/
/* !Description: Read function from the ADC channel                                           */
/* !PORT:AN32                                                                                 */
/* !LastAuthor:                                                                               */
/**********************************************************************************************/
uint16 IOHAL_u16Read_CH_ADC_IN_M_AN_DIAG_COS_H_1 (void)
{
   return ((uint16)VADC_u16GroupBuffer11[1]);
}
/**********************************************************************************************/
/* !Description: Read function from the ADC channel                                           */
/* !PORT:AN33                                                                                 */
/* !LastAuthor:                                                                               */
/**********************************************************************************************/
uint16 IOHAL_u16Read_CH_ADC_IN_M_AN_DIAG_COS_L_1 (void)
{
   return ((uint16)VADC_u16GroupBuffer11[2]);
}

/**********************************************************************************************/
/* !Description: Read function from the ADC channel                                           */
/* !PORT:AN35                                                                                 */
/* !LastAuthor:                                                                               */
/**********************************************************************************************/
uint16 IOHAL_u16Read_CH_ADC_IN_M_AN_DIAG_SIN_H_1 (void)
{
   return ((uint16)VADC_u16GroupBuffer8[8]);
}
/**********************************************************************************************/
/* !Description: Read function from the ADC channel                                           */
/* !PORT:AN37                                                                                 */
/* !LastAuthor:                                                                               */
/**********************************************************************************************/
uint16 IOHAL_u16Read_CH_ADC_IN_M_AN_DIAG_SIN_L_2 (void)
{
   return ((uint16)VADC_u16GroupBuffer11[0]);
}
/**********************************************************************************************/
/* !Description: Read function from the ADC channel                                           */
/* !PORT:AN38                                                                                 */
/* !LastAuthor:                                                                               */
/**********************************************************************************************/
uint16 IOHAL_u16Read_CH_ADC_IN_M_AN_DIAG_SIN_L_1 (void)
{
   return ((uint16)VADC_u16GroupBuffer8[9]);
}
/**********************************************************************************************/
/* !Description: Read function from the ADC channel                                           */
/* !PORT:AN39                                                                                 */
/* !LastAuthor:                                                                               */
/**********************************************************************************************/

/**********************************************************************************************/
/* !Description: Read function from the ADC channel                                           */
/* !PORT:AN40                                                                                 */
/* !LastAuthor:                                                                               */
/**********************************************************************************************/
uint16 IOHAL_u16Read_CH_ADC_IN_M_ACM_AN_CURRENT_U (void)
{
   return ((uint16)VADC_u16GroupBuffer8_2[0]);
}
/**********************************************************************************************/
/* !Description: Read function from the ADC channel                                           */
/* !PORT:AN41                                                                                 */
/* !LastAuthor:                                                                               */
/**********************************************************************************************/
uint16 IOHAL_u16Read_CH_ADC_IN_M_ACM_AN_CURRENT_V (void)
{
   return ((uint16)VADC_u16GroupBuffer8_2[1]);
}
/**********************************************************************************************/
/* !Description: Read function from the ADC channel                                           */
/* !PORT:AN42                                                                                 */
/* !LastAuthor:                                                                               */
/**********************************************************************************************/
uint16 IOHAL_u16Read_CH_ADC_IN_M_EPS_AN_CURRENT_U (void)
{
   return ((uint16)VADC_u16GroupBuffer8_2[3]);
}
/**********************************************************************************************/
/* !Description: Read function from the ADC channel                                           */
/* !PORT:AN43                                                                                 */
/* !LastAuthor:                                                                               */
/**********************************************************************************************/
uint16 IOHAL_u16Read_CH_ADC_IN_M_EPS_AN_CURRENT_V (void)
{
   return ((uint16)VADC_u16GroupBuffer8_2[4]);
}
/**********************************************************************************************/
/* !Description: Read function from the ADC channel                                           */
/* !PORT:AN44                                                                                 */
/* !LastAuthor:                                                                               */
/**********************************************************************************************/
uint16 IOHAL_u16Read_CH_ADC_IN_M_ACM_AN_CURRENT_W (void)
{
   return ((uint16)VADC_u16GroupBuffer8_2[2]);
}
/**********************************************************************************************/
/* !Description: Read function from the ADC channel                                           */
/* !PORT:AN45                                                                                 */
/* !LastAuthor:                                                                               */
/**********************************************************************************************/
uint16 IOHAL_u16Read_CH_ADC_IN_M_EPS_AN_CURRENT_W (void)
{
   return ((uint16)VADC_u16GroupBuffer8_2[5]);
}
/**********************************************************************************************/
/* !Description: Read function from the ADC channel                                           */
/* !PORT:AN46                                                                                 */
/* !LastAuthor:                                                                               */
/**********************************************************************************************/
uint16 IOHAL_u16Read_CH_ADC_IN_M_AN_MUX5 (void)
{
   return ((uint16)VADC_u16GroupBuffer8[0]);
}
uint16 IOHAL_u16Read_CH_ADC_IN_M_AN_MUX6 (void)
{
   return ((uint16)VADC_u16GroupBuffer8[1]);
}
/**********************************************************************************************/
/* !Description: Read function from the ADC channel                                           */
/* !PORT:AN47                                                                                 */
/* !LastAuthor:                                                                               */
/**********************************************************************************************/
uint16 IOHAL_u16Read_CH_ADC_IN_M_AN_MUX7 (void)
{
   return ((uint16)VADC_u16GroupBuffer8[2]);
}
uint16 IOHAL_u16Read_CH_ADC_IN_M_AN_MUX8 (void)
{
   return ((uint16)VADC_u16GroupBuffer8[3]);
}
uint16 IOHAL_u16Read_CH_ADC_IN_M_AN_MUX9 (void)
{
   return ((uint16)VADC_u16GroupBuffer8[4]);
}
uint16 IOHAL_u16Read_CH_ADC_IN_M_AN_MUX10 (void)
{
   return ((uint16)VADC_u16GroupBuffer8[5]);
}
uint16 IOHAL_u16Read_CH_ADC_IN_M_AN_MUX11 (void)
{
   return ((uint16)VADC_u16GroupBuffer8[6]);
}
uint16 IOHAL_u16Read_CH_ADC_IN_M_AN_MUX12 (void)
{
   return ((uint16)VADC_u16GroupBuffer8[7]);
}

uint16 IOHAL_u16Read_CH_ADC_IN_LV_VOL_SAMPLE(void)
{
   return PMux_u16GetInputVal(ePMUX_AN0_MUX10);
}

uint16 IOHAL_u16Read_CH_ADC_IN_P5V_COM_SAMPLE(void)
{
   return PMux_u16GetInputVal(ePMUX_AN2_MUX11);
}

uint16 IOHAL_u16Read_CH_ADC_IN_P5V_BT_SAMPLE(void)
{
   return PMux_u16GetInputVal(ePMUX_AN3_MUX11);
}

uint16 IOHAL_u16Read_CH_ADC_IN_P5V_HS_SAMPLE(void)
{
   return PMux_u16GetInputVal(ePMUX_AN2_MUX10);
}

uint16 IOHAL_u16Read_CH_ADC_IN_P5V_LS_SAMPLE(void)
{
   return PMux_u16GetInputVal(ePMUX_AN3_MUX10);
}

/**********************************************************************************************/
/* !Description: Read function from the PWM channel                                           */
/* !PORT:                                                                                     */
/* !LastAuthor:                                                                               */
/**********************************************************************************************/

float32 IOHAL_u16Read_CH_PWM_IN_M_TEMP_MEAS_MOD_U_2(void)
{
   return Icu_f32Cycle_M_TEMP_MEAS_MOD_U_2;
}
float32 IOHAL_u16Read_CH_PWM_IN_M_TEMP_MEAS_MOD_V_2(void)
{
   return Icu_f32Cycle_M_TEMP_MEAS_MOD_V_2;
}
float32 IOHAL_u16Read_CH_PWM_IN_M_TEMP_MEAS_MOD_W_2(void)
{
   return Icu_f32Cycle_M_TEMP_MEAS_MOD_W_2;
}
float32 IOHAL_u16Read_CH_PWM_IN_AN_VOL_DCLINK_EPS(void)
{
   return Icu_f32Cycle_AN_VOL_DCLINK_EPS;
}
float32 IOHAL_u16Read_CH_PWM_IN_AN_VOL_DCLINK_ACM(void)
{
   return Icu_f32Cycle_AN_VOL_DCLINK_ACM;
}
float32 IOHAL_u16Read_CH_PWM_IN_M_TEMP_MEAS_MOD_W_1(void)
{
   return Icu_f32Cycle_M_TEMP_MEAS_MOD_W_1;
}
float32 IOHAL_u16Read_CH_PWM_IN_M_TEMP_MEAS_MOD_V_1(void)
{
   return Icu_f32Cycle_M_TEMP_MEAS_MOD_V_1;
}
float32 IOHAL_u16Read_CH_PWM_IN_M_TEMP_MEAS_MOD_U_1(void)
{
   return Icu_f32Cycle_M_TEMP_MEAS_MOD_U_1;
}

float32 IOHAL_u16Read_CH_PWM_IN_M_EPS_TEMP_MEAS_MOD_W(void)
{
   return Icu_f32Cycle_M_EPS_TEMP_MEAS_MOD_W;
}
float32 IOHAL_u16Read_CH_PWM_IN_M_EPS_TEMP_MEAS_MOD_V(void)
{
   return Icu_f32Cycle_M_EPS_TEMP_MEAS_MOD_V;
}
float32 IOHAL_u16Read_CH_PWM_IN_M_ACM_TEMP_MEAS_MOD_W(void)
{
   return Icu_f32Cycle_M_ACM_TEMP_MEAS_MOD_W;
}
float32 IOHAL_u16Read_CH_PWM_IN_M_ACM_TEMP_MEAS_MOD_V(void)
{
   return Icu_f32Cycle_M_ACM_TEMP_MEAS_MOD_V;
}

#define IOHAL_STOP_SEC_CODE
#include "IOHAL_MemMap.h"

/*------------------------------ end of file ---------------------------------*/

