/*******************************************************************************
**                                                                            **
** Copyright (C) Hitex (UK) Ltd. (2020)                                       **
**                                                                            **
** All rights reserved.                                                       **
**                                                                            **
** This source code and any compilation or derivative thereof is the sole     **
** property of Hitex (UK) Ltd. and is provided pursuant to a Software         **
** License  Agreement. This code is the proprietary information of            **
** Hitex (UK) Ltd. and is confidential in nature. Its use and dissemination   **
** by any other party other than Hitex (UK) Ltd. is strictly limited by the   **
** confidential information provisions of the Agreement referenced above.     **
**                                                                            **
********************************************************************************
**                                                                            **
** FILENAME : TstM.c                                                          **
**                                                                            **
** REVISION : \$Revision: 29886 $                                              **
**                                                                            **
** DATE : \$LastChangedDate:: 2021-08-03 #$                                   **
**                                                                            **
** PLATFORM : AURIX 2G (TC3XX)                                                **
**                                                                            **
** AUTHOR : AURIX-SW-Dev                                                      **
**                                                                            **
** VENDOR : Hitex (UK) Ltd.                                                   **
**                                                                            **
** DESCRIPTION : Test Manager Source File                                     **
**                                                                            **
** SPECIFICATION(S) : <spec name, version>                                    **
**                                                                            **
** MAY BE CHANGED BY USER : Yes                                               **
**                                                                            **
*******************************************************************************/

/*******************************************************************************
 ****  Imported Standard Header Files
 ******************************************************************************/

/*******************************************************************************
 ****  Imported Project Header Files
 ******************************************************************************/

#include "TstM.h"
#include "McalLib.h"
#include "AppCbk.h"
#include "Smu.h"
#include "IfxSrc_reg.h"
#include "irq.h"
#include "bswsrv.h"
#if(HTXSTPIF_WDG_STACK_STATUS == STD_ON)
#include "SafeWdgM.h"
#endif
/*******************************************************************************
 ****  Private Macro Definitions
 ******************************************************************************/

/* Startup Test Seed */
#define TSTM_STARTUP_TEST_SEED      (5U)

/* Enable/Disable Startup Test Group Signature Verification */
/* - Disable: (0U) */
/* - Enable : (1U) */
#define TSTM_VERIFY_SIGNATURE       (1U)

#define TSTM_TOTAL_TEST_SEED        (16U)

/*******************************************************************************
 ****  Private Type Definitions
 ******************************************************************************/

/*******************************************************************************
 ****  Constant Definitions
 ******************************************************************************/

/* Expected Startup Test Group Signatures (use the value generated by Signature tool) */
#if(HTXTESTHND_STARTUP_TEST_GROUPS > 0U)
static const uint32 TstM_ExpectedStartupTestGrpSig[HTXTESTHND_STARTUP_TEST_GROUPS] =
{
    0x1447D059U,
    0xFA53EF1BU,
    0x82DF3E6CU
};
#endif

#if(HTXSTPIF_WDG_STACK_STATUS == STD_OFF)
#if(HTXTESTHND_RUNTIME_TEST_GROUPS > 0U)
static const uint32 TstM_ExpectedRuntimeTestGrpSig[TSTM_TOTAL_TEST_SEED]=
{
 0x76288876U,
 0x2325F887U,
 0x6877AEB7U,
 0x3D7ADE46U,
 0xA27372AEU,
 0xF77E025FU,
 0xBC2C546FU,
 0xE921249EU,
 0xCC02AE20U,
 0x990FDED1U,
 0xD25D88E1U,
 0x8750F810U,
 0x185954F8U,
 0x4D542409U,
 0x06067239U,
 0x530B02C8U
};
#endif /* #if(HTXTESTHND_RUNTIME_TEST_GROUPS > 0U) */
#endif /* #if(HTXSTPIF_WDG_STACK_STATUS == STD_OFF) */

/*******************************************************************************
 ****  Variable Declarations
 ******************************************************************************/

#if(HTXTESTHND_RUNTIME_TEST_GROUPS > 0U)
/* Test signature buffer for run-time tests */
static uint32 TstM_RunTimeTestGroupSignatures[HTXTESTHND_RUNTIME_TEST_GROUPS];
#endif

/* Test seed */
static uint8 TstM_TstSeed;

/*******************************************************************************
 ****  Private Function Declarations
 ******************************************************************************/

/*******************************************************************************
 ****  Global Function Definitions
 ******************************************************************************/

/*******************************************************************************
 *
 * \function      : void TstM_Init(void)
 *
 * \description   : This function initialises Test Manager Module
 *
 *******************************************************************************
 *
 * \param[in]     : None
 *
 * \param[out]    : None
 *
 * \param[in,out] : None
 *
 * \return        : None
 *
 *******************************************************************************
 *
 * \service id:   : 0x01
 *
 * \sync          : Synchronous
 *
 * \reentrancy    : Non-reentrant
 *
 * \pre           :
 * \post          :
 * \attention     : Only the Master Core shall call this function.
 * \traceability  :
 *
 ******************************************************************************/
void TstM_Init(void)
{
    Std_ReturnType Result;
    uint8 CoreId;

    Result = E_NOT_OK;

    /* Get Core Id */
    CoreId = (uint8)Mcal_GetCpuIndex();

    /* Check for Master Core */
    if(CoreId == HTXTESTHND_MASTER_CORE_ID)
    {
        /* Initialise Test Seed */
        TstM_TstSeed = 0U;

        /* Initialise Run-time Test Data */
        TstM_InvalidateRunTimeTestData();

        /* Initialise Test Handler */
        Result = HtxTestHnd_Init();
    }

    /* Check for error */
    if (Result != E_OK)
    {
        /* Report error */
        AppCbk_ErrorHandler(APPCBK_TSTM_INIT_FAIL);
    }

} /* End of TstM_Init() */

#if(HTXTESTHND_STARTUP_TEST_GROUPS > 0U)
/*******************************************************************************
 *
 * \function      : void TstM_ExecStartupTestGroup(uint8 GroupIndex)
 *
 * \description   : This function executes the given Startup Test Group
 *
 *******************************************************************************
 *
 * \param[in]     : GroupIndex - Startup Test Group Index
 *
 * \param[out]    : None
 *
 * \param[in,out] : None
 *
 * \return        : None
 *
 *******************************************************************************
 *
 * \service id:   : 0x02
 *
 * \sync          : Synchronous
 *
 * \reentrancy    : Non-reentrant
 *
 * \pre           :
 * \post          :
 * \attention     : GroupIndex shall belong to the calling core
 * \traceability  :
 *
 ******************************************************************************/
void TstM_ExecStartupTestGroup(uint8 GroupIndex)
{
    uint32 Signature;
    Std_ReturnType Result;

    Result = E_NOT_OK;

    /* Check for valid Startup Test Group Index */
    if(GroupIndex < HTXTESTHND_STARTUP_TEST_GROUPS)
    {
        /* Execute Startup Test Group */
        Result = HtxTestHnd_ExecStartupTestGrp(TSTM_STARTUP_TEST_SEED,
                                               GroupIndex,
                                               &Signature);

        #if (TSTM_VERIFY_SIGNATURE != 0U)
        /* Verify Test Group Signature */
        if(Signature != TstM_ExpectedStartupTestGrpSig[GroupIndex])
        {
            AppCbk_ErrorHandler(APPCBK_TSTM_STARTUP_TEST_FAIL);
        }
        #endif
    }

    /* Check for error */
    if(Result != E_OK)
    {
        /* Report error */
        AppCbk_ErrorHandler(APPCBK_TSTM_STARTUP_TEST_FAIL);
    }

} /* End of TstM_ExecStartupTestGroup() */
#endif /*#if(HTXTESTHND_STARTUP_TEST_GROUPS > 0U)*/

/*******************************************************************************
 *
 * \function      : void TstM_SwitchToRunPhase(void)
 *
 * \description   : This function switches Test Handler to RUN phase
 *
 *******************************************************************************
 *
 * \param[in]     : None
 *
 * \param[out]    : None
 *
 * \param[in,out] : None
 *
 * \return        : None
 *
 *******************************************************************************
 *
 * \service id:   : 0x03
 *
 * \sync          : Synchronous
 *
 * \reentrancy    : Non-reentrant
 *
 * \pre           :
 * \post          :
 * \attention     : Only the Master Core shall call this function.
 * \traceability  :
 *
 ******************************************************************************/
void TstM_SwitchToRunPhase(void)
{
    Std_ReturnType Result;
    Smu_CoreStateType lSmuState;
    uint8 CoreId;

    Result = E_NOT_OK;

    /* Get Core Id */
    CoreId = (uint8)Mcal_GetCpuIndex();

    /* Check for Master Core */
    if(CoreId == HTXTESTHND_MASTER_CORE_ID)
    {
        /* Initialise SMU driver */
        Result = Smu_Init(&Smu_Config);
        
        /* Check for error */
        if(Result == E_OK)
        {
            lSmuState = Smu_GetSmuState();

            /* Proceed further for valid states of SMU */
            if(lSmuState != SMU_UNDEFINED_STATE)
            {
                /* Note: SMU state machine is not affected by appl/sys reset */
                if(lSmuState != SMU_RUN_STATE)
                {
                    /* Setup FSP pin */
                    Result = Smu_SetupErrorPin();

                    if(Result == E_OK)
                    {
                        /* Release FSP */
                        Result = Smu_ReleaseFSP();
    
                        /* Check for error */
                        if(Result == E_OK)
                        {
                            /* Move SMU to RUN state */
                            Result = Smu_ActivateRunState(SMU_RUN_COMMAND);
                        }
                    }
                }

                /* Check for error */
                if(Result == E_OK)
                {
                    /* Lock the SMU configuration registers */
                    Result = Smu_LockConfigRegs();

                    /* Check for error */
                    if(Result == E_OK)
                    {
                        /* Switch Test Handler to RUN Phase */
                        Result = HtxTestHnd_SwitchToRunPhase();
                    }
                }
                
                SRC_SMU0.U = ((uint32)((uint32)1U << 10) | (uint32)((uint32)0 << 11) | (uint32)250);
            }
            else
            {
                Result = E_NOT_OK;
            }
        }
    }

    /* Check for error */
    if(Result != E_OK)
    {
        /* Report error */
        AppCbk_ErrorHandler(APPCBK_TSTM_SWITCH_TO_RUN_FAIL);
    }

} /* End of TstM_SwitchToRunPhase() */

#if(HTXTESTHND_RUNTIME_TEST_GROUPS > 0U)
/*******************************************************************************
 *
 * \function      : void TstM_ExecRunTimeTestGroup(uint8 GroupIndex)
 *
 * \description   : This function executes the given Run-time Test Group
 *
 *******************************************************************************
 *
 * \param[in]     : GroupIndex - Run-time Test Group Index
 *
 * \param[out]    : None
 *
 * \param[in,out] : None
 *
 * \return        : None
 *
 *******************************************************************************
 *
 * \service id:   : 0x04
 *
 * \sync          : Synchronous
 *
 * \reentrancy    : Non-reentrant
 *
 * \pre           :
 * \post          :
 * \attention     : GroupIndex shall belong to the calling core
 * \traceability  :
 *
 ******************************************************************************/
volatile uint8 signseed0[16] = {0};
void TstM_ExecRunTimeTestGroup(uint8 GroupIndex)
{
    Std_ReturnType Result;
    uint8 CoreId;
    static uint8 active = 0;
    static uint8 i = 0;

    Result = E_NOT_OK;

    #if(HTXSTPIF_WDG_STACK_STATUS == STD_ON)
    CoreId = (uint8)Mcal_GetCpuIndex();
    /* Get seed from watchdog, first core to request will set it */
    if(HTXTESTHND_MASTER_CORE_ID == CoreId)
    {
       if (TstM_TstSeed == HTXWDGIF_SAFEWDG_SEED_NOTVALID)
       {
          SafeWdgM_GetSeed(&TstM_TstSeed);
          BSW_vidSetProgFlowSeed(TstM_TstSeed);
          if(0 == active)
          {
             signseed0[i] = TstM_TstSeed;
             i++;
             if(i == 16)
             {
               active = 1;
             }
          }
       }
    }
    #endif

    /* Check for valid Run-time Test Group Index */
    if(GroupIndex < HTXTESTHND_RUNTIME_TEST_GROUPS)
    {
        /* Execute Run-time Test Group */
        Result = HtxTestHnd_ExecRuntimeTestGrp(TstM_TstSeed,
                                               GroupIndex,
                                               &TstM_RunTimeTestGroupSignatures[GroupIndex]);
    }

    /* Check for error */
    if (Result != E_OK)
    {
        /* Report error */
        AppCbk_ErrorHandler(APPCBK_TSTM_RUNTIME_TEST_FAIL);
    }

} /* End of TstM_ExecRunTimeTestGroup() */
#endif /* #if(HTXTESTHND_RUNTIME_TEST_GROUPS > 0U) */

#if(HTXTESTHND_RUNTIME_TEST_GROUPS > 0U)
/*******************************************************************************
 *
 * \function      : void TstM_ExecRuntimeTest(void)
 *
 * \description   : This function executes the runtime tests
 *
 *******************************************************************************
 *
 * \param[in]     : None
 *
 * \param[out]    : None
 *
 * \param[in,out] : None
 *
 * \return        : None
 *
 *******************************************************************************
 *
 * \service id:   : 0x05
 *
 * \sync          : Synchronous
 *
 * \reentrancy    : Non-reentrant
 *
 * \pre           :
 * \post          :
 * \attention     :
 * \traceability  :
 *
 ******************************************************************************/
void TstM_ExecRuntimeTest(void)
{
    uint8 CoreId, index;

    CoreId = (uint8)Mcal_GetCpuIndex();

    for(index=0U; index<HTXTESTHND_RUNTIME_TEST_GROUPS; index++)
    {
        if(HtxTestHnd_kRunTimeTestGrpCore[index] == CoreId)
        {
            TstM_ExecRunTimeTestGroup(index);
        }
    }

} /* End of TstM_ExecRuntimeTest() */
#endif /* #if(HTXTESTHND_RUNTIME_TEST_GROUPS > 0U) */

#if(HTXSTPIF_WDG_STACK_STATUS == STD_ON)
/*******************************************************************************
 *
 * \function      : void TstM_InvalidateSeed(void)
 *
 * \description   : This function invalidates Test Seed
 *
 *******************************************************************************
 *
 * \param[in]     : None
 *
 * \param[out]    : None
 *
 * \param[in,out] : None
 *
 * \return        : None
 *
 *******************************************************************************
 *
 * \service id:   : 0x05
 *
 * \sync          : Synchronous
 *
 * \reentrancy    : Non-reentrant
 *
 * \pre           :
 * \post          :
 * \attention     :
 * \traceability  :
 *
 ******************************************************************************/
void TstM_InvalidateSeed(void)
{
    /* Invalidate Test Seed */
    TstM_TstSeed = HTXWDGIF_SAFEWDG_SEED_NOTVALID;

} /* End of TstM_InvalidateSeed() */
#endif

/*******************************************************************************
 *
 * \function      : void TstM_InvalidateRunTimeTestData(void)
 *
 * \description   : This function invalidates Run-time Test Data
 *
 *******************************************************************************
 *
 * \param[in]     : None
 *
 * \param[out]    : None
 *
 * \param[in,out] : None
 *
 * \return        : None
 *
 *******************************************************************************
 *
 * \service id:   : 0x06
 *
 * \sync          : Synchronous
 *
 * \reentrancy    : Non-reentrant
 *
 * \pre           :
 * \post          :
 * \attention     :
 * \traceability  :
 *
 ******************************************************************************/
void TstM_InvalidateRunTimeTestData(void)
{
    #if(HTXTESTHND_RUNTIME_TEST_GROUPS > 0U)
    uint8 Index;

    HtxTestHnd_ClearRuntimeTestData();

    /* Invalidate Run-time Test Group Signatures */
    for(Index = 0U; Index < HTXTESTHND_RUNTIME_TEST_GROUPS; Index++)
    {
        TstM_RunTimeTestGroupSignatures[Index] = 0U;
    }
    #else
    /* user code */
    #endif
} /* End of TstM_InvalidateRunTimeTestData() */


/*******************************************************************************
 *
 * \function      : uint32 TstM_GetConsolidatedSignature(void)
 *
 * \description   : This function provides the consolidated run-time test group signature
 *
 *******************************************************************************
 *
 * \param[in]     : None
 *
 * \param[out]    : None
 *
 * \param[in,out] : None
 *
 * \return        : Consolidated run-time test group signature
 *
 *******************************************************************************
 *
 * \service id:   : 0x07
 *
 * \sync          : Synchronous
 *
 * \reentrancy    : Non-reentrant
 *
 * \pre           :
 * \post          :
 * \attention     :
 * \traceability  :
 *
 ******************************************************************************/
boolean TstM_bProgFlowStartFlag = FALSE;
boolean TstM_bGetProgFlowStartFlag(void)
{
   return TstM_bProgFlowStartFlag;
}

uint32 TstM_GetConsolidatedSignature(void)
{
    uint32 ConsolidatedSignature;
    uint32 u32LocAppSignature01 = 0;
    
    #if(HTXTESTHND_RUNTIME_TEST_GROUPS > 0U)
    uint8 Index;
    uint8 CoreId;
    #endif
    boolean bLocBswReady = FALSE;

    ConsolidatedSignature = 0U;

    #if(HTXTESTHND_RUNTIME_TEST_GROUPS > 0U)


    /* Consolidate signature across all the cores */
    for (CoreId = 0U; CoreId < MCAL_NO_OF_CORES; CoreId++)
    {
        /* Loop through each run-time test group */
        for(Index = 0U; Index < HTXTESTHND_RUNTIME_TEST_GROUPS; Index++)
        {
            /* Consolidate signature if CoreId matches */
            if(CoreId == HtxTestHnd_kRunTimeTestGrpCore[Index])
            {
                ConsolidatedSignature = CRC32(ConsolidatedSignature, TstM_RunTimeTestGroupSignatures[Index]);
            }
        }
    }
    #endif /* #if(HTXTESTHND_RUNTIME_TEST_GROUPS > 0U) */
    
    u32LocAppSignature01 = BSW_u32GetProgFlowSign01();
    bLocBswReady = BSW_bGetBswReadySts();
    if(TRUE == bLocBswReady)
    {
       TstM_bProgFlowStartFlag = TRUE;
       ConsolidatedSignature = CRC32(ConsolidatedSignature, u32LocAppSignature01);
    }

    return ConsolidatedSignature;
} /* End of TstM_GetConsolidatedSignature() */

#if(HTXSTPIF_WDG_STACK_STATUS == STD_OFF)
/*******************************************************************************
 *
 * \function      : void TstM_VerifyRuntimeTestSig(void)
 *
 * \description   : This function verifies the Signature of the runtime tests
 *
 *******************************************************************************
 *
 * \param[in]     : None
 *
 * \param[out]    : None
 *
 * \param[in,out] : None
 *
 * \return        : None
 *
 *******************************************************************************
 *
 * \service id:   :
 *
 * \sync          : Synchronous
 *
 * \reentrancy    : Non-reentrant
 *
 * \pre           :
 * \post          :
 * \attention     :
 * \traceability  :
 *
 ******************************************************************************/
void TstM_VerifyRuntimeTestSig(void)
{
    uint32 lConsolidatedSignature;

    /* Get consolidated signature from Test Manager */
    lConsolidatedSignature = TstM_GetConsolidatedSignature();

    /* Report error if job result is not success/accepted */
    if(lConsolidatedSignature != TstM_ExpectedRuntimeTestGrpSig[TstM_TstSeed])
    {
        AppCbk_ErrorHandler(APPCBK_SWDGM_SERVICE_FAIL);
    }

    /* Invalidate Test Data and increment the seed */
    TstM_TstSeed = (TstM_TstSeed + 1) % TSTM_TOTAL_TEST_SEED;
    TstM_InvalidateRunTimeTestData();
}
#endif /* End of TstM_VerifyRuntimeTestSig() */

/*******************************************************************************
 ****  Private Function Definitions
 ******************************************************************************/


/* EOF */
