/******************************************************************************/
/*                                                                            */
/* !Layer           : SRVL                                                    */
/*                                                                            */
/* !Component       : GESM                                                     */
/* !Description     : StateFlow of GESM component                              */
/*                                                                            */
/* !File            : GESM_TRA.C                                               */
/*                                                                            */
/* !Scope           : Public                                                  */
/*                                                                            */
/* !Target          : All                                                     */
/*                                                                            */
/* !Vendor          : invt                                                    */
/*                                                                            */
/* Coding language  : C                                                       */
/*                                                                            */
/* COPYRIGHT 2007 invt                                                        */
/* all rights reserved                                                        */
/*                                                                            */
/******************************************************************************/
/** 10/27/22, 09:10:37: generated by Genecode v2.6.0.0                        */
/* From Source Template : GSTFSRV_TRA_C.TPL                                    */
/******************************************************************************/

#include "Std_Types.h"
#include "gesm_tra.h"
#include "gesm_dat.h"


/******************************************************************************/
/* GLOBAL FUNCTION DEFINITION                                                 */
/******************************************************************************/

/*----------------------------------------------------------------------------*/
/* GESM Stateflow transitions definition                                       */
/*----------------------------------------------------------------------------*/

#define GSTFSRV_START_SEC_CODE
#include "MemMap.h"

/* -------- GESM Stateflow ECU_STATE -------- */


/* SCHED_5MS Event */

/* TRANSITION FROM STARTUP_I_MODE*/

FUNC (void, GSTFSRV_CODE) GESM_vidFromGESM_ST0OnGESM_EV0(void)
{
   if((GESM_StpIState == GESM_SFT_STATE_15))
   {
      GESM_bfOutEventCarrier |= GO2_STARTUP_II_EVENT; 
      GSTFSRV_vidSET_ACTIVE_STATE(GESM, GESM_STF0, GESM_ST1);   /* Activation of state STARTUP_II_MODE for stateflow ECU_STATE */
   }
}

/* TRANSITION FROM STARTUP_II_MODE*/

FUNC (void, GSTFSRV_CODE) GESM_vidFromGESM_ST1OnGESM_EV0(void)
{
   if(((GESM_StpIINfState == GESM_SFT_STATE_15) || (GESM_StpIIFtState == GESM_SFT_STATE_15)))
   {
      GESM_bfOutEventCarrier |= GO2_OPERATIONAL_EVENT; 
      GSTFSRV_vidSET_ACTIVE_STATE(GESM, GESM_STF0, GESM_ST2);   /* Activation of state OPERATIONAL_MODE for stateflow ECU_STATE */
   }
}

/* TRANSITION FROM OPERATIONAL_MODE*/

FUNC (void, GSTFSRV_CODE) GESM_vidFromGESM_ST2OnGESM_EV0(void)
{
   if(((GESM_OpNfState == GESM_SFT_STATE_14) || (GESM_PwrLFtState == GESM_SFT_STATE_15)))
   {
          GESM_bfOutEventCarrier |= GO2_STARTUP_II_EVENT; 
          GSTFSRV_vidSET_ACTIVE_STATE(GESM, GESM_STF0, GESM_ST1);  /* Activation of state STARTUP_II_MODE for stateflow ECU_STATE */
   }
   else
   {
      if((GESM_OpNfState == GESM_SFT_STATE_15))
      {
          GESM_bfOutEventCarrier |= GO2_POWERLATCH_EVENT; 
          GSTFSRV_vidSET_ACTIVE_STATE(GESM, GESM_STF0, GESM_ST3);  /* Activation of state POWERLATCH_MODE for stateflow ECU_STATE */
      }
   }
}

/* TRANSITION FROM POWERLATCH_MODE*/

FUNC (void, GSTFSRV_CODE) GESM_vidFromGESM_ST3OnGESM_EV0(void)
{
   if(((GESM_PwrLNfState == GESM_SFT_STATE_15) && (GESM_bPowerOffModeInhC == 0)))
   {
          GESM_bfOutEventCarrier |= GO2_POWER_OFF_EVENT; 
          GSTFSRV_vidSET_ACTIVE_STATE(GESM, GESM_STF0, GESM_ST4);  /* Activation of state POWER_OFF_MODE for stateflow ECU_STATE */
   }
   else
   {
      if((GESM_PwrLNfState == GESM_SFT_STATE_14))
      {
          GESM_bfOutEventCarrier |= GO2_STARTUP_II_EVENT; 
          GSTFSRV_vidSET_ACTIVE_STATE(GESM, GESM_STF0, GESM_ST1);  /* Activation of state STARTUP_II_MODE for stateflow ECU_STATE */
      }
   }
}


/* GO2_STARTUP_I Event */

/* TRANSITION FROM STARTUP_II_MODE*/

FUNC (void, GSTFSRV_CODE) GESM_vidFromGESM_ST1OnGESM_EV1(void)
{
      GESM_bfOutEventCarrier |= GO2_STARTUP_I_EVENT; 
      GSTFSRV_vidSET_ACTIVE_STATE(GESM, GESM_STF0, GESM_ST0);   /* Activation of state STARTUP_I_MODE for stateflow ECU_STATE */
}

/* TRANSITION FROM OPERATIONAL_MODE*/

FUNC (void, GSTFSRV_CODE) GESM_vidFromGESM_ST2OnGESM_EV1(void)
{
      GESM_bfOutEventCarrier |= GO2_STARTUP_I_EVENT; 
      GSTFSRV_vidSET_ACTIVE_STATE(GESM, GESM_STF0, GESM_ST0);   /* Activation of state STARTUP_I_MODE for stateflow ECU_STATE */
}

/* TRANSITION FROM POWERLATCH_MODE*/

FUNC (void, GSTFSRV_CODE) GESM_vidFromGESM_ST3OnGESM_EV1(void)
{
      GESM_bfOutEventCarrier |= GO2_STARTUP_I_EVENT; 
      GSTFSRV_vidSET_ACTIVE_STATE(GESM, GESM_STF0, GESM_ST0);   /* Activation of state STARTUP_I_MODE for stateflow ECU_STATE */
}

/* TRANSITION FROM POWER_OFF_MODE*/

FUNC (void, GSTFSRV_CODE) GESM_vidFromGESM_ST4OnGESM_EV1(void)
{
      GESM_bfOutEventCarrier |= GO2_STARTUP_I_EVENT; 
      GSTFSRV_vidSET_ACTIVE_STATE(GESM, GESM_STF0, GESM_ST0);   /* Activation of state STARTUP_I_MODE for stateflow ECU_STATE */
}




#define GSTFSRV_STOP_SEC_CODE
#include "MemMap.h"

/*-------------------------------- END OF FILE -------------------------------*/
