/******************************************************************************/
/*                                                                            */
/* !Layer           : SRVL                                                    */
/*                                                                            */
/* !Component       : GESM                                                     */
/* !Description     : StateFlow of GESM component                              */
/*                                                                            */
/* !File            : GESM_DAT.C                                               */
/*                                                                            */
/* !Scope           : Public                                                  */
/*                                                                            */
/* !Target          : All                                                     */
/*                                                                            */
/* !Vendor          : invt                                                    */
/*                                                                            */
/* Coding language  : C                                                       */
/*                                                                            */
/* COPYRIGHT 2007 invt                                                        */
/* all rights reserved                                                        */
/*                                                                            */
/******************************************************************************/
/** 10/27/22, 09:10:37: generated by Genecode v2.6.0.0                        */
/* From Source Template : GSTFSRV_DAT_C.TPL                                    */
/******************************************************************************/


#include "Std_Types.h"
#include "gstfsrv_types.h"
#include "GESM_DAT.h"


/******************************************************************************/
/* DATA DECLARATION                                                           */
/******************************************************************************/

/*----------------------------------------------------------------------------*/
/* GESM On event transition pointers                                           */
/*----------------------------------------------------------------------------*/

/* Stateflows :  ECU_STATE <=> GESM_STF0 */
/* Events :  IN_EVENT <=> GESM_EV0, IN_EVENT <=> GESM_EV1 */

#define GSTFSRV_START_SEC_VAR_UNSPECIFIED
#include "MemMap.h"

VAR (GSTFSRV_tpfFunctionPointerType, GSTFSRV_VAR) GESM_pfTransGESM_STF0OnGESM_EV0Ptr;
VAR (GSTFSRV_tpfFunctionPointerType, GSTFSRV_VAR) GESM_pfTransGESM_STF0OnGESM_EV1Ptr;
VAR (GSTFSRV_tpfFunctionPointerType, GSTFSRV_VAR) GESM_pfDuringGESM_STF0OnGESM_EV0Ptr;
VAR (GSTFSRV_tpfFunctionPointerType, GSTFSRV_VAR) GESM_pfDuringGESM_STF0OnGESM_EV1Ptr;

#define GSTFSRV_STOP_SEC_VAR_UNSPECIFIED
#include "MemMap.h"


#define GSTFSRV_START_SEC_VAR_16BIT
#include "MemMap.h"

VAR (uint16, GSTFSRV_VAR) GESM_bfOutEventCarrier;

#define GSTFSRV_STOP_SEC_VAR_16BIT
#include "MemMap.h"


/******************************************************************************/
/* GLOBAL FUNCTION DEFINITION                                                 */
/******************************************************************************/

/*----------------------------------------------------------------------------*/
/* GESM common data                                                            */
/*----------------------------------------------------------------------------*/

#define GSTFSRV_START_SEC_CODE
#include "MemMap.h"

FUNC (void, GSTFSRV_CODE) GESM_vidNoAction(void){}

#define GSTFSRV_STOP_SEC_CODE
#include "MemMap.h"

/*-------------------------------- END OF FILE -------------------------------*/
