/******************************************************************************/
/*                                                                            */
/* !Layer           : SRVL                                                    */
/*                                                                            */
/* !Component       : GESM                                                     */
/* !Description     : StateFlow of GESM component                              */
/*                                                                            */
/* !File            : GESM_STA.C                                               */
/*                                                                            */
/* !Scope           : Public                                                  */
/*                                                                            */
/* !Target          : All                                                     */
/*                                                                            */
/* !Vendor          : invt                                                    */
/*                                                                            */
/* Coding language  : C                                                       */
/*                                                                            */
/* COPYRIGHT 2007 invt                                                        */
/* all rights reserved                                                        */
/*                                                                            */
/******************************************************************************/
/** 10/27/22, 09:10:37: generated by Genecode v2.6.0.0                        */
/* From Source Template : GSTFSRV_STA_C.TPL                                    */
/******************************************************************************/

#include "Std_Types.h"
#include "gesm_tra.h"
#include "gesm_dat.h"
#include "gstfsrv_Includes.h"


/******************************************************************************/
/* GLOBAL FUNCTION DEFINITION                                                 */
/******************************************************************************/

/*----------------------------------------------------------------------------*/
/* GESM Stateflow Entry definition                                             */
/*----------------------------------------------------------------------------*/

#define GSTFSRV_START_SEC_CODE
#include "MemMap.h"

/* -------- GESM Stateflow ECU_STATE -------- */
/* ENTRY FUNCTIONS */

/* ENTRY FUNCTION FOR STARTUP_I_MODE*/
FUNC (void, GSTFSRV_CODE) GESM_vidEntryGESM_ST0(void)
{
   GESM_pfTransGESM_STF0OnGESM_EV0Ptr = GESM_GESM_ST0_ON_GESM_EV0_TRANS;
   GESM_pfTransGESM_STF0OnGESM_EV1Ptr = GESM_GESM_ST0_ON_GESM_EV1_TRANS;
   GESM_pfDuringGESM_STF0OnGESM_EV0Ptr = GESM_GESM_ST0_ON_GESM_EV0_DURING;
   GESM_pfDuringGESM_STF0OnGESM_EV1Ptr = GESM_GESM_ST0_ON_GESM_EV1_DURING;
   GESM_vidInit();
}

/* ENTRY FUNCTION FOR STARTUP_II_MODE*/
FUNC (void, GSTFSRV_CODE) GESM_vidEntryGESM_ST1(void)
{
   GESM_pfTransGESM_STF0OnGESM_EV0Ptr = GESM_GESM_ST1_ON_GESM_EV0_TRANS;
   GESM_pfTransGESM_STF0OnGESM_EV1Ptr = GESM_GESM_ST1_ON_GESM_EV1_TRANS;
   GESM_pfDuringGESM_STF0OnGESM_EV0Ptr = GESM_GESM_ST1_ON_GESM_EV0_DURING;
   GESM_pfDuringGESM_STF0OnGESM_EV1Ptr = GESM_GESM_ST1_ON_GESM_EV1_DURING;
}

/* ENTRY FUNCTION FOR OPERATIONAL_MODE*/
FUNC (void, GSTFSRV_CODE) GESM_vidEntryGESM_ST2(void)
{
   GESM_pfTransGESM_STF0OnGESM_EV0Ptr = GESM_GESM_ST2_ON_GESM_EV0_TRANS;
   GESM_pfTransGESM_STF0OnGESM_EV1Ptr = GESM_GESM_ST2_ON_GESM_EV1_TRANS;
   GESM_pfDuringGESM_STF0OnGESM_EV0Ptr = GESM_GESM_ST2_ON_GESM_EV0_DURING;
   GESM_pfDuringGESM_STF0OnGESM_EV1Ptr = GESM_GESM_ST2_ON_GESM_EV1_DURING;
}

/* ENTRY FUNCTION FOR POWERLATCH_MODE*/
FUNC (void, GSTFSRV_CODE) GESM_vidEntryGESM_ST3(void)
{
   GESM_pfTransGESM_STF0OnGESM_EV0Ptr = GESM_GESM_ST3_ON_GESM_EV0_TRANS;
   GESM_pfTransGESM_STF0OnGESM_EV1Ptr = GESM_GESM_ST3_ON_GESM_EV1_TRANS;
   GESM_pfDuringGESM_STF0OnGESM_EV0Ptr = GESM_GESM_ST3_ON_GESM_EV0_DURING;
   GESM_pfDuringGESM_STF0OnGESM_EV1Ptr = GESM_GESM_ST3_ON_GESM_EV1_DURING;
   GSTFSRV_vidINIT_TEMPO(GESM, GESM_POWERLATCH_TEMPO);
}

/* ENTRY FUNCTION FOR POWER_OFF_MODE*/
FUNC (void, GSTFSRV_CODE) GESM_vidEntryGESM_ST4(void)
{
   GESM_pfTransGESM_STF0OnGESM_EV0Ptr = GESM_GESM_ST4_ON_GESM_EV0_TRANS;
   GESM_pfTransGESM_STF0OnGESM_EV1Ptr = GESM_GESM_ST4_ON_GESM_EV1_TRANS;
   GESM_pfDuringGESM_STF0OnGESM_EV0Ptr = GESM_GESM_ST4_ON_GESM_EV0_DURING;
   GESM_pfDuringGESM_STF0OnGESM_EV1Ptr = GESM_GESM_ST4_ON_GESM_EV1_DURING;
}


/* DURING FUNCTIONS */

/* DURING FUNCTION FOR STARTUP_I_MODE ON SCHED_5MS*/
FUNC (void, GSTFSRV_CODE) GESM_vidDuringGESM_ST0OnGESM_EV0(void)
{
   GESM_vidStfStpI();
}

/* DURING FUNCTION FOR STARTUP_I_MODE ON GO2_STARTUP_I*/
FUNC (void, GSTFSRV_CODE) GESM_vidDuringGESM_ST0OnGESM_EV1(void)
{
   GESM_vidStfStpI();
}


/* DURING FUNCTION FOR STARTUP_II_MODE ON SCHED_5MS*/
FUNC (void, GSTFSRV_CODE) GESM_vidDuringGESM_ST1OnGESM_EV0(void)
{
   GESM_vidStfStpII();
}

/* DURING FUNCTION FOR STARTUP_II_MODE ON GO2_STARTUP_I*/
FUNC (void, GSTFSRV_CODE) GESM_vidDuringGESM_ST1OnGESM_EV1(void)
{
   GESM_vidStfStpII();
}


/* DURING FUNCTION FOR OPERATIONAL_MODE ON SCHED_5MS*/
FUNC (void, GSTFSRV_CODE) GESM_vidDuringGESM_ST2OnGESM_EV0(void)
{
   GESM_vidStfOp();
}

/* DURING FUNCTION FOR OPERATIONAL_MODE ON GO2_STARTUP_I*/
FUNC (void, GSTFSRV_CODE) GESM_vidDuringGESM_ST2OnGESM_EV1(void)
{
   GESM_vidStfOp();
}


/* DURING FUNCTION FOR POWERLATCH_MODE ON SCHED_5MS*/
FUNC (void, GSTFSRV_CODE) GESM_vidDuringGESM_ST3OnGESM_EV0(void)
{
   GESM_vidStfPwrL();
   GSTFSRV_vidDEC_TEMPO(GESM, GESM_POWERLATCH_TEMPO);
}

/* DURING FUNCTION FOR POWERLATCH_MODE ON GO2_STARTUP_I*/
FUNC (void, GSTFSRV_CODE) GESM_vidDuringGESM_ST3OnGESM_EV1(void)
{
   GESM_vidStfPwrL();
}


/* DURING FUNCTION FOR POWER_OFF_MODE ON SCHED_5MS*/
FUNC (void, GSTFSRV_CODE) GESM_vidDuringGESM_ST4OnGESM_EV0(void)
{
   GESM_vidStfPwrL();
}

/* DURING FUNCTION FOR POWER_OFF_MODE ON GO2_STARTUP_I*/
FUNC (void, GSTFSRV_CODE) GESM_vidDuringGESM_ST4OnGESM_EV1(void)
{
   GESM_vidStfPwrL();
}



/* IN EVENT EXEC FUNCTION */

FUNC (void, GSTFSRV_CODE) GESM_vidOnGESM_EV0(void)
{
   GSTFSRV_vidINTERNAL_SET_EVENT(GESM, GESM_STF0, GESM_EV0);
}
FUNC (void, GSTFSRV_CODE) GESM_vidOnGESM_EV1(void)
{
   GSTFSRV_vidINTERNAL_SET_EVENT(GESM, GESM_STF0, GESM_EV1);
}


/* OUT EVENT EXEC FUNCTION */

FUNC (void, GSTFSRV_CODE) GESM_vidExecOutEvent(uint16 bfCarrier)
{
   if ((bfCarrier & GO2_STARTUP_I_EVENT) != 0)
   {
      GGO2_STARTUP_I_EVENT_ACTION;
   }
   if ((bfCarrier & GO2_STARTUP_II_EVENT) != 0)
   {
      GGO2_STARTUP_II_EVENT_ACTION;
   }
   if ((bfCarrier & GO2_OPERATIONAL_EVENT) != 0)
   {
      GGO2_OPERATIONAL_EVENT_ACTION;
   }
   if ((bfCarrier & GO2_POWERLATCH_EVENT) != 0)
   {
      GGO2_POWERLATCH_EVENT_ACTION;
   }
   if ((bfCarrier & GO2_POWER_OFF_EVENT) != 0)
   {
      GGO2_POWER_OFF_EVENT_ACTION;
   }
}


#define GSTFSRV_STOP_SEC_CODE
#include "MemMap.h"


/*-------------------------------- END OF FILE -------------------------------*/