// H_File for initialization of MCS 
// generated by MCS assembler CASPR-MCS-1.1.6

#define MCS0_CH_INIT_RAM_LEN 100 
#define MCS0_tsk4_main 0x170
#define MCS0_tsk4_init 0x15c
#define MCS0_tsk3_main 0x13c
#define MCS0_tsk3_init 0x128
#define MCS0_tsk2_main 0x10c
#define MCS0_tsk2_init 0xf8
#define MCS0_tsk1_main 0xb0
#define MCS0_tsk1_init 0x9c
#define MCS0_tsk0_main 0x54
#define MCS0_tsk0_init 0x40
#define MCS0_var_h 0x3c
#define MCS0_var_g 0x38
#define MCS0_var_f 0x34
#define MCS0_var_e 0x30
#define MCS0_var_d 0x2c
#define MCS0_var_c 0x28
#define MCS0_var_b 0x24
#define MCS0_var_a 0x20
