ValidCodeList = []
dest = r".\donnee.txt"
Src_Oil = r".\FAULT.oil"
FAULT_Api_c  = r".\FAULT_Api.c"
FAULT_Api_h  = r".\FAULT_Api.h"
FAULT_Data_c = r".\FAULT_Data.c"
FAULT_Data_h = r".\FAULT_Data.h"

CompileFlagTxt = r".\CompiledFlag.txt"

HeadFileComment = "/******************************************************************************/\n\
/*                                                                            */\n\
/* !Layer           : SRV                                                     */\n\
/*                                                                            */\n\
/* !Component       : FAULT                                                   */\n\
/* !Description     :                                                         */\n\
/*                                                                            */\n\
/* !File            : FAULT_xxxx.x                                            */\n\
/*                                                                            */\n\
/* !Scope           : Public                                                  */\n\
/*                                                                            */\n\
/* !Target          : All                                                     */\n\
/*                                                                            */\n\
/* !Vendor          : invt                                                    */\n\
/*                                                                            */\n\
/* Coding language  : C                                                       */\n\
/*                                                                            */\n\
/* COPYRIGHT 2011 invt                                                        */\n\
/* all rights reserved                                                        */\n\
/*                                                                            */\n\
/******************************************************************************/\n\
/* SVN Information                                                            */\n\
/* $Archive:                                                                 $*/\n\
/* $Revision::            $$Author::                  $$Date::               $*/\n\
/******************************************************************************/\n\
/** Y-M-D H:M:S: generated by Genecode v2.6.0.0                       */\n\
/******************************************************************************/\n"

FuncComment = "\n/******************************************************************************/\n\
/*                                                                            */\n\
/*                                                                            */\n\
/******************************************************************************/\n\n"

DestList = []
DTCGroup_Invt = []
ValidCodeList = []
CodeStr = ""
DTCNum = 0
ModuleNum = 0
ModNum = 0

DTCName = []
DTC_Name = []
DTCModule = []
DTCNumInModule = []

IndexList = []
DECList = []           #''' Get DTC Name '''
INCList = []           #''' Get DTC Name '''
IRRList = []           #''' Get DTC Name '''
FailModList = []       #''' Get DTC Name '''
AUTList = []           #''' Get DTC Name '''
LockList = []          #''' Get DTC Name '''
CntIgnList = []        #''' Get DTC Name '''
IDList = []            #''' Get DTC Name '''
FailTypeList = []      #''' Get DTC Name '''


DTCModuleDefine = []
DTC_NameDefine = []
DTCCounterDefine = []
DTCINCDefine = []
DTCDECDefine = []
DTCFlagDefine = []
DTCModDefine = []

DTCFailModTable = []
DTCIncsTable = []
DTCDecsTable = []
DTCIrrTable = []
DTCAutInitTable = []
DTCLockedTable = []
DTCCntIgnTable = []
DTCOffsetTable = []
DTCIDTable = []
DTCFailTypeTable = []

FuncDefinitionCode = []
FuncDefine = []
FuncDeclaration = []

CompiledFlag = ''

import os
import re
import datetime
import sys
import time

now = datetime.datetime.now()
other_StyleTime = now.strftime("%Y-%m-%d %H:%M:%S")
print(other_StyleTime)

def TimeStampToTime(timestamp):
    timeStruct = time.localtime(timestamp)
    return time.strftime('%Y-%m-%d %H:%M:%S', timeStruct)

def search_dir(path):
    global CompiledFlag
    files = os.listdir(path) # Get all file name
    #print(files)
    FlagTime = 0
    OilTime = 0
    for file in files: # traversal dir
        if os.path.isdir(path+"\\"+file): # is sub dir
            search_dir(path+"\\"+file)
        else: # is file
            #print(path + "\\" + file)
            if file == Src_Oil[2:]:
                #print(file + " is oil file")
                OilTime = os.path.getmtime(path + "\\" + file)
                print("OilFile: " + TimeStampToTime(OilTime))
            elif file == os.path.basename(__file__):
                pass
            elif file == CompileFlagTxt[2:]:
                FlagTime = os.path.getmtime(path + "\\" + file)
                print("GeneratedFile: " + TimeStampToTime(FlagTime))
            else:
                #print(file + " is dest file")
                pass

    if OilTime > FlagTime:
        print("OilFile is Newer, Fault module needs to be updated\n")
    else:
        print("GeneratedFile is Newer, Fault module does not need to be updated\n")
        sys.exit(1)

path = r"."
search_dir(path)

f = open(Src_Oil)
lines = f.readlines()
for each in lines:
    InvalidCode0 = re.match(r"^/.*\n$", each)       #''' comment '''
    InvalidCode1 = re.match(r"^;.*\n$", each)       #''' comment '''
    InvalidCode2 = re.match(r"^ +\n$", each)        #''' space '''
    InvalidCode3 = re.match(r"^\n$", each)          #''' \n '''    
    InvalidCode4 = re.match(r"^\*/\n$", each)       #''' */ '''    
    ValidCode    = re.match(r"^ *\w+.*\n$", each)   #''' Valid Code '''
    
    if (ValidCode != None):
        ValidCodeList.append(each[:-1])
        #pass
        #print(each[:-1])
    elif (InvalidCode0 != None) or (InvalidCode1 != None) or (InvalidCode2 != None) or (InvalidCode3 != None) or (InvalidCode4 != None):
        pass
    else:
        ValidCodeList.append(each[:-1])
        #pass
        #print(each[:-1]) 
CodeStr = ''.join(ValidCodeList)
#for each in ValidCodeList[:5]:   
#    print(each)
f.close()

def GenDataDefine():
    global DTCNum
    global ModuleNum
    global ModNum
    global DTC_Name
    global DTCName
    global DTCModule
    global DTCNumInModule
    
    global IndexList
    global DECList           #''' Get DTC Name '''
    global INCList           #''' Get DTC Name '''
    global IRRList           #''' Get DTC Name '''
    global FailModList       #''' Get DTC Name '''
    global AUTList           #''' Get DTC Name '''
    global LockList          #''' Get DTC Name '''
    global CntIgnList        #''' Get DTC Name '''
    global IDList            #''' Get DTC Name '''
    global FailTypeList      #''' Get DTC Name '''
    
    DTCModule  = re.findall("FUNCTION (.*?){", CodeStr)       #''' Get Module Name '''
    DTCModuleContent = re.findall("FUNCTION (.*?)};\s*};", CodeStr)       #''' Get DTC Content '''

    for each in DTCModule:
        DTCModule[DTCModule.index(each)] = each + '                                                                      '     #''' Add Space To Sort '''
    
    for each in DTCModuleContent:
        DTCList = re.findall("{NAME = \"(.*?)\"", each)       #''' Get DTC Name '''
        DTCNumInModule.append(str(len(DTCList)))              #''' Get Number Of DTC In Each Module '''
        i = DTCModuleContent.index(each)

        TempDECList = re.findall("DEC *= (.*?);", each)           #''' Get DTC Name '''
        TempINCList = re.findall("INC *= (.*?);", each)           #''' Get DTC Name '''
        TempIRRList = re.findall("IRR *= (.*?);", each)           #''' Get DTC Name '''
        TempFailModList = re.findall("FAIL_MOD *= (.*?);", each)       #''' Get DTC Name '''
        TempAUTList = re.findall("AUT *= (.*?);", each)           #''' Get DTC Name '''
        TempLockList = re.findall("AUT_LOCK *= (.*?);", each)       #''' Get DTC Name '''
        TempCntIgnList = re.findall("CNT_IGN *= (.*?);", each)       #''' Get DTC Name '''
        TempIDList = re.findall("DTC_NB *= (.*?);", each)         #''' Get DTC Name '''
        TempFailTypeList = re.findall("DTC_FAILTYPE *= (.*?);", each)       #''' Get DTC Name '''

        DECList.extend(TempDECList)           #''' Get DTC Name '''
        INCList.extend(TempINCList)           #''' Get DTC Name '''
        IRRList.extend(TempIRRList)           #''' Get DTC Name '''
        FailModList.extend(TempFailModList)   #''' Get DTC Name '''
        AUTList.extend(TempAUTList)           #''' Get DTC Name '''
        LockList.extend(TempLockList)         #''' Get DTC Name '''
        CntIgnList.extend(TempCntIgnList)     #''' Get DTC Name '''
        IDList.extend(TempIDList)             #''' Get DTC Name '''
        FailTypeList.extend(TempFailTypeList) #''' Get DTC Name '''

        for DTC in DTCList:
            DTC_Name.append((DTCModule[i] + '_' + DTC).upper())
            DTCName.append(DTCModule[i] + DTC)

    temp = zip(DTCModule, DTCNumInModule)
    DTCModule, DTCNumInModule = (list(t) for t in zip(*sorted(temp)))

    for LocDTCNum in DTCNumInModule:
        IndexList.extend([Val for Val in range(0, int(LocDTCNum))])

    temp = zip(DTC_Name, DTCName, DECList, INCList, IRRList, FailModList, AUTList, LockList, CntIgnList, IDList, FailTypeList)
    DTC_Name, DTCName, DECList, INCList, IRRList, FailModList, AUTList, LockList, CntIgnList, IDList, FailTypeList = \
    (list(t) for t in zip(*sorted(temp)))

    #DTC_Name.sort(key = str.lower)
    #DTCName.sort(key = str.lower)

    TempModList = FailModList
    TempModList = list(set(TempModList))

    ModNum = len(TempModList)

    for each in DTC_Name:
        DTC_Name[DTC_Name.index(each)] = re.sub("\s*", '', each)

    for each in DTCName:
        DTCName[DTCName.index(each)] = re.sub("\s*", '', each)

    for each in DTCModule:
        DTCModule[DTCModule.index(each)] = re.sub("\s*", '', each)

    ListIndex = 0
    for each in IRRList:
        if re.sub("^[Ff].*", '0', each) == '0':
            IRRList[ListIndex] = re.sub("^[Ff].*", '0', each)
        else:
            IRRList[ListIndex] = '1'
        ListIndex += 1

    ListIndex = 0
    for each in AUTList:
        if re.sub("^[Ff].*", '0', each) == '0':
            AUTList[ListIndex] = re.sub("^[Ff].*", '0', each)
        else:
            AUTList[ListIndex] = '1'
        ListIndex += 1

    ListIndex = 0
    for each in LockList:
        if re.sub("^[Ff].*", '0', each) == '0':
            LockList[ListIndex] = re.sub("^[Ff].*", '0', each)
        else:
            LockList[ListIndex] = '1'
        ListIndex += 1

    ListIndex = 0
    for each in CntIgnList:
        if re.sub("^[Ff].*", '0', each) == '0':
            CntIgnList[ListIndex] = re.sub("^[Ff].*", '0', each)
        else:
            CntIgnList[ListIndex] = '1'
        ListIndex += 1

    ModuleNum = len(DTCModule)
    DTCNum = len(DTCName)

def GenComment(FileName):
    TempComment = HeadFileComment
    NameLen = len(FileName)
    if NameLen == 13:
        TempComment   = (re.sub("FAULT_xxxx.x", FileName[2:] + ' ', TempComment))    
        ResultComment = (re.sub("Y-M-D H:M:S", other_StyleTime, TempComment)) 
    elif NameLen == 14:
        TempComment   = (re.sub("FAULT_xxxx.x", FileName[2:], TempComment))    
        ResultComment = (re.sub("Y-M-D H:M:S", other_StyleTime, TempComment)) 
    return ResultComment

def GenSysNum(NumofModule, NumofDTC, NumofMod):
    temp = "#define   NB_FAULT_FUNCTION_TYPE              DTCNUM\n\
#define   NB_FAULT_FUNCTION                   MODULENUM\n\
#define   NB_FAIL_MOD_MAX                     MODNUM\n"
    HexAndComment = str(hex(NumofModule)) + "      /* " + str(NumofModule) + " */"
    temp   = (re.sub("MODULENUM", HexAndComment, temp))
    HexAndComment = str(hex(NumofDTC)) + "      /* " + str(NumofDTC) + " */"
    temp   = (re.sub("DTCNUM", HexAndComment, temp))
    Result = (re.sub("MODNUM", str(NumofMod), temp))
    return Result
    
def GenModuleDefine():
    for each in DTCModule:
        Temp = "#define " + each.upper()
        Length = 55 - len(Temp)
        #print(each + str(Length))
        SpaceList = [' ' for i in range(0, Length)]
        SpaceStr = ''.join(SpaceList)
        index = DTCModule.index(each)
        Str = Temp + SpaceStr + str(index) + '\n'
        DTCModuleDefine.append(Str)


def GenNameDefine():
    NameIndex = 0
    for LocDTCNum in DTCNumInModule:
        for ModuleIndex in range(0, int(LocDTCNum)):
            Temp = "#define " + DTC_Name[NameIndex]
            #print(DTC_Name[NameIndex])
            NameIndex += 1
            Length = 55 - len(Temp)
            SpaceList = [' ' for SpaceIndex in range(0, Length)]
            SpaceStr = ''.join(SpaceList)

            Array = str(ModuleIndex)
            Str = Temp + SpaceStr + Array + '\n'
            #print(Str)
            DTC_NameDefine.append(Str)

def GenCounterDefine():
    for each in DTCName:
        Temp = "#define Fault" + each + "Counter"
        Length = 55 - len(Temp)
        SpaceList = [' ' for i in range(0, Length)]
        SpaceStr = ''.join(SpaceList)
        Array = "FaultTableFuncTypeCounter1[{index}]".format(index = DTCName.index(each))
        Str = Temp + SpaceStr + Array + '\n'
        DTCCounterDefine.append(Str)

def GenINCDefine():
    for each in DTCName:
        Temp = "#define Fault" + each + "Inc"
        Length = 55 - len(Temp)
        SpaceList = [' ' for i in range(0, Length)]
        SpaceStr = ''.join(SpaceList)
        Array = "FaultFunctionTypeIncs[{index}]".format(index = DTCName.index(each))
        Str = Temp + SpaceStr + Array + '\n'
        DTCINCDefine.append(Str)

def GenDECDefine():
    for each in DTCName:
        Temp = "#define Fault" + each + "Dec"
        Length = 55 - len(Temp)
        SpaceList = [' ' for i in range(0, Length)]
        SpaceStr = ''.join(SpaceList)
        Array = "FaultFunctionTypeDecs[{index}]".format(index = DTCName.index(each))
        Str = Temp + SpaceStr + Array + '\n'
        DTCDECDefine.append(Str)

def GenFlagDefine():
    for each in DTCModule:
        Temp  = "extern FaultBitFieldType   Fault" + each + "Detected;\n"
        Temp1 = "extern FaultBitFieldType   Fault" + each + "Logged;\n"
        Str = Temp + Temp1 + '\n'
        DTCFlagDefine.append(Str)

def GenMODDefine():
    for each in DTCName:
        Temp = "#define Fault" + each + "FailMod"
        Length = 55 - len(Temp)
        SpaceList = [' ' for i in range(0, Length)]
        SpaceStr = ''.join(SpaceList)
        Array = "FaultFunctionTypeFailModTable[{index}]".format(index = DTCName.index(each))
        Str = Temp + SpaceStr + Array + '\n'
        DTCModDefine.append(Str)
    
def GenFailModTable():
    Index = 0
    for each in FailModList:
        Temp = "   " + each + " ,        /* " + DTCName[Index] + " */\n"
        Index += 1
        DTCFailModTable.append(Temp)

def GenIncsTable():
    Index = 0
    for each in INCList:
        Length = 2 - len('{:x}'.format(int(each)))
        ZeroList = ['0' for i in range(0, Length)]
        ZeroStr = ''.join(ZeroList)
        Temp = "   0x" + ZeroStr + '{:x}'.format(int(each)) + " ,        /* " + DTCName[Index] + " */\n"
        Index += 1
        DTCIncsTable.append(Temp)

def GenDecsTable():
    Index = 0
    for each in DECList:
        Length = 2 - len('{:x}'.format(int(each)))
        ZeroList = ['0' for i in range(0, Length)]
        ZeroStr = ''.join(ZeroList)
        Temp = "   0x" + ZeroStr + '{:x}'.format(int(each)) + " ,        /* " + DTCName[Index] + " */\n"
        Index += 1
        DTCDecsTable.append(Temp)

def GenIrrTable():
    Index = 0    
    for ArrayIndex in range(0, len(DTCModule)):
        LocDTCNum = DTCNumInModule[ArrayIndex]
        if LocDTCNum != "16":
            for BitIndex in range(0, int(LocDTCNum)):
                IrrVal = IRRList[Index]
                Temp = "   " + IrrVal + " << " + str(BitIndex) + " |       /* " + DTCName[Index] + " */\n"
                DTCIrrTable.append(Temp)
                Index += 1
            for BitIndex in range(int(LocDTCNum), 15):
                Temp = "   0 << " + str(BitIndex) + " |\n"
                DTCIrrTable.append(Temp)
            Temp = "   0 << 15 ,\n"
            DTCIrrTable.append(Temp)
        elif LocDTCNum == "16":
            for BitIndex in range(0, 15):
                IrrVal = IRRList[Index]
                Temp = "   " + IrrVal + " << " + str(BitIndex) + " |       /* " + DTCName[Index] + " */\n"
                DTCIrrTable.append(Temp)
                Index += 1
            BitIndex += 1
            IrrVal = IRRList[Index]
            Temp = "   " + IrrVal + " << " + str(BitIndex) + " ,       /* " + DTCName[Index] + " */\n"
            Index += 1
            DTCIrrTable.append(Temp)

def GenAutInitTable():
    Index = 0
    for ArrayIndex in range(0, len(DTCModule)):
        LocDTCNum = DTCNumInModule[ArrayIndex]
        if LocDTCNum != "16":
            for BitIndex in range(0, int(LocDTCNum)):
                AutVal = AUTList[Index]
                Temp = "   " + AutVal + " << " + str(BitIndex) + " |       /* " + DTCName[Index] + " */\n"
                DTCAutInitTable.append(Temp)
                Index += 1
            for BitIndex in range(int(LocDTCNum), 15):
                Temp = "   0 << " + str(BitIndex) + " |\n"
                DTCAutInitTable.append(Temp)
            Temp = "   0 << 15 ,\n"
            DTCAutInitTable.append(Temp)
        elif LocDTCNum == "16":
            for BitIndex in range(0, 15):
                AutVal = AUTList[Index]
                Temp = "   " + AutVal + " << " + str(BitIndex) + " |       /* " + DTCName[Index] + " */\n"
                DTCAutInitTable.append(Temp)
                Index += 1
            BitIndex += 1
            AutVal = AUTList[Index]
            Temp = "   " + AutVal + " << " + str(BitIndex) + " ,       /* " + DTCName[Index] + " */\n"
            Index += 1
            DTCAutInitTable.append(Temp)

def GenLockedTable():
    Index = 0
    for ArrayIndex in range(0, len(DTCModule)):
        LocDTCNum = DTCNumInModule[ArrayIndex]
        if LocDTCNum != "16":
            for BitIndex in range(0, int(LocDTCNum)):
                LockedVal = LockList[Index]
                Temp = "   " + LockedVal + " << " + str(BitIndex) + " |       /* " + DTCName[Index] + " */\n"
                DTCLockedTable.append(Temp)
                Index += 1
            for BitIndex in range(int(LocDTCNum), 15):
                Temp = "   0 << " + str(BitIndex) + " |\n"
                DTCLockedTable.append(Temp)
            Temp = "   0 << 15 ,\n"
            DTCLockedTable.append(Temp)
        elif LocDTCNum == "16":
            for BitIndex in range(0, 15):
                LockedVal = LockList[Index]
                Temp = "   " + LockedVal + " << " + str(BitIndex) + " |       /* " + DTCName[Index] + " */\n"
                DTCLockedTable.append(Temp)
                Index += 1
            BitIndex += 1
            LockedVal = LockList[Index]
            Temp = "   " + LockedVal + " << " + str(BitIndex) + " ,       /* " + DTCName[Index] + " */\n"
            Index += 1
            DTCLockedTable.append(Temp)

def GenCntIgnTable():
    Index = 0
    for ArrayIndex in range(0, len(DTCModule)):
        LocDTCNum = DTCNumInModule[ArrayIndex]
        if LocDTCNum != "16":
            for BitIndex in range(0, int(LocDTCNum)):
                CntIgnVal = CntIgnList[Index]
                Temp = "   " + CntIgnVal + " << " + str(BitIndex) + " |       /* " + DTCName[Index] + " */\n"
                DTCCntIgnTable.append(Temp)
                Index += 1
            for BitIndex in range(int(LocDTCNum), 15):
                Temp = "   0 << " + str(BitIndex) + " |\n"
                DTCCntIgnTable.append(Temp)
            Temp = "   0 << 15 ,\n"
            DTCCntIgnTable.append(Temp)
        elif LocDTCNum == "16":
            for BitIndex in range(0, 15):
                CntIgnVal = CntIgnList[Index]
                Temp = "   " + CntIgnVal + " << " + str(BitIndex) + " |       /* " + DTCName[Index] + " */\n"
                DTCCntIgnTable.append(Temp)
                Index += 1
            BitIndex += 1
            CntIgnVal = CntIgnList[Index]
            Temp = "   " + CntIgnVal + " << " + str(BitIndex) + " ,       /* " + DTCName[Index] + " */\n"
            Index += 1
            DTCCntIgnTable.append(Temp)

def GenOffsetTable():
    Index = 0
    NameIndex = 0
    for each in DTCNumInModule:
        Temp = "   " + str(Index) + " ,        /* " + DTCModule[NameIndex] + " => Index = " + str(NameIndex) + "; FunctionTypeNb = " + each + " */\n"
        Index = Index + int(each)
        NameIndex += 1
        DTCOffsetTable.append(Temp)
    Temp = "   " + str(Index) + "\n"
    DTCOffsetTable.append(Temp)

def GenIDTable():
    Index = 0
    for each in IDList:
        Temp = "   " + each.lower() + " ,        /* " + DTCName[IDList.index(each)] + " */\n"
        Index += 1
        DTCIDTable.append(Temp)

def GenFailTypeTable():
    Index = 0
    for each in FailTypeList:
        Temp = "   " + each + " ,        /* " + DTCName[Index] + " */\n"
        Index += 1
        DTCFailTypeTable.append(Temp)

def CommonGenBoolTable():
    Index = 0
    for ArrayIndex in range(0, len(DTCModule)):
        LocDTCNum = DTCNumInModule[ArrayIndex]
        if LocDTCNum != "16":
            for BitIndex in range(0, int(LocDTCNum)):
                CntIgnVal = CntIgnList[Index]
                Temp = "   " + CntIgnVal + " << " + str(BitIndex) + " |       /* " + DTCName[Index] + " */\n"
                DTCCntIgnTable.append(Temp)
                Index += 1
            for BitIndex in range(int(LocDTCNum), 15):
                Temp = "   0 << " + str(BitIndex) + " |\n"
                DTCCntIgnTable.append(Temp)
            Temp = "   0 << 15 ,\n"
            DTCCntIgnTable.append(Temp)
        elif LocDTCNum == "16":
            for BitIndex in range(0, 15):
                CntIgnVal = CntIgnList[Index]
                Temp = "   " + CntIgnVal + " << " + str(BitIndex) + " |       /* " + DTCName[Index] + " */\n"
                DTCCntIgnTable.append(Temp)
                Index += 1
            BitIndex += 1
            CntIgnVal = CntIgnList[Index]
            Temp = "   " + CntIgnVal + " << " + str(BitIndex) + " ,       /* " + DTCName[Index] + " */\n"
            Index += 1
            DTCCntIgnTable.append(Temp)

def GenData():
    ''' Data_h '''
    GenModuleDefine()
    GenNameDefine()
    GenCounterDefine()
    GenINCDefine()
    GenDECDefine()
    GenFlagDefine()
    GenMODDefine()
    '''Data_c'''
    GenFailModTable()
    GenIncsTable()
    GenDecsTable()
    GenIrrTable()
    GenAutInitTable()
    GenLockedTable()
    GenCntIgnTable()
    GenOffsetTable()
    GenIDTable()
    GenFailTypeTable()

def GenFuncDefine():
    Index = 0
    for ArrayIndex in range(0, len(DTCModule)):
        LocDTCNum = DTCNumInModule[ArrayIndex]
        for BitIndex in range(0, int(LocDTCNum)):
            Temp = "#define FaultDetn_{DTCName}(State)".format(DTCName = DTCName[Index])
            Length = 65 - len(Temp)
            SpaceList = [' ' for i in range(0, Length)]
            SpaceStr = ''.join(SpaceList)
            Array = "FaultDetection({ModuleName},{DTC},State)".format(ModuleName = DTCModule[ArrayIndex].upper(),\
            DTC = (DTC_Name[Index])[len(DTCModule[ArrayIndex]) + 1:])
            Index += 1
            Str = Temp + SpaceStr + Array + '\n'
            FuncDefine.append(Str)

def GenFuncDeclaration():
    Index = 0
    for ArrayIndex in range(0, len(DTCModule)):
        LocDTCNum = DTCNumInModule[ArrayIndex]
        for BitIndex in range(0, int(LocDTCNum)):
            FunTemp = "extern uint16 FaultDetn_u16Read_{DTCName}Detected(void);\n".format(DTCName = DTCName[Index])
            FuncDeclaration.append(FunTemp)
            Index += 1

    FuncDeclaration.append('\n')
    for ArrayIndex in range(0, len(DTCModule)):
        FunTemp = "extern uint16 FaultDetn_u16Read_{ModuleName}Detected(void);\n".format(ModuleName = DTCModule[ArrayIndex])
        FuncDeclaration.append(FunTemp)

    FuncDeclaration.append("\n\n/******************************************************************************/\n\
/* Declaration des interface DSM associes aux pannes Logged                   */\n\
/******************************************************************************/\n")

    Index = 0
    for ArrayIndex in range(0, len(DTCModule)):
        LocDTCNum = DTCNumInModule[ArrayIndex]
        for BitIndex in range(0, int(LocDTCNum)):
            FunTemp = "extern uint16 FaultDetn_u16Read_{DTCName}Logged(void);\n".format(DTCName = DTCName[Index])
            FuncDeclaration.append(FunTemp)
            Index += 1
    FuncDeclaration.append("\n")

    Index = 0
    for ArrayIndex in range(0, len(DTCModule)):
        LocDTCNum = DTCNumInModule[ArrayIndex]
        for BitIndex in range(0, int(LocDTCNum)):
            FunTemp = "#define FaultDetn_u16Read_{DTCName}_{IDList}_Logged FaultDetn_u16Read_{DTCName}Logged\n".format(DTCName = DTCName[Index], IDList = IDList[Index])
            FuncDeclaration.append(FunTemp)
            Index += 1

    FuncDeclaration.append('\n')
    for ArrayIndex in range(0, len(DTCModule)):
        FunTemp = "extern uint16 FaultDetn_u16Read_{ModuleName}Logged(void);\n".format(ModuleName = DTCModule[ArrayIndex])
        FuncDeclaration.append(FunTemp)

def GenFuncDefinition():
    Index = 0
    for ArrayIndex in range(0, len(DTCModule)):
        LocDTCNum = DTCNumInModule[ArrayIndex]
        for BitIndex in range(0, int(LocDTCNum)):
            FunTemp = "uint16 FaultDetn_u16Read_{DTCName}Detected(void)\n\
{{\n\
  uint16 localOutput ;\n\
  localOutput = (uint16) ((FaultFunctionTypeDetectedArray[{ModuleIndex}] & (0x0001 << {BitIndex})) >> {BitIndex});\n\
  return localOutput;\n\
}}\n\n".format(DTCName = DTCName[Index], ModuleIndex = ArrayIndex, BitIndex = BitIndex)
            Temp = FuncComment + FunTemp
            FuncDefinitionCode.append(Temp)
            Index += 1

    FuncDefinitionCode.append('\n')
    for ArrayIndex in range(0, len(DTCModule)):
        FunTemp = "uint16 FaultDetn_u16Read_{ModuleName}Detected(void)\n\
{{\n\
  uint16 localOutput ;\n\
  localOutput = (uint16)(FaultFunctionTypeDetectedArray[{ModuleIndex}]);\n\
  return localOutput;\n\
}}\n".format(ModuleName = DTCModule[ArrayIndex], ModuleIndex = ArrayIndex)
        Temp = FuncComment + FunTemp
        FuncDefinitionCode.append(Temp)

    FuncDefinitionCode.append("\n\n/******************************************************************************/\n\
/* Declaration des interface DSM associes aux pannes Logged                   */\n\
/******************************************************************************/\n")

    Index = 0
    for ArrayIndex in range(0, len(DTCModule)):
        LocDTCNum = DTCNumInModule[ArrayIndex]
        for BitIndex in range(0, int(LocDTCNum)):
            FunTemp = "uint16 FaultDetn_u16Read_{DTCName}Logged(void)\n\
{{\n\
  uint16 localOutput ;\n\
  localOutput = (uint16) ((FaultFunctionTypeLoggedArray[{ModuleIndex}] & (0x0001 << {BitIndex})) >> {BitIndex});\n\
  return localOutput;\n\
}}\n\n".format(DTCName = DTCName[Index], ModuleIndex = ArrayIndex, BitIndex = BitIndex)
            Temp = FuncComment + FunTemp
            FuncDefinitionCode.append(Temp)
            Index += 1

    FuncDefinitionCode.append('\n')
    for ArrayIndex in range(0, len(DTCModule)):
        FunTemp = "uint16 FaultDetn_u16Read_{ModuleName}Logged(void)\n\
{{\n\
  uint16 localOutput ;\n\
  localOutput = (uint16)(FaultFunctionTypeLoggedArray[{ModuleIndex}]);\n\
  return localOutput;\n\
}}\n".format(ModuleName = DTCModule[ArrayIndex], ModuleIndex = ArrayIndex)
        Temp = FuncComment + FunTemp
        FuncDefinitionCode.append(Temp)

def GenApi():
    ''' Api_h '''
    GenFuncDefine()
    GenFuncDeclaration()
    '''Api_c'''
    GenFuncDefinition()




GenDataDefine()
GenData()
GenApi()


with open(FAULT_Api_c,'w')as file:
    TempComment = GenComment(FAULT_Api_c)
    Comment = TempComment + "\n\
#include \"Std_Types.h\"\n\
\n\
#include \"DSM.h\"\n\
#include \"FAULT_Data.h\"\n\
#include \"FAULT_Api.h\"\n\
\n\n\
#define DSM_START_SEC_CODE\n\
#include \"MemMap.h\"\n\
\n\
/******************************************************************************/\n\
/*                                                                            */\n\
/*                                                                            */\n\
/******************************************************************************/\n\
\n\
uint8 FaultDetn_u8Read_FailureLevel(void)\n\
{\n\
   return (FaultFailureLevel);\n\
}\n\n\
/******************************************************************************/\n\
/* Declaration des interface DSM associes aux pannes Detected                 */\n\
/******************************************************************************/\n"
    file.write(Comment)

    Temp = ''.join(FuncDefinitionCode)
    file.write(Temp)

    file.write("\n\n#define DSM_STOP_SEC_CODE\n\
#include \"MemMap.h\"\n\n\
/*------------------------------- end of file --------------------------------*/\n")
    file.close()

with open(FAULT_Api_h,'w')as file:
    TempComment = GenComment(FAULT_Api_h)
    Comment = TempComment + "\n\
#ifndef _FAULT_API_H_INCLUS_\n\
#define _FAULT_API_H_INCLUS_\n\
\n\
#include \"DSM_Drv.h\"\n\
#include \"FAULT_Data.h\"\n\n\n\
/******************************************************************************/\n\
/* FUNCTIONS MACRO                                                            */\n\
/******************************************************************************/\n"
    file.write(Comment)

    Temp = ''.join(FuncDefine)
    file.write(Temp)

    file.write("\n\n/******************************************************************************/\n\
/* FUNCTIONS DECLARATION                                                      */\n\
/******************************************************************************/\n\n\
#define DSM_START_SEC_CODE\n\
#include \"MemMap.h\"\n\n\
extern uint8 FaultDetn_u8Read_FailureLevel(void);\n\n\
/******************************************************************************/\n\
/* Declaration des interface DSM associes aux pannes Detected                 */\n\
/******************************************************************************/\n")

    Temp = ''.join(FuncDeclaration)
    file.write(Temp)

    file.write("\n\n#define DSM_STOP_SEC_CODE\n\
#include \"MemMap.h\"\n\n\n\
#endif /*_FAULT_API_H_INCLUS_*/\n\n\
/*------------------------------ END OF FILE -----------------------------*/\n")
    file.close()


with open(FAULT_Data_c,'w')as file:
    TempComment = GenComment(FAULT_Data_c)
    Comment = TempComment + "\n#include \"Std_Types.h\"\n\
\n\
#include \"FAULT_Data.h\"\n\
\n\
/*  Tables en RAM  */\n\
\n\
#define DSM_START_SEC_VAR_UNSPECIFIED\n\
#include \"MemMap.h\"\n\
\n\
uint8             FaultTableFuncTypeCounter1        [NB_FAULT_FUNCTION_TYPE];\n\
\n\
FaultBitFieldType FaultFunctionTypeDetectedArray    [NB_FAULT_FUNCTION];\n\
FaultBitFieldType FaultFunctionTypeLoggedArray      [NB_FAULT_FUNCTION];\n\
FaultBitFieldType FaultFunctionTypeAuthorizedArray  [NB_FAULT_FUNCTION];\n\
FaultBitFieldType FaultFunctionTypeLogIgnArray      [NB_FAULT_FUNCTION];\n\
\n\
uint8             FaultFailModCounterTable          [NB_FAIL_MOD_MAX];\n\
\n\
#define DSM_STOP_SEC_VAR_UNSPECIFIED\n\
#include \"MemMap.h\"\n\
\n\
/* Tables calibrables */\n\
\n\
#define DSM_START_SEC_CALIB_UNSPECIFIED\n\
#include \"MemMap.h\"\n"
    file.write(Comment)

    file.write("\nconst FaultFailModType FaultFunctionTypeFailModTable [NB_FAULT_FUNCTION_TYPE] =\n\
{\n")
    Temp = ''.join(DTCFailModTable)
    file.write(Temp)
    file.write("};\n")

    file.write("\n\nconst FaultCntType FaultFunctionTypeIncs [NB_FAULT_FUNCTION_TYPE] =\n\
{\n")
    Temp = ''.join(DTCIncsTable)
    file.write(Temp)
    file.write("};\n")

    file.write("\n\n\nconst FaultCntType FaultFunctionTypeDecs [NB_FAULT_FUNCTION_TYPE] =\n\
{\n")
    Temp = ''.join(DTCDecsTable)
    file.write(Temp)
    file.write("};\n")

    file.write("\n\nconst FaultBitFieldType FaultFunctionTypeIrrArray[NB_FAULT_FUNCTION] =\n\
{\n")
    Temp = ''.join(DTCIrrTable)
    file.write(Temp)
    file.write("};\n")

    file.write("\n\nconst FaultBitFieldType FaultFunctionTypeAutInitArray[NB_FAULT_FUNCTION] =\n\
{\n")
    Temp = ''.join(DTCAutInitTable)
    file.write(Temp)
    file.write("};\n")

    file.write("\n\nconst FaultBitFieldType FaultFunctionTypeLockedArray[NB_FAULT_FUNCTION] =\n\
{\n")
    Temp = ''.join(DTCLockedTable)
    file.write(Temp)
    file.write("};\n")

    file.write("\n\nconst FaultBitFieldType FaultFunctionTypeCntIgnArray[NB_FAULT_FUNCTION] =\n\
{\n")
    Temp = ''.join(DTCCntIgnTable)
    file.write(Temp)
    file.write("};\n")

    file.write("\n#define DSM_STOP_SEC_CALIB_UNSPECIFIED\n\
#include \"MemMap.h\"\n\n\
/* Tables fixes */\n\n\
#define DSM_START_SEC_CONST_UNSPECIFIED\n\
#include \"MemMap.h\"\n\n\
const FaultOffsetType FaultFunctionTypeOffsetTable [NB_FAULT_FUNCTION + 1] =\n\
{\n")
    Temp = ''.join(DTCOffsetTable)
    file.write(Temp)
    file.write("};\n")

    file.write("\n\nconst FaultDtcNbType FaultFunctionTypeDtcNbTable [NB_FAULT_FUNCTION_TYPE] =\n\
{\n")
    Temp = ''.join(DTCIDTable)
    file.write(Temp)
    file.write("};\n")

    file.write("\n\nconst FaultDtcFailTypeType FaultFunctionTypeDtcFtTable [NB_FAULT_FUNCTION_TYPE] =\n\
{\n")
    Temp = ''.join(DTCFailTypeTable)
    file.write(Temp)
    file.write("};\n")

    file.write("\n#define DSM_STOP_SEC_CONST_UNSPECIFIED\n\
#include \"MemMap.h\"\n\n\
/*------------------------------- end of file --------------------------------*/\n")
    file.close()

with open(FAULT_Data_h,'w')as file:
    TempComment = GenComment(FAULT_Data_h)
    Comment = TempComment + "\n\
#ifndef _FAULT_DATA_H_INCLUS_\n\
#define _FAULT_DATA_H_INCLUS_\n\
\n\
#include \"DSM_Drv.h\"\n\
\n\
/* Definition des longueurs de table */\n" + GenSysNum(ModuleNum, DTCNum, ModNum)\
+ "\n\n/* Tables en RAM  */\n\
\n\
#define DSM_START_SEC_VAR_UNSPECIFIED\n\
#include \"MemMap.h\"\n\
\n\
extern   uint8             FaultTableFuncTypeCounter1       [NB_FAULT_FUNCTION_TYPE];\n\
\n\
extern   FaultBitFieldType FaultFunctionTypeDetectedArray   [NB_FAULT_FUNCTION];\n\
extern   FaultBitFieldType FaultFunctionTypeLoggedArray     [NB_FAULT_FUNCTION];\n\
extern   FaultBitFieldType FaultFunctionTypeAuthorizedArray [NB_FAULT_FUNCTION];\n\
extern   FaultBitFieldType FaultFunctionTypeLogIgnArray     [NB_FAULT_FUNCTION];\n\
\n\
extern   uint8             FaultFailModCounterTable         [NB_FAIL_MOD_MAX];\n\
\n\
#define DSM_STOP_SEC_VAR_UNSPECIFIED\n\
#include \"MemMap.h\"\n\
\n\
/* Tables calibrables */\n\
\n\
#define DSM_START_SEC_CALIB_UNSPECIFIED\n\
#include \"MemMap.h\"\n\
\n\
extern  const FaultCntType FaultFunctionTypeIncs                [NB_FAULT_FUNCTION_TYPE];\n\
extern  const FaultCntType FaultFunctionTypeDecs                [NB_FAULT_FUNCTION_TYPE];\n\
extern  const FaultBitFieldType FaultFunctionTypeIrrArray       [NB_FAULT_FUNCTION];\n\
extern  const FaultBitFieldType FaultFunctionTypeAutInitArray   [NB_FAULT_FUNCTION];\n\
extern  const FaultBitFieldType FaultFunctionTypeLockedArray    [NB_FAULT_FUNCTION];\n\
extern  const FaultBitFieldType FaultFunctionTypeCntIgnArray    [NB_FAULT_FUNCTION];\n\
extern  const FaultFailModType  FaultFunctionTypeFailModTable   [NB_FAULT_FUNCTION_TYPE];\n\
\n\
#define DSM_STOP_SEC_CALIB_UNSPECIFIED\n\
#include \"MemMap.h\"\n\
\n\
/* Tables fixes */\n\
\n\
#define DSM_START_SEC_CONST_UNSPECIFIED\n\
#include \"MemMap.h\"\n\
\n\
extern   const FaultOffsetType FaultFunctionTypeOffsetTable     [NB_FAULT_FUNCTION + 1];\n\
extern   const FaultDtcNbType FaultFunctionTypeDtcNbTable       [NB_FAULT_FUNCTION_TYPE];\n\
extern   const FaultDtcFailTypeType FaultFunctionTypeDtcFtTable [NB_FAULT_FUNCTION_TYPE];\n\
\n\
#define DSM_STOP_SEC_CONST_UNSPECIFIED\n\
#include \"MemMap.h\"\n"
    file.write(Comment)

    file.write("\n/* Indices des pannes dans la table des fonctions */\n\
/*  = 1er argument pour la procedure FaultDetection */\n")
    Temp = ''.join(DTCModuleDefine)
    file.write(Temp)

    file.write("\n\n/* Indices des pannes par type */\n\
/*  = 2eme argument pour la procedure FaultDetection */\n")
    Temp = ''.join(DTC_NameDefine)
    file.write(Temp)

    file.write("\n\n/* Declaration en DEFINE des compteurs de pannes associes chaque panne */\n")
    Temp = ''.join(DTCCounterDefine)
    file.write(Temp)

    file.write("\n\n/* Declaration en DEFINE des increments de pannes associes chaque panne */\n")
    Temp = ''.join(DTCINCDefine)
    file.write(Temp)

    file.write("\n\n/* Declaration en DEFINE des decrements de pannes associes chaque panne */\n")
    Temp = ''.join(DTCDECDefine)
    file.write(Temp)

    file.write("\n\n/* Declaration en externe des bits associes chaque fonction */\n\n\
#define DSM_START_SEC_VAR_UNSPECIFIED\n\
#include \"MemMap.h\"\n\n")
    Temp = ''.join(DTCFlagDefine)
    file.write(Temp)
    file.write("\n\n#define DSM_STOP_SEC_VAR_UNSPECIFIED\n\
#include \"MemMap.h\"\n")

    file.write("\n\n/* Declaration en DEFINE des compteurs de pannes associes chaque panne */\n")
    Temp = ''.join(DTCModDefine)
    file.write(Temp)
    file.write("\n\n#endif /*_FAULT_DATA_H_INCLUS_*/\n\n\
/*------------------------------- end of file --------------------------------*/\n")
    file.close()


with open(CompileFlagTxt,'w')as file:
    file.write("Do not delete this file")




