# The file contains project related settings
# Key shall not contain any special characters
# Values with multiple lines shall be avoided
#
#Tue Mar 12 10:23:02 CST 2024
Clean_Output_Directory=ALWAYS
DIR_OUT_FILES_SETTINGS=[c\=source][h\=header][arxml\=arxml]
STOP_ON_ERROR=true
com.bosch.autosartool.bsw.validation.merge_conflict_detection=true