/** \file         Rte_MemMap.h
  *
  * \brief        RTE Memory Mapping header file
  *
  * [$crn:2007:dox
  * \copyright Copyright 2007 - 2008 ETAS Engineering Tools Application and Services Ltd.
  *            Copyright 2008 ETAS GmbH.
  * $]
  *
  * \note         Implemented SWS: N/A
  *
  * \note         PLATFORM DEPENDANT [yes/no]: no
  *
  * \note         TO BE CHANGED BY USER [yes/no]: yes
  *
  * $Id: Rte_MemMap.h 41380 2022-06-21 08:58:48Z IQU1SGH $
  */

#if defined (START_WITH_IF)

#elif defined (RTE_START_SEC_APPL_SHARE_DATA)
#undef RTE_START_SEC_APPL_SHARE_DATA
#define APP_START_SEC_SHAREDATA
#elif defined (RTE_STOP_SEC_APPL_SHARE_DATA)
#undef RTE_STOP_SEC_APPL_SHARE_DATA
#define APP_STOP_SEC_SHAREDATA
#elif defined (RTE_START_SEC_APPL_SHARE_CODE)
#undef RTE_START_SEC_APPL_SHARE_CODE
#define APP_START_SEC_SHARECODE
#elif defined (RTE_STOP_SEC_APPL_SHARE_CODE)
#undef RTE_STOP_SEC_APPL_SHARE_CODE
#define APP_STOP_SEC_SHARECODE
#elif defined (RTE_START_SEC_APPL_PRIVITE_DATA0)
#undef RTE_START_SEC_APPL_PRIVITE_DATA0
#define APP_START_SEC_CPU0_DATA
#elif defined (RTE_STOP_SEC_APPL_PRIVITE_DATA0)
#undef RTE_STOP_SEC_APPL_PRIVITE_DATA0
#define APP_STOP_SEC_CPU0_DATA
#elif defined (RTE_START_SEC_APPL_PRIVITE_CODE0)
#undef RTE_START_SEC_APPL_PRIVITE_CODE0
#define APP_START_SEC_CPU0_CODE
#elif defined (RTE_STOP_SEC_APPL_PRIVITE_CODE0)
#undef RTE_STOP_SEC_APPL_PRIVITE_CODE0
#define APP_STOP_SEC_CPU0_CODE
#elif defined (RTE_START_SEC_APPL_PRIVITE_DATA1)
#undef RTE_START_SEC_APPL_PRIVITE_DATA1
#define APP_START_SEC_CPU1_DATA
#elif defined (RTE_STOP_SEC_APPL_PRIVITE_DATA1)
#undef RTE_STOP_SEC_APPL_PRIVITE_DATA1
#define APP_STOP_SEC_CPU1_DATA
#elif defined (RTE_START_SEC_APPL_PRIVITE_CODE1)
#undef RTE_START_SEC_APPL_PRIVITE_CODE1
#define APP_START_SEC_CPU1_CODE
#elif defined (RTE_STOP_SEC_APPL_PRIVITE_CODE1)
#undef RTE_STOP_SEC_APPL_PRIVITE_CODE1
#define APP_STOP_SEC_CPU1_CODE
#elif defined (RTE_START_SEC_APPL_PRIVITE_DATA2)
#undef RTE_START_SEC_APPL_PRIVITE_DATA2
#define APP_START_SEC_CPU2_DATA
#elif defined (RTE_STOP_SEC_APPL_PRIVITE_DATA2)
#undef RTE_STOP_SEC_APPL_PRIVITE_DATA2
#define APP_STOP_SEC_CPU2_DATA
#elif defined (RTE_START_SEC_APPL_PRIVITE_CODE2)
#undef RTE_START_SEC_APPL_PRIVITE_CODE2
#define APP_START_SEC_CPU2_CODE
#elif defined (RTE_STOP_SEC_APPL_PRIVITE_CODE2)
#undef RTE_STOP_SEC_APPL_PRIVITE_CODE2
#define APP_STOP_SEC_CPU2_CODE
#elif defined (RTE_START_SEC_APPL_PRIVITE_DATA3)
#undef RTE_START_SEC_APPL_PRIVITE_DATA3
#define APP_START_SEC_CPU3_DATA
#elif defined (RTE_STOP_SEC_APPL_PRIVITE_DATA3)
#undef RTE_STOP_SEC_APPL_PRIVITE_DATA3
#define APP_STOP_SEC_CPU3_DATA
#elif defined (RTE_START_SEC_APPL_PRIVITE_CODE3)
#undef RTE_START_SEC_APPL_PRIVITE_CODE3
#define APP_START_SEC_CPU3_CODE
#elif defined (RTE_STOP_SEC_APPL_PRIVITE_CODE3)
#undef RTE_STOP_SEC_APPL_PRIVITE_CODE3
#define APP_STOP_SEC_CPU3_CODE
#elif defined (RTE_START_SEC_APPL_PRIVITE_DATA4)
#undef RTE_START_SEC_APPL_PRIVITE_DATA4
#define APP_START_SEC_CPU4_DATA
#elif defined (RTE_STOP_SEC_APPL_PRIVITE_DATA4)
#undef RTE_STOP_SEC_APPL_PRIVITE_DATA4
#define APP_STOP_SEC_CPU4_DATA
#elif defined (RTE_START_SEC_APPL_PRIVITE_CODE4)
#undef RTE_START_SEC_APPL_PRIVITE_CODE4
#define APP_START_SEC_CPU4_CODE
#elif defined (RTE_STOP_SEC_APPL_PRIVITE_CODE4)
#undef RTE_STOP_SEC_APPL_PRIVITE_CODE4
#define APP_STOP_SEC_CPU4_CODE
#elif defined (RTE_START_SEC_APPL_PRIVITE_DATA5)
#undef RTE_START_SEC_APPL_PRIVITE_DATA5
#define APP_START_SEC_CPU5_DATA
#elif defined (RTE_STOP_SEC_APPL_PRIVITE_DATA5)
#undef RTE_STOP_SEC_APPL_PRIVITE_DATA5
#define APP_STOP_SEC_CPU5_DATA
#elif defined (RTE_START_SEC_APPL_PRIVITE_CODE5)
#undef RTE_START_SEC_APPL_PRIVITE_CODE5
#define APP_START_SEC_CPU5_CODE
#elif defined (RTE_STOP_SEC_APPL_PRIVITE_CODE5)
#undef RTE_STOP_SEC_APPL_PRIVITE_CODE5
#define APP_STOP_SEC_CPU5_CODE

#elif defined (RTE_START_SEC_APPL_CALIB_DATA)
#undef RTE_START_SEC_APPL_CALIB_DATA
#define CALIB_START_SEC_CONST_32
#elif defined (RTE_STOP_SEC_APPL_CALIB_DATA)
#undef RTE_STOP_SEC_APPL_CALIB_DATA
#define CALIB_STOP_SEC_CONST_32
// #else 
// #error "lack update Rte_MemMap for memmap define"

#endif /* START_WITH_IF */

#include "MemMap.h"

