
/********************************************************************************************************************/
/*                                                                                                                  */
/* TOOL-GENERATED SOURCECODE, DO NOT CHANGE                                                                         */
/*                                                                                                                  */
/********************************************************************************************************************/

#ifndef DEM_CFG_RTE_DEM_TYPE_H
#define DEM_CFG_RTE_DEM_TYPE_H

/********************************************************************************************************************/
/*                                                                                                                  */
/* This file contains the values which are normally generated by the RTE,                                           */
/* so they can be used for the templates in case no RTE is enabled in the project.                                  */
/* Included in Rte_Dem_Type.h_tpl                                                                                   */
/*                                                                                                                  */
/********************************************************************************************************************/

//Size of largest PID / DID / ExtendedDataRecord
#define Dem_MaxDataValueTypeSize 4

/* Size of configured DemRatioId */
#define DEM_CFG_RATIO_SIZE 0u

#endif

