/********************************************************************************************************************/
/*                                                                                                                  */
/* TOOL-GENERATED SOURCECODE, DO NOT CHANGE                                                                         */
/*                                                                                                                  */
/********************************************************************************************************************/

#ifndef DEM_CFG_ENVFREEZEFRAME_H
#define DEM_CFG_ENVFREEZEFRAME_H

#define DEM_CFG_ENVFREEZEFRAME2DID \
{ \
   DEM_DID_DID_CLASS_D007,   DEM_DID_DID_CLASS_D008,   DEM_DID_DID_CLASS_D009,   DEM_DID_DID_CLASS_D010,   DEM_DID_DID_CLASS_D011,   DEM_DID_DID_CLASS_D012,   DEM_DID_DID_CLASS_D013,   DEM_DID_DID_CLASS_D014,   DEM_DID_DID_CLASS_D015,   DEM_DID_DID_CLASS_D016,   DEM_DID_DID_CLASS_D017,   DEM_DID_DID_CLASS_D018,   DEM_DID_DID_CLASS_D019,   DEM_DID_DID_CLASS_D020,   DEM_DID_DID_CLASS_D021,   DEM_DID_DID_CLASS_D022,   DEM_DID_DID_CLASS_D023,   DEM_DID_DID_CLASS_D024,   DEM_DID_DID_CLASS_D025,   DEM_DID_DID_CLASS_D026,   DEM_DID_DID_CLASS_D027,   DEM_DID_DID_CLASS_D028,   DEM_DID_DID_CLASS_D029,   DEM_DID_DID_CLASS_D000,   DEM_DID_DID_CLASS_D001,   DEM_DID_DID_CLASS_D002,   DEM_DID_DID_CLASS_D003,   DEM_DID_DID_CLASS_D004,   DEM_DID_DID_CLASS_D005, /* DemFreezeFrameClass_Ecu1 */ \
   DEM_DID_DID_CLASS_D007,   DEM_DID_DID_CLASS_D008,   DEM_DID_DID_CLASS_D009,   DEM_DID_DID_CLASS_D010,   DEM_DID_DID_CLASS_D011,   DEM_DID_DID_CLASS_D012,   DEM_DID_DID_CLASS_D013,   DEM_DID_DID_CLASS_D014,   DEM_DID_DID_CLASS_D015,   DEM_DID_DID_CLASS_D016,   DEM_DID_DID_CLASS_D017,   DEM_DID_DID_CLASS_D018,   DEM_DID_DID_CLASS_D019,   DEM_DID_DID_CLASS_D020,   DEM_DID_DID_CLASS_D021,   DEM_DID_DID_CLASS_D022,   DEM_DID_DID_CLASS_D023,   DEM_DID_DID_CLASS_D024,   DEM_DID_DID_CLASS_D025,   DEM_DID_DID_CLASS_D026,   DEM_DID_DID_CLASS_D027,   DEM_DID_DID_CLASS_D028,   DEM_DID_DID_CLASS_D029,   DEM_DID_DID_CLASS_D000,   DEM_DID_DID_CLASS_D001,   DEM_DID_DID_CLASS_D002,   DEM_DID_DID_CLASS_D003,   DEM_DID_DID_CLASS_D004,   DEM_DID_DID_CLASS_D005, /* DemFreezeFrameClass_Ecu2 */ \
   DEM_DID_DID_CLASS_D007,   DEM_DID_DID_CLASS_D008,   DEM_DID_DID_CLASS_D009,   DEM_DID_DID_CLASS_D010,   DEM_DID_DID_CLASS_D011,   DEM_DID_DID_CLASS_D012,   DEM_DID_DID_CLASS_D013,   DEM_DID_DID_CLASS_D014,   DEM_DID_DID_CLASS_D015,   DEM_DID_DID_CLASS_D016,   DEM_DID_DID_CLASS_D017,   DEM_DID_DID_CLASS_D018,   DEM_DID_DID_CLASS_D019,   DEM_DID_DID_CLASS_D020,   DEM_DID_DID_CLASS_D021,   DEM_DID_DID_CLASS_D022,   DEM_DID_DID_CLASS_D023,   DEM_DID_DID_CLASS_D024,   DEM_DID_DID_CLASS_D025,   DEM_DID_DID_CLASS_D026,   DEM_DID_DID_CLASS_D027,   DEM_DID_DID_CLASS_D028,   DEM_DID_DID_CLASS_D029,   DEM_DID_DID_CLASS_D000,   DEM_DID_DID_CLASS_D001,   DEM_DID_DID_CLASS_D002,   DEM_DID_DID_CLASS_D003,   DEM_DID_DID_CLASS_D004,   DEM_DID_DID_CLASS_D005, /* DemFreezeFrameClass_Ecu3 */ \
   DEM_DID_DID_CLASS_D007,   DEM_DID_DID_CLASS_D008,   DEM_DID_DID_CLASS_D009,   DEM_DID_DID_CLASS_D010,   DEM_DID_DID_CLASS_D011,   DEM_DID_DID_CLASS_D012,   DEM_DID_DID_CLASS_D013,   DEM_DID_DID_CLASS_D014,   DEM_DID_DID_CLASS_D015,   DEM_DID_DID_CLASS_D016,   DEM_DID_DID_CLASS_D017,   DEM_DID_DID_CLASS_D018,   DEM_DID_DID_CLASS_D019,   DEM_DID_DID_CLASS_D020,   DEM_DID_DID_CLASS_D021,   DEM_DID_DID_CLASS_D022,   DEM_DID_DID_CLASS_D023,   DEM_DID_DID_CLASS_D024,   DEM_DID_DID_CLASS_D025,   DEM_DID_DID_CLASS_D026,   DEM_DID_DID_CLASS_D027,   DEM_DID_DID_CLASS_D028,   DEM_DID_DID_CLASS_D029,   DEM_DID_DID_CLASS_D000,   DEM_DID_DID_CLASS_D001,   DEM_DID_DID_CLASS_D002,   DEM_DID_DID_CLASS_D003,   DEM_DID_DID_CLASS_D004,   DEM_DID_DID_CLASS_D005, /* DemFreezeFrameClass_Ecu4 */ \
   DEM_DID_DID_CLASS_D030,   DEM_DID_DID_CLASS_D031,   DEM_DID_DID_CLASS_D032,   DEM_DID_DID_CLASS_D033,   DEM_DID_DID_CLASS_D034,   DEM_DID_DID_CLASS_D035,   DEM_DID_DID_CLASS_D036,   DEM_DID_DID_CLASS_D037,   DEM_DID_DID_CLASS_D038,   DEM_DID_DID_CLASS_D039,   DEM_DID_DID_CLASS_D040,   DEM_DID_DID_CLASS_D041,   DEM_DID_DID_CLASS_D042,   DEM_DID_DID_CLASS_D043,   DEM_DID_DID_CLASS_D044,   DEM_DID_DID_CLASS_D045,   DEM_DID_DID_CLASS_D046,   DEM_DID_DID_CLASS_D047,   DEM_DID_DID_CLASS_D048,   DEM_DID_DID_CLASS_D049, /* DemFreezeFrameClass_Ecu5 */ \
   0 \
}

#define DEM_FREEZEFRAME_DEMFREEZEFRAMECLASS_ECU1         1
#define DEM_FREEZEFRAME_DEMFREEZEFRAMECLASS_ECU2         2
#define DEM_FREEZEFRAME_DEMFREEZEFRAMECLASS_ECU3         3
#define DEM_FREEZEFRAME_DEMFREEZEFRAMECLASS_ECU4         4
#define DEM_FREEZEFRAME_DEMFREEZEFRAMECLASS_ECU5         5

#define DEM_CFG_ENVFREEZEFRAME \
{ \
   { 0,0 } \
   ,{ 29, 36 }   /* DEM_FREEZEFRAME_DEMFREEZEFRAMECLASS_ECU1 */  \
   ,{ 58, 36 }   /* DEM_FREEZEFRAME_DEMFREEZEFRAMECLASS_ECU2 */  \
   ,{ 87, 36 }   /* DEM_FREEZEFRAME_DEMFREEZEFRAMECLASS_ECU3 */  \
   ,{ 116, 36 }   /* DEM_FREEZEFRAME_DEMFREEZEFRAMECLASS_ECU4 */  \
   ,{ 136, 26 }   /* DEM_FREEZEFRAME_DEMFREEZEFRAMECLASS_ECU5 */  \
}

#define DEM_CFG_ENVFREEZEFRAME_ARRAYLENGTH  (5+1)

#endif

