/** @file     Core1_OsTask_ASW_10ms.c
  *
  * @brief    Task Core1_OsTask_ASW_10ms body
  *
  * @note     AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
  *
  * @note     Generated by ETAS RTA-RTE
  * @note     Version 7.5.3
  *
  * @date     Mon Mar 23 13:15:43 2026
  */

#define RTE_CORE

#include "Rte_Const.h"
#if !defined(RTE_VENDOR_MODE)
#pragma message "Compiling an individual task file but RTE_VENDOR_MODE not defined. Compiling a stale file?"
#endif /* !defined(RTE_VENDOR_MODE) */
#if defined(RTE_USE_TASK_HEADER)
#include "Core1_OsTask_ASW_10ms.h"
#else /* !defined(RTE_USE_TASK_HEADER) */
#include "Os.h"
#endif /* !defined(RTE_USE_TASK_HEADER) */
#if defined(RTE_REQUIRES_IOC)
#include "Ioc.h"
#endif /* defined(RTE_REQUIRES_IOC) */
#include "Rte.h"
#include "Rte_Intl.h"
#include "Rte_Type.h"
#include "Rte_DataHandleType.h"

/* Runnable entity prototypes */
#define ASW_COM_START_SEC_CODE
#include "ASW_COM_MemMap.h"
FUNC(void, ASW_COM_CODE) MainMsg_Can01_Below100ms_Func(void);
FUNC(void, ASW_COM_CODE) MainMsg_Can02_Below100ms_Func(void);
FUNC(void, ASW_COM_CODE) MainMsg_Can03_Below100ms_Func(void);
#define ASW_COM_STOP_SEC_CODE
#include "ASW_COM_MemMap.h"
#define ASW_CORE1_START_SEC_CODE
#include "ASW_CORE1_MemMap.h"
FUNC(void, ASW_CORE1_CODE) MAIN_CORE1_10ms_func(void);
FUNC(void, ASW_CORE1_CODE) RE_CORE1_SWC_func(void);
#define ASW_CORE1_STOP_SEC_CODE
#include "ASW_CORE1_MemMap.h"
#define CDD_CORE1_START_SEC_CODE
#include "CDD_CORE1_MemMap.h"
FUNC(void, CDD_CORE1_CODE) CDD_CORE1_func(void);
#define CDD_CORE1_STOP_SEC_CODE
#include "CDD_CORE1_MemMap.h"

#define RTE_CORE1_OSTASK_ASW_10MS_START_SEC_CODE
#include "Rte_MemMap.h"
TASK(Core1_OsTask_ASW_10ms)
{
   /* Box: Implicit Buffer Initialization begin */
   /* Box: Implicit Buffer Initialization end */
   /* Box: Implicit Buffer Fill begin */
   /* Box: Implicit Buffer Fill end */
   {
      /* Box: CPT_CDD_CORE1 begin */
      CDD_CORE1_func();
      /* Box: CPT_CDD_CORE1 end */
   }
   {
      /* Box: CPT_ASW_CORE1 begin */
      RE_CORE1_SWC_func();
      /* Box: CPT_ASW_CORE1 end */
   }
   {
      /* Box: CPT_ASW_CORE1 begin */
      MAIN_CORE1_10ms_func();
      /* Box: CPT_ASW_CORE1 end */
   }
   {
      /* Box: CPT_ASW_COM begin */
      MainMsg_Can01_Below100ms_Func();
      /* Box: CPT_ASW_COM end */
   }
   {
      /* Box: CPT_ASW_COM begin */
      MainMsg_Can02_Below100ms_Func();
      /* Box: CPT_ASW_COM end */
   }
   {
      /* Box: CPT_ASW_COM begin */
      MainMsg_Can03_Below100ms_Func();
      /* Box: CPT_ASW_COM end */
   }
   /* Box: Implicit Buffer Flush begin */
   /* Box: Implicit Buffer Flush end */
   TerminateTask();
} /* Core1_OsTask_ASW_10ms */
#define RTE_CORE1_OSTASK_ASW_10MS_STOP_SEC_CODE
#include "Rte_MemMap.h"

