/** @file     Core0_OsTask_BSW_1ms.c
  *
  * @brief    Task Core0_OsTask_BSW_1ms body
  *
  * @note     AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
  *
  * @note     Generated by ETAS RTA-RTE
  * @note     Version 7.5.3
  *
  * @date     Mon Mar 23 13:15:43 2026
  */

#define RTE_CORE

#include "Rte_Const.h"
#if !defined(RTE_VENDOR_MODE)
#pragma message "Compiling an individual task file but RTE_VENDOR_MODE not defined. Compiling a stale file?"
#endif /* !defined(RTE_VENDOR_MODE) */
#if defined(RTE_USE_TASK_HEADER)
#include "Core0_OsTask_BSW_1ms.h"
#else /* !defined(RTE_USE_TASK_HEADER) */
#include "Os.h"
#endif /* !defined(RTE_USE_TASK_HEADER) */
#if defined(RTE_REQUIRES_IOC)
#include "Ioc.h"
#endif /* defined(RTE_REQUIRES_IOC) */
#include "Rte.h"
#include "Rte_Intl.h"
#include "Rte_Type.h"
#include "Rte_DataHandleType.h"

/* Runnable entity prototypes */
#define CDD_CORE0_START_SEC_CODE
#include "CDD_CORE0_MemMap.h"
FUNC(void, CDD_CORE0_CODE) RE_OsShell_TriggerBg_func(void);
#define CDD_CORE0_STOP_SEC_CODE
#include "CDD_CORE0_MemMap.h"
#define CANNM_START_SEC_CODE
#include "CanNm_MemMap.h"
FUNC(void, CANNM_CODE) CanNm_MainFunction(void);
#define CANNM_STOP_SEC_CODE
#include "CanNm_MemMap.h"
#define CANTP_START_SEC_CODE
#include "CanTp_MemMap.h"
FUNC(void, CANTP_CODE) CanTp_MainFunction(void);
#define CANTP_STOP_SEC_CODE
#include "CanTp_MemMap.h"
#define CANTRCV_START_SEC_CODE
#include "CanTrcv_MemMap.h"
FUNC(void, CANTRCV_CODE) CanTrcv_MainFunction(void);
#define CANTRCV_STOP_SEC_CODE
#include "CanTrcv_MemMap.h"
#define COM_START_SEC_CODE
#include "Com_MemMap.h"
FUNC(void, COM_CODE) Com_MainFunctionRx(void);
FUNC(void, COM_CODE) Com_MainFunctionTx(void);
#define COM_STOP_SEC_CODE
#include "Com_MemMap.h"
#define DCM_START_SEC_CODE
#include "Dcm_MemMap.h"
FUNC(void, DCM_CODE) Dcm_MainFunction(void);
#define DCM_STOP_SEC_CODE
#include "Dcm_MemMap.h"
#define DEM_START_SEC_CODE
#include "Dem_MemMap.h"
FUNC(void, DEM_CODE) Dem_MainFunction(void);
#define DEM_STOP_SEC_CODE
#include "Dem_MemMap.h"
#define NVM_START_SEC_CODE
#include "NvM_MemMap.h"
FUNC(void, NVM_CODE) NvM_MainFunction(void);
#define NVM_STOP_SEC_CODE
#include "NvM_MemMap.h"

#define RTE_CORE0_OSTASK_BSW_1MS_START_SEC_CODE
#include "Rte_MemMap.h"
TASK(Core0_OsTask_BSW_1ms)
{
   /* Box: Implicit Buffer Initialization begin */
   /* Box: Implicit Buffer Initialization end */
   /* Box: Implicit Buffer Fill begin */
   /* Box: Implicit Buffer Fill end */
   {
      /* Box: BSWImpl13_CanTrcv begin */
      CanTrcv_MainFunction();
      /* Box: BSWImpl13_CanTrcv end */
   }
   {
      /* Box: BSWImpl14_CanNm begin */
      CanNm_MainFunction();
      /* Box: BSWImpl14_CanNm end */
   }
   {
      /* Box: CPT_CDD_CORE0 begin */
      RE_OsShell_TriggerBg_func();
      /* Box: CPT_CDD_CORE0 end */
   }
   {
      /* Box: BSWImpl5_NvM begin */
      NvM_MainFunction();
      /* Box: BSWImpl5_NvM end */
   }
   {
      /* Box: BSWImpl4_CanTp begin */
      CanTp_MainFunction();
      /* Box: BSWImpl4_CanTp end */
   }
   {
      /* Box: BSWImpl2_Dcm begin */
      Dcm_MainFunction();
      /* Box: BSWImpl2_Dcm end */
   }
   {
      /* Box: BSWImpl6_Dem begin */
      Dem_MainFunction();
      /* Box: BSWImpl6_Dem end */
   }
   {
      /* Box: BSWImpl0_Com begin */
      Com_MainFunctionTx();
      /* Box: BSWImpl0_Com end */
   }
   {
      /* Box: BSWImpl0_Com begin */
      Com_MainFunctionRx();
      /* Box: BSWImpl0_Com end */
   }
   /* Box: Implicit Buffer Flush begin */
   /* Box: Implicit Buffer Flush end */
   TerminateTask();
} /* Core0_OsTask_BSW_1ms */
#define RTE_CORE0_OSTASK_BSW_1MS_STOP_SEC_CODE
#include "Rte_MemMap.h"

