/** @file     Core0_OsTask_BSW_50ms.c
  *
  * @brief    Task Core0_OsTask_BSW_50ms body
  *
  * @note     AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
  *
  * @note     Generated by ETAS RTA-RTE
  * @note     Version 7.5.3
  *
  * @date     Mon Mar 23 13:15:43 2026
  */

#define RTE_CORE

#include "Rte_Const.h"
#if !defined(RTE_VENDOR_MODE)
#pragma message "Compiling an individual task file but RTE_VENDOR_MODE not defined. Compiling a stale file?"
#endif /* !defined(RTE_VENDOR_MODE) */
#if defined(RTE_USE_TASK_HEADER)
#include "Core0_OsTask_BSW_50ms.h"
#else /* !defined(RTE_USE_TASK_HEADER) */
#include "Os.h"
#endif /* !defined(RTE_USE_TASK_HEADER) */
#if defined(RTE_REQUIRES_IOC)
#include "Ioc.h"
#endif /* defined(RTE_REQUIRES_IOC) */
#include "Rte.h"
#include "Rte_Intl.h"
#include "Rte_Type.h"
#include "Rte_DataHandleType.h"

/* Runnable entity prototypes */
#define XCP_START_SEC_CODE
#include "Xcp_MemMap.h"
FUNC(void, XCP_CODE) Xcp_EventChannel_50ms(void);
#define XCP_STOP_SEC_CODE
#include "Xcp_MemMap.h"

#define RTE_CORE0_OSTASK_BSW_50MS_START_SEC_CODE
#include "Rte_MemMap.h"
TASK(Core0_OsTask_BSW_50ms)
{
   /* Box: Implicit Buffer Initialization begin */
   /* Box: Implicit Buffer Initialization end */
   /* Box: Implicit Buffer Fill begin */
   /* Box: Implicit Buffer Fill end */
   {
      /* Box: BSWImpl8_Xcp begin */
      Xcp_EventChannel_50ms();
      /* Box: BSWImpl8_Xcp end */
   }
   /* Box: Implicit Buffer Flush begin */
   /* Box: Implicit Buffer Flush end */
   TerminateTask();
} /* Core0_OsTask_BSW_50ms */
#define RTE_CORE0_OSTASK_BSW_50MS_STOP_SEC_CODE
#include "Rte_MemMap.h"

