/** @file     Rte_NvM.h
  *
  * @brief    Application header file
  *
  * @note     AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
  *
  * @note     Generated by ETAS RTA-RTE
  * @note     Version 7.5.3
  *
  * @date     Mon Mar 23 13:15:44 2026
  */

#ifndef RTE_NVM_H
#define RTE_NVM_H

#ifndef RTE_CORE
#ifdef RTE_APPLICATION_HEADER_FILE
#error Multiple application header files included.
#endif /* RTE_APPLICATION_HEADER_FILE */
#define RTE_APPLICATION_HEADER_FILE
#endif /* RTE_CORE */

/*******************************************************
 ***
 *** Includes
 ***
 *******************************************************/

#include "Rte.h"
#include "Rte_Intl.h"
#include "Rte_NvM_Type.h"

#include "Rte_DataHandleType.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#if defined(RTE_RUNNABLEAPI_EraseNvBlock)
   /* Do nothing for this and all elif clauses below (rte_sws_2751) */
#elif defined(RTE_RUNNABLEAPI_GetDataIndex)
#elif defined(RTE_RUNNABLEAPI_GetErrorStatus)
#elif defined(RTE_RUNNABLEAPI_InvalidateNvBlock)
#elif defined(RTE_RUNNABLEAPI_MainFunction)
#elif defined(RTE_RUNNABLEAPI_ReadBlock)
#elif defined(RTE_RUNNABLEAPI_ReadPRAMBlock)
#elif defined(RTE_RUNNABLEAPI_RestoreBlockDefaults)
#elif defined(RTE_RUNNABLEAPI_RestorePRAMBlockDefaults)
#elif defined(RTE_RUNNABLEAPI_SetBlockProtection)
#elif defined(RTE_RUNNABLEAPI_SetDataIndex)
#elif defined(RTE_RUNNABLEAPI_SetRamBlockStatus)
#elif defined(RTE_RUNNABLEAPI_WriteBlock)
#elif defined(RTE_RUNNABLEAPI_WritePRAMBlock)
#else
   /* None of above defined so define value including all APIs (rte_sws_2751) */
   #define RTE_PRV_ALL_API
#endif

/*******************************************************
 ***
 *** Constants
 ***
 *******************************************************/

#ifndef RTE_CORE
#define RTE_E_NvMService_E_NOT_OK ((Std_ReturnType)1)
#endif /* RTE_CORE */

/*******************************************************
 ***
 *** Public Types
 ***
 *******************************************************/

/* BEGIN: SWC types (core visible) */
struct Rte_CDS_NvM {
   uint8 Rte_Dummy;
};
typedef struct Rte_CDS_NvM Rte_CDS_NvM;
/* END: SWC types (core visible) */

/*******************************************************
 ***
 *** Private Types
 ***
 *******************************************************/

/* BEGIN: SWC types (private) */
/* END: SWC types (private) */

/*******************************************************
 ***
 *** Instance Declarations
 ***
 *******************************************************/

#define RTE_START_SEC_EcucPartition_Core0_CONST_UNSPECIFIED
#include "Rte_MemMap.h"
extern CONST(struct Rte_CDS_NvM, RTE_CONST) Rte_Inst_NvM;
#define RTE_STOP_SEC_EcucPartition_Core0_CONST_UNSPECIFIED
#include "Rte_MemMap.h"


#ifndef RTE_CORE
typedef CONSTP2CONST(struct Rte_CDS_NvM, AUTOMATIC, RTE_CONST) Rte_Instance;
#endif /* RTE_CORE */

/*******************************************************
 ***
 *** API Mapping macros
 ***
 *******************************************************/

/* API Mapping Macros */
#ifndef RTE_CORE

#endif /* RTE_CORE */

/*******************************************************
 ***
 *** RE Prototypes
 ***
 *******************************************************/

#define NvM_START_SEC_CODE
#include "NvM_MemMap.h"
FUNC(Std_ReturnType, NvM_CODE) NvM_EraseNvBlock(VAR(NvM_BlockIdType, AUTOMATIC) BlockId);
FUNC(Std_ReturnType, NvM_CODE) NvM_GetDataIndex(VAR(NvM_BlockIdType, AUTOMATIC) BlockId,
                                                P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) DataIndexPtr);
FUNC(Std_ReturnType, NvM_CODE) NvM_GetErrorStatus(VAR(NvM_BlockIdType, AUTOMATIC) BlockId,
                                                  P2VAR(NvM_RequestResultType, AUTOMATIC, RTE_APPL_DATA) RequestResultPtr);
FUNC(Std_ReturnType, NvM_CODE) NvM_InvalidateNvBlock(VAR(NvM_BlockIdType, AUTOMATIC) BlockId);
FUNC(Std_ReturnType, NvM_CODE) NvM_ReadBlock(VAR(NvM_BlockIdType, AUTOMATIC) BlockId,
                                             VAR(NvM_Rb_VoidPtr, AUTOMATIC) NvM_DstPtr);
FUNC(Std_ReturnType, NvM_CODE) NvM_ReadPRAMBlock(VAR(NvM_BlockIdType, AUTOMATIC) BlockId);
FUNC(Std_ReturnType, NvM_CODE) NvM_RestoreBlockDefaults(VAR(NvM_BlockIdType, AUTOMATIC) BlockId,
                                                        VAR(NvM_Rb_VoidPtr, AUTOMATIC) NvM_DstPtr);
FUNC(Std_ReturnType, NvM_CODE) NvM_RestorePRAMBlockDefaults(VAR(NvM_BlockIdType, AUTOMATIC) BlockId);
FUNC(Std_ReturnType, NvM_CODE) NvM_SetDataIndex(VAR(NvM_BlockIdType, AUTOMATIC) BlockId,
                                                VAR(uint8, AUTOMATIC) DataIndex);
FUNC(Std_ReturnType, NvM_CODE) NvM_SetRamBlockStatus(VAR(NvM_BlockIdType, AUTOMATIC) BlockId,
                                                     VAR(boolean, AUTOMATIC) BlockChanged);
FUNC(Std_ReturnType, NvM_CODE) NvM_WriteBlock(VAR(NvM_BlockIdType, AUTOMATIC) BlockId,
                                              VAR(NvM_Rb_ConstVoidPtr, AUTOMATIC) NvM_SrcPtr);
FUNC(Std_ReturnType, NvM_CODE) NvM_WritePRAMBlock(VAR(NvM_BlockIdType, AUTOMATIC) BlockId);
#define NvM_STOP_SEC_CODE
#include "NvM_MemMap.h"

/* Initial values for data element prototypes */

#ifdef __cplusplus
} /* extern C */
#endif /* __cplusplus */

#endif /* !RTE_NVM_H */
