/** @file     Rte_ASW_DEM_Type.h
  *
  * @brief    Application types header file
  *
  * @note     AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
  *
  * @note     Generated by ETAS RTA-RTE
  * @note     Version 7.5.3
  *
  * @date     Mon Mar 23 13:15:43 2026
  */

#ifndef RTE_ASW_DEM_TYPE_H
#define RTE_ASW_DEM_TYPE_H

#include "Rte_Type.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

/* BEGIN: SWC specific types */
/* END: SWC specific types */

/* BEGIN: SWC specific definitions */
#if !defined(RTE_CORE)

/* Box: /AUTOSAR_Dem/ImplementationDataTypes/Dem_IndicatorStatusType begin */
/* Box: DEM_INDICATOR_OFF ("DEM_INDICATOR_OFF") begin */
#ifndef DEM_INDICATOR_OFF
#define DEM_INDICATOR_OFF (0U)
#endif /* !DEM_INDICATOR_OFF */
/* Box: DEM_INDICATOR_OFF ("DEM_INDICATOR_OFF") end */
/* Box: DEM_INDICATOR_CONTINUOUS ("DEM_INDICATOR_CONTINUOUS") begin */
#ifndef DEM_INDICATOR_CONTINUOUS
#define DEM_INDICATOR_CONTINUOUS (1U)
#endif /* !DEM_INDICATOR_CONTINUOUS */
/* Box: DEM_INDICATOR_CONTINUOUS ("DEM_INDICATOR_CONTINUOUS") end */
/* Box: DEM_INDICATOR_BLINKING ("DEM_INDICATOR_BLINKING") begin */
#ifndef DEM_INDICATOR_BLINKING
#define DEM_INDICATOR_BLINKING (2U)
#endif /* !DEM_INDICATOR_BLINKING */
/* Box: DEM_INDICATOR_BLINKING ("DEM_INDICATOR_BLINKING") end */
/* Box: DEM_INDICATOR_BLINK_CONT ("DEM_INDICATOR_BLINK_CONT") begin */
#ifndef DEM_INDICATOR_BLINK_CONT
#define DEM_INDICATOR_BLINK_CONT (3U)
#endif /* !DEM_INDICATOR_BLINK_CONT */
/* Box: DEM_INDICATOR_BLINK_CONT ("DEM_INDICATOR_BLINK_CONT") end */
/* Box: DEM_INDICATOR_SLOW_FLASH ("DEM_INDICATOR_SLOW_FLASH") begin */
#ifndef DEM_INDICATOR_SLOW_FLASH
#define DEM_INDICATOR_SLOW_FLASH (4U)
#endif /* !DEM_INDICATOR_SLOW_FLASH */
/* Box: DEM_INDICATOR_SLOW_FLASH ("DEM_INDICATOR_SLOW_FLASH") end */
/* Box: DEM_INDICATOR_FAST_FLASH ("DEM_INDICATOR_FAST_FLASH") begin */
#ifndef DEM_INDICATOR_FAST_FLASH
#define DEM_INDICATOR_FAST_FLASH (5U)
#endif /* !DEM_INDICATOR_FAST_FLASH */
/* Box: DEM_INDICATOR_FAST_FLASH ("DEM_INDICATOR_FAST_FLASH") end */
/* Box: /AUTOSAR_Dem/ImplementationDataTypes/Dem_IndicatorStatusType end */

/* Box: /AUTOSAR_Dem/ImplementationDataTypes/Dem_OperationCycleStateType begin */
/* Box: DEM_CYCLE_STATE_START ("DEM_CYCLE_STATE_START") begin */
#ifndef DEM_CYCLE_STATE_START
#define DEM_CYCLE_STATE_START (0U)
#endif /* !DEM_CYCLE_STATE_START */
/* Box: DEM_CYCLE_STATE_START ("DEM_CYCLE_STATE_START") end */
/* Box: DEM_CYCLE_STATE_END ("DEM_CYCLE_STATE_END") begin */
#ifndef DEM_CYCLE_STATE_END
#define DEM_CYCLE_STATE_END (1U)
#endif /* !DEM_CYCLE_STATE_END */
/* Box: DEM_CYCLE_STATE_END ("DEM_CYCLE_STATE_END") end */
/* Box: /AUTOSAR_Dem/ImplementationDataTypes/Dem_OperationCycleStateType end */

/* Box: /AUTOSAR_Platform/ImplementationDataTypes/boolean begin */
/* Box: "FALSE" begin */
#ifndef FALSE
#define FALSE (0U)
#endif /* !FALSE */
/* Box: "FALSE" end */
/* Box: "TRUE" begin */
#ifndef TRUE
#define TRUE (1U)
#endif /* !TRUE */
/* Box: "TRUE" end */
/* Box: /AUTOSAR_Platform/ImplementationDataTypes/boolean end */
#endif /* !defined(RTE_CORE) */
/* END: SWC specific definitions */

#ifdef __cplusplus
} /* extern C */
#endif /* __cplusplus */

#endif /* !RTE_ASW_DEM_TYPE_H */
