/** @file     Rte_ASW_DCM_Type.h
  *
  * @brief    Application types header file
  *
  * @note     AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
  *
  * @note     Generated by ETAS RTA-RTE
  * @note     Version 7.5.3
  *
  * @date     Mon Mar 23 13:15:43 2026
  */

#ifndef RTE_ASW_DCM_TYPE_H
#define RTE_ASW_DCM_TYPE_H

#include "Rte_Type.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

/* BEGIN: SWC specific types */
/* END: SWC specific types */

/* BEGIN: SWC specific definitions */
#if !defined(RTE_CORE)

/* Box: /AUTOSAR_Dcm/ImplementationDataTypes/Dcm_OpStatusType begin */
/* Box: "DCM_INITIAL" begin */
#ifndef DCM_INITIAL
#define DCM_INITIAL (0U)
#endif /* !DCM_INITIAL */
/* Box: "DCM_INITIAL" end */
/* Box: "DCM_PENDING" begin */
#ifndef DCM_PENDING
#define DCM_PENDING (1U)
#endif /* !DCM_PENDING */
/* Box: "DCM_PENDING" end */
/* Box: "DCM_CANCEL" begin */
#ifndef DCM_CANCEL
#define DCM_CANCEL (2U)
#endif /* !DCM_CANCEL */
/* Box: "DCM_CANCEL" end */
/* Box: "DCM_FORCE_RCRRP_OK" begin */
#ifndef DCM_FORCE_RCRRP_OK
#define DCM_FORCE_RCRRP_OK (3U)
#endif /* !DCM_FORCE_RCRRP_OK */
/* Box: "DCM_FORCE_RCRRP_OK" end */
/* Box: /AUTOSAR_Dcm/ImplementationDataTypes/Dcm_OpStatusType end */

/* Box: /AUTOSAR_Dcm/ImplementationDataTypes/Dcm_ProtocolType begin */
/* Box: "DCM_OBD_ON_CAN" begin */
#ifndef DCM_OBD_ON_CAN
#define DCM_OBD_ON_CAN (0U)
#endif /* !DCM_OBD_ON_CAN */
/* Box: "DCM_OBD_ON_CAN" end */
/* Box: "DCM_OBD_ON_FLEXRAY" begin */
#ifndef DCM_OBD_ON_FLEXRAY
#define DCM_OBD_ON_FLEXRAY (1U)
#endif /* !DCM_OBD_ON_FLEXRAY */
/* Box: "DCM_OBD_ON_FLEXRAY" end */
/* Box: "DCM_OBD_ON_IP" begin */
#ifndef DCM_OBD_ON_IP
#define DCM_OBD_ON_IP (2U)
#endif /* !DCM_OBD_ON_IP */
/* Box: "DCM_OBD_ON_IP" end */
/* Box: "DCM_UDS_ON_CAN" begin */
#ifndef DCM_UDS_ON_CAN
#define DCM_UDS_ON_CAN (3U)
#endif /* !DCM_UDS_ON_CAN */
/* Box: "DCM_UDS_ON_CAN" end */
/* Box: "DCM_UDS_ON_FLEXRAY" begin */
#ifndef DCM_UDS_ON_FLEXRAY
#define DCM_UDS_ON_FLEXRAY (4U)
#endif /* !DCM_UDS_ON_FLEXRAY */
/* Box: "DCM_UDS_ON_FLEXRAY" end */
/* Box: "DCM_UDS_ON_IP" begin */
#ifndef DCM_UDS_ON_IP
#define DCM_UDS_ON_IP (5U)
#endif /* !DCM_UDS_ON_IP */
/* Box: "DCM_UDS_ON_IP" end */
/* Box: "DCM_ROE_ON_CAN" begin */
#ifndef DCM_ROE_ON_CAN
#define DCM_ROE_ON_CAN (6U)
#endif /* !DCM_ROE_ON_CAN */
/* Box: "DCM_ROE_ON_CAN" end */
/* Box: "DCM_ROE_ON_FLEXRAY" begin */
#ifndef DCM_ROE_ON_FLEXRAY
#define DCM_ROE_ON_FLEXRAY (7U)
#endif /* !DCM_ROE_ON_FLEXRAY */
/* Box: "DCM_ROE_ON_FLEXRAY" end */
/* Box: "DCM_ROE_ON_IP" begin */
#ifndef DCM_ROE_ON_IP
#define DCM_ROE_ON_IP (8U)
#endif /* !DCM_ROE_ON_IP */
/* Box: "DCM_ROE_ON_IP" end */
/* Box: "DCM_PERIODICTRANS_ON_CAN" begin */
#ifndef DCM_PERIODICTRANS_ON_CAN
#define DCM_PERIODICTRANS_ON_CAN (9U)
#endif /* !DCM_PERIODICTRANS_ON_CAN */
/* Box: "DCM_PERIODICTRANS_ON_CAN" end */
/* Box: "DCM_PERIODICTRANS_ON_FLEXRAY" begin */
#ifndef DCM_PERIODICTRANS_ON_FLEXRAY
#define DCM_PERIODICTRANS_ON_FLEXRAY (10U)
#endif /* !DCM_PERIODICTRANS_ON_FLEXRAY */
/* Box: "DCM_PERIODICTRANS_ON_FLEXRAY" end */
/* Box: "DCM_PERIODICTRANS_ON_IP" begin */
#ifndef DCM_PERIODICTRANS_ON_IP
#define DCM_PERIODICTRANS_ON_IP (11U)
#endif /* !DCM_PERIODICTRANS_ON_IP */
/* Box: "DCM_PERIODICTRANS_ON_IP" end */
/* Box: "DCM_NO_ACTIVE_PROTOCOL" begin */
#ifndef DCM_NO_ACTIVE_PROTOCOL
#define DCM_NO_ACTIVE_PROTOCOL (12U)
#endif /* !DCM_NO_ACTIVE_PROTOCOL */
/* Box: "DCM_NO_ACTIVE_PROTOCOL" end */
/* Box: "DCM_KWP_ON_KLINE" begin */
#ifndef DCM_KWP_ON_KLINE
#define DCM_KWP_ON_KLINE (128U)
#endif /* !DCM_KWP_ON_KLINE */
/* Box: "DCM_KWP_ON_KLINE" end */
/* Box: "DCM_KWP_ON_CAN" begin */
#ifndef DCM_KWP_ON_CAN
#define DCM_KWP_ON_CAN (129U)
#endif /* !DCM_KWP_ON_CAN */
/* Box: "DCM_KWP_ON_CAN" end */
/* Box: "DCM_ACEA_ON_CAN" begin */
#ifndef DCM_ACEA_ON_CAN
#define DCM_ACEA_ON_CAN (144U)
#endif /* !DCM_ACEA_ON_CAN */
/* Box: "DCM_ACEA_ON_CAN" end */
/* Box: "DCM_ACEA_ON_FLEXRAY" begin */
#ifndef DCM_ACEA_ON_FLEXRAY
#define DCM_ACEA_ON_FLEXRAY (145U)
#endif /* !DCM_ACEA_ON_FLEXRAY */
/* Box: "DCM_ACEA_ON_FLEXRAY" end */
/* Box: "DCM_CARB_ON_KLINE" begin */
#ifndef DCM_CARB_ON_KLINE
#define DCM_CARB_ON_KLINE (160U)
#endif /* !DCM_CARB_ON_KLINE */
/* Box: "DCM_CARB_ON_KLINE" end */
/* Box: "DCM_OBD_ON_KLINE" begin */
#ifndef DCM_OBD_ON_KLINE
#define DCM_OBD_ON_KLINE (161U)
#endif /* !DCM_OBD_ON_KLINE */
/* Box: "DCM_OBD_ON_KLINE" end */
/* Box: "DCM_SUPPLIER_1" begin */
#ifndef DCM_SUPPLIER_1
#define DCM_SUPPLIER_1 (240U)
#endif /* !DCM_SUPPLIER_1 */
/* Box: "DCM_SUPPLIER_1" end */
/* Box: "DCM_SUPPLIER_2" begin */
#ifndef DCM_SUPPLIER_2
#define DCM_SUPPLIER_2 (241U)
#endif /* !DCM_SUPPLIER_2 */
/* Box: "DCM_SUPPLIER_2" end */
/* Box: "DCM_SUPPLIER_3" begin */
#ifndef DCM_SUPPLIER_3
#define DCM_SUPPLIER_3 (242U)
#endif /* !DCM_SUPPLIER_3 */
/* Box: "DCM_SUPPLIER_3" end */
/* Box: "DCM_SUPPLIER_4" begin */
#ifndef DCM_SUPPLIER_4
#define DCM_SUPPLIER_4 (243U)
#endif /* !DCM_SUPPLIER_4 */
/* Box: "DCM_SUPPLIER_4" end */
/* Box: "DCM_SUPPLIER_5" begin */
#ifndef DCM_SUPPLIER_5
#define DCM_SUPPLIER_5 (244U)
#endif /* !DCM_SUPPLIER_5 */
/* Box: "DCM_SUPPLIER_5" end */
/* Box: "DCM_SUPPLIER_6" begin */
#ifndef DCM_SUPPLIER_6
#define DCM_SUPPLIER_6 (245U)
#endif /* !DCM_SUPPLIER_6 */
/* Box: "DCM_SUPPLIER_6" end */
/* Box: "DCM_SUPPLIER_7" begin */
#ifndef DCM_SUPPLIER_7
#define DCM_SUPPLIER_7 (246U)
#endif /* !DCM_SUPPLIER_7 */
/* Box: "DCM_SUPPLIER_7" end */
/* Box: "DCM_SUPPLIER_8" begin */
#ifndef DCM_SUPPLIER_8
#define DCM_SUPPLIER_8 (247U)
#endif /* !DCM_SUPPLIER_8 */
/* Box: "DCM_SUPPLIER_8" end */
/* Box: "DCM_SUPPLIER_9" begin */
#ifndef DCM_SUPPLIER_9
#define DCM_SUPPLIER_9 (248U)
#endif /* !DCM_SUPPLIER_9 */
/* Box: "DCM_SUPPLIER_9" end */
/* Box: "DCM_SUPPLIER_10" begin */
#ifndef DCM_SUPPLIER_10
#define DCM_SUPPLIER_10 (249U)
#endif /* !DCM_SUPPLIER_10 */
/* Box: "DCM_SUPPLIER_10" end */
/* Box: "DCM_SUPPLIER_11" begin */
#ifndef DCM_SUPPLIER_11
#define DCM_SUPPLIER_11 (250U)
#endif /* !DCM_SUPPLIER_11 */
/* Box: "DCM_SUPPLIER_11" end */
/* Box: "DCM_SUPPLIER_12" begin */
#ifndef DCM_SUPPLIER_12
#define DCM_SUPPLIER_12 (251U)
#endif /* !DCM_SUPPLIER_12 */
/* Box: "DCM_SUPPLIER_12" end */
/* Box: "DCM_SUPPLIER_13" begin */
#ifndef DCM_SUPPLIER_13
#define DCM_SUPPLIER_13 (252U)
#endif /* !DCM_SUPPLIER_13 */
/* Box: "DCM_SUPPLIER_13" end */
/* Box: "DCM_SUPPLIER_14" begin */
#ifndef DCM_SUPPLIER_14
#define DCM_SUPPLIER_14 (253U)
#endif /* !DCM_SUPPLIER_14 */
/* Box: "DCM_SUPPLIER_14" end */
/* Box: "DCM_SUPPLIER_15" begin */
#ifndef DCM_SUPPLIER_15
#define DCM_SUPPLIER_15 (254U)
#endif /* !DCM_SUPPLIER_15 */
/* Box: "DCM_SUPPLIER_15" end */
/* Box: /AUTOSAR_Dcm/ImplementationDataTypes/Dcm_ProtocolType end */

/* Box: /AUTOSAR_Dcm/ImplementationDataTypes/Dcm_SecLevelType begin */
/* Box: "DCM_SEC_LEV_L1" begin */
#ifndef DCM_SEC_LEV_L1
#define DCM_SEC_LEV_L1 (1U)
#endif /* !DCM_SEC_LEV_L1 */
/* Box: "DCM_SEC_LEV_L1" end */
/* Box: /AUTOSAR_Dcm/ImplementationDataTypes/Dcm_SecLevelType end */

/* Box: /AUTOSAR_Dcm/ImplementationDataTypes/Dcm_SesCtrlType begin */
/* Box: "DCM_DEFAULT_SESSION" begin */
#ifndef DCM_DEFAULT_SESSION
#define DCM_DEFAULT_SESSION (1U)
#endif /* !DCM_DEFAULT_SESSION */
/* Box: "DCM_DEFAULT_SESSION" end */
/* Box: "DCM_PROGRAMMING_SESSION" begin */
#ifndef DCM_PROGRAMMING_SESSION
#define DCM_PROGRAMMING_SESSION (2U)
#endif /* !DCM_PROGRAMMING_SESSION */
/* Box: "DCM_PROGRAMMING_SESSION" end */
/* Box: "DCM_EXTENDED_DIAGNOSTIC_SESSION" begin */
#ifndef DCM_EXTENDED_DIAGNOSTIC_SESSION
#define DCM_EXTENDED_DIAGNOSTIC_SESSION (3U)
#endif /* !DCM_EXTENDED_DIAGNOSTIC_SESSION */
/* Box: "DCM_EXTENDED_DIAGNOSTIC_SESSION" end */
/* Box: "DCM_SAFETY_SYSTEM_DIAGNOSTIC_SESSION" begin */
#ifndef DCM_SAFETY_SYSTEM_DIAGNOSTIC_SESSION
#define DCM_SAFETY_SYSTEM_DIAGNOSTIC_SESSION (4U)
#endif /* !DCM_SAFETY_SYSTEM_DIAGNOSTIC_SESSION */
/* Box: "DCM_SAFETY_SYSTEM_DIAGNOSTIC_SESSION" end */
/* Box: /AUTOSAR_Dcm/ImplementationDataTypes/Dcm_SesCtrlType end */

/* Box: /AUTOSAR_Platform/ImplementationDataTypes/boolean begin */
/* Box: "FALSE" begin */
#ifndef FALSE
#define FALSE (0U)
#endif /* !FALSE */
/* Box: "FALSE" end */
/* Box: "TRUE" begin */
#ifndef TRUE
#define TRUE (1U)
#endif /* !TRUE */
/* Box: "TRUE" end */
/* Box: /AUTOSAR_Platform/ImplementationDataTypes/boolean end */
#endif /* !defined(RTE_CORE) */
/* END: SWC specific definitions */

#ifdef __cplusplus
} /* extern C */
#endif /* __cplusplus */

#endif /* !RTE_ASW_DCM_TYPE_H */
