/** @file     Rte_Cbk.h
  *
  * @brief    RTE generated callbacks
  *
  * @note     AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
  *
  * @note     Generated by ETAS RTA-RTE
  * @note     Version 7.5.3
  *
  * @date     Mon Mar 23 13:15:45 2026
  */

#ifndef RTE_CBK_H
#define RTE_CBK_H

/* No COM Callback functions created */
#endif /* !RTE_CBK_H */
