/** @file     Rte_ASW_DCM.h
  *
  * @brief    Application header file
  *
  * @note     AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
  *
  * @note     Generated by ETAS RTA-RTE
  * @note     Version 7.5.3
  *
  * @date     Mon Mar 23 13:15:43 2026
  */

#ifndef RTE_ASW_DCM_H
#define RTE_ASW_DCM_H

#ifndef RTE_CORE
#ifdef RTE_APPLICATION_HEADER_FILE
#error Multiple application header files included.
#endif /* RTE_APPLICATION_HEADER_FILE */
#define RTE_APPLICATION_HEADER_FILE
#endif /* RTE_CORE */

/*******************************************************
 ***
 *** Includes
 ***
 *******************************************************/

#include "Rte.h"
#include "Rte_Intl.h"
#include "Rte_ASW_DCM_Type.h"

#include "Rte_DataHandleType.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#if defined(RTE_RUNNABLEAPI_ASW_DCM_PeriodicRunnable_10ms)
   /* Do nothing for this and all elif clauses below (rte_sws_2751) */
#elif defined(RTE_RUNNABLEAPI_DataServices_R_PID_04_ReadData)
#elif defined(RTE_RUNNABLEAPI_DataServices_R_PID_05_ReadData)
#elif defined(RTE_RUNNABLEAPI_DataServices_R_PID_0C_ReadData)
#elif defined(RTE_RUNNABLEAPI_DataServices_R_PID_0D_ReadData)
#elif defined(RTE_RUNNABLEAPI_DataServices_R_PID_21_ReadData)
#elif defined(RTE_RUNNABLEAPI_DataServices_R_PID_30_ReadData)
#elif defined(RTE_RUNNABLEAPI_DataServices_R_PID_31_ReadData)
#elif defined(RTE_RUNNABLEAPI_DataServices_R_PID_41_ReadData)
#elif defined(RTE_RUNNABLEAPI_DataServices_R_PID_42_ReadData)
#elif defined(RTE_RUNNABLEAPI_DataServices_R_PID_49_ReadData)
#elif defined(RTE_RUNNABLEAPI_RunnableEntity_VIT_04)
#elif defined(RTE_RUNNABLEAPI_RunnableEntity_VIT_06)
#elif defined(RTE_RUNNABLEAPI_RunnableEntity_VIT_0A)
#else
   /* None of above defined so define value including all APIs (rte_sws_2751) */
   #define RTE_PRV_ALL_API
#endif

/*******************************************************
 ***
 *** Constants
 ***
 *******************************************************/

#ifndef RTE_CORE
#define RTE_E_DCMServices_E_NOT_OK ((Std_ReturnType)1)
#define RTE_E_DCMServices_E_OK ((Std_ReturnType)0)
#define RTE_E_DataServices_DcmDspPidData_04_E_NOT_OK ((Std_ReturnType)1)
#define RTE_E_DataServices_DcmDspPidData_04_E_OK ((Std_ReturnType)0)
#define RTE_E_DataServices_DcmDspPidData_05_E_NOT_OK ((Std_ReturnType)1)
#define RTE_E_DataServices_DcmDspPidData_05_E_OK ((Std_ReturnType)0)
#define RTE_E_DataServices_DcmDspPidData_0C_E_NOT_OK ((Std_ReturnType)1)
#define RTE_E_DataServices_DcmDspPidData_0C_E_OK ((Std_ReturnType)0)
#define RTE_E_DataServices_DcmDspPidData_0D_E_NOT_OK ((Std_ReturnType)1)
#define RTE_E_DataServices_DcmDspPidData_0D_E_OK ((Std_ReturnType)0)
#define RTE_E_DataServices_DcmDspPidData_21_E_NOT_OK ((Std_ReturnType)1)
#define RTE_E_DataServices_DcmDspPidData_21_E_OK ((Std_ReturnType)0)
#define RTE_E_DataServices_DcmDspPidData_30_E_NOT_OK ((Std_ReturnType)1)
#define RTE_E_DataServices_DcmDspPidData_30_E_OK ((Std_ReturnType)0)
#define RTE_E_DataServices_DcmDspPidData_31_E_NOT_OK ((Std_ReturnType)1)
#define RTE_E_DataServices_DcmDspPidData_31_E_OK ((Std_ReturnType)0)
#define RTE_E_DataServices_DcmDspPidData_41_E_NOT_OK ((Std_ReturnType)1)
#define RTE_E_DataServices_DcmDspPidData_41_E_OK ((Std_ReturnType)0)
#define RTE_E_DataServices_DcmDspPidData_42_E_NOT_OK ((Std_ReturnType)1)
#define RTE_E_DataServices_DcmDspPidData_42_E_OK ((Std_ReturnType)0)
#define RTE_E_DataServices_DcmDspPidData_49_E_NOT_OK ((Std_ReturnType)1)
#define RTE_E_DataServices_DcmDspPidData_49_E_OK ((Std_ReturnType)0)
#define RTE_E_InfotypeServices_DcmDspVehInfoData_04_DCM_E_PENDING ((Std_ReturnType)10)
#define RTE_E_InfotypeServices_DcmDspVehInfoData_04_E_NOT_OK ((Std_ReturnType)1)
#define RTE_E_InfotypeServices_DcmDspVehInfoData_04_E_OK ((Std_ReturnType)0)
#define RTE_E_InfotypeServices_DcmDspVehInfoData_0A_DCM_E_PENDING ((Std_ReturnType)10)
#define RTE_E_InfotypeServices_DcmDspVehInfoData_0A_E_NOT_OK ((Std_ReturnType)1)
#define RTE_E_InfotypeServices_DcmDspVehInfoData_0A_E_OK ((Std_ReturnType)0)
#define RTE_E_InfotypeServices_VIT_06_0_DCM_E_PENDING ((Std_ReturnType)10)
#define RTE_E_InfotypeServices_VIT_06_0_E_NOT_OK ((Std_ReturnType)1)
#define RTE_E_InfotypeServices_VIT_06_0_E_OK ((Std_ReturnType)0)
#endif /* RTE_CORE */

/*******************************************************
 ***
 *** Public Types
 ***
 *******************************************************/

/* BEGIN: SWC types (core visible) */
struct Rte_CDS_ASW_DCM {
   uint8 Rte_Dummy;
};
typedef struct Rte_CDS_ASW_DCM Rte_CDS_ASW_DCM;
/* END: SWC types (core visible) */

/*******************************************************
 ***
 *** Private Types
 ***
 *******************************************************/

/* BEGIN: SWC types (private) */
/* END: SWC types (private) */

/*******************************************************
 ***
 *** Instance Declarations
 ***
 *******************************************************/

#define RTE_START_SEC_EcucPartition_Core0_CONST_UNSPECIFIED
#include "Rte_MemMap.h"
extern CONST(struct Rte_CDS_ASW_DCM, RTE_CONST) Rte_Inst_ASW_DCM;
#define RTE_STOP_SEC_EcucPartition_Core0_CONST_UNSPECIFIED
#include "Rte_MemMap.h"


#ifndef RTE_CORE
typedef CONSTP2CONST(struct Rte_CDS_ASW_DCM, AUTOMATIC, RTE_CONST) Rte_Instance;
#endif /* RTE_CORE */

/*******************************************************
 ***
 *** API Mapping macros
 ***
 *******************************************************/

/* API Mapping Macros */
#ifndef RTE_CORE

#endif /* RTE_CORE */

/*******************************************************
 ***
 *** RE Prototypes
 ***
 *******************************************************/

#define ASW_DCM_START_SEC_CODE
#include "ASW_DCM_MemMap.h"
FUNC(void, ASW_DCM_CODE) ASW_DCM_PeriodicRunnable_10ms_func(void);
FUNC(Std_ReturnType, ASW_DCM_CODE) DataServices_R_PID_04_ReadData(P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Data);
FUNC(Std_ReturnType, ASW_DCM_CODE) DataServices_R_PID_05_ReadData(P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Data);
FUNC(Std_ReturnType, ASW_DCM_CODE) DataServices_R_PID_0C_ReadData(P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Data);
FUNC(Std_ReturnType, ASW_DCM_CODE) DataServices_R_PID_0D_ReadData(P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Data);
FUNC(Std_ReturnType, ASW_DCM_CODE) DataServices_R_PID_21_ReadData(P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Data);
FUNC(Std_ReturnType, ASW_DCM_CODE) DataServices_R_PID_30_ReadData(P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Data);
FUNC(Std_ReturnType, ASW_DCM_CODE) DataServices_R_PID_31_ReadData(P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Data);
FUNC(Std_ReturnType, ASW_DCM_CODE) DataServices_R_PID_41_ReadData(P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Data);
FUNC(Std_ReturnType, ASW_DCM_CODE) DataServices_R_PID_42_ReadData(P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Data);
FUNC(Std_ReturnType, ASW_DCM_CODE) DataServices_R_PID_49_ReadData(P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Data);
FUNC(Std_ReturnType, ASW_DCM_CODE) RunnableEntity_0_VIT_04(VAR(Dcm_OpStatusType, AUTOMATIC) OpStatus,
                                                           P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) DataValueBuffer,
                                                           P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) DataValueBufferSize);
FUNC(Std_ReturnType, ASW_DCM_CODE) RunnableEntity_0_func_VIT_0A(VAR(Dcm_OpStatusType, AUTOMATIC) OpStatus,
                                                                P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) DataValueBuffer,
                                                                P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) DataValueBufferSize);
FUNC(Std_ReturnType, ASW_DCM_CODE) RunnableEntity_0_func_vit_06(VAR(Dcm_OpStatusType, AUTOMATIC) OpStatus,
                                                                P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) DataValueBuffer,
                                                                P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) DataValueBufferSize);
#define ASW_DCM_STOP_SEC_CODE
#include "ASW_DCM_MemMap.h"

/* Initial values for data element prototypes */

#ifdef __cplusplus
} /* extern C */
#endif /* __cplusplus */

#endif /* !RTE_ASW_DCM_H */
