/** @file     SchM_ComM_Type.h
  *
  * @brief    Basic Software Scheduler Module Interlink Types header file
  *
  * @note     AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
  *
  * @note     Generated by ETAS RTA-RTE
  * @note     Version 7.5.3
  *
  * @date     Mon Mar 23 13:15:44 2026
  */

#ifndef SchM_ComM_Type
#define SchM_ComM_Type

#include "Rte_Type.h"
#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

/* BEGIN: BSW implementation specific types */
/* END: BSW implementation specific types */

/* BEGIN: BSW implementation specific definitions */
/* END: BSW implementation specific definitions */


#ifdef __cplusplus
} /* extern C */
#endif /* __cplusplus */

#endif /* !SchM_ComM_Type */
