
/*<VersionHead>
 * This Configuration File is generated using versions (automatically filled in) as listed below.
 *
 * $Generator__: PduR  / AR42.10.0.0                Module Package Version
 * $Editor_____: ISOLAR-A/B 9.2.1_9.2.1                Tool Version
 * $Model______: 2.3.0.4                ECU Parameter Definition Version
 *
 
 </VersionHead>*/

#ifndef PDUR_PBCFG_H
#define PDUR_PBCFG_H
#include "PduR_Types.h"

/*
 These #defines are generated by the code generator tool. Respective module's function names are generated
 only if it is present in the PduR_PbCfg.c file in any one of the entries.
 */

/*
 These #defines correspond to the entries in the PduR_loTransmitTable in PduR_PBcfg.c.
 */

#if !defined(PduR_RF_CanTp_Transmit)
#define PduR_RF_CanTp_Transmit    (0)
#endif /* PduR_RF_CanTp_Transmit */

#define MAX_NO_OF_LO_TXTABLE_ENTRIES 0

/*
 These #defines correspond to the entries in the PduR_loCancelRxTable in PduR_Cfg.c.
 */

/*
 These #defines correspond to the entries in the PduR_loCancelTransmitTable in PduR_Cfg.c.
 */

#if !defined(PduR_RF_CanTp_CancelTransmit)
#define PduR_RF_CanTp_CancelTransmit    (0)
#endif /* PduR_RF_CanTp_CancelTransmit */

#define MAX_NO_OF_LO_CANCEL_TXTABLE_ENTRIES 0

/*
 These #defines correspond to the entries in the PduR_upIfRxIndicationTable in PduR_Cfg.c.
 */

/*
 These #defines correspond to the entries in the PduR_upIfTxConfirmationTable in PduR_Cfg.c.
 */

/*
 These #defines correspond to the entries in the PduR_upIfTriggerTxTable in PduR_Cfg.c.
 */

/*
 These #defines correspond to the entries in the PduR_upTpCopyRxDataTable in PduR_Cfg.c.
 */

#if !defined(PduR_RF_Dcm_CopyRxData)
#define PduR_RF_Dcm_CopyRxData    (0)
#endif /* PduR_RF_Dcm_CopyRxData */

#define MAX_NO_OF_UPTP_COPYRXDATA_TABLE_ENTRIES 0

/*
 These #defines correspond to the entries in the PduR_upTpStartOfReceptionTable in PduR_Cfg.c.
 */

#if !defined(PduR_RF_Dcm_StartOfReception)
#define PduR_RF_Dcm_StartOfReception    (0)
#endif /* PduR_RF_Dcm_StartOfReception */

#define MAX_NO_OF_UPTP_STARTOFRECEPTION_TABLE_ENTRIES 0

/*
 These #defines correspond to the entries in the PduR_upTpRxIndicationTable in PduR_Cfg.c.
 */

#if !defined(PduR_RF_Dcm_TpRxIndication)
#define PduR_RF_Dcm_TpRxIndication    (0)
#endif /* PduR_RF_Dcm_TpRxIndication */

#define MAX_NO_OF_UPTP_RXINDICATION_TABLE_ENTRIES 0

/*
 These #defines correspond to the entries in the PduR_upTpCopyTxDataTable in PduR_Cfg.c.
 */

#if !defined(PduR_RF_Dcm_CopyTxData)
#define PduR_RF_Dcm_CopyTxData    (0)
#endif /* PduR_RF_Dcm_CopyTxData */

#define MAX_NO_OF_UPTP_COPYTXDATA_TABLE_ENTRIES 0

/*
 These #defines correspond to the entries in the PduR_upTpTxConfirmationTable in PduR_Cfg.c.
 */

#if !defined(PduR_RF_Dcm_TpTxConfirmation)
#define PduR_RF_Dcm_TpTxConfirmation    (0)
#endif /* PduR_RF_Dcm_TpTxConfirmation */

#define MAX_NO_OF_UPTP_TXCONFIRMATION_TABLE_ENTRIES 0

#define PDUR_START_SEC_CONFIG_DATA_UNSPECIFIED
#include "PduR_MemMap.h"

#define PDUR_STOP_SEC_CONFIG_DATA_UNSPECIFIED
#include "PduR_MemMap.h"

#endif /* PDUR_PBCFG_H */
