/******************************************************************************/
/*                                                                            */
/* !Layer           : STD                                                     */
/*                                                                            */
/* !Component       : MEMMAP                                                  */
/* !Description     : MEMMAP Configuration                                    */
/*                                                                            */
/* !File            : CALIB_MEMMAP.H                                          */
/*                                                                            */
/* !Scope           : Public                                                  */
/*                                                                            */
/* !Target          :                                                         */
/*                                                                            */
/* !Vendor          : invt                                                    */
/*                                                                            */
/* Coding language  : C                                                       */
/*                                                                            */
/* COPYRIGHT 2009 invt                                                        */
/* all rights reserved                                                        */
/*                                                                            */
/******************************************************************************/
/* SVN Information                                                           */
/* $Archive::                                                                $*/
/* $Revision::            $$Author::                  $$Date::               $*/
/******************************************************************************/
/* 11/09/22, 19:32:04: generated by Genecode  v2.6.0.0                        */
/* From Source Template : MSN_MEMMAP_H.TPL                                    */
/******************************************************************************/



/******************************************************************************/
/*          MEMMAP selected mode:  SAFE                                       */
/******************************************************************************/
#define MEMMAP_ERROR

/* The following if is used only due to automatic generation */
#if !defined MEMMAP_ERROR

/* Project section mappings */
/* !Comment: CALIB Section allocation */
#elif defined   CALIB_START_SEC_CALIB_BEG
   #undef  CALIB_START_SEC_CALIB_BEG
   #define START_SEC_CALIB_BEG_SECTION
#elif defined   CALIB_STOP_SEC_CALIB_BEG
   #undef  CALIB_STOP_SEC_CALIB_BEG
   #define STOP_SEC_CALIB_BEG_SECTION

#elif defined   CALIB_START_SEC_CALIB_END
   #undef  CALIB_START_SEC_CALIB_END
   #define START_SEC_CALIB_END_SECTION
#elif defined   CALIB_STOP_SEC_CALIB_END
   #undef  CALIB_STOP_SEC_CALIB_END
   #define STOP_SEC_CALIB_END_SECTION

#elif defined CALUSR_START_SEC_CALIB_UNSPECIFIED
  #define  CALIB_START_SEC_CONST_UNSPECIFIED
  #include "MemMap.h"
   #undef CALUSR_START_SEC_CALIB_UNSPECIFIED
   #undef  MEMMAP_ERROR
#elif defined CALUSR_STOP_SEC_CALIB_UNSPECIFIED
  #define  CALIB_STOP_SEC_CONST_UNSPECIFIED
  #include "MemMap.h"
   #undef CALUSR_STOP_SEC_CALIB_UNSPECIFIED
   #undef  MEMMAP_ERROR






#endif

/* ECU specific section mappings */
#ifndef MEMMAP_START_DONE

/* The following if is used only due to automatic generation */

#if FALSE
/* !Comment: SEC_CALIB_BEG Start Section treatment */
   #elif defined   START_SEC_CALIB_BEG_SECTION
	  

      #pragma section "CALIB_BEG" a

      #undef  MEMMAP_ERROR
      #define MEMMAP_START_DONE

/* !Comment: SEC_CALIB_END Start Section treatment */
   #elif defined   START_SEC_CALIB_END_SECTION
	  

      #pragma section "CALIB_END" a

      #undef  MEMMAP_ERROR
      #define MEMMAP_START_DONE


   #endif

#else   /* if MEMMAP_START_DONE is not defined */

/* The following if is used only due to automatic generation */

#if FALSE
/* !Comment: SEC_CALIB_BEG Stop Section treatment */
   #elif defined   STOP_SEC_CALIB_BEG_SECTION && defined  START_SEC_CALIB_BEG_SECTION
	  

      #pragma section

      #undef START_SEC_CALIB_BEG_SECTION
      #undef STOP_SEC_CALIB_BEG_SECTION
      #undef MEMMAP_ERROR
      #undef MEMMAP_START_DONE

/* !Comment: SEC_CALIB_END Stop Section treatment */
   #elif defined   STOP_SEC_CALIB_END_SECTION && defined  START_SEC_CALIB_END_SECTION
	  

      #pragma section

      #undef START_SEC_CALIB_END_SECTION
      #undef STOP_SEC_CALIB_END_SECTION
      #undef MEMMAP_ERROR
      #undef MEMMAP_START_DONE


   #endif
#endif

#if defined MEMMAP_ERROR
   #error MEMMAP-E201 : Bad memory allocation into CALIB_MemMap.h
#endif


/*------------------------------- end of file --------------------------------*/

