

#ifndef RBA_DEMOBDBASIC_H
#define RBA_DEMOBDBASIC_H

#include "rba_DemObdBasic_Types.h"
/* BSW-8793 */
#include "rba_DemObdBasic_Dtr.h"
/* END BSW-8793 */
/* BSW-13093 */
#include "rba_DemObdBasic_DistanceTimePid.h"
/* END BSW-13093 */

#if (DEM_CFG_CHECKAPICONSISTENCY != FALSE)
#if DEM_CFG_OBD_IUMPR
/**
 * \defgroup DEM_OBD    OBD
 * Functions for OBD-relevant ECUs
 * @{
 */
/** @AR @RTE
 *
 * Dem314: Service is used to lock a denominator of a specific monitor.
 *
 * @param[in]    RatioID Ratio Identifier reporting that specific denominator is locked (for physical reasons - e.g. temperature conditions or minimum activity)
 * @return       E_OK = report of IUMPR denominator status was successfully reported.\n
 *               E_NOT_OK = Report of IUMPR denominator status was not successfully reported.\n
 */
/*MR12 RULE 8.5 VIOLATION: the function declaration is also generated by the RTE if it is configured, this does not cause any issues*/
Std_ReturnType Dem_RepIUMPRDenLock(Dem_RatioIdType RatioID);

/** @AR @RTE
 *
 * Dem315: Service is used to release a denominator of a specific monitor.
 *
 * @param[in]    RatioID Ratio Identifier reporting that specific denominator is released (for physical reasons - e.g. temperature conditions or minimum activity)
 * @return       E_OK = report of IUMPR denominator status was successfully reported.\n
 *               E_NOT_OK = Report of IUMPR denominator status was not successfully reported.\n
 */
/*MR12 RULE 8.5 VIOLATION: the function declaration is also generated by the RTE if it is configured, this does not cause any issues*/
Std_ReturnType Dem_RepIUMPRDenRelease(Dem_RatioIdType RatioID);


/** @AR @RTE
 *
 * Dem313: Service for reporting that faults are possibly found because all conditions are fullfilled.
 *
 * @param[in]    RatioID Ratio Identifier reporting that a respective monitor could have found a fault - only used when interface option "API" is selected.
 * @return       E_OK = Report of IUMPR result was successfully reported\n
 *               E_NOT_OK = Report of IUMPR result was not successfully reported\n
 */
/*MR12 RULE 8.5 VIOLATION: the function declaration is also generated by the RTE if it is configured, this does not cause any issues*/
Std_ReturnType Dem_RepIUMPRFaultDetect(Dem_RatioIdType RatioID);

/**
 * @ingroup DEM_H
 *
 * In order to communicate the status of the (additional) denominator conditions among the OBD relevant ECUs,
 * the API is used to forward the condition status to a Dem of a particular ECU.\n
 * API is needed in OBD-relevant ECUs only\n
 * \n
 * @param[in] ConditionId Identification of a IUMPR denominator condition ID (General Denominator, Cold start, EVAP, 500mi).
 *            ConditionStatus Status of the IUMPR denominator condition (Not-reached, reached, not reachable / inhibited)
 * @return E_OK: set of IUMPR denominator condition was successful\n
 *         E_NOT_OK: set of IUMPR denominator condition failed or could not be accepted.
 */
/*MR12 RULE 8.5 VIOLATION: the function declaration is also generated by the RTE if it is configured, this does not cause any issues*/
Std_ReturnType Dem_SetIUMPRDenCondition (Dem_IumprDenomCondIdType ConditionId, Dem_IumprDenomCondStatusType ConditionStatus);
#endif


/** @AR @RTE
 *
 * Dem312: Reports the event as disabled for the PID $41 computation.
 *
 * @note For the computation of PID $41, the monitor has to report its event as disabled, if the test cannot be carried out
 *       anymore until the end of this driving cycle.
 * @param[in]    EventId            Identification of an event by assigned EventId.
 * @return       E_OK = Setting of event to disabled was successful.\n
 *               E_NOT_OK = Setting of event to disabled failed.\n
 */
/*MR12 RULE 8.5 VIOLATION: the function declaration is also generated by the RTE if it is configured, this does not cause any issues*/
Std_ReturnType Dem_SetEventDisabled(Dem_EventIdType EventId);

/**@}*//* End of Doxygen subgroup DEM_OBD */
#endif /* DEM_CFG_CHECKAPICONSISTENCY */

#if DEM_CFG_OBD_IUMPR
/**
 * @ingroup DEM_H
 *
 * This service is used to read the numerator and denominator values of individual ratios, along with the Dem event that
 * is assigned to the ratio within the configuration.
 *
 * @param  [in]  RatioID     - Ratio Identifier about which the details are needed.
 * @param  [out] Numerator   - Pointer to the buffer where the numerator value will be written.
 * @param  [out] Denominator - Pointer to the buffer where the denominator value will be written.
 * @param  [out] EventID     - Pointer to the buffer where the mapped eventID will be written.
 * @param  [out] Group       - Pointer to the buffer where the mapped IUMPR group name will be written.
 *
 * @return       E_OK     - All information about the requested ratio is available in the output buffers. \n
 *               E_NOT_OK - Either the queried ratio does not exist or it is mapped to an event that is suppressed.
 */
Std_ReturnType Dem_GetIUMPRRatioData(Dem_RatioIdType RatioID, uint16* Numerator, uint16* Denominator, Dem_EventIdType* EventID, uint8* Group);

/* BSW-12813 */
/**
 * This service is used to retrieve all the ratios belonging to a group. This will only return ratio IDs for ratios that have events
 * which are not suppressed.
 *
 * @param  [in]  IumprGroupId        - Group Identifier which is queried for all ratios belonging to it.
 * @param  [out] RatioIDBuffer       - Pointer to the buffer where the ratio IDs will be written.
 * @param  [inout] RatioIDBufferSize - Pointer to variable containing the output buffer size, when this function should
 *                                     call, *RatioIDBufferSize shall contain the size of the allocated buffer referenced
 *                                     by RatioIDBuffer. When this function returns will contain the actual
 *                                     output size.
 * @return       E_OK     - Ratio IDs belonging to the requested group are written to the output buffer. \n
 *               E_NOT_OK - The requested group doesn't exist, NULL pointers are passed, passed buffer is too small, or
 *                          no events belonging to the requested group could be found .
 */
/* [$DD_BSWCODE 30040] */
Std_ReturnType Dem_Rb_GetIUMPRGroupRatios(uint8 IumprGroupId, Dem_RatioIdType* RatioIDBuffer, uint16* RatioIDBufferSize);
/* END BSW-12813 */

#endif
/**
 * @ingroup DEM_H
 *
 * This service is used to signal the end of the OBD ignition cycle. The visibility of the permanent DTCs is set accordingly in the main context after the service is called.
 * It can be used as alternative to the ignition cycle restart.
 *
 */
void Dem_SignalEndOfOBDIgnitionCycle(void);

/**
 * @ingroup DEM_H
 *
 * This API is used to get status of NvmRead of OBD relevant blocks.
 *
 * @return  TRUE - OBD relevant Blocks from Nvm could not be read successfully on Dem_Init().
 *          FALSE - All OBD relevant Blocks are read correctly from Nvm
 */
boolean Dem_IsOBDRelevantNvmBlockNotReadCorrectly(void);

#endif
