/** @file     Core0_OsTask_ASW_1ms.c
  *
  * @brief    Task Core0_OsTask_ASW_1ms body
  *
  * @note     AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
  *
  * @note     Generated by ETAS RTA-RTE
  * @note     Version 7.5.3
  *
  * @date     Sat May 18 17:18:22 2024
  */

#define RTE_CORE

#include "Rte_Const.h"
#if !defined(RTE_VENDOR_MODE)
#pragma message "Compiling an individual task file but RTE_VENDOR_MODE not defined. Compiling a stale file?"
#endif /* !defined(RTE_VENDOR_MODE) */
#if defined(RTE_USE_TASK_HEADER)
#include "Core0_OsTask_ASW_1ms.h"
#else /* !defined(RTE_USE_TASK_HEADER) */
#include "Os.h"
#endif /* !defined(RTE_USE_TASK_HEADER) */
#if defined(RTE_REQUIRES_IOC)
#include "Ioc.h"
#endif /* defined(RTE_REQUIRES_IOC) */
#include "Rte.h"
#include "Rte_Intl.h"
#include "Rte_Type.h"
#include "Rte_DataHandleType.h"

#define RTE_CORE0_OSTASK_ASW_1MS_START_SEC_VAR_CLEARED_8
#include "Rte_MemMap.h"
extern VAR(uint8, RTE_DATA) Rte_RECount_Core0_OsTask_ASW_1ms_divby2_0;

extern VAR(uint8, RTE_DATA) Rte_RECount_Core0_OsTask_ASW_1ms_divby5_0;

#define RTE_CORE0_OSTASK_ASW_1MS_STOP_SEC_VAR_CLEARED_8
#include "Rte_MemMap.h"

/* Runnable entity prototypes */
#define ASW_CORE0_START_SEC_CODE
#include "ASW_CORE0_MemMap.h"
FUNC(void, ASW_CORE0_CODE) CCP_DaqListSetEvent0_func(void);
FUNC(void, ASW_CORE0_CODE) CCP_DaqListSetEvent1_func(void);
FUNC(void, ASW_CORE0_CODE) MAIN_CORE0_1ms_func(void);
FUNC(void, ASW_CORE0_CODE) MAIN_CORE0_2ms_func(void);
FUNC(void, ASW_CORE0_CODE) MAIN_CORE0_5ms_func(void);
#define ASW_CORE0_STOP_SEC_CODE
#include "ASW_CORE0_MemMap.h"

#define RTE_CORE0_OSTASK_ASW_1MS_START_SEC_CODE
#include "Rte_MemMap.h"
TASK(Core0_OsTask_ASW_1ms)
{
   /* Box: Implicit Buffer Initialization begin */
   /* Box: Implicit Buffer Initialization end */
   /* Box: Implicit Buffer Fill begin */
   /* Box: Implicit Buffer Fill end */
   {
      /* Box: CPT_ASW_CORE0 begin */
      CCP_DaqListSetEvent0_func();
      /* Box: CPT_ASW_CORE0 end */
   }
   /* Box: CPT_ASW_CORE0 begin */
   if ( Rte_RECount_Core0_OsTask_ASW_1ms_divby5_0 == ((VAR(uint8, AUTOMATIC))0U) )
   {
      CCP_DaqListSetEvent1_func();
   }
   /* Box: CPT_ASW_CORE0 end */
   {
      /* Box: CPT_ASW_CORE0 begin */
      MAIN_CORE0_1ms_func();
      /* Box: CPT_ASW_CORE0 end */
   }
   /* Box: CPT_ASW_CORE0 begin */
   if ( Rte_RECount_Core0_OsTask_ASW_1ms_divby2_0 == ((VAR(uint8, AUTOMATIC))0U) )
   {
      MAIN_CORE0_2ms_func();
   }
   /* Box: CPT_ASW_CORE0 end */
   /* Box: CPT_ASW_CORE0 begin */
   if ( Rte_RECount_Core0_OsTask_ASW_1ms_divby5_0 == ((VAR(uint8, AUTOMATIC))0U) )
   {
      MAIN_CORE0_5ms_func();
   }
   /* Box: CPT_ASW_CORE0 end */
   /* Box: Implicit Buffer Flush begin */
   /* Box: Implicit Buffer Flush end */
   if ( Rte_RECount_Core0_OsTask_ASW_1ms_divby2_0 != ((VAR(uint8, AUTOMATIC))0U) )
   {
      Rte_RECount_Core0_OsTask_ASW_1ms_divby2_0--;
   }
   else
   {
      Rte_RECount_Core0_OsTask_ASW_1ms_divby2_0 = ((VAR(uint8, AUTOMATIC))1);
   }
   if ( Rte_RECount_Core0_OsTask_ASW_1ms_divby5_0 != ((VAR(uint8, AUTOMATIC))0U) )
   {
      Rte_RECount_Core0_OsTask_ASW_1ms_divby5_0--;
   }
   else
   {
      Rte_RECount_Core0_OsTask_ASW_1ms_divby5_0 = ((VAR(uint8, AUTOMATIC))4);
   }
   TerminateTask();
} /* Core0_OsTask_ASW_1ms */
#define RTE_CORE0_OSTASK_ASW_1MS_STOP_SEC_CODE
#include "Rte_MemMap.h"

