/** @file     Core0_BSW_OsTask_SwcRequest.c
  *
  * @brief    Task Core0_BSW_OsTask_SwcRequest body
  *
  * @note     AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
  *
  * @note     Generated by ETAS RTA-RTE
  * @note     Version 7.5.3
  *
  * @date     Tue Apr  8 17:08:23 2025
  */

#define RTE_CORE

#include "Rte_Const.h"
#if !defined(RTE_VENDOR_MODE)
#pragma message "Compiling an individual task file but RTE_VENDOR_MODE not defined. Compiling a stale file?"
#endif /* !defined(RTE_VENDOR_MODE) */
#if defined(RTE_USE_TASK_HEADER)
#include "Core0_BSW_OsTask_SwcRequest.h"
#else /* !defined(RTE_USE_TASK_HEADER) */
#include "Os.h"
#endif /* !defined(RTE_USE_TASK_HEADER) */
#if defined(RTE_REQUIRES_IOC)
#include "Ioc.h"
#endif /* defined(RTE_REQUIRES_IOC) */
#include "Rte.h"
#include "Rte_Intl.h"
#include "Rte_Type.h"
#include "Rte_DataHandleType.h"

#define RTE_AF_CPT_BSWM_DRE_BSWM_CFG_DFRDSWCREQST_BSWMSWCMODEREQUEST_START_SEC_VAR_CLEARED_8
#include "Rte_MemMap.h"
extern VAR(Rte_REActCounterType, RTE_DATA) Rte_ActCount_CPT_BswM_DRE_BswM_Cfg_DfrdSwcReqst_BswMSwcModeRequest;

#define RTE_AF_CPT_BSWM_DRE_BSWM_CFG_DFRDSWCREQST_BSWMSWCMODEREQUEST_STOP_SEC_VAR_CLEARED_8
#include "Rte_MemMap.h"

#define RTE_AF_CPT_BSWM_DRE_BSWM_CFG_DFRDSWCREQST_BSWM_MRP_SWC_NETWORK_START_SEC_VAR_CLEARED_8
#include "Rte_MemMap.h"
extern VAR(Rte_REActCounterType, RTE_DATA) Rte_ActCount_CPT_BswM_DRE_BswM_Cfg_DfrdSwcReqst_BswM_MRP_SWC_Network;

#define RTE_AF_CPT_BSWM_DRE_BSWM_CFG_DFRDSWCREQST_BSWM_MRP_SWC_NETWORK_STOP_SEC_VAR_CLEARED_8
#include "Rte_MemMap.h"

/* Runnable entity prototypes */
#define BswM_START_SEC_CODE
#include "BswM_MemMap.h"
FUNC(void, BswM_CODE) BswM_Cfg_DfrdSwcReqst_BswMSwcModeRequest(void);
FUNC(void, BswM_CODE) BswM_Cfg_DfrdSwcReqst_BswM_MRP_SWC_Network(void);
#define BswM_STOP_SEC_CODE
#include "BswM_MemMap.h"

#define RTE_CORE0_BSW_OSTASK_SWCREQUEST_START_SEC_CODE
#include "Rte_MemMap.h"
TASK(Core0_BSW_OsTask_SwcRequest)
{
   /* Box: Implicit Buffer Initialization begin */
   /* Box: Implicit Buffer Initialization end */
   /* Box: Implicit Buffer Fill begin */
   /* Box: Implicit Buffer Fill end */
   /* Box: CPT_BswM begin */
   if ( Rte_ActCount_CPT_BswM_DRE_BswM_Cfg_DfrdSwcReqst_BswM_MRP_SWC_Network != FALSE )
   {
      Rte_ActCount_CPT_BswM_DRE_BswM_Cfg_DfrdSwcReqst_BswM_MRP_SWC_Network = FALSE;
      BswM_Cfg_DfrdSwcReqst_BswM_MRP_SWC_Network();
   }
   /* Box: CPT_BswM end */
   /* Box: CPT_BswM begin */
   if ( Rte_ActCount_CPT_BswM_DRE_BswM_Cfg_DfrdSwcReqst_BswMSwcModeRequest != FALSE )
   {
      Rte_ActCount_CPT_BswM_DRE_BswM_Cfg_DfrdSwcReqst_BswMSwcModeRequest = FALSE;
      BswM_Cfg_DfrdSwcReqst_BswMSwcModeRequest();
   }
   /* Box: CPT_BswM end */
   /* Box: Implicit Buffer Flush begin */
   /* Box: Implicit Buffer Flush end */
   TerminateTask();
} /* Core0_BSW_OsTask_SwcRequest */
#define RTE_CORE0_BSW_OSTASK_SWCREQUEST_STOP_SEC_CODE
#include "Rte_MemMap.h"

