/** @file     Core1_OsTask_ASW_1ms.c
  *
  * @brief    Task Core1_OsTask_ASW_1ms body
  *
  * @note     AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
  *
  * @note     Generated by ETAS RTA-RTE
  * @note     Version 7.5.3
  *
  * @date     Fri Apr 18 09:20:23 2025
  */

#define RTE_CORE

#include "Rte_Const.h"
#if !defined(RTE_VENDOR_MODE)
#pragma message "Compiling an individual task file but RTE_VENDOR_MODE not defined. Compiling a stale file?"
#endif /* !defined(RTE_VENDOR_MODE) */
#if defined(RTE_USE_TASK_HEADER)
#include "Core1_OsTask_ASW_1ms.h"
#else /* !defined(RTE_USE_TASK_HEADER) */
#include "Os.h"
#endif /* !defined(RTE_USE_TASK_HEADER) */
#if defined(RTE_REQUIRES_IOC)
#include "Ioc.h"
#endif /* defined(RTE_REQUIRES_IOC) */
#include "Rte.h"
#include "Rte_Intl.h"
#include "Rte_Type.h"
#include "Rte_DataHandleType.h"

/* Runnable entity prototypes */
#define ASW_COM_START_SEC_CODE
#include "ASW_COM_MemMap.h"
FUNC(void, ASW_COM_CODE) MainMsg_Can01_SpecialPeriod_Func(void);
FUNC(void, ASW_COM_CODE) MainMsg_Can02_SpecialPeriod_Func(void);
FUNC(void, ASW_COM_CODE) MainMsg_Can03_SpecialPeriod_Func(void);
#define ASW_COM_STOP_SEC_CODE
#include "ASW_COM_MemMap.h"
#define ASW_CORE1_START_SEC_CODE
#include "ASW_CORE1_MemMap.h"
FUNC(void, ASW_CORE1_CODE) GMAIN_CORE1_1ms_func(void);
FUNC(void, ASW_CORE1_CODE) MAIN_CORE1_1ms_func(void);
#define ASW_CORE1_STOP_SEC_CODE
#include "ASW_CORE1_MemMap.h"

#define RTE_CORE1_OSTASK_ASW_1MS_START_SEC_CODE
#include "Rte_MemMap.h"
TASK(Core1_OsTask_ASW_1ms)
{
   /* Box: Implicit Buffer Initialization begin */
   /* Box: Implicit Buffer Initialization end */
   /* Box: Implicit Buffer Fill begin */
   /* Box: Implicit Buffer Fill end */
   {
      /* Box: CPT_ASW_CORE1 begin */
      MAIN_CORE1_1ms_func();
      /* Box: CPT_ASW_CORE1 end */
   }
   {
      /* Box: CPT_ASW_CORE1 begin */
      GMAIN_CORE1_1ms_func();
      /* Box: CPT_ASW_CORE1 end */
   }
   {
      /* Box: CPT_ASW_COM begin */
      MainMsg_Can01_SpecialPeriod_Func();
      /* Box: CPT_ASW_COM end */
   }
   {
      /* Box: CPT_ASW_COM begin */
      MainMsg_Can02_SpecialPeriod_Func();
      /* Box: CPT_ASW_COM end */
   }
   {
      /* Box: CPT_ASW_COM begin */
      MainMsg_Can03_SpecialPeriod_Func();
      /* Box: CPT_ASW_COM end */
   }
   /* Box: Implicit Buffer Flush begin */
   /* Box: Implicit Buffer Flush end */
   TerminateTask();
} /* Core1_OsTask_ASW_1ms */
#define RTE_CORE1_OSTASK_ASW_1MS_STOP_SEC_CODE
#include "Rte_MemMap.h"

