/** @file     Core2_OsTask_ASW_10ms.c
  *
  * @brief    Task Core2_OsTask_ASW_10ms body
  *
  * @note     AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
  *
  * @note     Generated by ETAS RTA-RTE
  * @note     Version 7.5.3
  *
  * @date     Wed May 22 14:06:13 2024
  */

#define RTE_CORE

#include "Rte_Const.h"
#if !defined(RTE_VENDOR_MODE)
#pragma message "Compiling an individual task file but RTE_VENDOR_MODE not defined. Compiling a stale file?"
#endif /* !defined(RTE_VENDOR_MODE) */
#if defined(RTE_USE_TASK_HEADER)
#include "Core2_OsTask_ASW_10ms.h"
#else /* !defined(RTE_USE_TASK_HEADER) */
#include "Os.h"
#endif /* !defined(RTE_USE_TASK_HEADER) */
#if defined(RTE_REQUIRES_IOC)
#include "Ioc.h"
#endif /* defined(RTE_REQUIRES_IOC) */
#include "Rte.h"
#include "Rte_Intl.h"
#include "Rte_Type.h"
#include "Rte_DataHandleType.h"

/* Runnable entity prototypes */
#define ASW_CORE2_START_SEC_CODE
#include "ASW_CORE2_MemMap.h"
FUNC(void, ASW_CORE2_CODE) GMAIN_CORE2_10ms_func(void);
#define ASW_CORE2_STOP_SEC_CODE
#include "ASW_CORE2_MemMap.h"

extern void ASW_WDG_vidAliveSE_CPU2(void);

#define RTE_CORE2_OSTASK_ASW_10MS_START_SEC_CODE
#include "Rte_MemMap.h"
TASK(Core2_OsTask_ASW_10ms)
{
   /* Box: Implicit Buffer Initialization begin */
   /* Box: Implicit Buffer Initialization end */
   /* Box: Implicit Buffer Fill begin */
   ASW_WDG_vidAliveSE_CPU2();

   /* Box: Implicit Buffer Fill end */
   {
      /* Box: CPT_ASW_CORE2 begin */
      GMAIN_CORE2_10ms_func();
      /* Box: CPT_ASW_CORE2 end */
   }
   /* Box: Implicit Buffer Flush begin */
   /* Box: Implicit Buffer Flush end */
   TerminateTask();
} /* Core2_OsTask_ASW_10ms */
#define RTE_CORE2_OSTASK_ASW_10MS_STOP_SEC_CODE
#include "Rte_MemMap.h"

