/** @file     Rte_ASW_COM.h
  *
  * @brief    Application header file
  *
  * @note     AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
  *
  * @note     Generated by ETAS RTA-RTE
  * @note     Version 7.5.3
  *
  * @date     Fri Apr 18 09:20:23 2025
  */

#ifndef RTE_ASW_COM_H
#define RTE_ASW_COM_H

#ifndef RTE_CORE
#ifdef RTE_APPLICATION_HEADER_FILE
#error Multiple application header files included.
#endif /* RTE_APPLICATION_HEADER_FILE */
#define RTE_APPLICATION_HEADER_FILE
#endif /* RTE_CORE */

/*******************************************************
 ***
 *** Includes
 ***
 *******************************************************/

#include "Rte.h"
#include "Rte_Intl.h"
#include "Rte_ASW_COM_Type.h"

#include "Rte_DataHandleType.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#if defined(RTE_RUNNABLEAPI_ASW_COM_Init)
   /* Do nothing for this and all elif clauses below (rte_sws_2751) */
#elif defined(RTE_RUNNABLEAPI_MainMsg_Can01_Above100ms)
#elif defined(RTE_RUNNABLEAPI_MainMsg_Can01_Below100ms)
#elif defined(RTE_RUNNABLEAPI_MainMsg_Can01_SpecialPeriod)
#elif defined(RTE_RUNNABLEAPI_MainMsg_Can02_Above100ms)
#elif defined(RTE_RUNNABLEAPI_MainMsg_Can02_Below100ms)
#elif defined(RTE_RUNNABLEAPI_MainMsg_Can02_SpecialPeriod)
#elif defined(RTE_RUNNABLEAPI_MainMsg_Can03_Above100ms)
#elif defined(RTE_RUNNABLEAPI_MainMsg_Can03_Below100ms)
#elif defined(RTE_RUNNABLEAPI_MainMsg_Can03_SpecialPeriod)
#else
   /* None of above defined so define value including all APIs (rte_sws_2751) */
   #define RTE_PRV_ALL_API
#endif

/*******************************************************
 ***
 *** Constants
 ***
 *******************************************************/


/*******************************************************
 ***
 *** Public Types
 ***
 *******************************************************/

/* BEGIN: SWC types (core visible) */
struct Rte_CDS_ASW_COM {
   uint8 Rte_Dummy;
};
typedef struct Rte_CDS_ASW_COM Rte_CDS_ASW_COM;
/* END: SWC types (core visible) */

/*******************************************************
 ***
 *** Private Types
 ***
 *******************************************************/

/* BEGIN: SWC types (private) */
/* END: SWC types (private) */

/*******************************************************
 ***
 *** Instance Declarations
 ***
 *******************************************************/

#define RTE_START_SEC_EcucPartition_Core1_CONST_UNSPECIFIED
#include "Rte_MemMap.h"
extern CONST(struct Rte_CDS_ASW_COM, RTE_CONST) Rte_Inst_ASW_COM;
#define RTE_STOP_SEC_EcucPartition_Core1_CONST_UNSPECIFIED
#include "Rte_MemMap.h"


#ifndef RTE_CORE
typedef CONSTP2CONST(struct Rte_CDS_ASW_COM, AUTOMATIC, RTE_CONST) Rte_Instance;
#endif /* RTE_CORE */

/*******************************************************
 ***
 *** API Mapping macros
 ***
 *******************************************************/

/* API Mapping Macros */
#ifndef RTE_CORE

#endif /* RTE_CORE */

/*******************************************************
 ***
 *** RE Prototypes
 ***
 *******************************************************/

#define ASW_COM_START_SEC_CODE
#include "ASW_COM_MemMap.h"
FUNC(void, ASW_COM_CODE) MainMsg_Can01_Above100ms_Func(void);
FUNC(void, ASW_COM_CODE) MainMsg_Can01_Below100ms_Func(void);
FUNC(void, ASW_COM_CODE) MainMsg_Can01_SpecialPeriod_Func(void);
FUNC(void, ASW_COM_CODE) MainMsg_Can02_Above100ms_Func(void);
FUNC(void, ASW_COM_CODE) MainMsg_Can02_Below100ms_Func(void);
FUNC(void, ASW_COM_CODE) MainMsg_Can02_SpecialPeriod_Func(void);
FUNC(void, ASW_COM_CODE) MainMsg_Can03_Above100ms_Func(void);
FUNC(void, ASW_COM_CODE) MainMsg_Can03_Below100ms_Func(void);
FUNC(void, ASW_COM_CODE) MainMsg_Can03_SpecialPeriod_Func(void);
#define ASW_COM_STOP_SEC_CODE
#include "ASW_COM_MemMap.h"

/* Initial values for data element prototypes */

#ifdef __cplusplus
} /* extern C */
#endif /* __cplusplus */

#endif /* !RTE_ASW_COM_H */
