/** @file     Rte_RSID.h
  *
  * @brief    Application header file
  *
  * @note     AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
  *
  * @note     Generated by ETAS RTA-RTE
  * @note     Version 7.5.3
  *
  * @date     Tue Mar  5 14:09:38 2024
  */

#ifndef RTE_RSID_H
#define RTE_RSID_H

#ifndef RTE_CORE
#ifdef RTE_APPLICATION_HEADER_FILE
#error Multiple application header files included.
#endif /* RTE_APPLICATION_HEADER_FILE */
#define RTE_APPLICATION_HEADER_FILE
#endif /* RTE_CORE */

/*******************************************************
 ***
 *** Includes
 ***
 *******************************************************/

#include "Rte.h"
#include "Rte_Intl.h"
#include "Rte_RSID_Type.h"

#include "Rte_DataHandleType.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#if defined(RTE_RUNNABLEAPI_Diag_RoutineServices_0203_RequestRoutineResults)
   /* Do nothing for this and all elif clauses below (rte_sws_2751) */
#elif defined(RTE_RUNNABLEAPI_Diag_RoutineServices_0203_Start)
#elif defined(RTE_RUNNABLEAPI_Runnable_RSID_100ms)
#else
   /* None of above defined so define value including all APIs (rte_sws_2751) */
   #define RTE_PRV_ALL_API
#endif

/*******************************************************
 ***
 *** Constants
 ***
 *******************************************************/

#ifndef RTE_CORE
#define RTE_E_RoutineServices_DcmDspRoutine_0203_DCM_E_FORCE_RCRRP ((Std_ReturnType)12)
#define RTE_E_RoutineServices_DcmDspRoutine_0203_DCM_E_PENDING ((Std_ReturnType)10)
#define RTE_E_RoutineServices_DcmDspRoutine_0203_E_NOT_OK ((Std_ReturnType)1)
#define RTE_E_RoutineServices_DcmDspRoutine_0203_E_OK ((Std_ReturnType)0)
#endif /* RTE_CORE */

/*******************************************************
 ***
 *** Public Types
 ***
 *******************************************************/

/* BEGIN: SWC types (core visible) */
struct Rte_CDS_RSID {
   uint8 Rte_Dummy;
};
typedef struct Rte_CDS_RSID Rte_CDS_RSID;
/* END: SWC types (core visible) */

/*******************************************************
 ***
 *** Private Types
 ***
 *******************************************************/

/* BEGIN: SWC types (private) */
/* END: SWC types (private) */

/*******************************************************
 ***
 *** Instance Declarations
 ***
 *******************************************************/

#define RTE_START_SEC_EcucPartition_Core0_CONST_UNSPECIFIED
#include "Rte_MemMap.h"
extern CONST(struct Rte_CDS_RSID, RTE_CONST) Rte_Inst_RSID;
#define RTE_STOP_SEC_EcucPartition_Core0_CONST_UNSPECIFIED
#include "Rte_MemMap.h"


#ifndef RTE_CORE
typedef CONSTP2CONST(struct Rte_CDS_RSID, AUTOMATIC, RTE_CONST) Rte_Instance;
#endif /* RTE_CORE */

/*******************************************************
 ***
 *** API Mapping macros
 ***
 *******************************************************/

/* API Mapping Macros */
#ifndef RTE_CORE

#endif /* RTE_CORE */

/*******************************************************
 ***
 *** RE Prototypes
 ***
 *******************************************************/

#define RSID_START_SEC_CODE
#include "RSID_MemMap.h"
FUNC(Std_ReturnType, RSID_CODE) Runnable_0203_RequestRoutineResults(VAR(Dcm_OpStatusType, AUTOMATIC) OpStatus,
                                                                    P2VAR(Dcm_RequestDataOut_DcmDspRoutine_0203_DcmDspRequestRoutineResultsOutSignal_0Type, AUTOMATIC, RTE_APPL_DATA) DataOut_DcmDspRequestRoutineResultsOutSignal_0,
                                                                    P2VAR(Dcm_NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode);
FUNC(Std_ReturnType, RSID_CODE) Runnable_0203_Start(VAR(Dcm_OpStatusType, AUTOMATIC) OpStatus,
                                                    P2VAR(Dcm_StartDataOut_DcmDspRoutine_0203_DcmDspStartRoutineOutSignalType, AUTOMATIC, RTE_APPL_DATA) DataOut_DcmDspStartRoutineOutSignal,
                                                    P2VAR(Dcm_NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode);
FUNC(void, RSID_CODE) Runnable_RSID_100ms(void);
#define RSID_STOP_SEC_CODE
#include "RSID_MemMap.h"

/* Initial values for data element prototypes */

#ifdef __cplusplus
} /* extern C */
#endif /* __cplusplus */

#endif /* !RTE_RSID_H */
