/** @file     Rte_Type.h
  *
  * @brief    RTE type definitions
  *
  * @note     AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
  *
  * @note     Generated by ETAS RTA-RTE
  * @note     Version 7.5.3
  *
  * @date     Fri Jan  9 15:35:43 2026
  */

#ifndef RTE_TYPE_H
#define RTE_TYPE_H

#include "Rte.h"
#include "Rte_Cfg.h"

/*******************************************************
 ***
 *** Forward Declarations
 ***
 *******************************************************/

struct Rte_CDS_ASW_BASE;
struct Rte_CDS_ASW_COM;
struct Rte_CDS_ASW_CORE0;
struct Rte_CDS_ASW_CORE1;
struct Rte_CDS_ASW_CORE2;
struct Rte_CDS_ASW_CORE3;
struct Rte_CDS_ASW_DCM;
struct Rte_CDS_ASW_DEM;
struct Rte_CDS_ASW_NM;
struct Rte_CDS_ASW_NVM;
struct Rte_CDS_ASW_WDG;
struct Rte_CDS_ASW_XCP;
struct Rte_CDS_BswM;
struct Rte_CDS_CDD_CORE0;
struct Rte_CDS_CDD_CORE1;
struct Rte_CDS_CDD_CORE2;
struct Rte_CDS_CDD_CORE3;
struct Rte_CDS_ComM;
struct Rte_CDS_Dcm;
struct Rte_CDS_Dem;
struct Rte_CDS_Det;
struct Rte_CDS_EcuM;
struct Rte_CDS_NvM;
struct Rte_CDS_RSID;
struct Rte_CDS_SWC_DEM;
struct Rte_CDS_WdgM;
struct Rte_CDS_rba_DiagLib;

/*******************************************************
 ***
 *** Types
 ***
 *******************************************************/

/* Information: No typedef for ImplementationDataType uint8 because typeEmitter is a value other than RTE */

typedef uint8 Impl_NVM_DstPtrType_1024[1024];
/* Information: No typedef for ImplementationDataType Std_VersionInfoType because typeEmitter is a value other than RTE */

/* Information: No typedef for ImplementationDataType BswM_ConfigType because typeEmitter is a value other than RTE */

typedef uint16 BswM_ModeType;

typedef uint16 BswM_UserType;

/* Information: No typedef for ImplementationDataType Can_HwHandleType because typeEmitter is a value other than RTE */

/* Information: No typedef for ImplementationDataType Can_IdType because typeEmitter is a value other than RTE */

/* Information: No typedef for ImplementationDataType Can_HwType because typeEmitter is a value other than RTE */

/* Information: No typedef for ImplementationDataType uint32 because typeEmitter is a value other than RTE */

typedef uint32 CanIf_u32_impl;

typedef uint16 CanIf_u16_impl;

typedef uint8 CanIf_u8_impl;

typedef struct {
   CanIf_u32_impl CanId;
   CanIf_u16_impl swPduHandle;
   CanIf_u8_impl  SduLength;
   CanIf_u8_impl  BufferIndex;
} CanIf_CanIdBuffer_struct_impl;

/* Information: No typedef for ImplementationDataType PduIdType because typeEmitter is a value other than RTE */

/* Information: No typedef for ImplementationDataType CanIf_ConfigType because typeEmitter is a value other than RTE */

/* Information: No typedef for ImplementationDataType CanIf_ControllerModeType because typeEmitter is a value other than RTE */

typedef uint8 CanIf_ControllerModeType_Enum_impl;

typedef struct {
   CanIf_u8_impl Ctrl_Pdu_mode;
} CanIf_ControllerStateType_struct_impl;

typedef CanIf_ControllerStateType_struct_impl CanIf_ControllerState_Astruct_impl[4];
/* Information: No typedef for ImplementationDataType CanIf_NotifStatusType because typeEmitter is a value other than RTE */

typedef uint8 CanIf_NotifStatusType_Enum_impl;

typedef CanIf_NotifStatusType_Enum_impl CanIf_NotifStatusType_Aenum_impl[152];
/* Information: No typedef for ImplementationDataType CanIf_PduGetModeType because typeEmitter is a value other than RTE */

/* Information: No typedef for ImplementationDataType CanIf_PduModeType because typeEmitter is a value other than RTE */

typedef uint8 CanIf_PduModeType_Enum_impl;

/* Information: No typedef for ImplementationDataType CanIf_PduSetModeType because typeEmitter is a value other than RTE */

typedef uint8 CanIf_Prv_BuffStatus_ten_Enum_impl;

typedef struct {
   CanIf_u8_impl last_index;
   CanIf_u8_impl bufferstatus;
} CanIf_Prv_TxBufferStatus_tst_struct_impl;

typedef CanIf_u8_impl CanIf_SDUBuffer_CanIf_Buffer_CanNodeNum_01_Tx_25_Au8_impl[80];
typedef CanIf_u8_impl CanIf_SDUBuffer_CanIf_Buffer_CanNodeNum_01_Tx_Basic_Au8_impl[240];
typedef CanIf_u8_impl CanIf_SDUBuffer_CanIf_Buffer_CanNodeNum_02_Tx_Basic_Au8_impl[80];
typedef CanIf_u8_impl CanIf_SDUBuffer_CanIf_Buffer_CanNodeNum_03_Tx_Basic_Au8_impl[80];
typedef CanIf_Prv_TxBufferStatus_tst_struct_impl CanIf_TxBufferRam_Astruct_impl[91];
typedef CanIf_CanIdBuffer_struct_impl CanIf_Tx_CanId_CanIf_Buffer_CanNodeNum_01_Tx_25_Astruct_impl[10];
typedef CanIf_CanIdBuffer_struct_impl CanIf_Tx_CanId_CanIf_Buffer_CanNodeNum_01_Tx_Basic_Astruct_impl[30];
typedef CanIf_CanIdBuffer_struct_impl CanIf_Tx_CanId_CanIf_Buffer_CanNodeNum_02_Tx_Basic_Astruct_impl[10];
typedef CanIf_CanIdBuffer_struct_impl CanIf_Tx_CanId_CanIf_Buffer_CanNodeNum_03_Tx_Basic_Astruct_impl[10];
typedef uint8 CanIf_boolean_impl;

/* Information: No typedef for ImplementationDataType CanNm_ConfigType because typeEmitter is a value other than RTE */

typedef uint8 CanSM_boolean_Impl;

typedef CanSM_boolean_Impl CanSM_Aboolean_impl[4];
typedef uint8 CanSM_u8_Impl;

typedef CanSM_u8_Impl CanSM_Au8_impl[4];
/* Information: No typedef for ImplementationDataType CanSM_BswMCurrentStateType because typeEmitter is a value other than RTE */

typedef uint8 CanSM_BusOffRecoveryStateType_Enum_impl;

/* Information: No typedef for ImplementationDataType CanSM_ConfigType because typeEmitter is a value other than RTE */

typedef uint8 CanSM_NetworkModeStateType_Enum_impl;

/* Information: No typedef for ImplementationDataType CanSM_StateType because typeEmitter is a value other than RTE */

typedef uint16 CanSM_u16_Impl;

typedef uint8 CanSM_TimerStateType_Enum_impl;

typedef struct {
   CanSM_u16_Impl                 cntTick_u16;
   CanSM_TimerStateType_Enum_impl stTimer;
} CanSM_TimerConfig_tst_struct_impl;

typedef CanSM_TimerConfig_tst_struct_impl CanSM_TimerConfig_ast_Astruct_impl[4];
typedef CanSM_BusOffRecoveryStateType_Enum_impl CanSM_currBOR_State_a_Aenum_impl[4];
typedef CanSM_NetworkModeStateType_Enum_impl CanSM_currComM_Mode_a_Aenum_impl[4];
/* Information: No typedef for ImplementationDataType CanTp_ConfigStructType because typeEmitter is a value other than RTE */

/* Information: No typedef for ImplementationDataType CanTp_ConfigType because typeEmitter is a value other than RTE */

/* Information: No typedef for ImplementationDataType CanTp_TickType because typeEmitter is a value other than RTE */

/* Information: No typedef for ImplementationDataType CanTrcv_ConfigType because typeEmitter is a value other than RTE */

/* Information: No typedef for ImplementationDataType Can_PduType because typeEmitter is a value other than RTE */

/* Information: No typedef for ImplementationDataType Can_ReturnType because typeEmitter is a value other than RTE */

/* Information: No typedef for ImplementationDataType Can_StateTransitionType because typeEmitter is a value other than RTE */

typedef uint8 Com_impl_u8;

typedef Com_impl_u8 Com_SigBuf_au8_impl[960];
typedef Com_impl_u8 Com_implDataType_au8_Size8[8];
/* Information: No typedef for ImplementationDataType boolean because typeEmitter is a value other than RTE */

typedef boolean Com_impl_b;

typedef uint16 Com_impl_u16;

typedef uint32 Com_impl_u32;

/* Information: No typedef for ImplementationDataType uint64 because typeEmitter is a value other than RTE */

typedef uint64 Com_impl_u64;

typedef uint32 ComM_uint32_Impl;

typedef uint16 ComM_uint16_Impl;

typedef uint8 ComM_uint8_Impl;

typedef uint8 ComM_bool_Impl;

typedef struct {
   ComM_uint32_Impl ChannelState_e;
   ComM_uint32_Impl LightTimeoutCtr_u32;
   ComM_uint16_Impl MinFullComTimeoutCtr_u16;
   ComM_uint16_Impl UserRequestCtr_u16;
   ComM_uint8_Impl  ChannelMode_u8;
   ComM_uint8_Impl  BusSmMode_u8;
   ComM_uint8_Impl  PassiveRequestState_u8;
   ComM_uint8_Impl  PncRequestCtr_u8;
   ComM_uint8_Impl  InhibitionReqStatus_u8;
   ComM_bool_Impl   NmNetworkRequestStatus_b;
   ComM_bool_Impl   DiagnosticRequestState_b;
   ComM_bool_Impl   CommunicationAllowed_b;
   ComM_bool_Impl   NmBusSleepIndicationStatus_b;
   ComM_bool_Impl   NmPrepareBusSleepIndicationStatus_b;
   ComM_bool_Impl   NmNetworkModeStatus_b;
} ComM_ChannelStruct_Impl;

typedef ComM_ChannelStruct_Impl ComM_ChannelStruct_Array_Impl[4];
typedef uint8 ComM_InhibitionStatusType;

typedef uint8 ComM_ModeType;

typedef uint8 ComM_UserHandleType;

typedef struct {
   ComM_uint16_Impl WakeUpInhibitionCtr_u16;
   ComM_uint16_Impl LimitToNoComCtr_u16;
   ComM_uint8_Impl  RequestedUserMode_u8;
   ComM_uint8_Impl  IndicatedUserMode_u8;
   ComM_uint8_Impl  numChannelsInFullCom_u8;
   ComM_uint8_Impl  numChannelsInSilentCom_u8;
   ComM_uint8_Impl  numChannelsInNoCom_u8;
} ComM_UserStruct_Impl;

typedef ComM_UserStruct_Impl ComM_UserStruct_Array_Impl[4];
/* Information: No typedef for ImplementationDataType BufReq_ReturnType because typeEmitter is a value other than RTE */

/* Information: No typedef for ImplementationDataType BusTrcvErrorType because typeEmitter is a value other than RTE */

/* Information: No typedef for ImplementationDataType IcomConfigIdType because typeEmitter is a value other than RTE */

/* Information: No typedef for ImplementationDataType IcomSwitch_ErrorType because typeEmitter is a value other than RTE */

/* Information: No typedef for ImplementationDataType NetworkHandleType because typeEmitter is a value other than RTE */

/* Information: No typedef for ImplementationDataType PNCHandleType because typeEmitter is a value other than RTE */

/* Information: No typedef for ImplementationDataType PduLengthType because typeEmitter is a value other than RTE */

/* Information: No typedef for ImplementationDataType PduInfoType because typeEmitter is a value other than RTE */

/* Information: No typedef for ImplementationDataType TpDataStateType because typeEmitter is a value other than RTE */

/* Information: No typedef for ImplementationDataType RetryInfoType because typeEmitter is a value other than RTE */

/* Information: No typedef for ImplementationDataType TPParameterType because typeEmitter is a value other than RTE */

/* Information: No typedef for ImplementationDataType Crc_DataType because typeEmitter is a value other than RTE */

typedef uint8 Dcm_ConfirmationStatusType;

typedef uint8 Dcm_DataArrayTypeUint8_DcmDspPidData_04Type[1];
typedef uint8 Dcm_DataArrayTypeUint8_DcmDspPidData_05Type[1];
typedef uint8 Dcm_DataArrayTypeUint8_DcmDspPidData_0CType[2];
typedef uint8 Dcm_DataArrayTypeUint8_DcmDspPidData_0DType[1];
typedef uint8 Dcm_DataArrayTypeUint8_DcmDspPidData_21Type[2];
typedef uint8 Dcm_DataArrayTypeUint8_DcmDspPidData_30Type[1];
typedef uint8 Dcm_DataArrayTypeUint8_DcmDspPidData_31Type[2];
typedef uint8 Dcm_DataArrayTypeUint8_DcmDspPidData_41Type[4];
typedef uint8 Dcm_DataArrayTypeUint8_DcmDspPidData_42Type[2];
typedef uint8 Dcm_DataArrayTypeUint8_DcmDspPidData_49Type[1];
typedef uint8 Dcm_DidSupportedType;

typedef uint8 Dcm_InfoTypeServicesArray_DcmDspVehInfoData_04Type[16];
typedef uint8 Dcm_InfoTypeServicesArray_DcmDspVehInfoData_0AType[20];
typedef uint8 Dcm_InfoTypeServicesArray_VIT_06_0Type[4];
typedef uint8 Dcm_NegativeResponseCodeType;

typedef uint8 Dcm_OpStatusType;

typedef uint8 Dcm_ProtocolType;

typedef uint8 Dcm_RequestDataOut_DcmDspRoutine_0203_DcmDspRequestRoutineResultsOutSignal_0PrimitivType;

typedef Dcm_RequestDataOut_DcmDspRoutine_0203_DcmDspRequestRoutineResultsOutSignal_0PrimitivType Dcm_RequestDataOut_DcmDspRoutine_0203_DcmDspRequestRoutineResultsOutSignal_0Type;

typedef uint8 Dcm_SecLevelType;

typedef uint8 Dcm_SesCtrlType;

typedef uint8 Dcm_StartDataOut_DcmDspRoutine_0203_DcmDspStartRoutineOutSignalPrimitivType;

typedef Dcm_StartDataOut_DcmDspRoutine_0203_DcmDspStartRoutineOutSignalPrimitivType Dcm_StartDataOut_DcmDspRoutine_0203_DcmDspStartRoutineOutSignalType;

/* Information: No typedef for ImplementationDataType Dcm_Struct_Dcm_ConfigType because typeEmitter is a value other than RTE */

typedef uint8 DemDataElememtDataSize_CS_ExtendedDataRecord_Aged_counter[1];
typedef uint8 DemDataElememtDataSize_CS_ExtendedDataRecord_Fault_pending_counter[1];
typedef uint8 DemDataElememtDataSize_PID_02[2];
typedef uint8 DemDataElememtDataSize_PID_04[1];
typedef uint8 DemDataElememtDataSize_PID_05[1];
typedef uint8 DemDataElememtDataSize_PID_0C[2];
typedef uint8 DemDataElememtDataSize_PID_0D[1];
typedef uint8 DemDataElememtDataSize_PID_42[2];
typedef uint8 DemDataElememtDataSize_PID_49[1];
typedef uint8 Dem_DTCFormatType;

typedef uint16 Dem_DTCOriginType;

typedef uint8 Dem_DTRControlType;

typedef uint8 Dem_DebounceResetStatusType;

typedef uint8 Dem_DebouncingStateType;

typedef uint32 Dem_DebugDataType;

typedef uint16 Dem_DtrIdType;

typedef uint16 Dem_EventIdType;

typedef uint8 Dem_EventStatusType;

typedef uint8 Dem_IndicatorIdType;

typedef uint8 Dem_IndicatorStatusType;

typedef uint8 Dem_InitMonitorReasonType;

typedef uint8 Dem_IumprDenomCondIdType;

typedef uint8 Dem_IumprDenomCondStatusType;

typedef uint8 Dem_MaxDataValueType[6];
typedef uint8 Dem_OperationCycleIdType;

typedef uint8 Dem_OperationCycleStateType;

typedef uint8 Dem_PID21valueType[2];
typedef uint8 Dem_PID31valueType[2];
typedef uint8 Dem_PID4DvalueType[2];
typedef uint8 Dem_PID4EvalueType[2];
typedef uint8 Dem_RatioIdType;

typedef uint8 Dem_UdsStatusByteType;

/* Information: No typedef for ImplementationDataType E2E_P01CheckStatusType because typeEmitter is a value other than RTE */

/* Information: No typedef for ImplementationDataType E2E_P01CheckStateType because typeEmitter is a value other than RTE */

/* Information: No typedef for ImplementationDataType E2E_P01DataIDMode because typeEmitter is a value other than RTE */

/* Information: No typedef for ImplementationDataType E2E_P01ConfigType because typeEmitter is a value other than RTE */

/* Information: No typedef for ImplementationDataType E2E_P01ProtectStateType because typeEmitter is a value other than RTE */

/* Information: No typedef for ImplementationDataType E2E_P02CheckStatusType because typeEmitter is a value other than RTE */

/* Information: No typedef for ImplementationDataType E2E_P02CheckStateType because typeEmitter is a value other than RTE */

/* Information: No typedef for ImplementationDataType E2E_P02ConfigType because typeEmitter is a value other than RTE */

/* Information: No typedef for ImplementationDataType E2E_P02ProtectStateType because typeEmitter is a value other than RTE */

/* Information: No typedef for ImplementationDataType E2E_P04CheckStatusType because typeEmitter is a value other than RTE */

/* Information: No typedef for ImplementationDataType E2E_P04CheckStateType because typeEmitter is a value other than RTE */

/* Information: No typedef for ImplementationDataType E2E_P04ConfigType because typeEmitter is a value other than RTE */

/* Information: No typedef for ImplementationDataType E2E_P04ProtectStateType because typeEmitter is a value other than RTE */

/* Information: No typedef for ImplementationDataType E2E_P05CheckStatusType because typeEmitter is a value other than RTE */

/* Information: No typedef for ImplementationDataType E2E_P05CheckStateType because typeEmitter is a value other than RTE */

/* Information: No typedef for ImplementationDataType E2E_P05ConfigType because typeEmitter is a value other than RTE */

/* Information: No typedef for ImplementationDataType E2E_P05ProtectStateType because typeEmitter is a value other than RTE */

/* Information: No typedef for ImplementationDataType E2E_P06CheckStatusType because typeEmitter is a value other than RTE */

/* Information: No typedef for ImplementationDataType E2E_P06CheckStateType because typeEmitter is a value other than RTE */

/* Information: No typedef for ImplementationDataType E2E_P06ConfigType because typeEmitter is a value other than RTE */

/* Information: No typedef for ImplementationDataType E2E_P06ProtectStateType because typeEmitter is a value other than RTE */

/* Information: No typedef for ImplementationDataType E2E_P11CheckStatusType because typeEmitter is a value other than RTE */

/* Information: No typedef for ImplementationDataType E2E_P11CheckStateType because typeEmitter is a value other than RTE */

/* Information: No typedef for ImplementationDataType E2E_P11DataIDMode because typeEmitter is a value other than RTE */

/* Information: No typedef for ImplementationDataType E2E_P11ConfigType because typeEmitter is a value other than RTE */

/* Information: No typedef for ImplementationDataType E2E_P11ProtectStateType because typeEmitter is a value other than RTE */

/* Information: No typedef for ImplementationDataType E2E_P22CheckStatusType because typeEmitter is a value other than RTE */

/* Information: No typedef for ImplementationDataType E2E_P22CheckStateType because typeEmitter is a value other than RTE */

/* Information: No typedef for ImplementationDataType E2E_P22ConfigType because typeEmitter is a value other than RTE */

/* Information: No typedef for ImplementationDataType E2E_P22ProtectStateType because typeEmitter is a value other than RTE */

/* Information: No typedef for ImplementationDataType E2E_P44CheckStatusType because typeEmitter is a value other than RTE */

/* Information: No typedef for ImplementationDataType E2E_P44CheckStateType because typeEmitter is a value other than RTE */

/* Information: No typedef for ImplementationDataType E2E_P44ConfigType because typeEmitter is a value other than RTE */

/* Information: No typedef for ImplementationDataType E2E_P44ProtectStateType because typeEmitter is a value other than RTE */

/* Information: No typedef for ImplementationDataType E2E_PCheckStatusType because typeEmitter is a value other than RTE */

/* Information: No typedef for ImplementationDataType E2E_SMStateType because typeEmitter is a value other than RTE */

/* Information: No typedef for ImplementationDataType E2E_SMCheckStateType because typeEmitter is a value other than RTE */

/* Information: No typedef for ImplementationDataType E2E_SMConfigType because typeEmitter is a value other than RTE */

/* Information: No typedef for ImplementationDataType E2EXf_ConfigType because typeEmitter is a value other than RTE */

typedef uint8 EcuM_BootTargetType;

/* Information: No typedef for ImplementationDataType EcuM_RunStatusType because typeEmitter is a value other than RTE */

typedef uint8 EcuM_ShutdownCauseType;

/* Information: No typedef for ImplementationDataType EcuM_ShutdownInfoType because typeEmitter is a value other than RTE */

typedef uint16 EcuM_ShutdownModeType;

typedef uint8 EcuM_ShutdownTargetType;

/* Information: No typedef for ImplementationDataType EcuM_StateType because typeEmitter is a value other than RTE */

typedef uint32 EcuM_TimeType;

typedef uint16 EcuM_UserType;

/* Information: No typedef for ImplementationDataType EcuM_WakeupSourceType because typeEmitter is a value other than RTE */

/* Information: No typedef for ImplementationDataType EcuM_WakeupStatusType because typeEmitter is a value other than RTE */

/* Information: No typedef for ImplementationDataType MemIf_JobResultType because typeEmitter is a value other than RTE */

/* Information: No typedef for ImplementationDataType MemIf_ModeType because typeEmitter is a value other than RTE */

/* Information: No typedef for ImplementationDataType MemIf_Rb_MigrationResult_ten because typeEmitter is a value other than RTE */

/* Information: No typedef for ImplementationDataType MemIf_StatusType because typeEmitter is a value other than RTE */

typedef uint16 NvM_BlockIdType;

typedef const void * NvM_Rb_ConstVoidPtr;
/* Information: No typedef for ImplementationDataType NvM_Rb_MigrationResult_ten because typeEmitter is a value other than RTE */

/* Information: No typedef for ImplementationDataType NvM_Rb_RequestType_ten because typeEmitter is a value other than RTE */

/* Information: No typedef for ImplementationDataType NvM_Rb_StatusType because typeEmitter is a value other than RTE */

typedef void * NvM_Rb_VoidPtr;
typedef uint8 NvM_RequestResultType;

typedef uint8 PduR_uint8_impl;

/* Information: No typedef for ImplementationDataType float32 because typeEmitter is a value other than RTE */

/* Information: No typedef for ImplementationDataType float64 because typeEmitter is a value other than RTE */

/* Information: No typedef for ImplementationDataType sint16 because typeEmitter is a value other than RTE */

/* Information: No typedef for ImplementationDataType sint16_least because typeEmitter is a value other than RTE */

/* Information: No typedef for ImplementationDataType sint32 because typeEmitter is a value other than RTE */

/* Information: No typedef for ImplementationDataType sint32_least because typeEmitter is a value other than RTE */

/* Information: No typedef for ImplementationDataType sint64 because typeEmitter is a value other than RTE */

/* Information: No typedef for ImplementationDataType sint8 because typeEmitter is a value other than RTE */

/* Information: No typedef for ImplementationDataType sint8_least because typeEmitter is a value other than RTE */

/* Information: No typedef for ImplementationDataType uint16_least because typeEmitter is a value other than RTE */

/* Information: No typedef for ImplementationDataType uint32_least because typeEmitter is a value other than RTE */

/* Information: No typedef for ImplementationDataType uint8_least because typeEmitter is a value other than RTE */

/* Information: No typedef for ImplementationDataType uint16 because typeEmitter is a value other than RTE */

/* Information: No typedef for ImplementationDataType Std_ReturnType because typeEmitter is a value other than RTE */

/* Information: No typedef for ImplementationDataType WdgIf_ModeType because typeEmitter is a value other than RTE */

/* Information: No typedef for ImplementationDataType Rte_ModeType_WdgMSupervisionCycle because typeEmitter is a value other than RTE */

/* Information: No typedef for ImplementationDataType TickType because typeEmitter is a value other than RTE */

typedef uint8 WdgM_CheckpointIdType;

typedef uint8 WdgM_SupervisedEntityIdType;

/* Information: No typedef for ImplementationDataType WdgM_AliveSupervisionType because typeEmitter is a value other than RTE */

typedef uint8 WdgM_ModeType;

/* Information: No typedef for ImplementationDataType WdgM_DeadlineSupervisionType because typeEmitter is a value other than RTE */

/* Information: No typedef for ImplementationDataType WdgM_LocalStatusParamsType because typeEmitter is a value other than RTE */

/* Information: No typedef for ImplementationDataType WdgM_TriggerType because typeEmitter is a value other than RTE */

/* Information: No typedef for ImplementationDataType WdgM_ExternalPositionInGraph_ten because typeEmitter is a value other than RTE */

/* Information: No typedef for ImplementationDataType WdgM_ExternalGraphType because typeEmitter is a value other than RTE */

/* Information: No typedef for ImplementationDataType WdgM_PrvModeType because typeEmitter is a value other than RTE */

/* Information: No typedef for ImplementationDataType WdgM_ConfigType because typeEmitter is a value other than RTE */

typedef uint8 WdgM_GlobalStatusType;

typedef uint8 WdgM_LocalStatusType;

typedef uint8 Array100ByteDataElement[100];
typedef boolean Boolean;
typedef float64 Double;
typedef float32 Float;
typedef uint16 UInt16;
typedef uint32 UInt32;
typedef uint8 UInt8;
typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_CallFP_ASW_CORE0_CPU_Utilization_CPU_Utilization) (VAR(uint32, AUTOMATIC) Duration_u32, P2VAR(float64, AUTOMATIC, RTE_APPL_DATA) CPU_PercentUtilization, P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Status);

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_CallFP_ASW_CORE0_Core_ClientServer_Interface_Core_ClientServer) (P2VAR(uint16, AUTOMATIC, RTE_APPL_DATA) CoreStatus, VAR(uint16, AUTOMATIC) Data2Core, P2VAR(uint16, AUTOMATIC, RTE_APPL_DATA) DataOfCore);

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_CallFP_ASW_CORE0_GetMaxUserStackUtilization_GetMaxUserStackUtilization) (P2VAR(float64, AUTOMATIC, RTE_APPL_DATA) MaxUserStackUtilization);

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_CallFP_ASW_CORE1_CPU_Utilization_CPU_Utilization) (VAR(uint32, AUTOMATIC) Duration_u32, P2VAR(float64, AUTOMATIC, RTE_APPL_DATA) CPU_PercentUtilization, P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Status);

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_CallFP_ASW_CORE1_GetMaxUserStackUtilization_GetMaxUserStackUtilization) (P2VAR(float64, AUTOMATIC, RTE_APPL_DATA) MaxUserStackUtilization);

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_CallFP_ASW_CORE2_CPU_Utilization_CPU_Utilization) (VAR(uint32, AUTOMATIC) Duration_u32, P2VAR(float64, AUTOMATIC, RTE_APPL_DATA) CPU_PercentUtilization, P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Status);

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_CallFP_ASW_CORE2_GetMaxUserStackUtilization_GetMaxUserStackUtilization) (P2VAR(float64, AUTOMATIC, RTE_APPL_DATA) MaxUserStackUtilization);

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_CallFP_ASW_CORE3_CPU_Utilization_CPU_Utilization) (VAR(uint32, AUTOMATIC) Duration_u32, P2VAR(float64, AUTOMATIC, RTE_APPL_DATA) CPU_PercentUtilization, P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Status);

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_CallFP_ASW_CORE3_GetMaxUserStackUtilization_GetMaxUserStackUtilization) (P2VAR(float64, AUTOMATIC, RTE_APPL_DATA) MaxUserStackUtilization);

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_CallFP_ASW_DEM_IndicatorStatus_GetIndicatorStatus) (P2VAR(Dem_IndicatorStatusType, AUTOMATIC, RTE_APPL_DATA) IndicatorStatus);

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_CallFP_ASW_DEM_OperationCycle_GetCycleQualified) (P2VAR(boolean, AUTOMATIC, RTE_APPL_DATA) CycleState);

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_CallFP_ASW_DEM_OperationCycle_GetOperationCycleState) (P2VAR(Dem_OperationCycleStateType, AUTOMATIC, RTE_APPL_DATA) CycleState);

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_CallFP_ASW_DEM_OperationCycle_SetCycleQualified) (void);

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_CallFP_ASW_DEM_OperationCycle_SetOperationCycleState) (VAR(Dem_OperationCycleStateType, AUTOMATIC) CycleState);

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_CallFP_ASW_NM_ComM_ECUModeLimitation_LimitECUToNoComMode) (VAR(boolean, AUTOMATIC) Status);

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_CallFP_ASW_NM_ComM_ECUModeLimitation_ReadInhibitCounter) (P2VAR(uint16, AUTOMATIC, RTE_APPL_DATA) CounterValue);

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_CallFP_ASW_NM_ComM_ECUModeLimitation_ResetInhibitCounter) (void);

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_CallFP_ASW_NM_ComM_ECUModeLimitation_SetECUGroupClassification) (VAR(ComM_InhibitionStatusType, AUTOMATIC) Status);

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_CallFP_ASW_NM_ComM_UserRequest_GetCurrentComMode) (P2VAR(ComM_ModeType, AUTOMATIC, RTE_APPL_DATA) ComMode);

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_CallFP_ASW_NM_ComM_UserRequest_GetMaxComMode) (P2VAR(ComM_ModeType, AUTOMATIC, RTE_APPL_DATA) ComMode);

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_CallFP_ASW_NM_ComM_UserRequest_GetRequestedComMode) (P2VAR(ComM_ModeType, AUTOMATIC, RTE_APPL_DATA) ComMode);

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_CallFP_ASW_NM_ComM_UserRequest_RequestComMode) (VAR(ComM_ModeType, AUTOMATIC) ComMode);

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_CallFP_ASW_NVM_NvMService_EraseBlock) (void);

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_CallFP_ASW_NVM_NvMService_GetDataIndex) (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) DataIndexPtr);

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_CallFP_ASW_NVM_NvMService_GetErrorStatus) (P2VAR(NvM_RequestResultType, AUTOMATIC, RTE_APPL_DATA) RequestResultPtr);

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_CallFP_ASW_NVM_NvMService_InvalidateNvBlock) (void);

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_CallFP_ASW_NVM_NvMService_ReadBlock) (VAR(NvM_Rb_VoidPtr, AUTOMATIC) DstPtr);

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_CallFP_ASW_NVM_NvMService_RestoreBlockDefaults) (VAR(NvM_Rb_VoidPtr, AUTOMATIC) DstPtr);

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_CallFP_ASW_NVM_NvMService_SetDataIndex) (VAR(uint8, AUTOMATIC) DataIndex);

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_CallFP_ASW_NVM_NvMService_SetRamBlockStatus) (VAR(boolean, AUTOMATIC) BlockChanged);

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_CallFP_ASW_NVM_NvMService_WriteBlock) (VAR(NvM_Rb_ConstVoidPtr, AUTOMATIC) SrcPtr);

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_CallFP_ASW_WDG_WdgM_LocalSupervision_CheckpointReached) (void);

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_CallFP_Dcm_DataServices_DcmDspPidData_04_ReadData) (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Data);

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_CallFP_Dcm_DataServices_DcmDspPidData_05_ReadData) (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Data);

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_CallFP_Dcm_DataServices_DcmDspPidData_0C_ReadData) (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Data);

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_CallFP_Dcm_DataServices_DcmDspPidData_0D_ReadData) (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Data);

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_CallFP_Dcm_DataServices_DcmDspPidData_21_ReadData) (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Data);

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_CallFP_Dcm_DataServices_DcmDspPidData_30_ReadData) (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Data);

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_CallFP_Dcm_DataServices_DcmDspPidData_31_ReadData) (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Data);

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_CallFP_Dcm_DataServices_DcmDspPidData_41_ReadData) (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Data);

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_CallFP_Dcm_DataServices_DcmDspPidData_42_ReadData) (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Data);

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_CallFP_Dcm_DataServices_DcmDspPidData_49_ReadData) (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Data);

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_CallFP_Dcm_InfotypeServices_DcmDspVehInfoData_04_GetInfotypeValueData) (VAR(Dcm_OpStatusType, AUTOMATIC) OpStatus, P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) DataValueBuffer, P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) DataValueBufferSize);

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_CallFP_Dcm_InfotypeServices_DcmDspVehInfoData_0A_GetInfotypeValueData) (VAR(Dcm_OpStatusType, AUTOMATIC) OpStatus, P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) DataValueBuffer, P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) DataValueBufferSize);

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_CallFP_Dcm_InfotypeServices_VIT_06_0_GetInfotypeValueData) (VAR(Dcm_OpStatusType, AUTOMATIC) OpStatus, P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) DataValueBuffer, P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) DataValueBufferSize);

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_CallFP_Dcm_RoutineServices_DcmDspRoutine_0203_RequestResults) (VAR(Dcm_OpStatusType, AUTOMATIC) OpStatus, P2VAR(Dcm_RequestDataOut_DcmDspRoutine_0203_DcmDspRequestRoutineResultsOutSignal_0Type, AUTOMATIC, RTE_APPL_DATA) DataOut_DcmDspRequestRoutineResultsOutSignal_0, P2VAR(Dcm_NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode);

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_CallFP_Dcm_RoutineServices_DcmDspRoutine_0203_Start) (VAR(Dcm_OpStatusType, AUTOMATIC) OpStatus, P2VAR(Dcm_StartDataOut_DcmDspRoutine_0203_DcmDspStartRoutineOutSignalType, AUTOMATIC, RTE_APPL_DATA) DataOut_DcmDspStartRoutineOutSignal, P2VAR(Dcm_NegativeResponseCodeType, AUTOMATIC, RTE_APPL_DATA) ErrorCode);

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_CallFP_Dem_DataServices_CS_ExtendedDataRecord_Aged_counter_ReadData) (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Data);

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_CallFP_Dem_DataServices_CS_ExtendedDataRecord_Fault_pending_counter_ReadData) (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Data);

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_CallFP_Dem_DataServices_PID_02_ReadData) (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Data);

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_CallFP_Dem_DataServices_PID_04_ReadData) (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Data);

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_CallFP_Dem_DataServices_PID_05_ReadData) (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Data);

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_CallFP_Dem_DataServices_PID_0C_ReadData) (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Data);

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_CallFP_Dem_DataServices_PID_0D_ReadData) (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Data);

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_CallFP_Dem_DataServices_PID_42_ReadData) (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Data);

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_CallFP_Dem_DataServices_PID_49_ReadData) (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Data);

typedef P2FUNC(void, RTE_CODE, Rte_IrvReadFP_ASW_CORE0_RE_CORE0_SWC_100ms_Explicit_IRV_1) (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data);

typedef P2FUNC(void, RTE_CODE, Rte_IrvWriteFP_ASW_CORE0_RE_CORE0_SWC_10ms_Explicit_IRV_1) (P2CONST(uint8, AUTOMATIC, RTE_APPL_DATA) data);

typedef Impl_NVM_DstPtrType_1024 Rte_PimType_ASW_NVM_ASW_NVM_BlockNative_1024_Type;
typedef P2FUNC(P2VAR(Rte_PimType_ASW_NVM_ASW_NVM_BlockNative_1024_Type, AUTOMATIC, RTE_APPL_DATA), RTE_CODE, Rte_PimFP_ASW_NVM_ASW_NVM_BlockNative_1024_1) (void);

typedef Impl_NVM_DstPtrType_1024 Rte_PimType_ASW_NVM_ASW_NVM_BlockRedundant_1024_Type;
typedef P2FUNC(P2VAR(Rte_PimType_ASW_NVM_ASW_NVM_BlockRedundant_1024_Type, AUTOMATIC, RTE_APPL_DATA), RTE_CODE, Rte_PimFP_ASW_NVM_ASW_NVM_BlockNative_1024_2) (void);

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_ReadFP_ASW_CORE0_DataTransfer100Byte_Core0Core1_Data_ptr) (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data);

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_ReadFP_ASW_CORE1_DataTransfer100Byte_Core0Core1_Data_ptr) (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data);

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_ReadFP_BswM_ETAS_SenderReceiverInterface_uint8_uint8) (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data);

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_ReadFP_BswM_ModeRequestInterface_AppMode) (P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data);

typedef P2CONST(struct Rte_CDS_ASW_BASE,AUTOMATIC,RTE_CONST) Rte_SelfType_ASW_BASE;

typedef P2CONST(struct Rte_CDS_ASW_COM,AUTOMATIC,RTE_CONST) Rte_SelfType_ASW_COM;

typedef P2CONST(struct Rte_CDS_ASW_CORE0,AUTOMATIC,RTE_CONST) Rte_SelfType_ASW_CORE0;

typedef P2CONST(struct Rte_CDS_ASW_CORE1,AUTOMATIC,RTE_CONST) Rte_SelfType_ASW_CORE1;

typedef P2CONST(struct Rte_CDS_ASW_CORE2,AUTOMATIC,RTE_CONST) Rte_SelfType_ASW_CORE2;

typedef P2CONST(struct Rte_CDS_ASW_CORE3,AUTOMATIC,RTE_CONST) Rte_SelfType_ASW_CORE3;

typedef P2CONST(struct Rte_CDS_ASW_DCM,AUTOMATIC,RTE_CONST) Rte_SelfType_ASW_DCM;

typedef P2CONST(struct Rte_CDS_ASW_DEM,AUTOMATIC,RTE_CONST) Rte_SelfType_ASW_DEM;

typedef P2CONST(struct Rte_CDS_ASW_NM,AUTOMATIC,RTE_CONST) Rte_SelfType_ASW_NM;

typedef P2CONST(struct Rte_CDS_ASW_NVM,AUTOMATIC,RTE_CONST) Rte_SelfType_ASW_NVM;

typedef P2CONST(struct Rte_CDS_ASW_WDG,AUTOMATIC,RTE_CONST) Rte_SelfType_ASW_WDG;

typedef P2CONST(struct Rte_CDS_ASW_XCP,AUTOMATIC,RTE_CONST) Rte_SelfType_ASW_XCP;

typedef P2CONST(struct Rte_CDS_BswM,AUTOMATIC,RTE_CONST) Rte_SelfType_BswM;

typedef P2CONST(struct Rte_CDS_CDD_CORE0,AUTOMATIC,RTE_CONST) Rte_SelfType_CDD_CORE0;

typedef P2CONST(struct Rte_CDS_CDD_CORE1,AUTOMATIC,RTE_CONST) Rte_SelfType_CDD_CORE1;

typedef P2CONST(struct Rte_CDS_CDD_CORE2,AUTOMATIC,RTE_CONST) Rte_SelfType_CDD_CORE2;

typedef P2CONST(struct Rte_CDS_CDD_CORE3,AUTOMATIC,RTE_CONST) Rte_SelfType_CDD_CORE3;

typedef P2CONST(struct Rte_CDS_ComM,AUTOMATIC,RTE_CONST) Rte_SelfType_ComM;

typedef P2CONST(struct Rte_CDS_Dcm,AUTOMATIC,RTE_CONST) Rte_SelfType_Dcm;

typedef P2CONST(struct Rte_CDS_Dem,AUTOMATIC,RTE_CONST) Rte_SelfType_Dem;

typedef P2CONST(struct Rte_CDS_Det,AUTOMATIC,RTE_CONST) Rte_SelfType_Det;

typedef P2CONST(struct Rte_CDS_EcuM,AUTOMATIC,RTE_CONST) Rte_SelfType_EcuM;

typedef P2CONST(struct Rte_CDS_NvM,AUTOMATIC,RTE_CONST) Rte_SelfType_NvM;

typedef P2CONST(struct Rte_CDS_RSID,AUTOMATIC,RTE_CONST) Rte_SelfType_RSID;

typedef P2CONST(struct Rte_CDS_SWC_DEM,AUTOMATIC,RTE_CONST) Rte_SelfType_SWC_DEM;

typedef P2CONST(struct Rte_CDS_WdgM,AUTOMATIC,RTE_CONST) Rte_SelfType_WdgM;

typedef P2CONST(struct Rte_CDS_rba_DiagLib,AUTOMATIC,RTE_CONST) Rte_SelfType_rba_DiagLib;

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_SwitchAckFP_WdgM_WdgM_GlobalMode_currentMode) (void);

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_SwitchAckFP_WdgM_WdgM_LocalMode_currentMode) (void);

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_SwitchFP_ComM_ComM_CurrentMode_currentMode) (VAR(uint8, AUTOMATIC) data);

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_SwitchFP_Dcm_DcmCommunicationControl_Can_Network_CanNodeNum_01_MDGP_DcmCommunicationControl_Can_Network_CanNodeNum_01) (VAR(uint8, AUTOMATIC) data);

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_SwitchFP_Dcm_DcmControlDTCSetting_MDGP_DcmControlDTCSetting) (VAR(uint8, AUTOMATIC) data);

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_SwitchFP_Dcm_DcmDiagnosticSessionControl_MDGP_DcmDiagnosticSessionControl) (VAR(uint8, AUTOMATIC) data);

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_SwitchFP_Dcm_DcmEcuReset_MDGP_DcmEcuReset) (VAR(uint8, AUTOMATIC) data);

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_SwitchFP_WdgM_WdgM_GlobalMode_currentMode) (VAR(uint8, AUTOMATIC) data);

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_SwitchFP_WdgM_WdgM_LocalMode_currentMode) (VAR(uint8, AUTOMATIC) data);

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_WriteFP_ASW_BASE_ModeRequestInterface_AppMode) (VAR(uint8, AUTOMATIC) data);

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_WriteFP_ASW_CORE0_DataTransfer100Byte_Core0Core1_Data_ptr) (P2CONST(uint8, AUTOMATIC, RTE_APPL_DATA) data);

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_WriteFP_ASW_CORE0_ModeRequestInterface_AppMode) (VAR(uint8, AUTOMATIC) data);

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_WriteFP_ASW_CORE1_DataTransfer100Byte_Core0Core1_Data_ptr) (P2CONST(uint8, AUTOMATIC, RTE_APPL_DATA) data);

typedef P2FUNC(VAR(Std_ReturnType, AUTOMATIC), RTE_CODE, Rte_WriteFP_ASW_NM_ETAS_SenderReceiverInterface_uint8_uint8) (VAR(uint8, AUTOMATIC) data);

#include "iocNeeds.h"

#endif /* !RTE_TYPE_H */
