/** @file     SchM_CanTp.h
  *
  * @brief    Basic Software Scheduler Module Interlink header file
  *
  * @note     AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
  *
  * @note     Generated by ETAS RTA-RTE
  * @note     Version 7.5.3
  *
  * @date     Tue Mar  5 14:09:38 2024
  */

#ifndef SchM_CanTp
#define SchM_CanTp

#include "SchM_CanTp_Type.h"
#include "Rte_Intl.h"
#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#if defined(RTE_RUNNABLEAPI_CE_CanTp_CancelReceive)
   /* Do nothing for this and all elif clauses below (rte_sws_2751) */
#elif defined(RTE_RUNNABLEAPI_CE_CanTp_CancelTransmit)
#elif defined(RTE_RUNNABLEAPI_CE_CanTp_ChangeParameter)
#elif defined(RTE_RUNNABLEAPI_CE_CanTp_GetVersionInfo)
#elif defined(RTE_RUNNABLEAPI_CE_CanTp_Init)
#elif defined(RTE_RUNNABLEAPI_CE_CanTp_ReadParameter)
#elif defined(RTE_RUNNABLEAPI_CE_CanTp_RxIndication)
#elif defined(RTE_RUNNABLEAPI_CE_CanTp_Shutdown)
#elif defined(RTE_RUNNABLEAPI_CE_CanTp_Transmit)
#elif defined(RTE_RUNNABLEAPI_CE_CanTp_TxConfirmation)
#elif defined(RTE_RUNNABLEAPI_CanTp_MainFunction)
#else
   /* None of above defined so define value including all APIs (rte_sws_2751) */
   #define RTE_PRV_ALL_API
#endif

/* API Mapping Macros */
#ifndef RTE_CORE

#endif /* RTE_CORE */

/*******************************************************
 ***
 *** Schedulable Entity Prototypes
 ***
 *******************************************************/

#define CANTP_START_SEC_CODE
#include "CanTp_MemMap.h"
FUNC(void, CANTP_CODE) CanTp_MainFunction(void);
#define CANTP_STOP_SEC_CODE
#include "CanTp_MemMap.h"

#ifdef __cplusplus
} /* extern C */
#endif /* __cplusplus */

#endif /* !SchM_CanTp */
