/** @file     SchM_WdgM_Type.h
  *
  * @brief    Basic Software Scheduler Module Interlink Types header file
  *
  * @note     AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
  *
  * @note     Generated by ETAS RTA-RTE
  * @note     Version 7.5.3
  *
  * @date     Tue Mar  5 14:09:38 2024
  */

#ifndef SchM_WdgM_Type
#define SchM_WdgM_Type

#include "Rte_Type.h"
#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

/* BEGIN: BSW implementation specific types */
#ifndef RTE_CORE
#ifndef RTE_MODETYPE_WDGMSUPERVISIONCYCLE
#define RTE_MODETYPE_WDGMSUPERVISIONCYCLE

typedef uint8 Rte_ModeType_WdgMSupervisionCycle;

#endif /* !RTE_MODETYPE_WDGMSUPERVISIONCYCLE */
#endif /* RTE_CORE */

/* END: BSW implementation specific types */

/* BEGIN: BSW implementation specific definitions */
#ifndef RTE_CORE
#ifndef RTE_MODE_WdgMSupervisionCycle_SUPERVISION_CYCLE_0
#define RTE_MODE_WdgMSupervisionCycle_SUPERVISION_CYCLE_0 0U
#endif /* !RTE_MODE_WdgMSupervisionCycle_SUPERVISION_CYCLE_0 */
#ifndef RTE_TRANSITION_WdgMSupervisionCycle
#define RTE_TRANSITION_WdgMSupervisionCycle               1U
#endif /* !RTE_TRANSITION_WdgMSupervisionCycle */
#endif /* RTE_CORE */

/* END: BSW implementation specific definitions */


#ifdef __cplusplus
} /* extern C */
#endif /* __cplusplus */

#endif /* !SchM_WdgM_Type */
