/*
 * Dcm_Cfg_Prot.h
 *
 *  Created on: May 23, 2019
 *      Author: ALN3KOR
 */

#ifndef RBA_CUBAS_DIAGNOSIS_DCM_API_DCM_CFG_PROT_H_
#define RBA_CUBAS_DIAGNOSIS_DCM_API_DCM_CFG_PROT_H_

#define CHECK_APICONSISTENCY

#endif /* RBA_RTA-BSW_DIAGNOSIS_DCM_API_DCM_CFG_PROT_H_ */
