
#This is where the user can specify overrides for RTA-BSW defaults.
MbSortingPref=direction,controllerName,canhandleType

manprop_ComMGeneral=\
ComMRteEnabled:true,\
ComMModeLimitationEnabled:true\

manprop_ComMChannel_ALL=\
ComMNoCom:false,\
ComMNoWakeup:false

manprop_NvMCommon=\
NvMRbSetWriteAllTriggerApi:true

manprop_FeeGeneral=\
FeeRbMachineType:MCU_RB_MANUAL_CFG,\
FeeRbFsSelect:FS1,\
FeeNvmJobEndNotification:Fee_NvmJobEndNotification,\
FeeNvmJobErrorNotification:Fee_NvmJobErrorNotification,

manprop_FeeGeneral/FeeRbSectorTable=\
FlsRbPageSize:8,\
FeeRbFastCacheInitActive:true,\
FeeRbHeaderRecheckActive:false,\
FlsRbErasedValue:0x0

manprop_NumberOfFeeRbSectors = 2
manprop_FeeGeneral/FeeRbSectorTable/FeeRbSector_ALL=\
FlsRbSectorSize:16384

DevErrorDetection=\
CanIf/CanIfPublicCfg/CanIfPublicDevErrorDetect:true,\
Com/ComGeneral/ComConfigurationUseDet:true,\
PduR/PduRGeneral/PduRDevErrorDetect:true,\
CanSM/CanSMGeneral/CanSMDevErrorDetect:true,\
CanNm/CanNmGlobalConfig/CanNmDevErrorDetect:true,\
ComM/ComMGeneral/ComMDevErrorDetect:true,\
Can/CanGeneral/CanDevErrorDetection:true,\
Nm/NmGlobalConfig/NmGlobalProperties/NmDevErrorDetect:true,\
NvM/NvMCommon/NvMDevErrorDetect:true,\
MemIf/MemIfGeneral/MemIfDevErrorDetect:true,\
Fee/FeeGeneral/FeeDevErrorDetect:true,

manprop_CanSMDemEventParameterRefs_ALL=\
CanSMRbDynCreate_CANSM_E_BUS_OFF:Disabled

manprop_NmGlobalConstants=\
NmRxIndicationCallback:Nm_RxIndicationCallback,\
NmStateChangeIndCallback:Nm_StateChangeIndication

manprop_CanSMGeneral=\
CanSMMainFunctionTimePeriod:0.001

manprop_CanIfDispatchCfg=\
CanIfDispatchUserCtrlBusOffName:CanSM_ControllerBusOff,\
CanIfDispatchUserTrcvModeIndicationUL:CAN_SM

rtabswprop_ComSignal_ALL=\
ComTransferProperty:PENDING



