/********************************************************************************************************************/
/*                                                                                                                  */
/* TOOL-GENERATED SOURCECODE, DO NOT CHANGE                                                                         */
/*                                                                                                                  */
/********************************************************************************************************************/

#ifndef DEM_CFG_ENVDATAELEMENT_DATASIZE_H
#define DEM_CFG_ENVDATAELEMENT_DATASIZE_H

#include "Std_Types.h"

#define DEM_CFG_ENV_DATAELEMENTS_EXTERN_AVAILABILITY   STD_ON
#define DEM_CFG_ENV_DATAELEMENTS_INTERN_AVAILABILITY  STD_ON

#define DemConf_DemDataElementDataSize_DEM_DATAELEM_CS_EXTENDEDDATARECORD_FAULT_PENDING_COUNTER  1   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_CS_EXTENDEDDATARECORD_AGED_COUNTER  1   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D000  1   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D001  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D002  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D003  1   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D004  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D005  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D007  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D008  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D009  1   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D010  1   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D011  1   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D012  1   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D013  1   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D014  1   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D015  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D016  1   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D017  1   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D018  1   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D019  1   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D020  1   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D021  1   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D022  1   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D023  1   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D024  1   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D025  1   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D026  1   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D027  1   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D028  1   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D029  1   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D030  1   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D031  1   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D032  1   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D033  1   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D034  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D035  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D036  1   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D037  1   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D038  1   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D039  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D040  1   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D041  1   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D042  1   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D043  1   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D044  1   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D045  1   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D046  1   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D047  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D048  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D049  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_1D06  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_1D07  1   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_1D08  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_1D09  1   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_1D0A  1   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_1D0B  1   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_1D0C  6   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_1D0D  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_1D0E  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_1D0F  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_1D13  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_1D14  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_1D15  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_1D16  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_1D17  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_1D18  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_1D19  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_1D1A  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_1D1B  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_1D1C  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_1D1D  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_1D1E  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_1D1F  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_1D20  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_1D21  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_1D22  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_1D23  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_1D24  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_1D25  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_1D26  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_1D27  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_1D28  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_1D29  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_2D02  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_2D03  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_2D04  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_2D05  1   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_2D06  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_2D07  1   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_2D08  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_2D0E  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_2D13  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_2D14  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_2D15  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_2D1C  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_2D1D  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_2D1E  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_2D1F  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_2D20  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_2D21  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_2D22  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_2D25  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_2D26  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_3D02  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_3D03  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_3D04  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_3D05  1   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_3D06  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_3D07  1   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_3D08  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_3D0E  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_3D13  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_3D14  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_3D15  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_3D1C  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_3D1D  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_3D1E  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_3D1F  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_3D20  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_3D21  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_3D22  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_3D25  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_3D26  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_4D27  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_4D28  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_4D29  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_4D2A  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_4D2B  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_4D2C  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_4D2D  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_4D2E  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_4D2F  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_4D30  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_4D31  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_4D32  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_4D33  1   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_4D34  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_4D35  1   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_4D36  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_4D37  1   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_4D38  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_4D39  1   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_4D3A  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_4D3B  1   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_4D3C  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_4D3D  1   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_PID_02  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_PID_04  1   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_PID_05  1   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_PID_0C  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_PID_0D  1   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_PID_42  2   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_PID_49  1   
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_INTER_EXTENDEDDATARECORD_FAULT_OCCURRENCE_COUNTER  1 
#define DemConf_DemDataElementDataSize_DEM_DATAELEM_INTER_EXTENDEDDATARECORD_AGING_COUNTER  1 

#endif

