/** @file     Rte_Dcm_Type.h
  *
  * @brief    Application types header file
  *
  * @note     AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
  *
  * @note     Generated by ETAS RTA-RTE
  * @note     Version 6.3.0pr11 
  *
  * @note     Generated by pre-release software - not for production use!
  *
  * @note     By using this software you agree to all of the terms in the
  *           End User License Agreement (README-PREVIEW_RELEASE_EULA.pdf)
  */

#ifndef RTE_Dcm_TYPE_H
#define RTE_Dcm_TYPE_H

#include "Rte_Type.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

/* BEGIN: SWC specific types */
#ifndef RTE_CORE
#ifndef RTE_MODETYPE_DCMCONTROLDTCSETTING
#define RTE_MODETYPE_DCMCONTROLDTCSETTING

typedef uint8 Rte_ModeType_DcmControlDTCSetting;

#endif /* !RTE_MODETYPE_DCMCONTROLDTCSETTING */
#ifndef RTE_MODETYPE_DCMDIAGNOSTICSESSIONCONTROL
#define RTE_MODETYPE_DCMDIAGNOSTICSESSIONCONTROL

typedef uint8 Rte_ModeType_DcmDiagnosticSessionControl;

#endif /* !RTE_MODETYPE_DCMDIAGNOSTICSESSIONCONTROL */
#ifndef RTE_MODETYPE_DCMECURESET
#define RTE_MODETYPE_DCMECURESET

typedef uint8 Rte_ModeType_DcmEcuReset;

#endif /* !RTE_MODETYPE_DCMECURESET */
#ifndef RTE_MODETYPE_MDG2
#define RTE_MODETYPE_MDG2

typedef uint8 Rte_ModeType_Mdg2;

#endif /* !RTE_MODETYPE_MDG2 */
#endif /* RTE_CORE */

/* END: SWC specific types */

/* BEGIN: SWC specific definitions */
#ifndef RTE_CORE
#ifndef RTE_MODE_DcmControlDTCSetting_DISABLEDTCSETTING
#define RTE_MODE_DcmControlDTCSetting_DISABLEDTCSETTING                  0U
#endif /* !RTE_MODE_DcmControlDTCSetting_DISABLEDTCSETTING */
#ifndef RTE_MODE_DcmControlDTCSetting_ENABLEDTCSETTING
#define RTE_MODE_DcmControlDTCSetting_ENABLEDTCSETTING                   1U
#endif /* !RTE_MODE_DcmControlDTCSetting_ENABLEDTCSETTING */
#ifndef RTE_MODE_DcmDiagnosticSessionControl_CODING_SESSION
#define RTE_MODE_DcmDiagnosticSessionControl_CODING_SESSION              0U
#endif /* !RTE_MODE_DcmDiagnosticSessionControl_CODING_SESSION */
#ifndef RTE_MODE_DcmDiagnosticSessionControl_DEFAULT_SESSION
#define RTE_MODE_DcmDiagnosticSessionControl_DEFAULT_SESSION             1U
#endif /* !RTE_MODE_DcmDiagnosticSessionControl_DEFAULT_SESSION */
#ifndef RTE_MODE_DcmDiagnosticSessionControl_EXTENDED_DIAGNOSTIC_SESSION
#define RTE_MODE_DcmDiagnosticSessionControl_EXTENDED_DIAGNOSTIC_SESSION 2U
#endif /* !RTE_MODE_DcmDiagnosticSessionControl_EXTENDED_DIAGNOSTIC_SESSION */
#ifndef RTE_MODE_DcmDiagnosticSessionControl_PROGRAMMING_SESSION
#define RTE_MODE_DcmDiagnosticSessionControl_PROGRAMMING_SESSION         3U
#endif /* !RTE_MODE_DcmDiagnosticSessionControl_PROGRAMMING_SESSION */
#ifndef RTE_MODE_DcmEcuReset_EXECUTE
#define RTE_MODE_DcmEcuReset_EXECUTE                                     0U
#endif /* !RTE_MODE_DcmEcuReset_EXECUTE */
#ifndef RTE_MODE_DcmEcuReset_JUMPTOBOOTLOADER
#define RTE_MODE_DcmEcuReset_JUMPTOBOOTLOADER                            1U
#endif /* !RTE_MODE_DcmEcuReset_JUMPTOBOOTLOADER */
#ifndef RTE_MODE_DcmEcuReset_JUMPTOSYSSUPPLIERBOOTLOADER
#define RTE_MODE_DcmEcuReset_JUMPTOSYSSUPPLIERBOOTLOADER                 2U
#endif /* !RTE_MODE_DcmEcuReset_JUMPTOSYSSUPPLIERBOOTLOADER */
#ifndef RTE_MODE_DcmEcuReset_NONE
#define RTE_MODE_DcmEcuReset_NONE                                        3U
#endif /* !RTE_MODE_DcmEcuReset_NONE */
#ifndef RTE_MODE_Mdg2_Mode1
#define RTE_MODE_Mdg2_Mode1                                              0U
#endif /* !RTE_MODE_Mdg2_Mode1 */
#ifndef RTE_TRANSITION_DcmControlDTCSetting
#define RTE_TRANSITION_DcmControlDTCSetting                              2U
#endif /* !RTE_TRANSITION_DcmControlDTCSetting */
#ifndef RTE_TRANSITION_DcmDiagnosticSessionControl
#define RTE_TRANSITION_DcmDiagnosticSessionControl                       4U
#endif /* !RTE_TRANSITION_DcmDiagnosticSessionControl */
#ifndef RTE_TRANSITION_DcmEcuReset
#define RTE_TRANSITION_DcmEcuReset                                       4U
#endif /* !RTE_TRANSITION_DcmEcuReset */
#ifndef RTE_TRANSITION_Mdg2
#define RTE_TRANSITION_Mdg2                                              1U
#endif /* !RTE_TRANSITION_Mdg2 */
#endif /* RTE_CORE */

#if !defined(RTE_CORE)

/* Box: /AUTOSAR_Dcm/ImplementationDataTypes/Dcm_NegativeResponseCodeType begin */
/* Box: "DCM_E_GENERALREJECT" begin */
#ifndef DCM_E_GENERALREJECT
#define DCM_E_GENERALREJECT (16U)
#endif /* !DCM_E_GENERALREJECT */
/* Box: "DCM_E_GENERALREJECT" end */
/* Box: "DCM_E_SERVICENOTSUPPORTED" begin */
#ifndef DCM_E_SERVICENOTSUPPORTED
#define DCM_E_SERVICENOTSUPPORTED (17U)
#endif /* !DCM_E_SERVICENOTSUPPORTED */
/* Box: "DCM_E_SERVICENOTSUPPORTED" end */
/* Box: "DCM_E_SUBFUNCTIONNOTSUPPORTED" begin */
#ifndef DCM_E_SUBFUNCTIONNOTSUPPORTED
#define DCM_E_SUBFUNCTIONNOTSUPPORTED (18U)
#endif /* !DCM_E_SUBFUNCTIONNOTSUPPORTED */
/* Box: "DCM_E_SUBFUNCTIONNOTSUPPORTED" end */
/* Box: "DCM_E_INCORRECTMESSAGELENGTHORINVALIDFORMAT" begin */
#ifndef DCM_E_INCORRECTMESSAGELENGTHORINVALIDFORMAT
#define DCM_E_INCORRECTMESSAGELENGTHORINVALIDFORMAT (19U)
#endif /* !DCM_E_INCORRECTMESSAGELENGTHORINVALIDFORMAT */
/* Box: "DCM_E_INCORRECTMESSAGELENGTHORINVALIDFORMAT" end */
/* Box: "DCM_E_RESPONSETOOLONG" begin */
#ifndef DCM_E_RESPONSETOOLONG
#define DCM_E_RESPONSETOOLONG (20U)
#endif /* !DCM_E_RESPONSETOOLONG */
/* Box: "DCM_E_RESPONSETOOLONG" end */
/* Box: "DCM_E_BUSYREPEATREQUEST" begin */
#ifndef DCM_E_BUSYREPEATREQUEST
#define DCM_E_BUSYREPEATREQUEST (33U)
#endif /* !DCM_E_BUSYREPEATREQUEST */
/* Box: "DCM_E_BUSYREPEATREQUEST" end */
/* Box: "DCM_E_CONDITIONSNOTCORRECT" begin */
#ifndef DCM_E_CONDITIONSNOTCORRECT
#define DCM_E_CONDITIONSNOTCORRECT (34U)
#endif /* !DCM_E_CONDITIONSNOTCORRECT */
/* Box: "DCM_E_CONDITIONSNOTCORRECT" end */
/* Box: "DCM_E_REQUESTSEQUENCEERROR" begin */
#ifndef DCM_E_REQUESTSEQUENCEERROR
#define DCM_E_REQUESTSEQUENCEERROR (36U)
#endif /* !DCM_E_REQUESTSEQUENCEERROR */
/* Box: "DCM_E_REQUESTSEQUENCEERROR" end */
/* Box: "DCM_E_NORESPONSEFROMSUBNETCOMPONENT" begin */
#ifndef DCM_E_NORESPONSEFROMSUBNETCOMPONENT
#define DCM_E_NORESPONSEFROMSUBNETCOMPONENT (37U)
#endif /* !DCM_E_NORESPONSEFROMSUBNETCOMPONENT */
/* Box: "DCM_E_NORESPONSEFROMSUBNETCOMPONENT" end */
/* Box: "DCM_E_FAILUREPREVENTSEXECUTIONOFREQUESTEDACTION" begin */
#ifndef DCM_E_FAILUREPREVENTSEXECUTIONOFREQUESTEDACTION
#define DCM_E_FAILUREPREVENTSEXECUTIONOFREQUESTEDACTION (38U)
#endif /* !DCM_E_FAILUREPREVENTSEXECUTIONOFREQUESTEDACTION */
/* Box: "DCM_E_FAILUREPREVENTSEXECUTIONOFREQUESTEDACTION" end */
/* Box: "DCM_E_REQUESTOUTOFRANGE" begin */
#ifndef DCM_E_REQUESTOUTOFRANGE
#define DCM_E_REQUESTOUTOFRANGE (49U)
#endif /* !DCM_E_REQUESTOUTOFRANGE */
/* Box: "DCM_E_REQUESTOUTOFRANGE" end */
/* Box: "DCM_E_SECURITYACCESSDENIED" begin */
#ifndef DCM_E_SECURITYACCESSDENIED
#define DCM_E_SECURITYACCESSDENIED (51U)
#endif /* !DCM_E_SECURITYACCESSDENIED */
/* Box: "DCM_E_SECURITYACCESSDENIED" end */
/* Box: "DCM_E_INVALIDKEY" begin */
#ifndef DCM_E_INVALIDKEY
#define DCM_E_INVALIDKEY (53U)
#endif /* !DCM_E_INVALIDKEY */
/* Box: "DCM_E_INVALIDKEY" end */
/* Box: "DCM_E_EXCEEDNUMBEROFATTEMPTS" begin */
#ifndef DCM_E_EXCEEDNUMBEROFATTEMPTS
#define DCM_E_EXCEEDNUMBEROFATTEMPTS (54U)
#endif /* !DCM_E_EXCEEDNUMBEROFATTEMPTS */
/* Box: "DCM_E_EXCEEDNUMBEROFATTEMPTS" end */
/* Box: "DCM_E_REQUIREDTIMEDELAYNOTEXPIRED" begin */
#ifndef DCM_E_REQUIREDTIMEDELAYNOTEXPIRED
#define DCM_E_REQUIREDTIMEDELAYNOTEXPIRED (55U)
#endif /* !DCM_E_REQUIREDTIMEDELAYNOTEXPIRED */
/* Box: "DCM_E_REQUIREDTIMEDELAYNOTEXPIRED" end */
/* Box: "DCM_E_UPLOADDOWNLOADNOTACCEPTED" begin */
#ifndef DCM_E_UPLOADDOWNLOADNOTACCEPTED
#define DCM_E_UPLOADDOWNLOADNOTACCEPTED (112U)
#endif /* !DCM_E_UPLOADDOWNLOADNOTACCEPTED */
/* Box: "DCM_E_UPLOADDOWNLOADNOTACCEPTED" end */
/* Box: "DCM_E_TRANSFERDATASUSPENDED" begin */
#ifndef DCM_E_TRANSFERDATASUSPENDED
#define DCM_E_TRANSFERDATASUSPENDED (113U)
#endif /* !DCM_E_TRANSFERDATASUSPENDED */
/* Box: "DCM_E_TRANSFERDATASUSPENDED" end */
/* Box: "DCM_E_GENERALPROGRAMMINGFAILURE" begin */
#ifndef DCM_E_GENERALPROGRAMMINGFAILURE
#define DCM_E_GENERALPROGRAMMINGFAILURE (114U)
#endif /* !DCM_E_GENERALPROGRAMMINGFAILURE */
/* Box: "DCM_E_GENERALPROGRAMMINGFAILURE" end */
/* Box: "DCM_E_WRONGBLOCKSEQUENCECOUNTER" begin */
#ifndef DCM_E_WRONGBLOCKSEQUENCECOUNTER
#define DCM_E_WRONGBLOCKSEQUENCECOUNTER (115U)
#endif /* !DCM_E_WRONGBLOCKSEQUENCECOUNTER */
/* Box: "DCM_E_WRONGBLOCKSEQUENCECOUNTER" end */
/* Box: "DCM_E_SUBFUNCTIONNOTSUPPORTEDINACTIVESESSION" begin */
#ifndef DCM_E_SUBFUNCTIONNOTSUPPORTEDINACTIVESESSION
#define DCM_E_SUBFUNCTIONNOTSUPPORTEDINACTIVESESSION (126U)
#endif /* !DCM_E_SUBFUNCTIONNOTSUPPORTEDINACTIVESESSION */
/* Box: "DCM_E_SUBFUNCTIONNOTSUPPORTEDINACTIVESESSION" end */
/* Box: "DCM_E_SERVICENOTSUPPORTEDINACTIVESESSION" begin */
#ifndef DCM_E_SERVICENOTSUPPORTEDINACTIVESESSION
#define DCM_E_SERVICENOTSUPPORTEDINACTIVESESSION (127U)
#endif /* !DCM_E_SERVICENOTSUPPORTEDINACTIVESESSION */
/* Box: "DCM_E_SERVICENOTSUPPORTEDINACTIVESESSION" end */
/* Box: "DCM_E_RPMTOOHIGH" begin */
#ifndef DCM_E_RPMTOOHIGH
#define DCM_E_RPMTOOHIGH (129U)
#endif /* !DCM_E_RPMTOOHIGH */
/* Box: "DCM_E_RPMTOOHIGH" end */
/* Box: "DCM_E_RPMTOOLOW" begin */
#ifndef DCM_E_RPMTOOLOW
#define DCM_E_RPMTOOLOW (130U)
#endif /* !DCM_E_RPMTOOLOW */
/* Box: "DCM_E_RPMTOOLOW" end */
/* Box: "DCM_E_ENGINEISRUNNING" begin */
#ifndef DCM_E_ENGINEISRUNNING
#define DCM_E_ENGINEISRUNNING (131U)
#endif /* !DCM_E_ENGINEISRUNNING */
/* Box: "DCM_E_ENGINEISRUNNING" end */
/* Box: "DCM_E_ENGINEISNOTRUNNING" begin */
#ifndef DCM_E_ENGINEISNOTRUNNING
#define DCM_E_ENGINEISNOTRUNNING (132U)
#endif /* !DCM_E_ENGINEISNOTRUNNING */
/* Box: "DCM_E_ENGINEISNOTRUNNING" end */
/* Box: "DCM_E_ENGINERUNTIMETOOLOW" begin */
#ifndef DCM_E_ENGINERUNTIMETOOLOW
#define DCM_E_ENGINERUNTIMETOOLOW (133U)
#endif /* !DCM_E_ENGINERUNTIMETOOLOW */
/* Box: "DCM_E_ENGINERUNTIMETOOLOW" end */
/* Box: "DCM_E_TEMPERATURETOOHIGH" begin */
#ifndef DCM_E_TEMPERATURETOOHIGH
#define DCM_E_TEMPERATURETOOHIGH (134U)
#endif /* !DCM_E_TEMPERATURETOOHIGH */
/* Box: "DCM_E_TEMPERATURETOOHIGH" end */
/* Box: "DCM_E_TEMPERATURETOOLOW" begin */
#ifndef DCM_E_TEMPERATURETOOLOW
#define DCM_E_TEMPERATURETOOLOW (135U)
#endif /* !DCM_E_TEMPERATURETOOLOW */
/* Box: "DCM_E_TEMPERATURETOOLOW" end */
/* Box: "DCM_E_VEHICLESPEEDTOOHIGH" begin */
#ifndef DCM_E_VEHICLESPEEDTOOHIGH
#define DCM_E_VEHICLESPEEDTOOHIGH (136U)
#endif /* !DCM_E_VEHICLESPEEDTOOHIGH */
/* Box: "DCM_E_VEHICLESPEEDTOOHIGH" end */
/* Box: "DCM_E_VEHICLESPEEDTOOLOW" begin */
#ifndef DCM_E_VEHICLESPEEDTOOLOW
#define DCM_E_VEHICLESPEEDTOOLOW (137U)
#endif /* !DCM_E_VEHICLESPEEDTOOLOW */
/* Box: "DCM_E_VEHICLESPEEDTOOLOW" end */
/* Box: "DCM_E_THROTTLE_PEDALTOOHIGH" begin */
#ifndef DCM_E_THROTTLE_PEDALTOOHIGH
#define DCM_E_THROTTLE_PEDALTOOHIGH (138U)
#endif /* !DCM_E_THROTTLE_PEDALTOOHIGH */
/* Box: "DCM_E_THROTTLE_PEDALTOOHIGH" end */
/* Box: "DCM_E_THROTTLE_PEDALTOOLOW" begin */
#ifndef DCM_E_THROTTLE_PEDALTOOLOW
#define DCM_E_THROTTLE_PEDALTOOLOW (139U)
#endif /* !DCM_E_THROTTLE_PEDALTOOLOW */
/* Box: "DCM_E_THROTTLE_PEDALTOOLOW" end */
/* Box: "DCM_E_TRANSMISSIONRANGENOTINNEUTRAL" begin */
#ifndef DCM_E_TRANSMISSIONRANGENOTINNEUTRAL
#define DCM_E_TRANSMISSIONRANGENOTINNEUTRAL (140U)
#endif /* !DCM_E_TRANSMISSIONRANGENOTINNEUTRAL */
/* Box: "DCM_E_TRANSMISSIONRANGENOTINNEUTRAL" end */
/* Box: "DCM_E_TRANSMISSIONRANGENOTINGEAR" begin */
#ifndef DCM_E_TRANSMISSIONRANGENOTINGEAR
#define DCM_E_TRANSMISSIONRANGENOTINGEAR (141U)
#endif /* !DCM_E_TRANSMISSIONRANGENOTINGEAR */
/* Box: "DCM_E_TRANSMISSIONRANGENOTINGEAR" end */
/* Box: "DCM_E_BRAKESWITCH_NOTCLOSED" begin */
#ifndef DCM_E_BRAKESWITCH_NOTCLOSED
#define DCM_E_BRAKESWITCH_NOTCLOSED (143U)
#endif /* !DCM_E_BRAKESWITCH_NOTCLOSED */
/* Box: "DCM_E_BRAKESWITCH_NOTCLOSED" end */
/* Box: "DCM_E_SHIFTERLEVERNOTINPARK" begin */
#ifndef DCM_E_SHIFTERLEVERNOTINPARK
#define DCM_E_SHIFTERLEVERNOTINPARK (144U)
#endif /* !DCM_E_SHIFTERLEVERNOTINPARK */
/* Box: "DCM_E_SHIFTERLEVERNOTINPARK" end */
/* Box: "DCM_E_TORQUECONVERTERCLUTCHLOCKED" begin */
#ifndef DCM_E_TORQUECONVERTERCLUTCHLOCKED
#define DCM_E_TORQUECONVERTERCLUTCHLOCKED (145U)
#endif /* !DCM_E_TORQUECONVERTERCLUTCHLOCKED */
/* Box: "DCM_E_TORQUECONVERTERCLUTCHLOCKED" end */
/* Box: "DCM_E_VOLTAGETOOHIGH" begin */
#ifndef DCM_E_VOLTAGETOOHIGH
#define DCM_E_VOLTAGETOOHIGH (146U)
#endif /* !DCM_E_VOLTAGETOOHIGH */
/* Box: "DCM_E_VOLTAGETOOHIGH" end */
/* Box: "DCM_E_VOLTAGETOOLOW" begin */
#ifndef DCM_E_VOLTAGETOOLOW
#define DCM_E_VOLTAGETOOLOW (147U)
#endif /* !DCM_E_VOLTAGETOOLOW */
/* Box: "DCM_E_VOLTAGETOOLOW" end */
/* Box: /AUTOSAR_Dcm/ImplementationDataTypes/Dcm_NegativeResponseCodeType end */

/* Box: /AUTOSAR_Dcm/ImplementationDataTypes/Dcm_OpStatusType begin */
/* Box: "DCM_INITIAL" begin */
#ifndef DCM_INITIAL
#define DCM_INITIAL (0U)
#endif /* !DCM_INITIAL */
/* Box: "DCM_INITIAL" end */
/* Box: "DCM_PENDING" begin */
#ifndef DCM_PENDING
#define DCM_PENDING (1U)
#endif /* !DCM_PENDING */
/* Box: "DCM_PENDING" end */
/* Box: "DCM_CANCEL" begin */
#ifndef DCM_CANCEL
#define DCM_CANCEL (2U)
#endif /* !DCM_CANCEL */
/* Box: "DCM_CANCEL" end */
/* Box: "DCM_FORCE_RCRRP_OK" begin */
#ifndef DCM_FORCE_RCRRP_OK
#define DCM_FORCE_RCRRP_OK (3U)
#endif /* !DCM_FORCE_RCRRP_OK */
/* Box: "DCM_FORCE_RCRRP_OK" end */
/* Box: /AUTOSAR_Dcm/ImplementationDataTypes/Dcm_OpStatusType end */

/* Box: /AUTOSAR_Dcm/ImplementationDataTypes/Dcm_ProtocolType begin */
/* Box: "DCM_OBD_ON_CAN" begin */
#ifndef DCM_OBD_ON_CAN
#define DCM_OBD_ON_CAN (0U)
#endif /* !DCM_OBD_ON_CAN */
/* Box: "DCM_OBD_ON_CAN" end */
/* Box: "DCM_OBD_ON_FLEXRAY" begin */
#ifndef DCM_OBD_ON_FLEXRAY
#define DCM_OBD_ON_FLEXRAY (1U)
#endif /* !DCM_OBD_ON_FLEXRAY */
/* Box: "DCM_OBD_ON_FLEXRAY" end */
/* Box: "DCM_OBD_ON_IP" begin */
#ifndef DCM_OBD_ON_IP
#define DCM_OBD_ON_IP (2U)
#endif /* !DCM_OBD_ON_IP */
/* Box: "DCM_OBD_ON_IP" end */
/* Box: "DCM_UDS_ON_CAN" begin */
#ifndef DCM_UDS_ON_CAN
#define DCM_UDS_ON_CAN (3U)
#endif /* !DCM_UDS_ON_CAN */
/* Box: "DCM_UDS_ON_CAN" end */
/* Box: "DCM_UDS_ON_FLEXRAY" begin */
#ifndef DCM_UDS_ON_FLEXRAY
#define DCM_UDS_ON_FLEXRAY (4U)
#endif /* !DCM_UDS_ON_FLEXRAY */
/* Box: "DCM_UDS_ON_FLEXRAY" end */
/* Box: "DCM_UDS_ON_IP" begin */
#ifndef DCM_UDS_ON_IP
#define DCM_UDS_ON_IP (5U)
#endif /* !DCM_UDS_ON_IP */
/* Box: "DCM_UDS_ON_IP" end */
/* Box: "DCM_ROE_ON_CAN" begin */
#ifndef DCM_ROE_ON_CAN
#define DCM_ROE_ON_CAN (6U)
#endif /* !DCM_ROE_ON_CAN */
/* Box: "DCM_ROE_ON_CAN" end */
/* Box: "DCM_ROE_ON_FLEXRAY" begin */
#ifndef DCM_ROE_ON_FLEXRAY
#define DCM_ROE_ON_FLEXRAY (7U)
#endif /* !DCM_ROE_ON_FLEXRAY */
/* Box: "DCM_ROE_ON_FLEXRAY" end */
/* Box: "DCM_ROE_ON_IP" begin */
#ifndef DCM_ROE_ON_IP
#define DCM_ROE_ON_IP (8U)
#endif /* !DCM_ROE_ON_IP */
/* Box: "DCM_ROE_ON_IP" end */
/* Box: "DCM_PERIODICTRANS_ON_CAN" begin */
#ifndef DCM_PERIODICTRANS_ON_CAN
#define DCM_PERIODICTRANS_ON_CAN (9U)
#endif /* !DCM_PERIODICTRANS_ON_CAN */
/* Box: "DCM_PERIODICTRANS_ON_CAN" end */
/* Box: "DCM_PERIODICTRANS_ON_FLEXRAY" begin */
#ifndef DCM_PERIODICTRANS_ON_FLEXRAY
#define DCM_PERIODICTRANS_ON_FLEXRAY (10U)
#endif /* !DCM_PERIODICTRANS_ON_FLEXRAY */
/* Box: "DCM_PERIODICTRANS_ON_FLEXRAY" end */
/* Box: "DCM_PERIODICTRANS_ON_IP" begin */
#ifndef DCM_PERIODICTRANS_ON_IP
#define DCM_PERIODICTRANS_ON_IP (11U)
#endif /* !DCM_PERIODICTRANS_ON_IP */
/* Box: "DCM_PERIODICTRANS_ON_IP" end */
/* Box: "DCM_ACEA_ON_CAN" begin */
#ifndef DCM_ACEA_ON_CAN
#define DCM_ACEA_ON_CAN (12U)
#endif /* !DCM_ACEA_ON_CAN */
/* Box: "DCM_ACEA_ON_CAN" end */
/* Box: "DCM_NO_ACTIVE_PROTOCOL" begin */
#ifndef DCM_NO_ACTIVE_PROTOCOL
#define DCM_NO_ACTIVE_PROTOCOL (12U)
#endif /* !DCM_NO_ACTIVE_PROTOCOL */
/* Box: "DCM_NO_ACTIVE_PROTOCOL" end */
/* Box: "DCM_KWP_ON_CAN" begin */
#ifndef DCM_KWP_ON_CAN
#define DCM_KWP_ON_CAN (129U)
#endif /* !DCM_KWP_ON_CAN */
/* Box: "DCM_KWP_ON_CAN" end */
/* Box: "DCM_ACEA_ON_FLEXRAY" begin */
#ifndef DCM_ACEA_ON_FLEXRAY
#define DCM_ACEA_ON_FLEXRAY (144U)
#endif /* !DCM_ACEA_ON_FLEXRAY */
/* Box: "DCM_ACEA_ON_FLEXRAY" end */
/* Box: "DCM_KWP_ON_KLINE" begin */
#ifndef DCM_KWP_ON_KLINE
#define DCM_KWP_ON_KLINE (145U)
#endif /* !DCM_KWP_ON_KLINE */
/* Box: "DCM_KWP_ON_KLINE" end */
/* Box: "DCM_CARB_ON_KLINE" begin */
#ifndef DCM_CARB_ON_KLINE
#define DCM_CARB_ON_KLINE (160U)
#endif /* !DCM_CARB_ON_KLINE */
/* Box: "DCM_CARB_ON_KLINE" end */
/* Box: "DCM_OBD_ON_KLINE" begin */
#ifndef DCM_OBD_ON_KLINE
#define DCM_OBD_ON_KLINE (161U)
#endif /* !DCM_OBD_ON_KLINE */
/* Box: "DCM_OBD_ON_KLINE" end */
/* Box: "DCM_SUPPLIER_1" begin */
#ifndef DCM_SUPPLIER_1
#define DCM_SUPPLIER_1 (240U)
#endif /* !DCM_SUPPLIER_1 */
/* Box: "DCM_SUPPLIER_1" end */
/* Box: "DCM_SUPPLIER_2" begin */
#ifndef DCM_SUPPLIER_2
#define DCM_SUPPLIER_2 (241U)
#endif /* !DCM_SUPPLIER_2 */
/* Box: "DCM_SUPPLIER_2" end */
/* Box: "DCM_SUPPLIER_3" begin */
#ifndef DCM_SUPPLIER_3
#define DCM_SUPPLIER_3 (242U)
#endif /* !DCM_SUPPLIER_3 */
/* Box: "DCM_SUPPLIER_3" end */
/* Box: "DCM_SUPPLIER_4" begin */
#ifndef DCM_SUPPLIER_4
#define DCM_SUPPLIER_4 (243U)
#endif /* !DCM_SUPPLIER_4 */
/* Box: "DCM_SUPPLIER_4" end */
/* Box: "DCM_SUPPLIER_5" begin */
#ifndef DCM_SUPPLIER_5
#define DCM_SUPPLIER_5 (244U)
#endif /* !DCM_SUPPLIER_5 */
/* Box: "DCM_SUPPLIER_5" end */
/* Box: "DCM_SUPPLIER_6" begin */
#ifndef DCM_SUPPLIER_6
#define DCM_SUPPLIER_6 (245U)
#endif /* !DCM_SUPPLIER_6 */
/* Box: "DCM_SUPPLIER_6" end */
/* Box: "DCM_SUPPLIER_7" begin */
#ifndef DCM_SUPPLIER_7
#define DCM_SUPPLIER_7 (246U)
#endif /* !DCM_SUPPLIER_7 */
/* Box: "DCM_SUPPLIER_7" end */
/* Box: "DCM_SUPPLIER_8" begin */
#ifndef DCM_SUPPLIER_8
#define DCM_SUPPLIER_8 (247U)
#endif /* !DCM_SUPPLIER_8 */
/* Box: "DCM_SUPPLIER_8" end */
/* Box: "DCM_SUPPLIER_9" begin */
#ifndef DCM_SUPPLIER_9
#define DCM_SUPPLIER_9 (248U)
#endif /* !DCM_SUPPLIER_9 */
/* Box: "DCM_SUPPLIER_9" end */
/* Box: "DCM_SUPPLIER_10" begin */
#ifndef DCM_SUPPLIER_10
#define DCM_SUPPLIER_10 (249U)
#endif /* !DCM_SUPPLIER_10 */
/* Box: "DCM_SUPPLIER_10" end */
/* Box: "DCM_SUPPLIER_11" begin */
#ifndef DCM_SUPPLIER_11
#define DCM_SUPPLIER_11 (250U)
#endif /* !DCM_SUPPLIER_11 */
/* Box: "DCM_SUPPLIER_11" end */
/* Box: "DCM_SUPPLIER_12" begin */
#ifndef DCM_SUPPLIER_12
#define DCM_SUPPLIER_12 (251U)
#endif /* !DCM_SUPPLIER_12 */
/* Box: "DCM_SUPPLIER_12" end */
/* Box: "DCM_SUPPLIER_13" begin */
#ifndef DCM_SUPPLIER_13
#define DCM_SUPPLIER_13 (252U)
#endif /* !DCM_SUPPLIER_13 */
/* Box: "DCM_SUPPLIER_13" end */
/* Box: "DCM_SUPPLIER_14" begin */
#ifndef DCM_SUPPLIER_14
#define DCM_SUPPLIER_14 (253U)
#endif /* !DCM_SUPPLIER_14 */
/* Box: "DCM_SUPPLIER_14" end */
/* Box: "DCM_SUPPLIER_15" begin */
#ifndef DCM_SUPPLIER_15
#define DCM_SUPPLIER_15 (254U)
#endif /* !DCM_SUPPLIER_15 */
/* Box: "DCM_SUPPLIER_15" end */
/* Box: /AUTOSAR_Dcm/ImplementationDataTypes/Dcm_ProtocolType end */

/* Box: /AUTOSAR_Dcm/ImplementationDataTypes/Dcm_SecLevelType begin */
/* Box: "DCM_SEC_LEV_L1" begin */
#ifndef DCM_SEC_LEV_L1
#define DCM_SEC_LEV_L1 (1U)
#endif /* !DCM_SEC_LEV_L1 */
/* Box: "DCM_SEC_LEV_L1" end */
/* Box: "DSP_SEC_LEV_L2" begin */
#ifndef DSP_SEC_LEV_L2
#define DSP_SEC_LEV_L2 (2U)
#endif /* !DSP_SEC_LEV_L2 */
/* Box: "DSP_SEC_LEV_L2" end */
/* Box: "DSP_SEC_LEV_L3" begin */
#ifndef DSP_SEC_LEV_L3
#define DSP_SEC_LEV_L3 (3U)
#endif /* !DSP_SEC_LEV_L3 */
/* Box: "DSP_SEC_LEV_L3" end */
/* Box: "DSP_SEC_LEV_L4" begin */
#ifndef DSP_SEC_LEV_L4
#define DSP_SEC_LEV_L4 (4U)
#endif /* !DSP_SEC_LEV_L4 */
/* Box: "DSP_SEC_LEV_L4" end */
/* Box: /AUTOSAR_Dcm/ImplementationDataTypes/Dcm_SecLevelType end */

/* Box: /AUTOSAR_Dcm/ImplementationDataTypes/Dcm_SesCtrlType begin */
/* Box: "DCM_DEFAULT_SESSION" begin */
#ifndef DCM_DEFAULT_SESSION
#define DCM_DEFAULT_SESSION (1U)
#endif /* !DCM_DEFAULT_SESSION */
/* Box: "DCM_DEFAULT_SESSION" end */
/* Box: "DCM_PROGRAMMING_SESSION" begin */
#ifndef DCM_PROGRAMMING_SESSION
#define DCM_PROGRAMMING_SESSION (2U)
#endif /* !DCM_PROGRAMMING_SESSION */
/* Box: "DCM_PROGRAMMING_SESSION" end */
/* Box: "DCM_EXTENDED_DIAGNOSTIC_SESSION" begin */
#ifndef DCM_EXTENDED_DIAGNOSTIC_SESSION
#define DCM_EXTENDED_DIAGNOSTIC_SESSION (3U)
#endif /* !DCM_EXTENDED_DIAGNOSTIC_SESSION */
/* Box: "DCM_EXTENDED_DIAGNOSTIC_SESSION" end */
/* Box: "DCM_SAFETY_SYSTEM_DIAGNOSTIC_SESSION" begin */
#ifndef DCM_SAFETY_SYSTEM_DIAGNOSTIC_SESSION
#define DCM_SAFETY_SYSTEM_DIAGNOSTIC_SESSION (4U)
#endif /* !DCM_SAFETY_SYSTEM_DIAGNOSTIC_SESSION */
/* Box: "DCM_SAFETY_SYSTEM_DIAGNOSTIC_SESSION" end */
/* Box: "CODING_SESSION" begin */
#ifndef CODING_SESSION
#define CODING_SESSION (65U)
#endif /* !CODING_SESSION */
/* Box: "CODING_SESSION" end */
/* Box: /AUTOSAR_Dcm/ImplementationDataTypes/Dcm_SesCtrlType end */

/* Box: /AUTOSAR_Platform/ImplementationDataTypes/boolean begin */
/* Box: "FALSE" begin */
#ifndef FALSE
#define FALSE (0U)
#endif /* !FALSE */
/* Box: "FALSE" end */
/* Box: "TRUE" begin */
#ifndef TRUE
#define TRUE (1U)
#endif /* !TRUE */
/* Box: "TRUE" end */
/* Box: /AUTOSAR_Platform/ImplementationDataTypes/boolean end */
#endif /* !defined(RTE_CORE) */
/* END: SWC specific definitions */

#ifdef __cplusplus
} /* extern C */
#endif /* __cplusplus */

#endif /* !RTE_Dcm_TYPE_H */
