/** @file     SchM_Can_Type.h
  *
  * @brief    Basic Software Scheduler Module Interlink Types header file
  *
  * @note     AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
  *
  * @note     Generated by ETAS RTA-RTE
  * @note     Version 7.1.0 
  */

#ifndef SchM_Can_Type
#define SchM_Can_Type

#include "Rte_Type.h"
#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

/* BEGIN: BSW implementation specific types */
/* END: BSW implementation specific types */

/* BEGIN: BSW implementation specific definitions */
/* END: BSW implementation specific definitions */


#ifdef __cplusplus
} /* extern C */
#endif /* __cplusplus */

#endif /* !SchM_Can_Type */
