/******************************************************************************/
/*                                                                            */
/* !Layer           : STD                                                     */
/*                                                                            */
/* !Component       : MEMMAP                                                  */
/* !Description     : MEMMAP Configuration                                    */
/*                                                                            */
/* !File            : DEVHAL_MEMMAP.H                                          */
/*                                                                            */
/* !Scope           : Public                                                  */
/*                                                                            */
/* !Target          :                                                         */
/*                                                                            */
/* !Vendor          : invt                                                    */
/*                                                                            */
/* Coding language  : C                                                       */
/*                                                                            */
/* COPYRIGHT 2009 invt                                                        */
/* all rights reserved                                                        */
/*                                                                            */
/******************************************************************************/
/* SVN Information                                                           */
/* $Archive::                                                                $*/
/* $Revision::            $$Author::                  $$Date::               $*/
/******************************************************************************/
/* 11/09/22, 19:32:04: generated by Genecode  v2.6.0.0                        */
/* From Source Template : MSN_MEMMAP_H.TPL                                    */
/******************************************************************************/



/******************************************************************************/
/*          MEMMAP selected mode:  SAFE                                       */
/******************************************************************************/
#define MEMMAP_ERROR

/* The following if is used only due to automatic generation */
#if !defined MEMMAP_ERROR

/* Project section mappings */
/* !Comment: DEVHAL Section allocation */
#elif defined   DEVHAL_START_SEC_CODE
   #undef  DEVHAL_START_SEC_CODE
   #define START_SEC_CODE_SECTION
#elif defined   DEVHAL_STOP_SEC_CODE
   #undef  DEVHAL_STOP_SEC_CODE
   #define STOP_SEC_CODE_SECTION

#elif defined   DEVHAL_START_SEC_CALIB_UNSPECIFIED
   #undef  DEVHAL_START_SEC_CALIB_UNSPECIFIED
   #define START_SEC_CALIB_UNSPECIFIED_SECTION
#elif defined   DEVHAL_STOP_SEC_CALIB_UNSPECIFIED
   #undef  DEVHAL_STOP_SEC_CALIB_UNSPECIFIED
   #define STOP_SEC_CALIB_UNSPECIFIED_SECTION

#elif defined   DEVHAL_START_SEC_VAR_INIT_UNSPECIFIED
   #undef  DEVHAL_START_SEC_VAR_INIT_UNSPECIFIED
   #define START_SEC_VAR_INIT_UNSPECIFIED_SECTION
#elif defined   DEVHAL_STOP_SEC_VAR_INIT_UNSPECIFIED
   #undef  DEVHAL_STOP_SEC_VAR_INIT_UNSPECIFIED
   #define STOP_SEC_VAR_INIT_UNSPECIFIED_SECTION

#elif defined   DEVHAL_START_SEC_VAR_UNSPECIFIED
   #undef  DEVHAL_START_SEC_VAR_UNSPECIFIED
   #define START_SEC_VAR_UNSPECIFIED_SECTION
#elif defined   DEVHAL_STOP_SEC_VAR_UNSPECIFIED
   #undef  DEVHAL_STOP_SEC_VAR_UNSPECIFIED
   #define STOP_SEC_VAR_UNSPECIFIED_SECTION

#elif defined   DEVHAL_START_SEC_VAR_CLEARED_BOOLEAN
   #undef  DEVHAL_START_SEC_VAR_CLEARED_BOOLEAN
   #define START_SEC_VAR_CLEARED_BOOLEAN_SECTION
#elif defined   DEVHAL_STOP_SEC_VAR_CLEARED_BOOLEAN
   #undef  DEVHAL_STOP_SEC_VAR_CLEARED_BOOLEAN
   #define STOP_SEC_VAR_CLEARED_BOOLEAN_SECTION

#elif defined   DEVHAL_START_SEC_VAR_CLEARED_8BIT
   #undef  DEVHAL_START_SEC_VAR_CLEARED_8BIT
   #define START_SEC_VAR_CLEARED_8BIT_SECTION
#elif defined   DEVHAL_STOP_SEC_VAR_CLEARED_8BIT
   #undef  DEVHAL_STOP_SEC_VAR_CLEARED_8BIT
   #define STOP_SEC_VAR_CLEARED_8BIT_SECTION


#endif

/* ECU specific section mappings */
#ifndef MEMMAP_START_DONE

/* The following if is used only due to automatic generation */

#if FALSE
/* !Comment: SEC_CODE Start Section treatment */
   #elif defined   START_SEC_CODE_SECTION
	  

      #pragma section ".text" ax

      #undef  MEMMAP_ERROR
      #define MEMMAP_START_DONE

/* !Comment: SEC_CALIB_UNSPECIFIED Start Section treatment */
   #elif defined   START_SEC_CALIB_UNSPECIFIED_SECTION
	  

      #pragma section ".calib" a

      #undef  MEMMAP_ERROR
      #define MEMMAP_START_DONE

/* !Comment: SEC_VAR_INIT_UNSPECIFIED Start Section treatment */
   #elif defined   START_SEC_VAR_INIT_UNSPECIFIED_SECTION
	  

      #pragma section ".data" aw

      #undef  MEMMAP_ERROR
      #define MEMMAP_START_DONE

/* !Comment: SEC_VAR_UNSPECIFIED Start Section treatment */
   #elif defined   START_SEC_VAR_UNSPECIFIED_SECTION
	  
      #undef  MEMMAP_ERROR
      #define MEMMAP_START_DONE

/* !Comment: SEC_VAR_CLEARED_BOOLEAN Start Section treatment */
   #elif defined   START_SEC_VAR_CLEARED_BOOLEAN_SECTION
	  

      #pragma section ".bss" awB

      #undef  MEMMAP_ERROR
      #define MEMMAP_START_DONE

/* !Comment: SEC_VAR_CLEARED_8BIT Start Section treatment */
   #elif defined   START_SEC_VAR_CLEARED_8BIT_SECTION
	  

      #pragma section ".bss" awB

      #undef  MEMMAP_ERROR
      #define MEMMAP_START_DONE


   #endif

#else   /* if MEMMAP_START_DONE is not defined */

/* The following if is used only due to automatic generation */

#if FALSE
/* !Comment: SEC_CODE Stop Section treatment */
   #elif defined   STOP_SEC_CODE_SECTION && defined  START_SEC_CODE_SECTION
	  

      #pragma section

      #undef START_SEC_CODE_SECTION
      #undef STOP_SEC_CODE_SECTION
      #undef MEMMAP_ERROR
      #undef MEMMAP_START_DONE

/* !Comment: SEC_CALIB_UNSPECIFIED Stop Section treatment */
   #elif defined   STOP_SEC_CALIB_UNSPECIFIED_SECTION && defined  START_SEC_CALIB_UNSPECIFIED_SECTION
	  

      #pragma section

      #undef START_SEC_CALIB_UNSPECIFIED_SECTION
      #undef STOP_SEC_CALIB_UNSPECIFIED_SECTION
      #undef MEMMAP_ERROR
      #undef MEMMAP_START_DONE

/* !Comment: SEC_VAR_INIT_UNSPECIFIED Stop Section treatment */
   #elif defined   STOP_SEC_VAR_INIT_UNSPECIFIED_SECTION && defined  START_SEC_VAR_INIT_UNSPECIFIED_SECTION
	  

      #pragma section

      #undef START_SEC_VAR_INIT_UNSPECIFIED_SECTION
      #undef STOP_SEC_VAR_INIT_UNSPECIFIED_SECTION
      #undef MEMMAP_ERROR
      #undef MEMMAP_START_DONE

/* !Comment: SEC_VAR_UNSPECIFIED Stop Section treatment */
   #elif defined   STOP_SEC_VAR_UNSPECIFIED_SECTION && defined  START_SEC_VAR_UNSPECIFIED_SECTION
	  
      #undef START_SEC_VAR_UNSPECIFIED_SECTION
      #undef STOP_SEC_VAR_UNSPECIFIED_SECTION
      #undef MEMMAP_ERROR
      #undef MEMMAP_START_DONE

/* !Comment: SEC_VAR_CLEARED_BOOLEAN Stop Section treatment */
   #elif defined   STOP_SEC_VAR_CLEARED_BOOLEAN_SECTION && defined  START_SEC_VAR_CLEARED_BOOLEAN_SECTION
	  

      #pragma section

      #undef START_SEC_VAR_CLEARED_BOOLEAN_SECTION
      #undef STOP_SEC_VAR_CLEARED_BOOLEAN_SECTION
      #undef MEMMAP_ERROR
      #undef MEMMAP_START_DONE

/* !Comment: SEC_VAR_CLEARED_8BIT Stop Section treatment */
   #elif defined   STOP_SEC_VAR_CLEARED_8BIT_SECTION && defined  START_SEC_VAR_CLEARED_8BIT_SECTION
	  

      #pragma section

      #undef START_SEC_VAR_CLEARED_8BIT_SECTION
      #undef STOP_SEC_VAR_CLEARED_8BIT_SECTION
      #undef MEMMAP_ERROR
      #undef MEMMAP_START_DONE


   #endif
#endif

#if defined MEMMAP_ERROR
   #error MEMMAP-E201 : Bad memory allocation into DEVHAL_MemMap.h
#endif


/*------------------------------- end of file --------------------------------*/

