


/*
 ***************************************************************************************************
 * Includes
 ***************************************************************************************************
 */

#include "ComM_Priv.h"

/*
 ***************************************************************************************************
 * Defines
 ***************************************************************************************************
 */

/*
 ***************************************************************************************************
 * Type definitions
 ***************************************************************************************************
 */

/*
 ***************************************************************************************************
 * Variables
 ***************************************************************************************************
 */

#define COMM_START_SEC_CODE
#include "ComM_MemMap.h"


/********************************************************************************************
 * Function name    : ComM_GetCurrentComMode
 * Syntax           : Std_ReturnType ComM_GetCurrentComMode
 *                   (
 *                     ComM_UserHandleType User, ComM_ModeType* ComMode
 *                     )
 * Description      : Function to query the current Communication Mode.
 * Parameters       : User -> Handle of the user who requests a mode
 *                    ComMode -> ComM_ModeType
 * Return value     : E_OK:Succesfully returned Communication Mode from Bus State Manager
 *                    E_NOT_OK: Return of Communication Mode from Bus State Manager failed
 *                    COMM_E_UNINIT: ComM not initialized
 **********************************************************************************************/

/* MR12 RULE 8.3 VIOLATION:Two declarations exists for this api. One is in ComM.h & another generated by RTE. Hence,the difference in identifiers.*/
Std_ReturnType ComM_GetCurrentComMode(ComM_UserHandleType User, ComM_ModeType * ComMode)

{

    /***********************************************DET STARTS HERE****************************************/
    /* Local variable initialization */
    /***********************************************DET STARTS HERE****************************************/
    #if (COMM_DEV_ERROR_DETECT != STD_OFF)
    /* DET check for ComM not initialized */
    if (ComM_GlobalStruct.ComM_InitStatus_en != COMM_INIT)
    {
        (void)Det_ReportError(COMM_MODULE_ID,COMM_INSTANCE_ID,COMM_GET_CUR_COMMODE_APIID,COMM_E_NOT_INITED);
        return COMM_E_NOT_INITIALIZED;
    }

    /* DET check for pointer passed to be a NULL pointer */
    if (ComMode==NULL_PTR)
    {
        (void)Det_ReportError(COMM_MODULE_ID,COMM_INSTANCE_ID,COMM_GET_CUR_COMMODE_APIID,COMM_E_WRONG_PARAMETERS);
        return E_NOT_OK;
    }

    /* DET  for Invalid user */
    if ( ComM_Prv_ValidateUserId(User) == FALSE)
    {
        (void)Det_ReportError(COMM_MODULE_ID,COMM_INSTANCE_ID,COMM_GET_CUR_COMMODE_APIID,COMM_E_WRONG_PARAMETERS);
        return E_NOT_OK;
    }
    #endif  /*  #if (COMM_DEV_ERROR_DETECT != STD_OFF)  */
    /*************************************DET ENDS HERE*************************************************/

    *ComMode = ComM_Prv_getLeastBusSmMode(User);
    return E_OK;
}

#define COMM_STOP_SEC_CODE
#include "ComM_MemMap.h"

