/******************************************************************************/
/*                                                                            */
/* !Layer           : SRVL                                                    */
/*                                                                            */
/* !Component       : ESM                                                     */
/* !Description     : StateFlow of ESM component                              */
/*                                                                            */
/* !File            : ESM_DAT.H                                               */
/*                                                                            */
/* !Scope           : Public                                                  */
/*                                                                            */
/* !Target          : All                                                     */
/*                                                                            */
/* !Vendor          : invt                                                    */
/*                                                                            */
/* Coding language  : C                                                       */
/*                                                                            */
/* COPYRIGHT 2007 invt                                                        */
/* all rights reserved                                                        */
/*                                                                            */
/******************************************************************************/
/** 10/27/22, 09:10:37: generated by Genecode v2.6.0.0                        */
/* From Source Template : STFSRV_DAT_H.TPL                                    */
/******************************************************************************/

#ifndef ESM_DAT_H
#define ESM_DAT_H

#include "Std_Types.h"
#include "stfsrv_Includes.h"
#include "stfsrv_types.h"
#include "esm.h"
#include "esm_l.h"


/******************************************************************************/
/* DEFINES                                                                    */
/******************************************************************************/

/*----------------------------------------------------------------------------*/
/* ESM Stateflows configuration                                               */
/*----------------------------------------------------------------------------*/
/* Stateflows :  ECU_STATE <=> ESM_STF0        */
/*----------------------------------------------------------------------------*/


#define ESM_udtSTATEFLOW_NB   1

#define ESM_STFSRV_MAIN   ESM_STF0  /* ECU_STATE */

/* ESM_ECU_STATE */

#define ESM_ESM_STF0_VAR            ESM_EcuState
#define ESM_ESM_STF0_INIT_STATE     ESM_ST0  /* STARTUP_I_MODE */
#define ESM_ESM_STF0_NB_STATE       5




/*----------------------------------------------------------------------------*/
/* ESM States declaration                                                   */
/*----------------------------------------------------------------------------*/
#define   ESM_STARTUP_I_MODE     1
#define   ESM_STARTUP_II_MODE     2
#define   ESM_OPERATIONAL_MODE     4
#define   ESM_POWERLATCH_MODE     8
#define   ESM_POWER_OFF_MODE     16


/*----------------------------------------------------------------------------*/
/* ESM States configuration                                                   */
/*----------------------------------------------------------------------------*/

#define ESM_ESM_ST0_VAL     ESM_STARTUP_I_MODE
#define ESM_ESM_ST1_VAL     ESM_STARTUP_II_MODE
#define ESM_ESM_ST2_VAL     ESM_OPERATIONAL_MODE
#define ESM_ESM_ST3_VAL     ESM_POWERLATCH_MODE
#define ESM_ESM_ST4_VAL     ESM_POWER_OFF_MODE





/*----------------------------------------------------------------------------*/
/* ESM Events configuration                                                   */
/*----------------------------------------------------------------------------*/
#define ESM_ON_SCHED_5MS_FUNC          ESM_vidOnESM_EV0
#define ESM_ON_GO2_STARTUP_I_FUNC          ESM_vidOnESM_EV1

#define GO2_STARTUP_I_EVENT            (uint16)(1 << 0)
#define GO2_STARTUP_II_EVENT            (uint16)(1 << 1)
#define GO2_OPERATIONAL_EVENT            (uint16)(1 << 2)
#define GO2_POWERLATCH_EVENT            (uint16)(1 << 3)
#define GO2_POWER_OFF_EVENT            (uint16)(1 << 4)

#define GO2_STARTUP_I_EVENT_ACTION          ESM_StpIState = ESM_SFT_STATE_1;
#define GO2_STARTUP_II_EVENT_ACTION          ESM_StpIINfState = ESM_SFT_STATE_1; ESM_StpIIFtState = ESM_SFT_STATE_1; ESM_PwrLFtState = ESM_SFT_STATE_1;
#define GO2_OPERATIONAL_EVENT_ACTION          ESM_OpNfState = ESM_SFT_STATE_1; ESM_OpFtState = ESM_SFT_STATE_1;
#define GO2_POWERLATCH_EVENT_ACTION          ESM_PwrLNfState = ESM_SFT_STATE_1; ESM_PwrLFtState = ESM_SFT_STATE_1;
#define GO2_POWER_OFF_EVENT_ACTION          ESM_PwrLNfState = ESM_SFT_STATE_15;

#define ESM_EXEC_OUT_EVENT_FUNC       ESM_vidExecOutEvent
#define ESM_OUT_EVENT_CARRIER    ESM_bfOutEventCarrier

/*----------------------------------------------------------------------------*/
/* ESM common data                                                            */
/*----------------------------------------------------------------------------*/

#define ESM_ON_EVENT_NO_ACTION   ESM_vidNoAction

/* Transition function for stateflow ECU_STATE on event SCHED_5MS */
#define ESM_ESM_STF0_ON_ESM_EV0_TRANS_PTR   ESM_pfTransESM_STF0OnESM_EV0Ptr


/* Transition function for stateflow ECU_STATE on event GO2_STARTUP_I */
#define ESM_ESM_STF0_ON_ESM_EV1_TRANS_PTR   ESM_pfTransESM_STF0OnESM_EV1Ptr


/* During function for stateflow ECU_STATE on event SCHED_5MS */
#define ESM_ESM_STF0_ON_ESM_EV0_DURING_PTR   ESM_pfDuringESM_STF0OnESM_EV0Ptr


/* During function for stateflow ECU_STATE on event GO2_STARTUP_I */
#define ESM_ESM_STF0_ON_ESM_EV1_DURING_PTR   ESM_pfDuringESM_STF0OnESM_EV1Ptr





/*----------------------------------------------------------------------------*/
/* ESM entry functions                                                        */
/*----------------------------------------------------------------------------*/

#define ESM_ESM_ST0_ENTRY             ESM_vidEntryESM_ST0   /* ESM_STARTUP_I_MODE */
#define ESM_ESM_ST1_ENTRY             ESM_vidEntryESM_ST1   /* ESM_STARTUP_II_MODE */
#define ESM_ESM_ST2_ENTRY             ESM_vidEntryESM_ST2   /* ESM_OPERATIONAL_MODE */
#define ESM_ESM_ST3_ENTRY             ESM_vidEntryESM_ST3   /* ESM_POWERLATCH_MODE */
#define ESM_ESM_ST4_ENTRY             ESM_vidEntryESM_ST4   /* ESM_POWER_OFF_MODE */


/*----------------------------------------------------------------------------*/
/* ESM during functions                                                       */
/*----------------------------------------------------------------------------*/

#define ESM_ESM_ST0_ON_ESM_EV0_DURING             ESM_vidDuringESM_ST0OnESM_EV0   /* During function for STARTUP_I_MODE on event SCHED_5MS */
#define ESM_ESM_ST0_ON_ESM_EV1_DURING             ESM_vidDuringESM_ST0OnESM_EV1   /* During function for STARTUP_I_MODE on event GO2_STARTUP_I */

#define ESM_ESM_ST1_ON_ESM_EV0_DURING             ESM_vidDuringESM_ST1OnESM_EV0   /* During function for STARTUP_II_MODE on event SCHED_5MS */
#define ESM_ESM_ST1_ON_ESM_EV1_DURING             ESM_vidDuringESM_ST1OnESM_EV1   /* During function for STARTUP_II_MODE on event GO2_STARTUP_I */

#define ESM_ESM_ST2_ON_ESM_EV0_DURING             ESM_vidDuringESM_ST2OnESM_EV0   /* During function for OPERATIONAL_MODE on event SCHED_5MS */
#define ESM_ESM_ST2_ON_ESM_EV1_DURING             ESM_vidDuringESM_ST2OnESM_EV1   /* During function for OPERATIONAL_MODE on event GO2_STARTUP_I */

#define ESM_ESM_ST3_ON_ESM_EV0_DURING             ESM_vidDuringESM_ST3OnESM_EV0   /* During function for POWERLATCH_MODE on event SCHED_5MS */
#define ESM_ESM_ST3_ON_ESM_EV1_DURING             ESM_vidDuringESM_ST3OnESM_EV1   /* During function for POWERLATCH_MODE on event GO2_STARTUP_I */

#define ESM_ESM_ST4_ON_ESM_EV0_DURING             ESM_vidDuringESM_ST4OnESM_EV0   /* During function for POWER_OFF_MODE on event SCHED_5MS */
#define ESM_ESM_ST4_ON_ESM_EV1_DURING             ESM_vidDuringESM_ST4OnESM_EV1   /* During function for POWER_OFF_MODE on event GO2_STARTUP_I */



/*----------------------------------------------------------------------------*/
/* ESM transition functions                                                   */
/*----------------------------------------------------------------------------*/

#define ESM_ESM_ST0_ON_ESM_EV0_TRANS         ESM_vidFromESM_ST0OnESM_EV0/* Transition function from STARTUP_I_MODE on event SCHED_5MS */
#define ESM_ESM_ST1_ON_ESM_EV0_TRANS         ESM_vidFromESM_ST1OnESM_EV0/* Transition function from STARTUP_II_MODE on event SCHED_5MS */
#define ESM_ESM_ST2_ON_ESM_EV0_TRANS         ESM_vidFromESM_ST2OnESM_EV0/* Transition function from OPERATIONAL_MODE on event SCHED_5MS */
#define ESM_ESM_ST3_ON_ESM_EV0_TRANS         ESM_vidFromESM_ST3OnESM_EV0/* Transition function from POWERLATCH_MODE on event SCHED_5MS */
#define ESM_ESM_ST4_ON_ESM_EV0_TRANS         ESM_ON_EVENT_NO_ACTION      /* Transition function from POWER_OFF_MODE on event SCHED_5MS */

#define ESM_ESM_ST0_ON_ESM_EV1_TRANS         ESM_ON_EVENT_NO_ACTION      /* Transition function from STARTUP_I_MODE on event GO2_STARTUP_I */
#define ESM_ESM_ST1_ON_ESM_EV1_TRANS         ESM_vidFromESM_ST1OnESM_EV1/* Transition function from STARTUP_II_MODE on event GO2_STARTUP_I */
#define ESM_ESM_ST2_ON_ESM_EV1_TRANS         ESM_vidFromESM_ST2OnESM_EV1/* Transition function from OPERATIONAL_MODE on event GO2_STARTUP_I */
#define ESM_ESM_ST3_ON_ESM_EV1_TRANS         ESM_vidFromESM_ST3OnESM_EV1/* Transition function from POWERLATCH_MODE on event GO2_STARTUP_I */
#define ESM_ESM_ST4_ON_ESM_EV1_TRANS         ESM_vidFromESM_ST4OnESM_EV1/* Transition function from POWER_OFF_MODE on event GO2_STARTUP_I */



/*----------------------------------------------------------------------------*/
/* ESM tempo data                                                             */
/*----------------------------------------------------------------------------*/
#define ESM_TEMPO_ESM_POWERLATCH_TEMPO_VAR     ESM_u16PowerLatchTempo
#define ESM_TEMPO_ESM_POWERLATCH_TEMPO_INIT    ESM_u16PowerLatchTempoC


/******************************************************************************/
/* DATA DECLARATION                                                           */
/******************************************************************************/

#define STFSRV_START_SEC_CODE
#include "MemMap.h"

FUNC (void, STFSRV_CODE) ESM_vidOnESM_EV0(void);
FUNC (void, STFSRV_CODE) ESM_vidOnESM_EV1(void);

FUNC(void, STFSRV_CODE) ESM_vidExecOutEvent(uint16 bfCarrier);

FUNC (void, STFSRV_CODE) ESM_vidNoAction(void);

FUNC (void, STFSRV_CODE) ESM_vidEntryESM_ST0(void);
FUNC (void, STFSRV_CODE) ESM_vidEntryESM_ST1(void);
FUNC (void, STFSRV_CODE) ESM_vidEntryESM_ST2(void);
FUNC (void, STFSRV_CODE) ESM_vidEntryESM_ST3(void);
FUNC (void, STFSRV_CODE) ESM_vidEntryESM_ST4(void);


FUNC (void, STFSRV_CODE) ESM_vidDuringESM_ST0OnESM_EV0(void);
FUNC (void, STFSRV_CODE) ESM_vidDuringESM_ST0OnESM_EV1(void);

FUNC (void, STFSRV_CODE) ESM_vidDuringESM_ST1OnESM_EV0(void);
FUNC (void, STFSRV_CODE) ESM_vidDuringESM_ST1OnESM_EV1(void);

FUNC (void, STFSRV_CODE) ESM_vidDuringESM_ST2OnESM_EV0(void);
FUNC (void, STFSRV_CODE) ESM_vidDuringESM_ST2OnESM_EV1(void);

FUNC (void, STFSRV_CODE) ESM_vidDuringESM_ST3OnESM_EV0(void);
FUNC (void, STFSRV_CODE) ESM_vidDuringESM_ST3OnESM_EV1(void);

FUNC (void, STFSRV_CODE) ESM_vidDuringESM_ST4OnESM_EV0(void);
FUNC (void, STFSRV_CODE) ESM_vidDuringESM_ST4OnESM_EV1(void);



FUNC (void, STFSRV_CODE) ESM_vidFromESM_ST0OnESM_EV0(void);
FUNC (void, STFSRV_CODE) ESM_vidFromESM_ST1OnESM_EV0(void);
FUNC (void, STFSRV_CODE) ESM_vidFromESM_ST2OnESM_EV0(void);
FUNC (void, STFSRV_CODE) ESM_vidFromESM_ST3OnESM_EV0(void);

FUNC (void, STFSRV_CODE) ESM_vidFromESM_ST1OnESM_EV1(void);
FUNC (void, STFSRV_CODE) ESM_vidFromESM_ST2OnESM_EV1(void);
FUNC (void, STFSRV_CODE) ESM_vidFromESM_ST3OnESM_EV1(void);
FUNC (void, STFSRV_CODE) ESM_vidFromESM_ST4OnESM_EV1(void);


#define STFSRV_STOP_SEC_CODE
#include "MemMap.h"


#define STFSRV_START_SEC_VAR_16BIT
#include "MemMap.h"

extern VAR (uint16, STFSRV_VAR) ESM_bfOutEventCarrier;

#define STFSRV_STOP_SEC_VAR_16BIT
#include "MemMap.h"


#define STFSRV_START_SEC_VAR_UNSPECIFIED
#include "MemMap.h"

extern VAR (STFSRV_tpfFunctionPointerType, STFSRV_VAR) ESM_pfTransESM_STF0OnESM_EV0Ptr;

extern VAR (STFSRV_tpfFunctionPointerType, STFSRV_VAR) ESM_pfTransESM_STF0OnESM_EV1Ptr;

extern VAR (STFSRV_tpfFunctionPointerType, STFSRV_VAR) ESM_pfDuringESM_STF0OnESM_EV0Ptr;

extern VAR (STFSRV_tpfFunctionPointerType, STFSRV_VAR) ESM_pfDuringESM_STF0OnESM_EV1Ptr;



#define STFSRV_STOP_SEC_VAR_UNSPECIFIED
#include "MemMap.h"

#endif /* ESM_DAT_H */

/*------------------------------ END OF FILE ---------------------------------*/
