/******************************************************************************/
/*                                                                            */
/* !Layer           : SRVL                                                    */
/*                                                                            */
/* !Component       : ESM                                                     */
/* !Description     : StateFlow of ESM component                              */
/*                                                                            */
/* !File            : ESM_TRA.H                                               */
/*                                                                            */
/* !Scope           : Public                                                  */
/*                                                                            */
/* !Target          : All                                                     */
/*                                                                            */
/* !Vendor          : invt                                                    */
/*                                                                            */
/* Coding language  : C                                                       */
/*                                                                            */
/* COPYRIGHT 2007 invt                                                        */
/* all rights reserved                                                        */
/*                                                                            */
/******************************************************************************/
/** 10/27/22, 09:10:37: generated by Genecode v2.6.0.0                        */
/* From Source Template : STFSRV_TRA_H.TPL                                    */
/******************************************************************************/

#ifndef ESM_TRA_H
#define ESM_TRA_H

#include "Std_Types.h"
#include "esm_dat.h"
#include "stfsrv_Includes.h"


/******************************************************************************/
/* MACRO FUNCTIONS                                                            */
/******************************************************************************/

/*----------------------------------------------------------------------------*/
/* ESM Stateflow transitions definition                                       */
/*----------------------------------------------------------------------------*/

/* -------- ESM Stateflow ECU_STATE -------- */

/* SCHED_5MS Event */
/* GO2_STARTUP_I Event */


#endif /* ESM_TRA_H */

/*-------------------------------- END OF FILE -------------------------------*/
