/******************************************************************************/
/*                                                                            */
/* !Layer           : SRVL                                                    */
/*                                                                            */
/* !Component       : ESM                                                     */
/* !Description     : StateFlow of ESM component                              */
/*                                                                            */
/* !File            : ESM_DAT.C                                               */
/*                                                                            */
/* !Scope           : Public                                                  */
/*                                                                            */
/* !Target          : All                                                     */
/*                                                                            */
/* !Vendor          : invt                                                    */
/*                                                                            */
/* Coding language  : C                                                       */
/*                                                                            */
/* COPYRIGHT 2007 invt                                                        */
/* all rights reserved                                                        */
/*                                                                            */
/******************************************************************************/
/** 10/27/22, 09:10:37: generated by Genecode v2.6.0.0                        */
/* From Source Template : STFSRV_DAT_C.TPL                                    */
/******************************************************************************/


#include "Std_Types.h"
#include "stfsrv_types.h"
#include "ESM_DAT.h"


/******************************************************************************/
/* DATA DECLARATION                                                           */
/******************************************************************************/

/*----------------------------------------------------------------------------*/
/* ESM On event transition pointers                                           */
/*----------------------------------------------------------------------------*/

/* Stateflows :  ECU_STATE <=> ESM_STF0 */
/* Events :  IN_EVENT <=> ESM_EV0, IN_EVENT <=> ESM_EV1 */

#define STFSRV_START_SEC_VAR_UNSPECIFIED
#include "MemMap.h"

VAR (STFSRV_tpfFunctionPointerType, STFSRV_VAR) ESM_pfTransESM_STF0OnESM_EV0Ptr;
VAR (STFSRV_tpfFunctionPointerType, STFSRV_VAR) ESM_pfTransESM_STF0OnESM_EV1Ptr;
VAR (STFSRV_tpfFunctionPointerType, STFSRV_VAR) ESM_pfDuringESM_STF0OnESM_EV0Ptr;
VAR (STFSRV_tpfFunctionPointerType, STFSRV_VAR) ESM_pfDuringESM_STF0OnESM_EV1Ptr;

#define STFSRV_STOP_SEC_VAR_UNSPECIFIED
#include "MemMap.h"


#define STFSRV_START_SEC_VAR_16BIT
#include "MemMap.h"

VAR (uint16, STFSRV_VAR) ESM_bfOutEventCarrier;

#define STFSRV_STOP_SEC_VAR_16BIT
#include "MemMap.h"


/******************************************************************************/
/* GLOBAL FUNCTION DEFINITION                                                 */
/******************************************************************************/

/*----------------------------------------------------------------------------*/
/* ESM common data                                                            */
/*----------------------------------------------------------------------------*/

#define STFSRV_START_SEC_CODE
#include "MemMap.h"

FUNC (void, STFSRV_CODE) ESM_vidNoAction(void){}

#define STFSRV_STOP_SEC_CODE
#include "MemMap.h"

/*-------------------------------- END OF FILE -------------------------------*/
