/******************************************************************************/
/*                                                                            */
/* !Layer           : SRVL                                                    */
/*                                                                            */
/* !Component       : ESM                                                     */
/* !Description     : StateFlow of ESM component                              */
/*                                                                            */
/* !File            : ESM_TRA.C                                               */
/*                                                                            */
/* !Scope           : Public                                                  */
/*                                                                            */
/* !Target          : All                                                     */
/*                                                                            */
/* !Vendor          : invt                                                    */
/*                                                                            */
/* Coding language  : C                                                       */
/*                                                                            */
/* COPYRIGHT 2007 invt                                                        */
/* all rights reserved                                                        */
/*                                                                            */
/******************************************************************************/
/** 10/27/22, 09:10:37: generated by Genecode v2.6.0.0                        */
/* From Source Template : STFSRV_TRA_C.TPL                                    */
/******************************************************************************/

#include "Std_Types.h"
#include "esm_tra.h"
#include "esm_dat.h"


/******************************************************************************/
/* GLOBAL FUNCTION DEFINITION                                                 */
/******************************************************************************/

/*----------------------------------------------------------------------------*/
/* ESM Stateflow transitions definition                                       */
/*----------------------------------------------------------------------------*/

#define STFSRV_START_SEC_CODE
#include "MemMap.h"

/* -------- ESM Stateflow ECU_STATE -------- */


/* SCHED_5MS Event */

/* TRANSITION FROM STARTUP_I_MODE*/

FUNC (void, STFSRV_CODE) ESM_vidFromESM_ST0OnESM_EV0(void)
{
   if((ESM_StpIState == ESM_SFT_STATE_15))
   {
      ESM_bfOutEventCarrier |= GO2_STARTUP_II_EVENT; 
      STFSRV_vidSET_ACTIVE_STATE(ESM, ESM_STF0, ESM_ST1);   /* Activation of state STARTUP_II_MODE for stateflow ECU_STATE */
   }
}

/* TRANSITION FROM STARTUP_II_MODE*/

FUNC (void, STFSRV_CODE) ESM_vidFromESM_ST1OnESM_EV0(void)
{
   if(((ESM_StpIINfState == ESM_SFT_STATE_15) || (ESM_StpIIFtState == ESM_SFT_STATE_15)))
   {
      ESM_bfOutEventCarrier |= GO2_OPERATIONAL_EVENT; 
      STFSRV_vidSET_ACTIVE_STATE(ESM, ESM_STF0, ESM_ST2);   /* Activation of state OPERATIONAL_MODE for stateflow ECU_STATE */
   }
}

/* TRANSITION FROM OPERATIONAL_MODE*/

FUNC (void, STFSRV_CODE) ESM_vidFromESM_ST2OnESM_EV0(void)
{
   if(((ESM_OpNfState == ESM_SFT_STATE_14) || (ESM_PwrLFtState == ESM_SFT_STATE_15)))
   {
          ESM_bfOutEventCarrier |= GO2_STARTUP_II_EVENT; 
          STFSRV_vidSET_ACTIVE_STATE(ESM, ESM_STF0, ESM_ST1);  /* Activation of state STARTUP_II_MODE for stateflow ECU_STATE */
   }
   else
   {
      if((ESM_OpNfState == ESM_SFT_STATE_15))
      {
          ESM_bfOutEventCarrier |= GO2_POWERLATCH_EVENT; 
          STFSRV_vidSET_ACTIVE_STATE(ESM, ESM_STF0, ESM_ST3);  /* Activation of state POWERLATCH_MODE for stateflow ECU_STATE */
      }
   }
}

/* TRANSITION FROM POWERLATCH_MODE*/

FUNC (void, STFSRV_CODE) ESM_vidFromESM_ST3OnESM_EV0(void)
{
   if(((ESM_PwrLNfState == ESM_SFT_STATE_15) && (ESM_bPowerOffModeInhC == 0)))
   {
          ESM_bfOutEventCarrier |= GO2_POWER_OFF_EVENT; 
          STFSRV_vidSET_ACTIVE_STATE(ESM, ESM_STF0, ESM_ST4);  /* Activation of state POWER_OFF_MODE for stateflow ECU_STATE */
   }
   else
   {
      if((ESM_PwrLNfState == ESM_SFT_STATE_14))
      {
          ESM_bfOutEventCarrier |= GO2_STARTUP_II_EVENT; 
          STFSRV_vidSET_ACTIVE_STATE(ESM, ESM_STF0, ESM_ST1);  /* Activation of state STARTUP_II_MODE for stateflow ECU_STATE */
      }
   }
}


/* GO2_STARTUP_I Event */

/* TRANSITION FROM STARTUP_II_MODE*/

FUNC (void, STFSRV_CODE) ESM_vidFromESM_ST1OnESM_EV1(void)
{
      ESM_bfOutEventCarrier |= GO2_STARTUP_I_EVENT; 
      STFSRV_vidSET_ACTIVE_STATE(ESM, ESM_STF0, ESM_ST0);   /* Activation of state STARTUP_I_MODE for stateflow ECU_STATE */
}

/* TRANSITION FROM OPERATIONAL_MODE*/

FUNC (void, STFSRV_CODE) ESM_vidFromESM_ST2OnESM_EV1(void)
{
      ESM_bfOutEventCarrier |= GO2_STARTUP_I_EVENT; 
      STFSRV_vidSET_ACTIVE_STATE(ESM, ESM_STF0, ESM_ST0);   /* Activation of state STARTUP_I_MODE for stateflow ECU_STATE */
}

/* TRANSITION FROM POWERLATCH_MODE*/

FUNC (void, STFSRV_CODE) ESM_vidFromESM_ST3OnESM_EV1(void)
{
      ESM_bfOutEventCarrier |= GO2_STARTUP_I_EVENT; 
      STFSRV_vidSET_ACTIVE_STATE(ESM, ESM_STF0, ESM_ST0);   /* Activation of state STARTUP_I_MODE for stateflow ECU_STATE */
}

/* TRANSITION FROM POWER_OFF_MODE*/

FUNC (void, STFSRV_CODE) ESM_vidFromESM_ST4OnESM_EV1(void)
{
      ESM_bfOutEventCarrier |= GO2_STARTUP_I_EVENT; 
      STFSRV_vidSET_ACTIVE_STATE(ESM, ESM_STF0, ESM_ST0);   /* Activation of state STARTUP_I_MODE for stateflow ECU_STATE */
}




#define STFSRV_STOP_SEC_CODE
#include "MemMap.h"

/*-------------------------------- END OF FILE -------------------------------*/
