/******************************************************************************/
/*                                                                            */
/* !Layer           : SRVL                                                    */
/*                                                                            */
/* !Component       : ESM                                                     */
/* !Description     : StateFlow of ESM component                              */
/*                                                                            */
/* !File            : ESM_STA.C                                               */
/*                                                                            */
/* !Scope           : Public                                                  */
/*                                                                            */
/* !Target          : All                                                     */
/*                                                                            */
/* !Vendor          : invt                                                    */
/*                                                                            */
/* Coding language  : C                                                       */
/*                                                                            */
/* COPYRIGHT 2007 invt                                                        */
/* all rights reserved                                                        */
/*                                                                            */
/******************************************************************************/
/** 10/27/22, 09:10:37: generated by Genecode v2.6.0.0                        */
/* From Source Template : STFSRV_STA_C.TPL                                    */
/******************************************************************************/

#include "Std_Types.h"
#include "esm_tra.h"
#include "esm_dat.h"
#include "stfsrv_Includes.h"


/******************************************************************************/
/* GLOBAL FUNCTION DEFINITION                                                 */
/******************************************************************************/

/*----------------------------------------------------------------------------*/
/* ESM Stateflow Entry definition                                             */
/*----------------------------------------------------------------------------*/

#define STFSRV_START_SEC_CODE
#include "MemMap.h"

/* -------- ESM Stateflow ECU_STATE -------- */
/* ENTRY FUNCTIONS */

/* ENTRY FUNCTION FOR STARTUP_I_MODE*/
FUNC (void, STFSRV_CODE) ESM_vidEntryESM_ST0(void)
{
   ESM_pfTransESM_STF0OnESM_EV0Ptr = ESM_ESM_ST0_ON_ESM_EV0_TRANS;
   ESM_pfTransESM_STF0OnESM_EV1Ptr = ESM_ESM_ST0_ON_ESM_EV1_TRANS;
   ESM_pfDuringESM_STF0OnESM_EV0Ptr = ESM_ESM_ST0_ON_ESM_EV0_DURING;
   ESM_pfDuringESM_STF0OnESM_EV1Ptr = ESM_ESM_ST0_ON_ESM_EV1_DURING;
   ESM_vidInit();
}

/* ENTRY FUNCTION FOR STARTUP_II_MODE*/
FUNC (void, STFSRV_CODE) ESM_vidEntryESM_ST1(void)
{
   ESM_pfTransESM_STF0OnESM_EV0Ptr = ESM_ESM_ST1_ON_ESM_EV0_TRANS;
   ESM_pfTransESM_STF0OnESM_EV1Ptr = ESM_ESM_ST1_ON_ESM_EV1_TRANS;
   ESM_pfDuringESM_STF0OnESM_EV0Ptr = ESM_ESM_ST1_ON_ESM_EV0_DURING;
   ESM_pfDuringESM_STF0OnESM_EV1Ptr = ESM_ESM_ST1_ON_ESM_EV1_DURING;
}

/* ENTRY FUNCTION FOR OPERATIONAL_MODE*/
FUNC (void, STFSRV_CODE) ESM_vidEntryESM_ST2(void)
{
   ESM_pfTransESM_STF0OnESM_EV0Ptr = ESM_ESM_ST2_ON_ESM_EV0_TRANS;
   ESM_pfTransESM_STF0OnESM_EV1Ptr = ESM_ESM_ST2_ON_ESM_EV1_TRANS;
   ESM_pfDuringESM_STF0OnESM_EV0Ptr = ESM_ESM_ST2_ON_ESM_EV0_DURING;
   ESM_pfDuringESM_STF0OnESM_EV1Ptr = ESM_ESM_ST2_ON_ESM_EV1_DURING;
}

/* ENTRY FUNCTION FOR POWERLATCH_MODE*/
FUNC (void, STFSRV_CODE) ESM_vidEntryESM_ST3(void)
{
   ESM_pfTransESM_STF0OnESM_EV0Ptr = ESM_ESM_ST3_ON_ESM_EV0_TRANS;
   ESM_pfTransESM_STF0OnESM_EV1Ptr = ESM_ESM_ST3_ON_ESM_EV1_TRANS;
   ESM_pfDuringESM_STF0OnESM_EV0Ptr = ESM_ESM_ST3_ON_ESM_EV0_DURING;
   ESM_pfDuringESM_STF0OnESM_EV1Ptr = ESM_ESM_ST3_ON_ESM_EV1_DURING;
   STFSRV_vidINIT_TEMPO(ESM, ESM_POWERLATCH_TEMPO);
}

/* ENTRY FUNCTION FOR POWER_OFF_MODE*/
FUNC (void, STFSRV_CODE) ESM_vidEntryESM_ST4(void)
{
   ESM_pfTransESM_STF0OnESM_EV0Ptr = ESM_ESM_ST4_ON_ESM_EV0_TRANS;
   ESM_pfTransESM_STF0OnESM_EV1Ptr = ESM_ESM_ST4_ON_ESM_EV1_TRANS;
   ESM_pfDuringESM_STF0OnESM_EV0Ptr = ESM_ESM_ST4_ON_ESM_EV0_DURING;
   ESM_pfDuringESM_STF0OnESM_EV1Ptr = ESM_ESM_ST4_ON_ESM_EV1_DURING;
}


/* DURING FUNCTIONS */

/* DURING FUNCTION FOR STARTUP_I_MODE ON SCHED_5MS*/
FUNC (void, STFSRV_CODE) ESM_vidDuringESM_ST0OnESM_EV0(void)
{
   ESM_vidStfStpI();
}

/* DURING FUNCTION FOR STARTUP_I_MODE ON GO2_STARTUP_I*/
FUNC (void, STFSRV_CODE) ESM_vidDuringESM_ST0OnESM_EV1(void)
{
   ESM_vidStfStpI();
}


/* DURING FUNCTION FOR STARTUP_II_MODE ON SCHED_5MS*/
FUNC (void, STFSRV_CODE) ESM_vidDuringESM_ST1OnESM_EV0(void)
{
   ESM_vidStfStpII();
}

/* DURING FUNCTION FOR STARTUP_II_MODE ON GO2_STARTUP_I*/
FUNC (void, STFSRV_CODE) ESM_vidDuringESM_ST1OnESM_EV1(void)
{
   ESM_vidStfStpII();
}


/* DURING FUNCTION FOR OPERATIONAL_MODE ON SCHED_5MS*/
FUNC (void, STFSRV_CODE) ESM_vidDuringESM_ST2OnESM_EV0(void)
{
   ESM_vidStfOp();
}

/* DURING FUNCTION FOR OPERATIONAL_MODE ON GO2_STARTUP_I*/
FUNC (void, STFSRV_CODE) ESM_vidDuringESM_ST2OnESM_EV1(void)
{
   ESM_vidStfOp();
}


/* DURING FUNCTION FOR POWERLATCH_MODE ON SCHED_5MS*/
FUNC (void, STFSRV_CODE) ESM_vidDuringESM_ST3OnESM_EV0(void)
{
   ESM_vidStfPwrL();
   STFSRV_vidDEC_TEMPO(ESM, ESM_POWERLATCH_TEMPO);
}

/* DURING FUNCTION FOR POWERLATCH_MODE ON GO2_STARTUP_I*/
FUNC (void, STFSRV_CODE) ESM_vidDuringESM_ST3OnESM_EV1(void)
{
   ESM_vidStfPwrL();
}


/* DURING FUNCTION FOR POWER_OFF_MODE ON SCHED_5MS*/
FUNC (void, STFSRV_CODE) ESM_vidDuringESM_ST4OnESM_EV0(void)
{
   ESM_vidStfPwrL();
}

/* DURING FUNCTION FOR POWER_OFF_MODE ON GO2_STARTUP_I*/
FUNC (void, STFSRV_CODE) ESM_vidDuringESM_ST4OnESM_EV1(void)
{
   ESM_vidStfPwrL();
}



/* IN EVENT EXEC FUNCTION */

FUNC (void, STFSRV_CODE) ESM_vidOnESM_EV0(void)
{
   STFSRV_vidINTERNAL_SET_EVENT(ESM, ESM_STF0, ESM_EV0);
}
FUNC (void, STFSRV_CODE) ESM_vidOnESM_EV1(void)
{
   STFSRV_vidINTERNAL_SET_EVENT(ESM, ESM_STF0, ESM_EV1);
}


/* OUT EVENT EXEC FUNCTION */

FUNC (void, STFSRV_CODE) ESM_vidExecOutEvent(uint16 bfCarrier)
{
   if ((bfCarrier & GO2_STARTUP_I_EVENT) != 0)
   {
      GO2_STARTUP_I_EVENT_ACTION;
   }
   if ((bfCarrier & GO2_STARTUP_II_EVENT) != 0)
   {
      GO2_STARTUP_II_EVENT_ACTION;
   }
   if ((bfCarrier & GO2_OPERATIONAL_EVENT) != 0)
   {
      GO2_OPERATIONAL_EVENT_ACTION;
   }
   if ((bfCarrier & GO2_POWERLATCH_EVENT) != 0)
   {
      GO2_POWERLATCH_EVENT_ACTION;
   }
   if ((bfCarrier & GO2_POWER_OFF_EVENT) != 0)
   {
      GO2_POWER_OFF_EVENT_ACTION;
   }
}


#define STFSRV_STOP_SEC_CODE
#include "MemMap.h"


/*-------------------------------- END OF FILE -------------------------------*/