########## BEGIN SCONSTRUCT ##########
import sys
import os,sys,shutil


sys.path.append(Dir('#').abspath + "\\site_scons\\site_tools")


# Ensure tool versions
EnsureSConsVersion(3,1,)

# Settings file to be read
# Implements: COR009
settings_file = 'settings.py'

def gen_linfils_s(fname,flist):
    with open(fname,'w') as fdoc:
        for f in flist:
            fdoc.write('%s\n' % os.path.relpath(str(f).replace('\\','/')))
        fdoc.close()
    return fname
# Load all the variables into the environment
if not os.path.exists(settings_file):
    print ('Could not find file ' + settings_file + ' in current directory.')
else:
    vars = Variables(settings_file)

    # Add variables to environment along with some help text
    vars.Add('OUTPUT_DIR',             'Path to build all target files.', 'output')
    vars.Add('LOG_DIR',             'Path to store all log files.', 'log')
    vars.Add('CPU_TARGET',             'CPU to build for.  Must match what the compiler is expecting as \'cpu\' option.')
    vars.Add('COMPILER_TOOL',         'Custom SCons tool to be used for building.  Must match the file name located in the site_tools directory.')
    vars.Add('COMPILER_ROOT',         'Path to compiler executables.')
    vars.Add('COMPILER_FLAGS',         'Compiler flags to use for building.')
    vars.Add('COMPILER_DEFINES',     'Compiler defines to use for building.')
    vars.Add('ASSEMBLER_FLAGS',     'Assembler flags to use for building.')
    vars.Add('ASSEMBLER_DEFINES',     'Assembler defines to use for building.')
    vars.Add('LINKER_FLAGS',         'Linker flags to be used for building.')
    vars.Add('LINKER_FILE',         'Path to linker file to be used during linking.')
    vars.Add('ADD_LIBRARIES',         'Names of additional libraries to be included during linking.  These do not need the file extension.')
    vars.Add('LIBRARY_PATHS',         'Paths to look for the additional libraries.')
    vars.Add('A2L_COMMAND',         'A command to run in order to build the A2L file.  The name of the A2L file will be passed in as the last argument to this command line.')
    vars.Add('BUILD_TYPE',             'Type of build to be done.  Options are: DEBUG, PROD, DEVEL')
    vars.Add('PROJ_NAME',             'Name of the project to be built.')
    vars.Add('SW_VERSION_MSB',         'Most signification numbers of the SW version.')
    vars.Add('SW_VERSION_LSB',         'Least signification numbers of the SW version.')
    vars.Add('PYTHON_VERSION',         'python3 or python2')
    vars.Add('CEN_HEADER_DIR',      'path to centralized header file of project.')
    vars.Add('LIBRARY_SEARCH_PATH', 'Path to search a specific library')
    vars.Add('CPU_USED',         'CPU Used.')

    # Initialize the default SCons environment
    env = Environment(variables = vars)

    # Generate variables help text
    env.Help(vars.GenerateHelpText(env))

    
    
if not GetOption('help'):

    import scons_common
    import listfile
    import prebuild

    # Setup logging of output
    scons_common.setuplogging(env)

    # Validate the mandatory values of the environment
    scons_common.validate_environment(env)
    
    # Build target/project name
    if env['BUILD_TYPE'] == 'PROD':
        env['PROJ_PREFIX'] = 'P'
    else:
        env['PROJ_PREFIX'] = 'D'
        
    env['TARGET_NAME']       = env.subst('$PROJ_PREFIX') + '_' + env.subst('$PROJ_NAME') + '_' + env.subst('$SW_VERSION_MSB') + '_' + env.subst('$SW_VERSION_LSB')

############ START SCONSCRIPT ############

    if ARGUMENTS.get('VERBOSE') != "1":
        env['LINKCOMSTR'] = "******** Linking $TARGET"
        env['CCCOMSTR'] = "-------- Compiling $TARGET"
        env['ARCOMSTR'] = "######## Archiving $TARGET"

    # Clone the environment and setup compiler specific enivronment
    env = env.Clone(tools=[env['COMPILER_TOOL']])


    #remove all psuedo header file
    prebuild.cleanHeaderDir(env['CEN_HEADER_DIR'])


    # Check on the command line whether or not additional user defines are present
    for key, value in ARGLIST:
        if key == 'D':
            env.Append(CPPDEFINES=value)

    #if env['BUILD_TYPE'] == 'DEBUG':
    cur_ptah = os.getcwd()
 
    #update include & source files Sconscript
    BSW_ExceptFileList=[]
    os.chdir('./bsw')
    listfile.List('.',BSW_ExceptFileList)
    os.chdir(cur_ptah)
    print('updated sconsscript folder ./bsw done')

    os.chdir('./bswcdd')
    listfile.List('.',[])
    os.chdir(cur_ptah)
    print('updated sconsscript folder ./bswcdd done')
    
    os.chdir('./main')
    listfile.List('.',[])
    os.chdir(cur_ptah)
    print('updated sconsscript folder ./main done')

    os.chdir('./rte')
    listfile.List('.',[])
    os.chdir(cur_ptah)
    print('updated sconsscript folder ./rte done')

    os.chdir('./os') 
    listfile.List('.',[])
    os.chdir(cur_ptah)
    print('updated sconsscript folder ./os done')

    os.chdir('./ASW')
    listfile.List('.',[])
    os.chdir(cur_ptah)
    print('updated sconsscript folder ./asw done')

    os.chdir('./Targets')
    listfile.List('.',[])
    os.chdir(cur_ptah)
    print('updated sconsscript folder ./Targets done')

    os.chdir('./Integration')
    listfile.List('.',[])
    os.chdir(cur_ptah)
    print('updated sconsscript folder ./Integration done')
    
    # Storage of all objects to be linked
    objects = []
    #libobjects = []

    # Setup build directories for sub-systems
    # Setup build directories for sub-systems
    asw_build_dir           = os.path.join(env.subst('$OUTPUT_DIR'), 'objs', 'ASW')
    bsw_build_dir           = os.path.join(env.subst('$OUTPUT_DIR'), 'objs', 'bsw')
    bswcdd_build_dir        = os.path.join(env.subst('$OUTPUT_DIR'), 'objs', 'bswcdd')
    main_build_dir        = os.path.join(env.subst('$OUTPUT_DIR'), 'objs', 'main')
    rte_build_dir           = os.path.join(env.subst('$OUTPUT_DIR'), 'objs', 'rte')
    os_build_dir            = os.path.join(env.subst('$OUTPUT_DIR'), 'objs', 'os')
    target_build_dir        = os.path.join(env.subst('$OUTPUT_DIR'), 'objs', 'Targets')
    Integration_build_dir   = os.path.join(env.subst('$OUTPUT_DIR'), 'objs', 'Integration')     

    # Specify which SConscript to build
    asw_path            = os.path.join('ASW/SConscript')
    bsw_path            = os.path.join('bsw/SConscript')
    bswcdd_path         = os.path.join('bswcdd/SConscript')
    main_path         = os.path.join('main/SConscript')
    rte_path            = os.path.join('rte/SConscript')
    os_path              = os.path.join('os/SConscript')
    target_path         = os.path.join('Targets/SConscript')
    Integration_path    = os.path.join('Integration/SConscript')

    # Compile each subsystem's SConscript file and collect all objects
    objects += SConscript(target_path, exports='env', variant_dir=target_build_dir, duplicate=0)
    objects += SConscript(Integration_path, exports='env', variant_dir=Integration_build_dir, duplicate=0)
    objects += SConscript(bsw_path, exports='env', variant_dir=bsw_build_dir, duplicate=0)    
    objects += SConscript(bswcdd_path, exports='env', variant_dir=bswcdd_build_dir, duplicate=0)    
    objects += SConscript(os_path, exports='env', variant_dir=os_build_dir, duplicate=0) 	
    #libobjects = objects
    objects += SConscript(rte_path, exports='env', variant_dir=rte_build_dir, duplicate=0)
    objects += SConscript(asw_path, exports='env', variant_dir=asw_build_dir, duplicate=0)
    objects += SConscript(main_path, exports='env', variant_dir=main_build_dir, duplicate=0)
    
    # Setup output path for debug, hex and A2L files
    dbg_path     = os.path.join(env.subst('$OUTPUT_DIR'), 'dbg', env.subst('$TARGET_NAME'))
    lib_path     = os.path.join(env.subst('$OUTPUT_DIR'), 'lib', env.subst('BSW'))
    hex_path    = os.path.join(env.subst('$OUTPUT_DIR'), 'hex', env.subst('$TARGET_NAME'))
    a2l_path    = os.path.join(env.subst('$OUTPUT_DIR'), 'a2l', env.subst('$TARGET_NAME'))
    mem_path    = os.path.join(env.subst('$OUTPUT_DIR'), 'dbg', env.subst('$TARGET_NAME')+'.mem')

    rsp_file = gen_linfils_s('linksile.lst',objects)
    #env.Append(LINKFLAGS= ' -f%s' % os.path.relpath(rsp_file))

    # Build final debug, hex and A2L files
    dbg_exe     = env.Program(dbg_path, objects)
    hex_exe     = env.Hex(hex_path, dbg_exe)
    #dbg_lib     = env.Library(lib_path, libobjects)
    #a2l_file    = env.A2L(a2l_path,hex_exe)

############ END SCONSCRIPT ############

########## END SCONSTRUCT ##########