# The file contains project related settings
# Key shall not contain any special characters
# Values with multiple lines shall be avoided
#
#Wed Apr 17 09:41:00 CST 2024
BuildDebugEnabled=true
Clean_Output_Directory=ALWAYS
DIR_OUT_FILES_SETTINGS=[c\=source][h\=header][arxml\=arxml]
STOP_ON_ERROR=true
com.bosch.autosartool.bsw.validation.merge_conflict_detection=true