/******************************************************************************/
/*                                                                            */
/* !Layer           : SRVL                                                    */
/*                                                                            */
/* !Component       : AESM                                                     */
/* !Description     : StateFlow of AESM component                              */
/*                                                                            */
/* !File            : AESM_TRA.C                                               */
/*                                                                            */
/* !Scope           : Public                                                  */
/*                                                                            */
/* !Target          : All                                                     */
/*                                                                            */
/* !Vendor          : invt                                                    */
/*                                                                            */
/* Coding language  : C                                                       */
/*                                                                            */
/* COPYRIGHT 2007 invt                                                        */
/* all rights reserved                                                        */
/*                                                                            */
/******************************************************************************/
/** 10/27/22, 09:10:37: generated by Genecode v2.6.0.0                        */
/* From Source Template : ASTFSRV_TRA_C.TPL                                    */
/******************************************************************************/

#include "Std_Types.h"
#include "aesm_tra.h"
#include "aesm_dat.h"


/******************************************************************************/
/* GLOBAL FUNCTION DEFINITION                                                 */
/******************************************************************************/

/*----------------------------------------------------------------------------*/
/* AESM Stateflow transitions definition                                       */
/*----------------------------------------------------------------------------*/

#define ASTFSRV_START_SEC_CODE
#include "MemMap.h"

/* -------- AESM Stateflow ECU_STATE -------- */


/* SCHED_5MS Event */

/* TRANSITION FROM STARTUP_I_MODE*/

FUNC (void, ASTFSRV_CODE) AESM_vidFromAESM_ST0OnAESM_EV0(void)
{
   if((AESM_StpIState == AESM_SFT_STATE_15))
   {
      AESM_bfOutEventCarrier |= GO2_STARTUP_II_EVENT; 
      ASTFSRV_vidSET_ACTIVE_STATE(AESM, AESM_STF0, AESM_ST1);   /* Activation of state STARTUP_II_MODE for stateflow ECU_STATE */
   }
}

/* TRANSITION FROM STARTUP_II_MODE*/

FUNC (void, ASTFSRV_CODE) AESM_vidFromAESM_ST1OnAESM_EV0(void)
{
   if(((AESM_StpIINfState == AESM_SFT_STATE_15) || (AESM_StpIIFtState == AESM_SFT_STATE_15)))
   {
      AESM_bfOutEventCarrier |= GO2_OPERATIONAL_EVENT; 
      ASTFSRV_vidSET_ACTIVE_STATE(AESM, AESM_STF0, AESM_ST2);   /* Activation of state OPERATIONAL_MODE for stateflow ECU_STATE */
   }
}

/* TRANSITION FROM OPERATIONAL_MODE*/

FUNC (void, ASTFSRV_CODE) AESM_vidFromAESM_ST2OnAESM_EV0(void)
{
   if(((AESM_OpNfState == AESM_SFT_STATE_14) || (AESM_PwrLFtState == AESM_SFT_STATE_15)))
   {
          AESM_bfOutEventCarrier |= GO2_STARTUP_II_EVENT; 
          ASTFSRV_vidSET_ACTIVE_STATE(AESM, AESM_STF0, AESM_ST1);  /* Activation of state STARTUP_II_MODE for stateflow ECU_STATE */
   }
   else
   {
      if((AESM_OpNfState == AESM_SFT_STATE_15))
      {
          AESM_bfOutEventCarrier |= GO2_POWERLATCH_EVENT; 
          ASTFSRV_vidSET_ACTIVE_STATE(AESM, AESM_STF0, AESM_ST3);  /* Activation of state POWERLATCH_MODE for stateflow ECU_STATE */
      }
   }
}

/* TRANSITION FROM POWERLATCH_MODE*/

FUNC (void, ASTFSRV_CODE) AESM_vidFromAESM_ST3OnAESM_EV0(void)
{
   if(((AESM_PwrLNfState == AESM_SFT_STATE_15) && (AESM_bPowerOffModeInhC == 0)))
   {
          AESM_bfOutEventCarrier |= GO2_POWER_OFF_EVENT; 
          ASTFSRV_vidSET_ACTIVE_STATE(AESM, AESM_STF0, AESM_ST4);  /* Activation of state POWER_OFF_MODE for stateflow ECU_STATE */
   }
   else
   {
      if((AESM_PwrLNfState == AESM_SFT_STATE_14))
      {
          AESM_bfOutEventCarrier |= GO2_STARTUP_II_EVENT; 
          ASTFSRV_vidSET_ACTIVE_STATE(AESM, AESM_STF0, AESM_ST1);  /* Activation of state STARTUP_II_MODE for stateflow ECU_STATE */
      }
   }
}


/* GO2_STARTUP_I Event */

/* TRANSITION FROM STARTUP_II_MODE*/

FUNC (void, ASTFSRV_CODE) AESM_vidFromAESM_ST1OnAESM_EV1(void)
{
      AESM_bfOutEventCarrier |= GO2_STARTUP_I_EVENT; 
      ASTFSRV_vidSET_ACTIVE_STATE(AESM, AESM_STF0, AESM_ST0);   /* Activation of state STARTUP_I_MODE for stateflow ECU_STATE */
}

/* TRANSITION FROM OPERATIONAL_MODE*/

FUNC (void, ASTFSRV_CODE) AESM_vidFromAESM_ST2OnAESM_EV1(void)
{
      AESM_bfOutEventCarrier |= GO2_STARTUP_I_EVENT; 
      ASTFSRV_vidSET_ACTIVE_STATE(AESM, AESM_STF0, AESM_ST0);   /* Activation of state STARTUP_I_MODE for stateflow ECU_STATE */
}

/* TRANSITION FROM POWERLATCH_MODE*/

FUNC (void, ASTFSRV_CODE) AESM_vidFromAESM_ST3OnAESM_EV1(void)
{
      AESM_bfOutEventCarrier |= GO2_STARTUP_I_EVENT; 
      ASTFSRV_vidSET_ACTIVE_STATE(AESM, AESM_STF0, AESM_ST0);   /* Activation of state STARTUP_I_MODE for stateflow ECU_STATE */
}

/* TRANSITION FROM POWER_OFF_MODE*/

FUNC (void, ASTFSRV_CODE) AESM_vidFromAESM_ST4OnAESM_EV1(void)
{
      AESM_bfOutEventCarrier |= GO2_STARTUP_I_EVENT; 
      ASTFSRV_vidSET_ACTIVE_STATE(AESM, AESM_STF0, AESM_ST0);   /* Activation of state STARTUP_I_MODE for stateflow ECU_STATE */
}




#define ASTFSRV_STOP_SEC_CODE
#include "MemMap.h"

/*-------------------------------- END OF FILE -------------------------------*/
