/******************************************************************************/
/*                                                                            */
/* !Layer           : SRVL                                                    */
/*                                                                            */
/* !Component       : AESM                                                     */
/* !Description     : StateFlow of AESM component                              */
/*                                                                            */
/* !File            : AESM_DAT.H                                               */
/*                                                                            */
/* !Scope           : Public                                                  */
/*                                                                            */
/* !Target          : All                                                     */
/*                                                                            */
/* !Vendor          : invt                                                    */
/*                                                                            */
/* Coding language  : C                                                       */
/*                                                                            */
/* COPYRIGHT 2007 invt                                                        */
/* all rights reserved                                                        */
/*                                                                            */
/******************************************************************************/
/** 10/27/22, 09:10:37: generated by Genecode v2.6.0.0                        */
/* From Source Template : ASTFSRV_DAT_H.TPL                                    */
/******************************************************************************/

#ifndef AESM_DAT_H
#define AESM_DAT_H

#include "Std_Types.h"
#include "astfsrv_Includes.h"
#include "astfsrv_types.h"
#include "aesm.h"
#include "aesm_l.h"


/******************************************************************************/
/* DEFINES                                                                    */
/******************************************************************************/

/*----------------------------------------------------------------------------*/
/* AESM Stateflows configuration                                               */
/*----------------------------------------------------------------------------*/
/* Stateflows :  ECU_STATE <=> AESM_STF0        */
/*----------------------------------------------------------------------------*/


#define AESM_udtSTATEFLOW_NB   1

#define AESM_ASTFSRV_MAIN   AESM_STF0  /* ECU_STATE */

/* AESM_ECU_STATE */

#define AESM_AESM_STF0_VAR            AESM_EcuState
#define AESM_AESM_STF0_INIT_STATE     AESM_ST0  /* STARTUP_I_MODE */
#define AESM_AESM_STF0_NB_STATE       5




/*----------------------------------------------------------------------------*/
/* AESM States declaration                                                   */
/*----------------------------------------------------------------------------*/
#define   AESM_STARTUP_I_MODE     1
#define   AESM_STARTUP_II_MODE     2
#define   AESM_OPERATIONAL_MODE     4
#define   AESM_POWERLATCH_MODE     8
#define   AESM_POWER_OFF_MODE     16


/*----------------------------------------------------------------------------*/
/* AESM States configuration                                                   */
/*----------------------------------------------------------------------------*/

#define AESM_AESM_ST0_VAL     AESM_STARTUP_I_MODE
#define AESM_AESM_ST1_VAL     AESM_STARTUP_II_MODE
#define AESM_AESM_ST2_VAL     AESM_OPERATIONAL_MODE
#define AESM_AESM_ST3_VAL     AESM_POWERLATCH_MODE
#define AESM_AESM_ST4_VAL     AESM_POWER_OFF_MODE





/*----------------------------------------------------------------------------*/
/* AESM Events configuration                                                   */
/*----------------------------------------------------------------------------*/
#define AESM_ON_SCHED_5MS_FUNC          AESM_vidOnAESM_EV0
#define AESM_ON_GO2_STARTUP_I_FUNC          AESM_vidOnAESM_EV1

#define GO2_STARTUP_I_EVENT            (uint16)(1 << 0)
#define GO2_STARTUP_II_EVENT            (uint16)(1 << 1)
#define GO2_OPERATIONAL_EVENT            (uint16)(1 << 2)
#define GO2_POWERLATCH_EVENT            (uint16)(1 << 3)
#define GO2_POWER_OFF_EVENT            (uint16)(1 << 4)

#define GGO2_STARTUP_I_EVENT_ACTION          AESM_StpIState = AESM_SFT_STATE_1;
#define GGO2_STARTUP_II_EVENT_ACTION          AESM_StpIINfState = AESM_SFT_STATE_1; AESM_StpIIFtState = AESM_SFT_STATE_1; AESM_PwrLFtState = AESM_SFT_STATE_1;
#define GGO2_OPERATIONAL_EVENT_ACTION          AESM_OpNfState = AESM_SFT_STATE_1; AESM_OpFtState = AESM_SFT_STATE_1;
#define GGO2_POWERLATCH_EVENT_ACTION          AESM_PwrLNfState = AESM_SFT_STATE_1; AESM_PwrLFtState = AESM_SFT_STATE_1;
#define GGO2_POWER_OFF_EVENT_ACTION          AESM_PwrLNfState = AESM_SFT_STATE_15;

#define AESM_EXEC_OUT_EVENT_FUNC       AESM_vidExecOutEvent
#define AESM_OUT_EVENT_CARRIER    AESM_bfOutEventCarrier

/*----------------------------------------------------------------------------*/
/* AESM common data                                                            */
/*----------------------------------------------------------------------------*/

#define AESM_ON_EVENT_NO_ACTION   AESM_vidNoAction

/* Transition function for stateflow ECU_STATE on event SCHED_5MS */
#define AESM_AESM_STF0_ON_AESM_EV0_TRANS_PTR   AESM_pfTransAESM_STF0OnAESM_EV0Ptr


/* Transition function for stateflow ECU_STATE on event GO2_STARTUP_I */
#define AESM_AESM_STF0_ON_AESM_EV1_TRANS_PTR   AESM_pfTransAESM_STF0OnAESM_EV1Ptr


/* During function for stateflow ECU_STATE on event SCHED_5MS */
#define AESM_AESM_STF0_ON_AESM_EV0_DURING_PTR   AESM_pfDuringAESM_STF0OnAESM_EV0Ptr


/* During function for stateflow ECU_STATE on event GO2_STARTUP_I */
#define AESM_AESM_STF0_ON_AESM_EV1_DURING_PTR   AESM_pfDuringAESM_STF0OnAESM_EV1Ptr





/*----------------------------------------------------------------------------*/
/* AESM entry functions                                                        */
/*----------------------------------------------------------------------------*/

#define AESM_AESM_ST0_ENTRY             AESM_vidEntryAESM_ST0   /* AESM_STARTUP_I_MODE */
#define AESM_AESM_ST1_ENTRY             AESM_vidEntryAESM_ST1   /* AESM_STARTUP_II_MODE */
#define AESM_AESM_ST2_ENTRY             AESM_vidEntryAESM_ST2   /* AESM_OPERATIONAL_MODE */
#define AESM_AESM_ST3_ENTRY             AESM_vidEntryAESM_ST3   /* AESM_POWERLATCH_MODE */
#define AESM_AESM_ST4_ENTRY             AESM_vidEntryAESM_ST4   /* AESM_POWER_OFF_MODE */


/*----------------------------------------------------------------------------*/
/* AESM during functions                                                       */
/*----------------------------------------------------------------------------*/

#define AESM_AESM_ST0_ON_AESM_EV0_DURING             AESM_vidDuringAESM_ST0OnAESM_EV0   /* During function for STARTUP_I_MODE on event SCHED_5MS */
#define AESM_AESM_ST0_ON_AESM_EV1_DURING             AESM_vidDuringAESM_ST0OnAESM_EV1   /* During function for STARTUP_I_MODE on event GO2_STARTUP_I */

#define AESM_AESM_ST1_ON_AESM_EV0_DURING             AESM_vidDuringAESM_ST1OnAESM_EV0   /* During function for STARTUP_II_MODE on event SCHED_5MS */
#define AESM_AESM_ST1_ON_AESM_EV1_DURING             AESM_vidDuringAESM_ST1OnAESM_EV1   /* During function for STARTUP_II_MODE on event GO2_STARTUP_I */

#define AESM_AESM_ST2_ON_AESM_EV0_DURING             AESM_vidDuringAESM_ST2OnAESM_EV0   /* During function for OPERATIONAL_MODE on event SCHED_5MS */
#define AESM_AESM_ST2_ON_AESM_EV1_DURING             AESM_vidDuringAESM_ST2OnAESM_EV1   /* During function for OPERATIONAL_MODE on event GO2_STARTUP_I */

#define AESM_AESM_ST3_ON_AESM_EV0_DURING             AESM_vidDuringAESM_ST3OnAESM_EV0   /* During function for POWERLATCH_MODE on event SCHED_5MS */
#define AESM_AESM_ST3_ON_AESM_EV1_DURING             AESM_vidDuringAESM_ST3OnAESM_EV1   /* During function for POWERLATCH_MODE on event GO2_STARTUP_I */

#define AESM_AESM_ST4_ON_AESM_EV0_DURING             AESM_vidDuringAESM_ST4OnAESM_EV0   /* During function for POWER_OFF_MODE on event SCHED_5MS */
#define AESM_AESM_ST4_ON_AESM_EV1_DURING             AESM_vidDuringAESM_ST4OnAESM_EV1   /* During function for POWER_OFF_MODE on event GO2_STARTUP_I */



/*----------------------------------------------------------------------------*/
/* AESM transition functions                                                   */
/*----------------------------------------------------------------------------*/

#define AESM_AESM_ST0_ON_AESM_EV0_TRANS         AESM_vidFromAESM_ST0OnAESM_EV0/* Transition function from STARTUP_I_MODE on event SCHED_5MS */
#define AESM_AESM_ST1_ON_AESM_EV0_TRANS         AESM_vidFromAESM_ST1OnAESM_EV0/* Transition function from STARTUP_II_MODE on event SCHED_5MS */
#define AESM_AESM_ST2_ON_AESM_EV0_TRANS         AESM_vidFromAESM_ST2OnAESM_EV0/* Transition function from OPERATIONAL_MODE on event SCHED_5MS */
#define AESM_AESM_ST3_ON_AESM_EV0_TRANS         AESM_vidFromAESM_ST3OnAESM_EV0/* Transition function from POWERLATCH_MODE on event SCHED_5MS */
#define AESM_AESM_ST4_ON_AESM_EV0_TRANS         AESM_ON_EVENT_NO_ACTION      /* Transition function from POWER_OFF_MODE on event SCHED_5MS */

#define AESM_AESM_ST0_ON_AESM_EV1_TRANS         AESM_ON_EVENT_NO_ACTION      /* Transition function from STARTUP_I_MODE on event GO2_STARTUP_I */
#define AESM_AESM_ST1_ON_AESM_EV1_TRANS         AESM_vidFromAESM_ST1OnAESM_EV1/* Transition function from STARTUP_II_MODE on event GO2_STARTUP_I */
#define AESM_AESM_ST2_ON_AESM_EV1_TRANS         AESM_vidFromAESM_ST2OnAESM_EV1/* Transition function from OPERATIONAL_MODE on event GO2_STARTUP_I */
#define AESM_AESM_ST3_ON_AESM_EV1_TRANS         AESM_vidFromAESM_ST3OnAESM_EV1/* Transition function from POWERLATCH_MODE on event GO2_STARTUP_I */
#define AESM_AESM_ST4_ON_AESM_EV1_TRANS         AESM_vidFromAESM_ST4OnAESM_EV1/* Transition function from POWER_OFF_MODE on event GO2_STARTUP_I */



/*----------------------------------------------------------------------------*/
/* AESM tempo data                                                             */
/*----------------------------------------------------------------------------*/
#define AESM_TEMPO_AESM_POWERLATCH_TEMPO_VAR     AESM_u16PowerLatchTempo
#define AESM_TEMPO_AESM_POWERLATCH_TEMPO_INIT    AESM_u16PowerLatchTempoC


/******************************************************************************/
/* DATA DECLARATION                                                           */
/******************************************************************************/

#define ASTFSRV_START_SEC_CODE
#include "MemMap.h"

FUNC (void, ASTFSRV_CODE) AESM_vidOnAESM_EV0(void);
FUNC (void, ASTFSRV_CODE) AESM_vidOnAESM_EV1(void);

FUNC(void, ASTFSRV_CODE) AESM_vidExecOutEvent(uint16 bfCarrier);

FUNC (void, ASTFSRV_CODE) AESM_vidNoAction(void);

FUNC (void, ASTFSRV_CODE) AESM_vidEntryAESM_ST0(void);
FUNC (void, ASTFSRV_CODE) AESM_vidEntryAESM_ST1(void);
FUNC (void, ASTFSRV_CODE) AESM_vidEntryAESM_ST2(void);
FUNC (void, ASTFSRV_CODE) AESM_vidEntryAESM_ST3(void);
FUNC (void, ASTFSRV_CODE) AESM_vidEntryAESM_ST4(void);


FUNC (void, ASTFSRV_CODE) AESM_vidDuringAESM_ST0OnAESM_EV0(void);
FUNC (void, ASTFSRV_CODE) AESM_vidDuringAESM_ST0OnAESM_EV1(void);

FUNC (void, ASTFSRV_CODE) AESM_vidDuringAESM_ST1OnAESM_EV0(void);
FUNC (void, ASTFSRV_CODE) AESM_vidDuringAESM_ST1OnAESM_EV1(void);

FUNC (void, ASTFSRV_CODE) AESM_vidDuringAESM_ST2OnAESM_EV0(void);
FUNC (void, ASTFSRV_CODE) AESM_vidDuringAESM_ST2OnAESM_EV1(void);

FUNC (void, ASTFSRV_CODE) AESM_vidDuringAESM_ST3OnAESM_EV0(void);
FUNC (void, ASTFSRV_CODE) AESM_vidDuringAESM_ST3OnAESM_EV1(void);

FUNC (void, ASTFSRV_CODE) AESM_vidDuringAESM_ST4OnAESM_EV0(void);
FUNC (void, ASTFSRV_CODE) AESM_vidDuringAESM_ST4OnAESM_EV1(void);



FUNC (void, ASTFSRV_CODE) AESM_vidFromAESM_ST0OnAESM_EV0(void);
FUNC (void, ASTFSRV_CODE) AESM_vidFromAESM_ST1OnAESM_EV0(void);
FUNC (void, ASTFSRV_CODE) AESM_vidFromAESM_ST2OnAESM_EV0(void);
FUNC (void, ASTFSRV_CODE) AESM_vidFromAESM_ST3OnAESM_EV0(void);

FUNC (void, ASTFSRV_CODE) AESM_vidFromAESM_ST1OnAESM_EV1(void);
FUNC (void, ASTFSRV_CODE) AESM_vidFromAESM_ST2OnAESM_EV1(void);
FUNC (void, ASTFSRV_CODE) AESM_vidFromAESM_ST3OnAESM_EV1(void);
FUNC (void, ASTFSRV_CODE) AESM_vidFromAESM_ST4OnAESM_EV1(void);


#define ASTFSRV_STOP_SEC_CODE
#include "MemMap.h"


#define ASTFSRV_START_SEC_VAR_16BIT
#include "MemMap.h"

extern VAR (uint16, ASTFSRV_VAR) AESM_bfOutEventCarrier;

#define ASTFSRV_STOP_SEC_VAR_16BIT
#include "MemMap.h"


#define ASTFSRV_START_SEC_VAR_UNSPECIFIED
#include "MemMap.h"

extern VAR (ASTFSRV_tpfFunctionPointerType, ASTFSRV_VAR) AESM_pfTransAESM_STF0OnAESM_EV0Ptr;

extern VAR (ASTFSRV_tpfFunctionPointerType, ASTFSRV_VAR) AESM_pfTransAESM_STF0OnAESM_EV1Ptr;

extern VAR (ASTFSRV_tpfFunctionPointerType, ASTFSRV_VAR) AESM_pfDuringAESM_STF0OnAESM_EV0Ptr;

extern VAR (ASTFSRV_tpfFunctionPointerType, ASTFSRV_VAR) AESM_pfDuringAESM_STF0OnAESM_EV1Ptr;



#define ASTFSRV_STOP_SEC_VAR_UNSPECIFIED
#include "MemMap.h"

#endif /* AESM_DAT_H */

/*------------------------------ END OF FILE ---------------------------------*/
