/******************************************************************************/
/*                                                                            */
/* !Layer           : SRVL                                                    */
/*                                                                            */
/* !Component       : AESM                                                     */
/* !Description     : StateFlow of AESM component                              */
/*                                                                            */
/* !File            : AESM_DAT.C                                               */
/*                                                                            */
/* !Scope           : Public                                                  */
/*                                                                            */
/* !Target          : All                                                     */
/*                                                                            */
/* !Vendor          : invt                                                    */
/*                                                                            */
/* Coding language  : C                                                       */
/*                                                                            */
/* COPYRIGHT 2007 invt                                                        */
/* all rights reserved                                                        */
/*                                                                            */
/******************************************************************************/
/** 10/27/22, 09:10:37: generated by Genecode v2.6.0.0                        */
/* From Source Template : ASTFSRV_DAT_C.TPL                                    */
/******************************************************************************/


#include "Std_Types.h"
#include "astfsrv_types.h"
#include "AESM_DAT.h"


/******************************************************************************/
/* DATA DECLARATION                                                           */
/******************************************************************************/

/*----------------------------------------------------------------------------*/
/* AESM On event transition pointers                                           */
/*----------------------------------------------------------------------------*/

/* Stateflows :  ECU_STATE <=> AESM_STF0 */
/* Events :  IN_EVENT <=> AESM_EV0, IN_EVENT <=> AESM_EV1 */

#define ASTFSRV_START_SEC_VAR_UNSPECIFIED
#include "MemMap.h"

VAR (ASTFSRV_tpfFunctionPointerType, ASTFSRV_VAR) AESM_pfTransAESM_STF0OnAESM_EV0Ptr;
VAR (ASTFSRV_tpfFunctionPointerType, ASTFSRV_VAR) AESM_pfTransAESM_STF0OnAESM_EV1Ptr;
VAR (ASTFSRV_tpfFunctionPointerType, ASTFSRV_VAR) AESM_pfDuringAESM_STF0OnAESM_EV0Ptr;
VAR (ASTFSRV_tpfFunctionPointerType, ASTFSRV_VAR) AESM_pfDuringAESM_STF0OnAESM_EV1Ptr;

#define ASTFSRV_STOP_SEC_VAR_UNSPECIFIED
#include "MemMap.h"


#define ASTFSRV_START_SEC_VAR_16BIT
#include "MemMap.h"

VAR (uint16, ASTFSRV_VAR) AESM_bfOutEventCarrier;

#define ASTFSRV_STOP_SEC_VAR_16BIT
#include "MemMap.h"


/******************************************************************************/
/* GLOBAL FUNCTION DEFINITION                                                 */
/******************************************************************************/

/*----------------------------------------------------------------------------*/
/* AESM common data                                                            */
/*----------------------------------------------------------------------------*/

#define ASTFSRV_START_SEC_CODE
#include "MemMap.h"

FUNC (void, ASTFSRV_CODE) AESM_vidNoAction(void){}

#define ASTFSRV_STOP_SEC_CODE
#include "MemMap.h"

/*-------------------------------- END OF FILE -------------------------------*/
