/******************************************************************************/
/*                                                                            */
/* !Layer           : SRVL                                                    */
/*                                                                            */
/* !Component       : AESM                                                     */
/* !Description     : StateFlow of AESM component                              */
/*                                                                            */
/* !File            : AESM_STA.C                                               */
/*                                                                            */
/* !Scope           : Public                                                  */
/*                                                                            */
/* !Target          : All                                                     */
/*                                                                            */
/* !Vendor          : invt                                                    */
/*                                                                            */
/* Coding language  : C                                                       */
/*                                                                            */
/* COPYRIGHT 2007 invt                                                        */
/* all rights reserved                                                        */
/*                                                                            */
/******************************************************************************/
/** 10/27/22, 09:10:37: generated by Genecode v2.6.0.0                        */
/* From Source Template : ASTFSRV_STA_C.TPL                                    */
/******************************************************************************/

#include "Std_Types.h"
#include "aesm_tra.h"
#include "aesm_dat.h"
#include "astfsrv_Includes.h"


/******************************************************************************/
/* GLOBAL FUNCTION DEFINITION                                                 */
/******************************************************************************/

/*----------------------------------------------------------------------------*/
/* AESM Stateflow Entry definition                                             */
/*----------------------------------------------------------------------------*/

#define ASTFSRV_START_SEC_CODE
#include "MemMap.h"

/* -------- AESM Stateflow ECU_STATE -------- */
/* ENTRY FUNCTIONS */

/* ENTRY FUNCTION FOR STARTUP_I_MODE*/
FUNC (void, ASTFSRV_CODE) AESM_vidEntryAESM_ST0(void)
{
   AESM_pfTransAESM_STF0OnAESM_EV0Ptr = AESM_AESM_ST0_ON_AESM_EV0_TRANS;
   AESM_pfTransAESM_STF0OnAESM_EV1Ptr = AESM_AESM_ST0_ON_AESM_EV1_TRANS;
   AESM_pfDuringAESM_STF0OnAESM_EV0Ptr = AESM_AESM_ST0_ON_AESM_EV0_DURING;
   AESM_pfDuringAESM_STF0OnAESM_EV1Ptr = AESM_AESM_ST0_ON_AESM_EV1_DURING;
   AESM_vidInit();
}

/* ENTRY FUNCTION FOR STARTUP_II_MODE*/
FUNC (void, ASTFSRV_CODE) AESM_vidEntryAESM_ST1(void)
{
   AESM_pfTransAESM_STF0OnAESM_EV0Ptr = AESM_AESM_ST1_ON_AESM_EV0_TRANS;
   AESM_pfTransAESM_STF0OnAESM_EV1Ptr = AESM_AESM_ST1_ON_AESM_EV1_TRANS;
   AESM_pfDuringAESM_STF0OnAESM_EV0Ptr = AESM_AESM_ST1_ON_AESM_EV0_DURING;
   AESM_pfDuringAESM_STF0OnAESM_EV1Ptr = AESM_AESM_ST1_ON_AESM_EV1_DURING;
}

/* ENTRY FUNCTION FOR OPERATIONAL_MODE*/
FUNC (void, ASTFSRV_CODE) AESM_vidEntryAESM_ST2(void)
{
   AESM_pfTransAESM_STF0OnAESM_EV0Ptr = AESM_AESM_ST2_ON_AESM_EV0_TRANS;
   AESM_pfTransAESM_STF0OnAESM_EV1Ptr = AESM_AESM_ST2_ON_AESM_EV1_TRANS;
   AESM_pfDuringAESM_STF0OnAESM_EV0Ptr = AESM_AESM_ST2_ON_AESM_EV0_DURING;
   AESM_pfDuringAESM_STF0OnAESM_EV1Ptr = AESM_AESM_ST2_ON_AESM_EV1_DURING;
}

/* ENTRY FUNCTION FOR POWERLATCH_MODE*/
FUNC (void, ASTFSRV_CODE) AESM_vidEntryAESM_ST3(void)
{
   AESM_pfTransAESM_STF0OnAESM_EV0Ptr = AESM_AESM_ST3_ON_AESM_EV0_TRANS;
   AESM_pfTransAESM_STF0OnAESM_EV1Ptr = AESM_AESM_ST3_ON_AESM_EV1_TRANS;
   AESM_pfDuringAESM_STF0OnAESM_EV0Ptr = AESM_AESM_ST3_ON_AESM_EV0_DURING;
   AESM_pfDuringAESM_STF0OnAESM_EV1Ptr = AESM_AESM_ST3_ON_AESM_EV1_DURING;
   ASTFSRV_vidINIT_TEMPO(AESM, AESM_POWERLATCH_TEMPO);
}

/* ENTRY FUNCTION FOR POWER_OFF_MODE*/
FUNC (void, ASTFSRV_CODE) AESM_vidEntryAESM_ST4(void)
{
   AESM_pfTransAESM_STF0OnAESM_EV0Ptr = AESM_AESM_ST4_ON_AESM_EV0_TRANS;
   AESM_pfTransAESM_STF0OnAESM_EV1Ptr = AESM_AESM_ST4_ON_AESM_EV1_TRANS;
   AESM_pfDuringAESM_STF0OnAESM_EV0Ptr = AESM_AESM_ST4_ON_AESM_EV0_DURING;
   AESM_pfDuringAESM_STF0OnAESM_EV1Ptr = AESM_AESM_ST4_ON_AESM_EV1_DURING;
}


/* DURING FUNCTIONS */

/* DURING FUNCTION FOR STARTUP_I_MODE ON SCHED_5MS*/
FUNC (void, ASTFSRV_CODE) AESM_vidDuringAESM_ST0OnAESM_EV0(void)
{
   AESM_vidStfStpI();
}

/* DURING FUNCTION FOR STARTUP_I_MODE ON GO2_STARTUP_I*/
FUNC (void, ASTFSRV_CODE) AESM_vidDuringAESM_ST0OnAESM_EV1(void)
{
   AESM_vidStfStpI();
}


/* DURING FUNCTION FOR STARTUP_II_MODE ON SCHED_5MS*/
FUNC (void, ASTFSRV_CODE) AESM_vidDuringAESM_ST1OnAESM_EV0(void)
{
   AESM_vidStfStpII();
}

/* DURING FUNCTION FOR STARTUP_II_MODE ON GO2_STARTUP_I*/
FUNC (void, ASTFSRV_CODE) AESM_vidDuringAESM_ST1OnAESM_EV1(void)
{
   AESM_vidStfStpII();
}


/* DURING FUNCTION FOR OPERATIONAL_MODE ON SCHED_5MS*/
FUNC (void, ASTFSRV_CODE) AESM_vidDuringAESM_ST2OnAESM_EV0(void)
{
   AESM_vidStfOp();
}

/* DURING FUNCTION FOR OPERATIONAL_MODE ON GO2_STARTUP_I*/
FUNC (void, ASTFSRV_CODE) AESM_vidDuringAESM_ST2OnAESM_EV1(void)
{
   AESM_vidStfOp();
}


/* DURING FUNCTION FOR POWERLATCH_MODE ON SCHED_5MS*/
FUNC (void, ASTFSRV_CODE) AESM_vidDuringAESM_ST3OnAESM_EV0(void)
{
   AESM_vidStfPwrL();
   ASTFSRV_vidDEC_TEMPO(AESM, AESM_POWERLATCH_TEMPO);
}

/* DURING FUNCTION FOR POWERLATCH_MODE ON GO2_STARTUP_I*/
FUNC (void, ASTFSRV_CODE) AESM_vidDuringAESM_ST3OnAESM_EV1(void)
{
   AESM_vidStfPwrL();
}


/* DURING FUNCTION FOR POWER_OFF_MODE ON SCHED_5MS*/
FUNC (void, ASTFSRV_CODE) AESM_vidDuringAESM_ST4OnAESM_EV0(void)
{
   AESM_vidStfPwrL();
}

/* DURING FUNCTION FOR POWER_OFF_MODE ON GO2_STARTUP_I*/
FUNC (void, ASTFSRV_CODE) AESM_vidDuringAESM_ST4OnAESM_EV1(void)
{
   AESM_vidStfPwrL();
}



/* IN EVENT EXEC FUNCTION */

FUNC (void, ASTFSRV_CODE) AESM_vidOnAESM_EV0(void)
{
   ASTFSRV_vidINTERNAL_SET_EVENT(AESM, AESM_STF0, AESM_EV0);
}
FUNC (void, ASTFSRV_CODE) AESM_vidOnAESM_EV1(void)
{
   ASTFSRV_vidINTERNAL_SET_EVENT(AESM, AESM_STF0, AESM_EV1);
}


/* OUT EVENT EXEC FUNCTION */

FUNC (void, ASTFSRV_CODE) AESM_vidExecOutEvent(uint16 bfCarrier)
{
   if ((bfCarrier & GO2_STARTUP_I_EVENT) != 0)
   {
      GGO2_STARTUP_I_EVENT_ACTION;
   }
   if ((bfCarrier & GO2_STARTUP_II_EVENT) != 0)
   {
      GGO2_STARTUP_II_EVENT_ACTION;
   }
   if ((bfCarrier & GO2_OPERATIONAL_EVENT) != 0)
   {
      GGO2_OPERATIONAL_EVENT_ACTION;
   }
   if ((bfCarrier & GO2_POWERLATCH_EVENT) != 0)
   {
      GGO2_POWERLATCH_EVENT_ACTION;
   }
   if ((bfCarrier & GO2_POWER_OFF_EVENT) != 0)
   {
      GGO2_POWER_OFF_EVENT_ACTION;
   }
}


#define ASTFSRV_STOP_SEC_CODE
#include "MemMap.h"


/*-------------------------------- END OF FILE -------------------------------*/