/******************************************************************************/
/*                                                                            */
/* !Layer           : SRVL                                                    */
/*                                                                            */
/* !Component       : AESM                                                     */
/* !Description     : StateFlow of AESM component                              */
/*                                                                            */
/* !File            : AESM_TRA.H                                               */
/*                                                                            */
/* !Scope           : Public                                                  */
/*                                                                            */
/* !Target          : All                                                     */
/*                                                                            */
/* !Vendor          : invt                                                    */
/*                                                                            */
/* Coding language  : C                                                       */
/*                                                                            */
/* COPYRIGHT 2007 invt                                                        */
/* all rights reserved                                                        */
/*                                                                            */
/******************************************************************************/
/** 10/27/22, 09:10:37: generated by Genecode v2.6.0.0                        */
/* From Source Template : ASTFSRV_TRA_H.TPL                                    */
/******************************************************************************/

#ifndef AESM_TRA_H
#define AESM_TRA_H

#include "Std_Types.h"
#include "aesm_dat.h"
#include "astfsrv_Includes.h"


/******************************************************************************/
/* MACRO FUNCTIONS                                                            */
/******************************************************************************/

/*----------------------------------------------------------------------------*/
/* AESM Stateflow transitions definition                                       */
/*----------------------------------------------------------------------------*/

/* -------- AESM Stateflow ECU_STATE -------- */

/* SCHED_5MS Event */
/* GO2_STARTUP_I Event */


#endif /* AESM_TRA_H */

/*-------------------------------- END OF FILE -------------------------------*/
