

#ifndef DCMDSPUDS_RMBA_PUB_H
#define DCMDSPUDS_RMBA_PUB_H

#if((DCM_CFG_DSP_READMEMORYBYADDRESS_ENABLED != DCM_CFG_OFF)||(DCM_CFG_DSP_TRANSFERDATA_ENABLED!= DCM_CFG_OFF))
/**
 * @ingroup DCMDSP_UDS_EXTENDED
 * Dcm_RmbaSupportRet_t:\n
 * DCM_RMBA_SUPPORT_OK,\n
 * DCM_RMBA_SUPPORT_SESSION_VIOLATED,\n
 * DCM_RMBA_SUPPORT_SECURITY_VIOLATED,\n
 * DCM_RMBA_SUPPORT_CONDITION_VIOLATED
 */
typedef enum
{
    DCM_RMBA_SUPPORT_OK,
    DCM_RMBA_SUPPORT_SESSION_VIOLATED,
    DCM_RMBA_SUPPORT_SECURITY_VIOLATED,
    DCM_RMBA_SUPPORT_CONDITION_VIOLATED
} Dcm_RmbaSupportRet_t;




#endif

#endif /* _DCMDSPUDS_RMBA_PUB_H  */

