/******************************************************************************/
/*                                                                            */
/* !Layer           : SRVL                                                    */
/*                                                                            */
/* !Component       : OESM                                                     */
/* !Description     : StateFlow of OESM component                              */
/*                                                                            */
/* !File            : OESM_STA.C                                               */
/*                                                                            */
/* !Scope           : Public                                                  */
/*                                                                            */
/* !Target          : All                                                     */
/*                                                                            */
/* !Vendor          : invt                                                    */
/*                                                                            */
/* Coding language  : C                                                       */
/*                                                                            */
/* COPYRIGHT 2007 invt                                                        */
/* all rights reserved                                                        */
/*                                                                            */
/******************************************************************************/
/** 10/27/22, 09:10:37: generated by Genecode v2.6.0.0                        */
/* From Source Template : OSTFSRV_STA_C.TPL                                    */
/******************************************************************************/

#include "Std_Types.h"
#include "oesm_tra.h"
#include "oesm_dat.h"
#include "ostfsrv_Includes.h"


/******************************************************************************/
/* GLOBAL FUNCTION DEFINITION                                                 */
/******************************************************************************/

/*----------------------------------------------------------------------------*/
/* OESM Stateflow Entry definition                                             */
/*----------------------------------------------------------------------------*/

#define OSTFSRV_START_SEC_CODE
#include "MemMap.h"

/* -------- OESM Stateflow ECU_STATE -------- */
/* ENTRY FUNCTIONS */

/* ENTRY FUNCTION FOR STARTUP_I_MODE*/
FUNC (void, OSTFSRV_CODE) OESM_vidEntryOESM_ST0(void)
{
   OESM_pfTransOESM_STF0OnOESM_EV0Ptr = OESM_OESM_ST0_ON_OESM_EV0_TRANS;
   OESM_pfTransOESM_STF0OnOESM_EV1Ptr = OESM_OESM_ST0_ON_OESM_EV1_TRANS;
   OESM_pfDuringOESM_STF0OnOESM_EV0Ptr = OESM_OESM_ST0_ON_OESM_EV0_DURING;
   OESM_pfDuringOESM_STF0OnOESM_EV1Ptr = OESM_OESM_ST0_ON_OESM_EV1_DURING;
   OESM_vidInit();
}

/* ENTRY FUNCTION FOR STARTUP_II_MODE*/
FUNC (void, OSTFSRV_CODE) OESM_vidEntryOESM_ST1(void)
{
   OESM_pfTransOESM_STF0OnOESM_EV0Ptr = OESM_OESM_ST1_ON_OESM_EV0_TRANS;
   OESM_pfTransOESM_STF0OnOESM_EV1Ptr = OESM_OESM_ST1_ON_OESM_EV1_TRANS;
   OESM_pfDuringOESM_STF0OnOESM_EV0Ptr = OESM_OESM_ST1_ON_OESM_EV0_DURING;
   OESM_pfDuringOESM_STF0OnOESM_EV1Ptr = OESM_OESM_ST1_ON_OESM_EV1_DURING;
}

/* ENTRY FUNCTION FOR OPERATIONAL_MODE*/
FUNC (void, OSTFSRV_CODE) OESM_vidEntryOESM_ST2(void)
{
   OESM_pfTransOESM_STF0OnOESM_EV0Ptr = OESM_OESM_ST2_ON_OESM_EV0_TRANS;
   OESM_pfTransOESM_STF0OnOESM_EV1Ptr = OESM_OESM_ST2_ON_OESM_EV1_TRANS;
   OESM_pfDuringOESM_STF0OnOESM_EV0Ptr = OESM_OESM_ST2_ON_OESM_EV0_DURING;
   OESM_pfDuringOESM_STF0OnOESM_EV1Ptr = OESM_OESM_ST2_ON_OESM_EV1_DURING;
}

/* ENTRY FUNCTION FOR POWERLATCH_MODE*/
FUNC (void, OSTFSRV_CODE) OESM_vidEntryOESM_ST3(void)
{
   OESM_pfTransOESM_STF0OnOESM_EV0Ptr = OESM_OESM_ST3_ON_OESM_EV0_TRANS;
   OESM_pfTransOESM_STF0OnOESM_EV1Ptr = OESM_OESM_ST3_ON_OESM_EV1_TRANS;
   OESM_pfDuringOESM_STF0OnOESM_EV0Ptr = OESM_OESM_ST3_ON_OESM_EV0_DURING;
   OESM_pfDuringOESM_STF0OnOESM_EV1Ptr = OESM_OESM_ST3_ON_OESM_EV1_DURING;
   OSTFSRV_vidINIT_TEMPO(OESM, OESM_POWERLATCH_TEMPO);
}

/* ENTRY FUNCTION FOR POWER_OFF_MODE*/
FUNC (void, OSTFSRV_CODE) OESM_vidEntryOESM_ST4(void)
{
   OESM_pfTransOESM_STF0OnOESM_EV0Ptr = OESM_OESM_ST4_ON_OESM_EV0_TRANS;
   OESM_pfTransOESM_STF0OnOESM_EV1Ptr = OESM_OESM_ST4_ON_OESM_EV1_TRANS;
   OESM_pfDuringOESM_STF0OnOESM_EV0Ptr = OESM_OESM_ST4_ON_OESM_EV0_DURING;
   OESM_pfDuringOESM_STF0OnOESM_EV1Ptr = OESM_OESM_ST4_ON_OESM_EV1_DURING;
}


/* DURING FUNCTIONS */

/* DURING FUNCTION FOR STARTUP_I_MODE ON SCHED_5MS*/
FUNC (void, OSTFSRV_CODE) OESM_vidDuringOESM_ST0OnOESM_EV0(void)
{
   OESM_vidStfStpI();
}

/* DURING FUNCTION FOR STARTUP_I_MODE ON GO2_STARTUP_I*/
FUNC (void, OSTFSRV_CODE) OESM_vidDuringOESM_ST0OnOESM_EV1(void)
{
   OESM_vidStfStpI();
}


/* DURING FUNCTION FOR STARTUP_II_MODE ON SCHED_5MS*/
FUNC (void, OSTFSRV_CODE) OESM_vidDuringOESM_ST1OnOESM_EV0(void)
{
   OESM_vidStfStpII();
}

/* DURING FUNCTION FOR STARTUP_II_MODE ON GO2_STARTUP_I*/
FUNC (void, OSTFSRV_CODE) OESM_vidDuringOESM_ST1OnOESM_EV1(void)
{
   OESM_vidStfStpII();
}


/* DURING FUNCTION FOR OPERATIONAL_MODE ON SCHED_5MS*/
FUNC (void, OSTFSRV_CODE) OESM_vidDuringOESM_ST2OnOESM_EV0(void)
{
   OESM_vidStfOp();
}

/* DURING FUNCTION FOR OPERATIONAL_MODE ON GO2_STARTUP_I*/
FUNC (void, OSTFSRV_CODE) OESM_vidDuringOESM_ST2OnOESM_EV1(void)
{
   OESM_vidStfOp();
}


/* DURING FUNCTION FOR POWERLATCH_MODE ON SCHED_5MS*/
FUNC (void, OSTFSRV_CODE) OESM_vidDuringOESM_ST3OnOESM_EV0(void)
{
   OESM_vidStfPwrL();
   OSTFSRV_vidDEC_TEMPO(OESM, OESM_POWERLATCH_TEMPO);
}

/* DURING FUNCTION FOR POWERLATCH_MODE ON GO2_STARTUP_I*/
FUNC (void, OSTFSRV_CODE) OESM_vidDuringOESM_ST3OnOESM_EV1(void)
{
   OESM_vidStfPwrL();
}


/* DURING FUNCTION FOR POWER_OFF_MODE ON SCHED_5MS*/
FUNC (void, OSTFSRV_CODE) OESM_vidDuringOESM_ST4OnOESM_EV0(void)
{
   OESM_vidStfPwrL();
}

/* DURING FUNCTION FOR POWER_OFF_MODE ON GO2_STARTUP_I*/
FUNC (void, OSTFSRV_CODE) OESM_vidDuringOESM_ST4OnOESM_EV1(void)
{
   OESM_vidStfPwrL();
}



/* IN EVENT EXEC FUNCTION */

FUNC (void, OSTFSRV_CODE) OESM_vidOnOESM_EV0(void)
{
   OSTFSRV_vidINTERNAL_SET_EVENT(OESM, OESM_STF0, OESM_EV0);
}
FUNC (void, OSTFSRV_CODE) OESM_vidOnOESM_EV1(void)
{
   OSTFSRV_vidINTERNAL_SET_EVENT(OESM, OESM_STF0, OESM_EV1);
}


/* OUT EVENT EXEC FUNCTION */

FUNC (void, OSTFSRV_CODE) OESM_vidExecOutEvent(uint16 bfCarrier)
{
   if ((bfCarrier & GO2_STARTUP_I_EVENT) != 0)
   {
      GGO2_STARTUP_I_EVENT_ACTION;
   }
   if ((bfCarrier & GO2_STARTUP_II_EVENT) != 0)
   {
      GGO2_STARTUP_II_EVENT_ACTION;
   }
   if ((bfCarrier & GO2_OPERATIONAL_EVENT) != 0)
   {
      GGO2_OPERATIONAL_EVENT_ACTION;
   }
   if ((bfCarrier & GO2_POWERLATCH_EVENT) != 0)
   {
      GGO2_POWERLATCH_EVENT_ACTION;
   }
   if ((bfCarrier & GO2_POWER_OFF_EVENT) != 0)
   {
      GGO2_POWER_OFF_EVENT_ACTION;
   }
}


#define OSTFSRV_STOP_SEC_CODE
#include "MemMap.h"


/*-------------------------------- END OF FILE -------------------------------*/