/******************************************************************************/
/*                                                                            */
/* !Layer           : SRVL                                                    */
/*                                                                            */
/* !Component       : OESM                                                     */
/* !Description     : StateFlow of OESM component                              */
/*                                                                            */
/* !File            : OESM_TRA.H                                               */
/*                                                                            */
/* !Scope           : Public                                                  */
/*                                                                            */
/* !Target          : All                                                     */
/*                                                                            */
/* !Vendor          : invt                                                    */
/*                                                                            */
/* Coding language  : C                                                       */
/*                                                                            */
/* COPYRIGHT 2007 invt                                                        */
/* all rights reserved                                                        */
/*                                                                            */
/******************************************************************************/
/** 10/27/22, 09:10:37: generated by Genecode v2.6.0.0                        */
/* From Source Template : OSTFSRV_TRA_H.TPL                                    */
/******************************************************************************/

#ifndef OESM_TRA_H
#define OESM_TRA_H

#include "Std_Types.h"
#include "oesm_dat.h"
#include "ostfsrv_Includes.h"


/******************************************************************************/
/* MACRO FUNCTIONS                                                            */
/******************************************************************************/

/*----------------------------------------------------------------------------*/
/* OESM Stateflow transitions definition                                       */
/*----------------------------------------------------------------------------*/

/* -------- OESM Stateflow ECU_STATE -------- */

/* SCHED_5MS Event */
/* GO2_STARTUP_I Event */


#endif /* OESM_TRA_H */

/*-------------------------------- END OF FILE -------------------------------*/
