/******************************************************************************/
/*                                                                            */
/* !Layer           : SRVL                                                    */
/*                                                                            */
/* !Component       : OESM                                                     */
/* !Description     : StateFlow of OESM component                              */
/*                                                                            */
/* !File            : OESM_TRA.C                                               */
/*                                                                            */
/* !Scope           : Public                                                  */
/*                                                                            */
/* !Target          : All                                                     */
/*                                                                            */
/* !Vendor          : invt                                                    */
/*                                                                            */
/* Coding language  : C                                                       */
/*                                                                            */
/* COPYRIGHT 2007 invt                                                        */
/* all rights reserved                                                        */
/*                                                                            */
/******************************************************************************/
/** 10/27/22, 09:10:37: generated by Genecode v2.6.0.0                        */
/* From Source Template : OSTFSRV_TRA_C.TPL                                    */
/******************************************************************************/

#include "Std_Types.h"
#include "oesm_tra.h"
#include "oesm_dat.h"


/******************************************************************************/
/* GLOBAL FUNCTION DEFINITION                                                 */
/******************************************************************************/

/*----------------------------------------------------------------------------*/
/* OESM Stateflow transitions definition                                       */
/*----------------------------------------------------------------------------*/

#define OSTFSRV_START_SEC_CODE
#include "MemMap.h"

/* -------- OESM Stateflow ECU_STATE -------- */


/* SCHED_5MS Event */

/* TRANSITION FROM STARTUP_I_MODE*/

FUNC (void, OSTFSRV_CODE) OESM_vidFromOESM_ST0OnOESM_EV0(void)
{
   if((OESM_StpIState == OESM_SFT_STATE_15))
   {
      OESM_bfOutEventCarrier |= GO2_STARTUP_II_EVENT; 
      OSTFSRV_vidSET_ACTIVE_STATE(OESM, OESM_STF0, OESM_ST1);   /* Activation of state STARTUP_II_MODE for stateflow ECU_STATE */
   }
}

/* TRANSITION FROM STARTUP_II_MODE*/

FUNC (void, OSTFSRV_CODE) OESM_vidFromOESM_ST1OnOESM_EV0(void)
{
   if(((OESM_StpIINfState == OESM_SFT_STATE_15) || (OESM_StpIIFtState == OESM_SFT_STATE_15)))
   {
      OESM_bfOutEventCarrier |= GO2_OPERATIONAL_EVENT; 
      OSTFSRV_vidSET_ACTIVE_STATE(OESM, OESM_STF0, OESM_ST2);   /* Activation of state OPERATIONAL_MODE for stateflow ECU_STATE */
   }
}

/* TRANSITION FROM OPERATIONAL_MODE*/

FUNC (void, OSTFSRV_CODE) OESM_vidFromOESM_ST2OnOESM_EV0(void)
{
   if(((OESM_OpNfState == OESM_SFT_STATE_14) || (OESM_PwrLFtState == OESM_SFT_STATE_15)))
   {
          OESM_bfOutEventCarrier |= GO2_STARTUP_II_EVENT; 
          OSTFSRV_vidSET_ACTIVE_STATE(OESM, OESM_STF0, OESM_ST1);  /* Activation of state STARTUP_II_MODE for stateflow ECU_STATE */
   }
   else
   {
      if((OESM_OpNfState == OESM_SFT_STATE_15))
      {
          OESM_bfOutEventCarrier |= GO2_POWERLATCH_EVENT; 
          OSTFSRV_vidSET_ACTIVE_STATE(OESM, OESM_STF0, OESM_ST3);  /* Activation of state POWERLATCH_MODE for stateflow ECU_STATE */
      }
   }
}

/* TRANSITION FROM POWERLATCH_MODE*/

FUNC (void, OSTFSRV_CODE) OESM_vidFromOESM_ST3OnOESM_EV0(void)
{
   if(((OESM_PwrLNfState == OESM_SFT_STATE_15) && (OESM_bPowerOffModeInhC == 0)))
   {
          OESM_bfOutEventCarrier |= GO2_POWER_OFF_EVENT; 
          OSTFSRV_vidSET_ACTIVE_STATE(OESM, OESM_STF0, OESM_ST4);  /* Activation of state POWER_OFF_MODE for stateflow ECU_STATE */
   }
   else
   {
      if((OESM_PwrLNfState == OESM_SFT_STATE_14))
      {
          OESM_bfOutEventCarrier |= GO2_STARTUP_II_EVENT; 
          OSTFSRV_vidSET_ACTIVE_STATE(OESM, OESM_STF0, OESM_ST1);  /* Activation of state STARTUP_II_MODE for stateflow ECU_STATE */
      }
   }
}


/* GO2_STARTUP_I Event */

/* TRANSITION FROM STARTUP_II_MODE*/

FUNC (void, OSTFSRV_CODE) OESM_vidFromOESM_ST1OnOESM_EV1(void)
{
      OESM_bfOutEventCarrier |= GO2_STARTUP_I_EVENT; 
      OSTFSRV_vidSET_ACTIVE_STATE(OESM, OESM_STF0, OESM_ST0);   /* Activation of state STARTUP_I_MODE for stateflow ECU_STATE */
}

/* TRANSITION FROM OPERATIONAL_MODE*/

FUNC (void, OSTFSRV_CODE) OESM_vidFromOESM_ST2OnOESM_EV1(void)
{
      OESM_bfOutEventCarrier |= GO2_STARTUP_I_EVENT; 
      OSTFSRV_vidSET_ACTIVE_STATE(OESM, OESM_STF0, OESM_ST0);   /* Activation of state STARTUP_I_MODE for stateflow ECU_STATE */
}

/* TRANSITION FROM POWERLATCH_MODE*/

FUNC (void, OSTFSRV_CODE) OESM_vidFromOESM_ST3OnOESM_EV1(void)
{
      OESM_bfOutEventCarrier |= GO2_STARTUP_I_EVENT; 
      OSTFSRV_vidSET_ACTIVE_STATE(OESM, OESM_STF0, OESM_ST0);   /* Activation of state STARTUP_I_MODE for stateflow ECU_STATE */
}

/* TRANSITION FROM POWER_OFF_MODE*/

FUNC (void, OSTFSRV_CODE) OESM_vidFromOESM_ST4OnOESM_EV1(void)
{
      OESM_bfOutEventCarrier |= GO2_STARTUP_I_EVENT; 
      OSTFSRV_vidSET_ACTIVE_STATE(OESM, OESM_STF0, OESM_ST0);   /* Activation of state STARTUP_I_MODE for stateflow ECU_STATE */
}




#define OSTFSRV_STOP_SEC_CODE
#include "MemMap.h"

/*-------------------------------- END OF FILE -------------------------------*/
