/******************************************************************************/
/*                                                                            */
/* !Layer           : SRVL                                                    */
/*                                                                            */
/* !Component       : OESM                                                     */
/* !Description     : StateFlow of OESM component                              */
/*                                                                            */
/* !File            : OESM_DAT.C                                               */
/*                                                                            */
/* !Scope           : Public                                                  */
/*                                                                            */
/* !Target          : All                                                     */
/*                                                                            */
/* !Vendor          : invt                                                    */
/*                                                                            */
/* Coding language  : C                                                       */
/*                                                                            */
/* COPYRIGHT 2007 invt                                                        */
/* all rights reserved                                                        */
/*                                                                            */
/******************************************************************************/
/** 10/27/22, 09:10:37: generated by Genecode v2.6.0.0                        */
/* From Source Template : OSTFSRV_DAT_C.TPL                                    */
/******************************************************************************/


#include "Std_Types.h"
#include "ostfsrv_types.h"
#include "OESM_DAT.h"


/******************************************************************************/
/* DATA DECLARATION                                                           */
/******************************************************************************/

/*----------------------------------------------------------------------------*/
/* OESM On event transition pointers                                           */
/*----------------------------------------------------------------------------*/

/* Stateflows :  ECU_STATE <=> OESM_STF0 */
/* Events :  IN_EVENT <=> OESM_EV0, IN_EVENT <=> OESM_EV1 */

#define OSTFSRV_START_SEC_VAR_UNSPECIFIED
#include "MemMap.h"

VAR (OSTFSRV_tpfFunctionPointerType, OSTFSRV_VAR) OESM_pfTransOESM_STF0OnOESM_EV0Ptr;
VAR (OSTFSRV_tpfFunctionPointerType, OSTFSRV_VAR) OESM_pfTransOESM_STF0OnOESM_EV1Ptr;
VAR (OSTFSRV_tpfFunctionPointerType, OSTFSRV_VAR) OESM_pfDuringOESM_STF0OnOESM_EV0Ptr;
VAR (OSTFSRV_tpfFunctionPointerType, OSTFSRV_VAR) OESM_pfDuringOESM_STF0OnOESM_EV1Ptr;

#define OSTFSRV_STOP_SEC_VAR_UNSPECIFIED
#include "MemMap.h"


#define OSTFSRV_START_SEC_VAR_16BIT
#include "MemMap.h"

VAR (uint16, OSTFSRV_VAR) OESM_bfOutEventCarrier;

#define OSTFSRV_STOP_SEC_VAR_16BIT
#include "MemMap.h"


/******************************************************************************/
/* GLOBAL FUNCTION DEFINITION                                                 */
/******************************************************************************/

/*----------------------------------------------------------------------------*/
/* OESM common data                                                            */
/*----------------------------------------------------------------------------*/

#define OSTFSRV_START_SEC_CODE
#include "MemMap.h"

FUNC (void, OSTFSRV_CODE) OESM_vidNoAction(void){}

#define OSTFSRV_STOP_SEC_CODE
#include "MemMap.h"

/*-------------------------------- END OF FILE -------------------------------*/
