/** @file     Core2_OsTask_ASW_1ms.c
  *
  * @brief    Task Core2_OsTask_ASW_1ms body
  *
  * @note     AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
  *
  * @note     Generated by ETAS RTA-RTE
  * @note     Version 7.5.3
  *
  * @date     Tue Apr  8 17:08:23 2025
  */

#define RTE_CORE

#include "Rte_Const.h"
#if !defined(RTE_VENDOR_MODE)
#pragma message "Compiling an individual task file but RTE_VENDOR_MODE not defined. Compiling a stale file?"
#endif /* !defined(RTE_VENDOR_MODE) */
#if defined(RTE_USE_TASK_HEADER)
#include "Core2_OsTask_ASW_1ms.h"
#else /* !defined(RTE_USE_TASK_HEADER) */
#include "Os.h"
#endif /* !defined(RTE_USE_TASK_HEADER) */
#if defined(RTE_REQUIRES_IOC)
#include "Ioc.h"
#endif /* defined(RTE_REQUIRES_IOC) */
#include "Rte.h"
#include "Rte_Intl.h"
#include "Rte_Type.h"
#include "Rte_DataHandleType.h"

#define RTE_CORE2_OSTASK_ASW_1MS_START_SEC_VAR_CLEARED_8
#include "Rte_MemMap.h"
extern VAR(uint8, RTE_DATA) Rte_RECount_Core2_OsTask_ASW_1ms_divby2_0;

#define RTE_CORE2_OSTASK_ASW_1MS_STOP_SEC_VAR_CLEARED_8
#include "Rte_MemMap.h"

/* Runnable entity prototypes */
#define ASW_CORE2_START_SEC_CODE
#include "ASW_CORE2_MemMap.h"
FUNC(void, ASW_CORE2_CODE) GMAIN_CORE2_1ms_func(void);
FUNC(void, ASW_CORE2_CODE) GMAIN_CORE2_2ms_func(void);
#define ASW_CORE2_STOP_SEC_CODE
#include "ASW_CORE2_MemMap.h"

#define RTE_CORE2_OSTASK_ASW_1MS_START_SEC_CODE
#include "Rte_MemMap.h"
TASK(Core2_OsTask_ASW_1ms)
{
   /* Box: Implicit Buffer Initialization begin */
   /* Box: Implicit Buffer Initialization end */
   /* Box: Implicit Buffer Fill begin */
   /* Box: Implicit Buffer Fill end */
   {
      /* Box: CPT_ASW_CORE2 begin */
      GMAIN_CORE2_1ms_func();
      /* Box: CPT_ASW_CORE2 end */
   }
   /* Box: CPT_ASW_CORE2 begin */
   if ( Rte_RECount_Core2_OsTask_ASW_1ms_divby2_0 == ((VAR(uint8, AUTOMATIC))0U) )
   {
      GMAIN_CORE2_2ms_func();
   }
   /* Box: CPT_ASW_CORE2 end */
   /* Box: Implicit Buffer Flush begin */
   /* Box: Implicit Buffer Flush end */
   if ( Rte_RECount_Core2_OsTask_ASW_1ms_divby2_0 != ((VAR(uint8, AUTOMATIC))0U) )
   {
      Rte_RECount_Core2_OsTask_ASW_1ms_divby2_0--;
   }
   else
   {
      Rte_RECount_Core2_OsTask_ASW_1ms_divby2_0 = ((VAR(uint8, AUTOMATIC))1);
   }
   TerminateTask();
} /* Core2_OsTask_ASW_1ms */
#define RTE_CORE2_OSTASK_ASW_1MS_STOP_SEC_CODE
#include "Rte_MemMap.h"

