/** @file     Core3_OsTask_ASW_1ms.c
  *
  * @brief    Task Core3_OsTask_ASW_1ms body
  *
  * @note     AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
  *
  * @note     Generated by ETAS RTA-RTE
  * @note     Version 7.5.3
  *
  * @date     Wed May 22 14:06:13 2024
  */

#define RTE_CORE

#include "Rte_Const.h"
#if !defined(RTE_VENDOR_MODE)
#pragma message "Compiling an individual task file but RTE_VENDOR_MODE not defined. Compiling a stale file?"
#endif /* !defined(RTE_VENDOR_MODE) */
#if defined(RTE_USE_TASK_HEADER)
#include "Core3_OsTask_ASW_1ms.h"
#else /* !defined(RTE_USE_TASK_HEADER) */
#include "Os.h"
#endif /* !defined(RTE_USE_TASK_HEADER) */
#if defined(RTE_REQUIRES_IOC)
#include "Ioc.h"
#endif /* defined(RTE_REQUIRES_IOC) */
#include "Rte.h"
#include "Rte_Intl.h"
#include "Rte_Type.h"
#include "Rte_DataHandleType.h"

/* Runnable entity prototypes */
#define ASW_CORE3_START_SEC_CODE
#include "ASW_CORE3_MemMap.h"
FUNC(void, ASW_CORE3_CODE) RE_CORE3_SWC_1ms_func(void);
#define ASW_CORE3_STOP_SEC_CODE
#include "ASW_CORE3_MemMap.h"

#define RTE_CORE3_OSTASK_ASW_1MS_START_SEC_CODE
#include "Rte_MemMap.h"
TASK(Core3_OsTask_ASW_1ms)
{
   /* Box: Implicit Buffer Initialization begin */
   /* Box: Implicit Buffer Initialization end */
   /* Box: Implicit Buffer Fill begin */
   /* Box: Implicit Buffer Fill end */
   {
      /* Box: CPT_ASW_CORE3 begin */
      RE_CORE3_SWC_1ms_func();
      /* Box: CPT_ASW_CORE3 end */
   }
   /* Box: Implicit Buffer Flush begin */
   /* Box: Implicit Buffer Flush end */
   TerminateTask();
} /* Core3_OsTask_ASW_1ms */
#define RTE_CORE3_OSTASK_ASW_1MS_STOP_SEC_CODE
#include "Rte_MemMap.h"

