/** @file     iocNeeds.h
  *
  * @brief    Initialisers required for correct IOC operation.
  *
  * @note     AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
  *
  * @note     Generated by ETAS RTA-RTE
  * @note     Version 7.5.3
  *
  * @date     Tue Mar 12 09:43:05 2024
  */

#ifndef RTE_IOCNEEDS_H
#define RTE_IOCNEEDS_H


#endif /* !RTE_IOCNEEDS_H */
