/** @file     Rte_ASW_CORE1.h
  *
  * @brief    Application header file
  *
  * @note     AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
  *
  * @note     Generated by ETAS RTA-RTE
  * @note     Version 7.5.3
  *
  * @date     Wed May 22 14:06:13 2024
  */

#ifndef RTE_ASW_CORE1_H
#define RTE_ASW_CORE1_H

#ifndef RTE_CORE
#ifdef RTE_APPLICATION_HEADER_FILE
#error Multiple application header files included.
#endif /* RTE_APPLICATION_HEADER_FILE */
#define RTE_APPLICATION_HEADER_FILE
#endif /* RTE_CORE */

/*******************************************************
 ***
 *** Includes
 ***
 *******************************************************/

#include "Rte.h"
#include "Rte_Intl.h"
#include "Rte_ASW_CORE1_Type.h"

#include "Rte_DataHandleType.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#if defined(RTE_RUNNABLEAPI_GMAIN_CORE1_1ms)
   /* Do nothing for this and all elif clauses below (rte_sws_2751) */
#elif defined(RTE_RUNNABLEAPI_MAIN_CORE1_10ms)
#elif defined(RTE_RUNNABLEAPI_MAIN_CORE1_1ms)
#elif defined(RTE_RUNNABLEAPI_RE_CORE1_SWC)
#else
   /* None of above defined so define value including all APIs (rte_sws_2751) */
   #define RTE_PRV_ALL_API
#endif

/*******************************************************
 ***
 *** Constants
 ***
 *******************************************************/

#ifndef RTE_CORE
#define RTE_E_CPU_Utilization_E_NOT_OK ((Std_ReturnType)1)
#define RTE_E_CPU_Utilization_E_OK ((Std_ReturnType)0)
#define RTE_E_CPU_Utilization_ON_PROGRESS ((Std_ReturnType)63)
#define RTE_E_GetMaxUserStackUtilization_E_NOT_OK ((Std_ReturnType)1)
#define RTE_E_GetMaxUserStackUtilization_E_OK ((Std_ReturnType)0)
#endif /* RTE_CORE */

/*******************************************************
 ***
 *** Public Types
 ***
 *******************************************************/

/* BEGIN: SWC types (core visible) */
struct Rte_CDS_ASW_CORE1 {
   uint8 Rte_Dummy;
};
typedef struct Rte_CDS_ASW_CORE1 Rte_CDS_ASW_CORE1;
/* END: SWC types (core visible) */

/*******************************************************
 ***
 *** Private Types
 ***
 *******************************************************/

/* BEGIN: SWC types (private) */
/* END: SWC types (private) */

/*******************************************************
 ***
 *** Instance Declarations
 ***
 *******************************************************/

#define RTE_START_SEC_EcucPartition_Core1_CONST_UNSPECIFIED
#include "Rte_MemMap.h"
extern CONST(struct Rte_CDS_ASW_CORE1, RTE_CONST) Rte_Inst_ASW_CORE1;
#define RTE_STOP_SEC_EcucPartition_Core1_CONST_UNSPECIFIED
#include "Rte_MemMap.h"


#ifndef RTE_CORE
typedef CONSTP2CONST(struct Rte_CDS_ASW_CORE1, AUTOMATIC, RTE_CONST) Rte_Instance;
#endif /* RTE_CORE */

/*******************************************************
 ***
 *** API Mapping macros
 ***
 *******************************************************/

/* API Mapping Macros */
#ifndef RTE_CORE

#define CDD_CORE1_START_SEC_CODE
#include "CDD_CORE1_MemMap.h"
FUNC(Std_ReturnType, CDD_CORE1_CODE) GetMaxUserStackUtilization_Core1_func(P2VAR(float64, AUTOMATIC, RTE_APPL_DATA) MaxUserStackUtilization);

FUNC(void, CDD_CORE1_CODE) CPUUtilizationCore1_func(VAR(uint32, AUTOMATIC) Duration_u32,
                                                    P2VAR(float64, AUTOMATIC, RTE_APPL_DATA) CPU_PercentUtilization,
                                                    P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Status);

#define CDD_CORE1_STOP_SEC_CODE
#include "CDD_CORE1_MemMap.h"
#define RTE_START_SEC_EcucPartition_Core1_CONST_UNSPECIFIED
#include "Rte_MemMap.h"
extern CONST(Rte_SelfType_CDD_CORE1, RTE_CONST) Rte_Self_CPT_CDD_CORE1;
#define RTE_STOP_SEC_EcucPartition_Core1_CONST_UNSPECIFIED
#include "Rte_MemMap.h"
#define RTE_ASW_CORE1_START_SEC_CODE
#include "Rte_MemMap.h"
FUNC(Std_ReturnType, RTE_CODE) Rte_Read_ASW_CORE1_RPort_ReceiverDataFromCore0_Data_ptr(P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) data);
FUNC(Std_ReturnType, RTE_CODE) Rte_Write_ASW_CORE1_PPort_TransmitData2Core0_Data_ptr(P2CONST(uint8, AUTOMATIC, RTE_APPL_DATA) data);
#define RTE_ASW_CORE1_STOP_SEC_CODE
#include "Rte_MemMap.h"
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_RE_CORE1_SWC)
/* Inline function call optimization; Rte_Call_RPort_CPUUtilizationCore1_CPU_Utilization to CPUUtilizationCore1_func */
#define Rte_Call_RPort_CPUUtilizationCore1_CPU_Utilization( Duration_u32, CPU_PercentUtilization, Status ) ( CPUUtilizationCore1_func(Duration_u32, CPU_PercentUtilization, Status), ((VAR(Std_ReturnType, AUTOMATIC))RTE_E_OK) )

#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_RE_CORE1_SWC)
/* Inline function call optimization; Rte_Call_RPort_GetMaxUserStackUtilization_GetMaxUserStackUtilization to GetMaxUserStackUtilization_Core1_func */
#define Rte_Call_RPort_GetMaxUserStackUtilization_GetMaxUserStackUtilization( MaxUserStackUtilization ) GetMaxUserStackUtilization_Core1_func(MaxUserStackUtilization)

#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_RE_CORE1_SWC)
#define Rte_Read_RPort_ReceiverDataFromCore0_Data_ptr( data ) (Rte_Read_ASW_CORE1_RPort_ReceiverDataFromCore0_Data_ptr(data))
#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_RE_CORE1_SWC)
#define Rte_Write_PPort_TransmitData2Core0_Data_ptr( data ) (Rte_Write_ASW_CORE1_PPort_TransmitData2Core0_Data_ptr(data))
#endif

#endif /* RTE_CORE */

/*******************************************************
 ***
 *** RE Prototypes
 ***
 *******************************************************/

#define ASW_CORE1_START_SEC_CODE
#include "ASW_CORE1_MemMap.h"
FUNC(void, ASW_CORE1_CODE) GMAIN_CORE1_1ms_func(void);
FUNC(void, ASW_CORE1_CODE) MAIN_CORE1_10ms_func(void);
FUNC(void, ASW_CORE1_CODE) MAIN_CORE1_1ms_func(void);
FUNC(void, ASW_CORE1_CODE) RE_CORE1_SWC_func(void);
#define ASW_CORE1_STOP_SEC_CODE
#include "ASW_CORE1_MemMap.h"

/* Initial values for data element prototypes */

#ifdef __cplusplus
} /* extern C */
#endif /* __cplusplus */

#endif /* !RTE_ASW_CORE1_H */
