/** @file     Rte_ASW_WDG.h
  *
  * @brief    Application header file
  *
  * @note     AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
  *
  * @note     Generated by ETAS RTA-RTE
  * @note     Version 7.5.3
  *
  * @date     Thu Jun 26 19:34:30 2025
  */

#ifndef RTE_ASW_WDG_H
#define RTE_ASW_WDG_H

#ifndef RTE_CORE
#ifdef RTE_APPLICATION_HEADER_FILE
#error Multiple application header files included.
#endif /* RTE_APPLICATION_HEADER_FILE */
#define RTE_APPLICATION_HEADER_FILE
#endif /* RTE_CORE */

/*******************************************************
 ***
 *** Includes
 ***
 *******************************************************/

#include "Rte.h"
#include "Rte_Intl.h"
#include "Rte_ASW_WDG_Type.h"

#include "Rte_DataHandleType.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#if defined(RTE_RUNNABLEAPI_RE_ASW_WDG_Alive_Supervision_Entity1)
   /* Do nothing for this and all elif clauses below (rte_sws_2751) */
#else
   /* None of above defined so define value including all APIs (rte_sws_2751) */
   #define RTE_PRV_ALL_API
#endif

/*******************************************************
 ***
 *** Constants
 ***
 *******************************************************/

#ifndef RTE_CORE
#define RTE_E_WdgM_LocalSupervision_E_NOT_OK ((Std_ReturnType)1)
#define RTE_E_WdgM_LocalSupervision_E_OK ((Std_ReturnType)0)
#endif /* RTE_CORE */

/*******************************************************
 ***
 *** Public Types
 ***
 *******************************************************/

/* BEGIN: SWC types (core visible) */
struct Rte_CDS_ASW_WDG {
   uint8 Rte_Dummy;
};
typedef struct Rte_CDS_ASW_WDG Rte_CDS_ASW_WDG;
/* END: SWC types (core visible) */

/*******************************************************
 ***
 *** Private Types
 ***
 *******************************************************/

/* BEGIN: SWC types (private) */
/* END: SWC types (private) */

/*******************************************************
 ***
 *** Instance Declarations
 ***
 *******************************************************/

#define RTE_START_SEC_EcucPartition_Core0_CONST_UNSPECIFIED
#include "Rte_MemMap.h"
extern CONST(struct Rte_CDS_ASW_WDG, RTE_CONST) Rte_Inst_ASW_WDG;
#define RTE_STOP_SEC_EcucPartition_Core0_CONST_UNSPECIFIED
#include "Rte_MemMap.h"


#ifndef RTE_CORE
typedef CONSTP2CONST(struct Rte_CDS_ASW_WDG, AUTOMATIC, RTE_CONST) Rte_Instance;
#endif /* RTE_CORE */

/*******************************************************
 ***
 *** API Mapping macros
 ***
 *******************************************************/

/* API Mapping Macros */
#ifndef RTE_CORE

#define RTE_START_SEC_EcucPartition_Core0_CONST_UNSPECIFIED
#include "Rte_MemMap.h"
extern CONST(Rte_SelfType_WdgM, RTE_CONST) Rte_Self_CPT_WdgM;
#define RTE_STOP_SEC_EcucPartition_Core0_CONST_UNSPECIFIED
#include "Rte_MemMap.h"
#define WdgM_START_SEC_CODE_FAST
#include "WdgM_MemMap.h"
FUNC(Std_ReturnType, WdgM_CODE_FAST) WdgM_CheckpointReached(VAR(WdgM_SupervisedEntityIdType, AUTOMATIC) SEID,
                                                            VAR(WdgM_CheckpointIdType, AUTOMATIC) CheckpointID);

#define WdgM_STOP_SEC_CODE_FAST
#include "WdgM_MemMap.h"
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_RE_ASW_WDG_Alive_Supervision_Entity1)
/* Inline function call optimization; Rte_Call_RPort_Alive_Supervision_Entity1_CheckpointReached to WdgM_CheckpointReached */
#define Rte_Call_RPort_Alive_Supervision_Entity1_CheckpointReached() WdgM_CheckpointReached(((VAR(WdgM_SupervisedEntityIdType, AUTOMATIC))3), ((VAR(WdgM_CheckpointIdType, AUTOMATIC))0))

#endif

#endif /* RTE_CORE */

/*******************************************************
 ***
 *** RE Prototypes
 ***
 *******************************************************/

#define ASW_WDG_START_SEC_CODE
#include "ASW_WDG_MemMap.h"
FUNC(void, ASW_WDG_CODE) RE_ASW_WDG_Alive_Supervision_Entity1_func(void);
#define ASW_WDG_STOP_SEC_CODE
#include "ASW_WDG_MemMap.h"

/* Initial values for data element prototypes */

#ifdef __cplusplus
} /* extern C */
#endif /* __cplusplus */

#endif /* !RTE_ASW_WDG_H */
