/** @file     Rte_CDD_CORE1.h
  *
  * @brief    Application header file
  *
  * @note     AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
  *
  * @note     Generated by ETAS RTA-RTE
  * @note     Version 7.5.3
  *
  * @date     Tue Mar  5 14:09:38 2024
  */

#ifndef RTE_CDD_CORE1_H
#define RTE_CDD_CORE1_H

#ifndef RTE_CORE
#ifdef RTE_APPLICATION_HEADER_FILE
#error Multiple application header files included.
#endif /* RTE_APPLICATION_HEADER_FILE */
#define RTE_APPLICATION_HEADER_FILE
#endif /* RTE_CORE */

/*******************************************************
 ***
 *** Includes
 ***
 *******************************************************/

#include "Rte.h"
#include "Rte_Intl.h"
#include "Rte_CDD_CORE1_Type.h"

#include "Rte_DataHandleType.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#if defined(RTE_RUNNABLEAPI_CDD_CORE1)
   /* Do nothing for this and all elif clauses below (rte_sws_2751) */
#elif defined(RTE_RUNNABLEAPI_CPUUtilizationCore1)
#elif defined(RTE_RUNNABLEAPI_GetMaxUserStackUtilization_Core1)
#else
   /* None of above defined so define value including all APIs (rte_sws_2751) */
   #define RTE_PRV_ALL_API
#endif

/*******************************************************
 ***
 *** Constants
 ***
 *******************************************************/

#ifndef RTE_CORE
#define RTE_E_CPU_Utilization_E_NOT_OK ((Std_ReturnType)1)
#define RTE_E_CPU_Utilization_E_OK ((Std_ReturnType)0)
#define RTE_E_CPU_Utilization_ON_PROGRESS ((Std_ReturnType)63)
#define RTE_E_GetMaxUserStackUtilization_E_NOT_OK ((Std_ReturnType)1)
#define RTE_E_GetMaxUserStackUtilization_E_OK ((Std_ReturnType)0)
#endif /* RTE_CORE */

/*******************************************************
 ***
 *** Public Types
 ***
 *******************************************************/

/* BEGIN: SWC types (core visible) */
struct Rte_CDS_CDD_CORE1 {
   uint8 Rte_Dummy;
};
typedef struct Rte_CDS_CDD_CORE1 Rte_CDS_CDD_CORE1;
/* END: SWC types (core visible) */

/*******************************************************
 ***
 *** Private Types
 ***
 *******************************************************/

/* BEGIN: SWC types (private) */
/* END: SWC types (private) */

/*******************************************************
 ***
 *** Instance Declarations
 ***
 *******************************************************/

#define RTE_START_SEC_EcucPartition_Core1_CONST_UNSPECIFIED
#include "Rte_MemMap.h"
extern CONST(struct Rte_CDS_CDD_CORE1, RTE_CONST) Rte_Inst_CDD_CORE1;
#define RTE_STOP_SEC_EcucPartition_Core1_CONST_UNSPECIFIED
#include "Rte_MemMap.h"


#ifndef RTE_CORE
typedef CONSTP2CONST(struct Rte_CDS_CDD_CORE1, AUTOMATIC, RTE_CONST) Rte_Instance;
#endif /* RTE_CORE */

/*******************************************************
 ***
 *** API Mapping macros
 ***
 *******************************************************/

/* API Mapping Macros */
#ifndef RTE_CORE

#endif /* RTE_CORE */

/*******************************************************
 ***
 *** RE Prototypes
 ***
 *******************************************************/

#define CDD_CORE1_START_SEC_CODE
#include "CDD_CORE1_MemMap.h"
FUNC(void, CDD_CORE1_CODE) CDD_CORE1_func(void);
FUNC(void, CDD_CORE1_CODE) CPUUtilizationCore1_func(VAR(uint32, AUTOMATIC) Duration_u32,
                                                    P2VAR(float64, AUTOMATIC, RTE_APPL_DATA) CPU_PercentUtilization,
                                                    P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Status);
FUNC(Std_ReturnType, CDD_CORE1_CODE) GetMaxUserStackUtilization_Core1_func(P2VAR(float64, AUTOMATIC, RTE_APPL_DATA) MaxUserStackUtilization);
#define CDD_CORE1_STOP_SEC_CODE
#include "CDD_CORE1_MemMap.h"

/* Initial values for data element prototypes */

#ifdef __cplusplus
} /* extern C */
#endif /* __cplusplus */

#endif /* !RTE_CDD_CORE1_H */
