/** @file     Rte_ASW_NM_Type.h
  *
  * @brief    Application types header file
  *
  * @note     AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
  *
  * @note     Generated by ETAS RTA-RTE
  * @note     Version 7.5.3
  *
  * @date     Tue Mar  5 14:09:38 2024
  */

#ifndef RTE_ASW_NM_TYPE_H
#define RTE_ASW_NM_TYPE_H

#include "Rte_Type.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

/* BEGIN: SWC specific types */
/* END: SWC specific types */

/* BEGIN: SWC specific definitions */
#if !defined(RTE_CORE)

/* Box: /AUTOSAR_ComM/ImplementationDataTypes/ComM_ModeType begin */
/* Box: "COMM_NO_COMMUNICATION" begin */
#ifndef COMM_NO_COMMUNICATION
#define COMM_NO_COMMUNICATION (0U)
#endif /* !COMM_NO_COMMUNICATION */
/* Box: "COMM_NO_COMMUNICATION" end */
/* Box: "COMM_SILENT_COMMUNICATION" begin */
#ifndef COMM_SILENT_COMMUNICATION
#define COMM_SILENT_COMMUNICATION (1U)
#endif /* !COMM_SILENT_COMMUNICATION */
/* Box: "COMM_SILENT_COMMUNICATION" end */
/* Box: "COMM_FULL_COMMUNICATION" begin */
#ifndef COMM_FULL_COMMUNICATION
#define COMM_FULL_COMMUNICATION (2U)
#endif /* !COMM_FULL_COMMUNICATION */
/* Box: "COMM_FULL_COMMUNICATION" end */
/* Box: /AUTOSAR_ComM/ImplementationDataTypes/ComM_ModeType end */

/* Box: /AUTOSAR_Platform/ImplementationDataTypes/boolean begin */
/* Box: "FALSE" begin */
#ifndef FALSE
#define FALSE (0U)
#endif /* !FALSE */
/* Box: "FALSE" end */
/* Box: "TRUE" begin */
#ifndef TRUE
#define TRUE (1U)
#endif /* !TRUE */
/* Box: "TRUE" end */
/* Box: /AUTOSAR_Platform/ImplementationDataTypes/boolean end */
#endif /* !defined(RTE_CORE) */
/* END: SWC specific definitions */

#ifdef __cplusplus
} /* extern C */
#endif /* __cplusplus */

#endif /* !RTE_ASW_NM_TYPE_H */
