/** @file     Rte_ASW_DEM.h
  *
  * @brief    Application header file
  *
  * @note     AUTOMATICALLY GENERATED FILE! DO NOT EDIT!
  *
  * @note     Generated by ETAS RTA-RTE
  * @note     Version 7.5.3
  *
  * @date     Mon May 13 15:35:46 2024
  */

#ifndef RTE_ASW_DEM_H
#define RTE_ASW_DEM_H

#ifndef RTE_CORE
#ifdef RTE_APPLICATION_HEADER_FILE
#error Multiple application header files included.
#endif /* RTE_APPLICATION_HEADER_FILE */
#define RTE_APPLICATION_HEADER_FILE
#endif /* RTE_CORE */

/*******************************************************
 ***
 *** Includes
 ***
 *******************************************************/

#include "Rte.h"
#include "Rte_Intl.h"
#include "Rte_ASW_DEM_Type.h"

#include "Rte_DataHandleType.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#if defined(RTE_RUNNABLEAPI_ASW_DEM_CBStatusComp_DemComponent)
   /* Do nothing for this and all elif clauses below (rte_sws_2751) */
#elif defined(RTE_RUNNABLEAPI_ASW_DEM_DataServices_CS_ExtendedDataRecord_Aged_counter)
#elif defined(RTE_RUNNABLEAPI_ASW_DEM_DataServices_CS_ExtendedDataRecord_Fault_pending_counter)
#elif defined(RTE_RUNNABLEAPI_ASW_DEM_PeriodicRunnable_10ms)
#else
   /* None of above defined so define value including all APIs (rte_sws_2751) */
   #define RTE_PRV_ALL_API
#endif

/*******************************************************
 ***
 *** Constants
 ***
 *******************************************************/

#ifndef RTE_CORE
#define RTE_E_DataServices_CS_ExtendedDataRecord_Aged_counter_E_NOT_OK ((Std_ReturnType)1)
#define RTE_E_DataServices_CS_ExtendedDataRecord_Aged_counter_E_OK ((Std_ReturnType)0)
#define RTE_E_DataServices_CS_ExtendedDataRecord_Fault_pending_counter_E_NOT_OK ((Std_ReturnType)1)
#define RTE_E_DataServices_CS_ExtendedDataRecord_Fault_pending_counter_E_OK ((Std_ReturnType)0)
#define RTE_E_IndicatorStatus_E_NOT_OK ((Std_ReturnType)1)
#define RTE_E_IndicatorStatus_E_OK ((Std_ReturnType)0)
#define RTE_E_OperationCycle_E_NOT_OK ((Std_ReturnType)1)
#define RTE_E_OperationCycle_E_OK ((Std_ReturnType)0)
#endif /* RTE_CORE */

/*******************************************************
 ***
 *** Public Types
 ***
 *******************************************************/

/* BEGIN: SWC types (core visible) */
struct Rte_CDS_ASW_DEM {
   uint8 Rte_Dummy;
};
typedef struct Rte_CDS_ASW_DEM Rte_CDS_ASW_DEM;
/* END: SWC types (core visible) */

/*******************************************************
 ***
 *** Private Types
 ***
 *******************************************************/

/* BEGIN: SWC types (private) */
/* END: SWC types (private) */

/*******************************************************
 ***
 *** Instance Declarations
 ***
 *******************************************************/

#define RTE_START_SEC_EcucPartition_Core0_CONST_UNSPECIFIED
#include "Rte_MemMap.h"
extern CONST(struct Rte_CDS_ASW_DEM, RTE_CONST) Rte_Inst_ASW_DEM;
#define RTE_STOP_SEC_EcucPartition_Core0_CONST_UNSPECIFIED
#include "Rte_MemMap.h"


#ifndef RTE_CORE
typedef CONSTP2CONST(struct Rte_CDS_ASW_DEM, AUTOMATIC, RTE_CONST) Rte_Instance;
#endif /* RTE_CORE */

/*******************************************************
 ***
 *** API Mapping macros
 ***
 *******************************************************/

/* API Mapping Macros */
#ifndef RTE_CORE

#define Dem_START_SEC_CODE
#include "Dem_MemMap.h"
FUNC(Std_ReturnType, Dem_CODE) Dem_GetCycleQualified(VAR(Dem_OperationCycleIdType, AUTOMATIC) OperationCycleId,
                                                     P2VAR(boolean, AUTOMATIC, RTE_APPL_DATA) isQualified);

FUNC(Std_ReturnType, Dem_CODE) Dem_GetIndicatorStatus(VAR(uint8, AUTOMATIC) IndicatorId,
                                                      P2VAR(Dem_IndicatorStatusType, AUTOMATIC, RTE_APPL_DATA) IndicatorStatus);

FUNC(Std_ReturnType, Dem_CODE) Dem_GetOperationCycleState(VAR(Dem_OperationCycleIdType, AUTOMATIC) OperationCycleId,
                                                          P2VAR(Dem_OperationCycleStateType, AUTOMATIC, RTE_APPL_DATA) CycleState);

FUNC(Std_ReturnType, Dem_CODE) Dem_SetCycleQualified(VAR(Dem_OperationCycleIdType, AUTOMATIC) OperationCycleId);

FUNC(Std_ReturnType, Dem_CODE) Dem_SetOperationCycleState(VAR(Dem_OperationCycleIdType, AUTOMATIC) OperationCycleId,
                                                          VAR(Dem_OperationCycleStateType, AUTOMATIC) CycleState);

#define Dem_STOP_SEC_CODE
#include "Dem_MemMap.h"
#define RTE_START_SEC_EcucPartition_Core0_CONST_UNSPECIFIED
#include "Rte_MemMap.h"
extern CONST(Rte_SelfType_Dem, RTE_CONST) Rte_Self_CPT_Dem;
#define RTE_STOP_SEC_EcucPartition_Core0_CONST_UNSPECIFIED
#include "Rte_MemMap.h"
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASW_DEM_PeriodicRunnable_10ms)
/* Inline function call optimization; Rte_Call_IndStatus_MIL_GetIndicatorStatus to Dem_GetIndicatorStatus */
#define Rte_Call_IndStatus_MIL_GetIndicatorStatus( IndicatorStatus ) Dem_GetIndicatorStatus(((VAR(uint8, AUTOMATIC))1), IndicatorStatus)

#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASW_DEM_PeriodicRunnable_10ms)
/* Inline function call optimization; Rte_Call_OpCycle_DemOperationCycle_Ignition_GetOperationCycleState to Dem_GetOperationCycleState */
#define Rte_Call_OpCycle_DemOperationCycle_Ignition_GetOperationCycleState( CycleState ) Dem_GetOperationCycleState(((VAR(Dem_OperationCycleIdType, AUTOMATIC))3), CycleState)

#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASW_DEM_PeriodicRunnable_10ms)
/* Inline function call optimization; Rte_Call_OpCycle_DemOperationCycle_Ignition_SetOperationCycleState to Dem_SetOperationCycleState */
#define Rte_Call_OpCycle_DemOperationCycle_Ignition_SetOperationCycleState( CycleState ) Dem_SetOperationCycleState(((VAR(Dem_OperationCycleIdType, AUTOMATIC))3), CycleState)

#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASW_DEM_PeriodicRunnable_10ms)
/* Inline function call optimization; Rte_Call_RPort_OpCycle_DemOperationCycle_Power_GetCycleQualified to Dem_GetCycleQualified */
#define Rte_Call_RPort_OpCycle_DemOperationCycle_Power_GetCycleQualified( CycleState ) Dem_GetCycleQualified(((VAR(Dem_OperationCycleIdType, AUTOMATIC))4), CycleState)

#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASW_DEM_PeriodicRunnable_10ms)
/* Inline function call optimization; Rte_Call_RPort_OpCycle_DemOperationCycle_Power_GetOperationCycleState to Dem_GetOperationCycleState */
#define Rte_Call_RPort_OpCycle_DemOperationCycle_Power_GetOperationCycleState( CycleState ) Dem_GetOperationCycleState(((VAR(Dem_OperationCycleIdType, AUTOMATIC))4), CycleState)

#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASW_DEM_PeriodicRunnable_10ms)
/* Inline function call optimization; Rte_Call_RPort_OpCycle_DemOperationCycle_Power_SetCycleQualified to Dem_SetCycleQualified */
#define Rte_Call_RPort_OpCycle_DemOperationCycle_Power_SetCycleQualified() Dem_SetCycleQualified(((VAR(Dem_OperationCycleIdType, AUTOMATIC))4))

#endif
#if defined(RTE_PRV_ALL_API) || defined(RTE_RUNNABLEAPI_ASW_DEM_PeriodicRunnable_10ms)
/* Inline function call optimization; Rte_Call_RPort_OpCycle_DemOperationCycle_Power_SetOperationCycleState to Dem_SetOperationCycleState */
#define Rte_Call_RPort_OpCycle_DemOperationCycle_Power_SetOperationCycleState( CycleState ) Dem_SetOperationCycleState(((VAR(Dem_OperationCycleIdType, AUTOMATIC))4), CycleState)

#endif

#endif /* RTE_CORE */

/*******************************************************
 ***
 *** RE Prototypes
 ***
 *******************************************************/

#define ASW_DEM_START_SEC_CODE
#include "ASW_DEM_MemMap.h"
FUNC(Std_ReturnType, ASW_DEM_CODE) ASW_DEM_DataServices_CS_ExtendedDataRecord_Aged_counter_ReadData_func(P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Data);
FUNC(Std_ReturnType, ASW_DEM_CODE) ASW_DEM_DataServices_CS_ExtendedDataRecord_Fault_pending_counter_ReadData_func(P2VAR(uint8, AUTOMATIC, RTE_APPL_DATA) Data);
FUNC(void, ASW_DEM_CODE) ASW_DEM_PeriodicRunnable_10ms_func(void);
#define ASW_DEM_STOP_SEC_CODE
#include "ASW_DEM_MemMap.h"

/* Initial values for data element prototypes */

#ifdef __cplusplus
} /* extern C */
#endif /* __cplusplus */

#endif /* !RTE_ASW_DEM_H */
