#ifndef __MAIN_MSG_RXVALIDFLAG__
#define __MAIN_MSG_RXVALIDFLAG__

#include "CAN01_DEF.h"
#include "MAIN_L.h"
/*********************************************************************
*
* !Description : DONT MODIFY!Code below are maintained by BSW layer
*
* !Date          Version      Author         Operation
* --------------------------------------------------------------------
* 2025/05/29      V1.0         Lzj             Create
**********************************************************************/
/*Can01*/
#define  MAIN_MsgValidFlag_Can01_Rx01  (((!BSW_bRxTOutFlag_Can01_Rx01) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can01_Rx02  (((!BSW_bRxTOutFlag_Can01_Rx02) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can01_Rx03  (((!BSW_bRxTOutFlag_Can01_Rx03) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can01_Rx04  (((!BSW_bRxTOutFlag_Can01_Rx04) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can01_Rx05  (((!BSW_bRxTOutFlag_Can01_Rx05) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can01_Rx06  (((!BSW_bRxTOutFlag_Can01_Rx06) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can01_Rx07  (((!BSW_bRxTOutFlag_Can01_Rx07) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can01_Rx08  (((!BSW_bRxTOutFlag_Can01_Rx08) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can01_Rx09  (((!BSW_bRxTOutFlag_Can01_Rx09) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can01_Rx10  (((!BSW_bRxTOutFlag_Can01_Rx10) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can01_Rx11  (((!BSW_bRxTOutFlag_Can01_Rx11) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can01_Rx12  (((!BSW_bRxTOutFlag_Can01_Rx12) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can01_Rx13  (((!BSW_bRxTOutFlag_Can01_Rx13) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can01_Rx14  (((!BSW_bRxTOutFlag_Can01_Rx14) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can01_Rx15  (((!BSW_bRxTOutFlag_Can01_Rx15) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can01_Rx16  (((!BSW_bRxTOutFlag_Can01_Rx16) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can01_Rx17  (((!BSW_bRxTOutFlag_Can01_Rx17) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can01_Rx18  (((!BSW_bRxTOutFlag_Can01_Rx18) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can01_Rx19  (((!BSW_bRxTOutFlag_Can01_Rx19) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can01_Rx20  (((!BSW_bRxTOutFlag_Can01_Rx20) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can01_Rx21  (((!BSW_bRxTOutFlag_Can01_Rx21) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can01_Rx22  (((!BSW_bRxTOutFlag_Can01_Rx22) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can01_Rx23  (((!BSW_bRxTOutFlag_Can01_Rx23) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can01_Rx24  (((!BSW_bRxTOutFlag_Can01_Rx24) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can01_Rx25  (((!BSW_bRxTOutFlag_Can01_Rx25) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can01_Rx25  (((!BSW_bRxTOutFlag_Can01_Rx25) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can01_Rx26  (((!BSW_bRxTOutFlag_Can01_Rx26) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can01_Rx27  (((!BSW_bRxTOutFlag_Can01_Rx27) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can01_Rx28  (((!BSW_bRxTOutFlag_Can01_Rx28) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can01_Rx29  (((!BSW_bRxTOutFlag_Can01_Rx29) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can01_Rx30  (((!BSW_bRxTOutFlag_Can01_Rx30) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can01_Rx31  (((!BSW_bRxTOutFlag_Can01_Rx31) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can01_Rx32  (((!BSW_bRxTOutFlag_Can01_Rx32) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can01_Rx33  (((!BSW_bRxTOutFlag_Can01_Rx33) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can01_Rx34  (((!BSW_bRxTOutFlag_Can01_Rx34) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can01_Rx35  (((!BSW_bRxTOutFlag_Can01_Rx35) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can01_Rx36  (((!BSW_bRxTOutFlag_Can01_Rx36) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can01_Rx37  (((!BSW_bRxTOutFlag_Can01_Rx37) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can01_Rx38  (((!BSW_bRxTOutFlag_Can01_Rx38) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can01_Rx39  (((!BSW_bRxTOutFlag_Can01_Rx39) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can01_Rx40  (((!BSW_bRxTOutFlag_Can01_Rx40) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
/*Can02*/
#define  MAIN_MsgValidFlag_Can02_Rx01  (((!BSW_bRxTOutFlag_Can02_Rx01) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can02_Rx02  (((!BSW_bRxTOutFlag_Can02_Rx02) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can02_Rx03  (((!BSW_bRxTOutFlag_Can02_Rx03) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can02_Rx04  (((!BSW_bRxTOutFlag_Can02_Rx04) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can02_Rx05  (((!BSW_bRxTOutFlag_Can02_Rx05) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can02_Rx06  (((!BSW_bRxTOutFlag_Can02_Rx06) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can02_Rx07  (((!BSW_bRxTOutFlag_Can02_Rx07) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can02_Rx08  (((!BSW_bRxTOutFlag_Can02_Rx08) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can02_Rx09  (((!BSW_bRxTOutFlag_Can02_Rx09) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can02_Rx10  (((!BSW_bRxTOutFlag_Can02_Rx10) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can02_Rx11  (((!BSW_bRxTOutFlag_Can02_Rx11) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can02_Rx12  (((!BSW_bRxTOutFlag_Can02_Rx12) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can02_Rx13  (((!BSW_bRxTOutFlag_Can02_Rx13) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can02_Rx14  (((!BSW_bRxTOutFlag_Can02_Rx14) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can02_Rx15  (((!BSW_bRxTOutFlag_Can02_Rx15) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can02_Rx16  (((!BSW_bRxTOutFlag_Can02_Rx16) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can02_Rx17  (((!BSW_bRxTOutFlag_Can02_Rx17) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can02_Rx18  (((!BSW_bRxTOutFlag_Can02_Rx18) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can02_Rx19  (((!BSW_bRxTOutFlag_Can02_Rx19) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can02_Rx20  (((!BSW_bRxTOutFlag_Can02_Rx20) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can02_Rx21  (((!BSW_bRxTOutFlag_Can02_Rx21) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can02_Rx22  (((!BSW_bRxTOutFlag_Can02_Rx22) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can02_Rx23  (((!BSW_bRxTOutFlag_Can02_Rx23) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can02_Rx24  (((!BSW_bRxTOutFlag_Can02_Rx24) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can02_Rx25  (((!BSW_bRxTOutFlag_Can02_Rx25) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can02_Rx25  (((!BSW_bRxTOutFlag_Can02_Rx25) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can02_Rx26  (((!BSW_bRxTOutFlag_Can02_Rx26) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can02_Rx27  (((!BSW_bRxTOutFlag_Can02_Rx27) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can02_Rx28  (((!BSW_bRxTOutFlag_Can02_Rx28) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can02_Rx29  (((!BSW_bRxTOutFlag_Can02_Rx29) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can02_Rx30  (((!BSW_bRxTOutFlag_Can02_Rx30) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can02_Rx31  (((!BSW_bRxTOutFlag_Can02_Rx31) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can02_Rx32  (((!BSW_bRxTOutFlag_Can02_Rx32) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can02_Rx33  (((!BSW_bRxTOutFlag_Can02_Rx33) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can02_Rx34  (((!BSW_bRxTOutFlag_Can02_Rx34) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can02_Rx35  (((!BSW_bRxTOutFlag_Can02_Rx35) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can02_Rx36  (((!BSW_bRxTOutFlag_Can02_Rx36) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can02_Rx37  (((!BSW_bRxTOutFlag_Can02_Rx37) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can02_Rx38  (((!BSW_bRxTOutFlag_Can02_Rx38) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can02_Rx39  (((!BSW_bRxTOutFlag_Can02_Rx39) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can02_Rx40  (((!BSW_bRxTOutFlag_Can02_Rx40) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
/*Can03*/
#define  MAIN_MsgValidFlag_Can03_Rx01  (((!BSW_bRxTOutFlag_Can03_Rx01) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can03_Rx02  (((!BSW_bRxTOutFlag_Can03_Rx02) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can03_Rx03  (((!BSW_bRxTOutFlag_Can03_Rx03) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can03_Rx04  (((!BSW_bRxTOutFlag_Can03_Rx04) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can03_Rx05  (((!BSW_bRxTOutFlag_Can03_Rx05) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can03_Rx06  (((!BSW_bRxTOutFlag_Can03_Rx06) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can03_Rx07  (((!BSW_bRxTOutFlag_Can03_Rx07) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can03_Rx08  (((!BSW_bRxTOutFlag_Can03_Rx08) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can03_Rx09  (((!BSW_bRxTOutFlag_Can03_Rx09) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can03_Rx10  (((!BSW_bRxTOutFlag_Can03_Rx10) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can03_Rx11  (((!BSW_bRxTOutFlag_Can03_Rx11) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can03_Rx12  (((!BSW_bRxTOutFlag_Can03_Rx12) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can03_Rx13  (((!BSW_bRxTOutFlag_Can03_Rx13) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can03_Rx14  (((!BSW_bRxTOutFlag_Can03_Rx14) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can03_Rx15  (((!BSW_bRxTOutFlag_Can03_Rx15) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can03_Rx16  (((!BSW_bRxTOutFlag_Can03_Rx16) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can03_Rx17  (((!BSW_bRxTOutFlag_Can03_Rx17) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can03_Rx18  (((!BSW_bRxTOutFlag_Can03_Rx18) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can03_Rx19  (((!BSW_bRxTOutFlag_Can03_Rx19) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can03_Rx20  (((!BSW_bRxTOutFlag_Can03_Rx20) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can03_Rx21  (((!BSW_bRxTOutFlag_Can03_Rx21) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can03_Rx22  (((!BSW_bRxTOutFlag_Can03_Rx22) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can03_Rx23  (((!BSW_bRxTOutFlag_Can03_Rx23) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can03_Rx24  (((!BSW_bRxTOutFlag_Can03_Rx24) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can03_Rx25  (((!BSW_bRxTOutFlag_Can03_Rx25) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can03_Rx25  (((!BSW_bRxTOutFlag_Can03_Rx25) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can03_Rx26  (((!BSW_bRxTOutFlag_Can03_Rx26) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can03_Rx27  (((!BSW_bRxTOutFlag_Can03_Rx27) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can03_Rx28  (((!BSW_bRxTOutFlag_Can03_Rx28) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can03_Rx29  (((!BSW_bRxTOutFlag_Can03_Rx29) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can03_Rx30  (((!BSW_bRxTOutFlag_Can03_Rx30) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can03_Rx31  (((!BSW_bRxTOutFlag_Can03_Rx31) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can03_Rx32  (((!BSW_bRxTOutFlag_Can03_Rx32) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can03_Rx33  (((!BSW_bRxTOutFlag_Can03_Rx33) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can03_Rx34  (((!BSW_bRxTOutFlag_Can03_Rx34) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can03_Rx35  (((!BSW_bRxTOutFlag_Can03_Rx35) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can03_Rx36  (((!BSW_bRxTOutFlag_Can03_Rx36) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can03_Rx37  (((!BSW_bRxTOutFlag_Can03_Rx37) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can03_Rx38  (((!BSW_bRxTOutFlag_Can03_Rx38) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can03_Rx39  (((!BSW_bRxTOutFlag_Can03_Rx39) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))
#define  MAIN_MsgValidFlag_Can03_Rx40  (((!BSW_bRxTOutFlag_Can03_Rx40) || (MAIN_bMSGRxToutBenchOnC)) && (!MAIN_bComRxDisableFlgByUds))

#endif /*End of __MAIN_MSG_RXVALIDFLAG__*/
/*-------------------------------------EOF--------------------------------------*/

