
#ifndef NVM_PRV_HIDERTEAPI_H
#define NVM_PRV_HIDERTEAPI_H
/*
 **********************************************************************************************************************
 * Includes
 **********************************************************************************************************************
 */
#include "rba_MemLib_UseRte.h"

/*
 **********************************************************************************************************************
 * Type definitions
 **********************************************************************************************************************
 */
#ifdef RBA_MEMLIB_USE_RTE
/**
 * Definition of a compiler switch which controls hiding of public NvM APIs and data types provided by RTE generator,
 * for details please see coding guidelines Rule BSW_ServiceRTE_002.
 */
# define NVM_RB_HIDE_RTEAPI
#endif

// If RTE generator is NOT used then the NvM uses all public APIs and data types from NvM.h and not from header files
// generated by the RTE.
#include "NvM.h"


/**
 * If RTE generator is used then the NvM uses all public APIs and data types from header files generated by the RTE
 * and not from NvM.h.
 */
#ifdef NVM_RB_HIDE_RTEAPI
# include "Rte_NvM.h"
# include "Rte_NvM_Type.h"
# include "SchM_NvM.h"
#endif

/* NVM_PRV_HIDERTEAPI_H */
#endif

