/******************************************************************************/
/* !Layer           : MCAL                                                   */
/* !Component       : RES                                                    */
/* !Description     : Resolver driver Configurations                         */
/*                                                                           */
/* !File            : RES_Cfg.h                                              */
/* !Description     : RES configuration                                      */
/*                                                                           */
/* !Reference       :                                                        */
/*                                                                           */
/* Coding language  : C                                                      */
/*                                                                           */
/* COPYRIGHT invt  all rights reserved                                       */
/******************************************************************************/
/* Dimension Informations
 * %PCMS_HEADER_SUBSTITUTION_START:%
 * The PID has this format: <Product ID>:<Item ID>.<Variant>-<Item Type>;<Revision>
 * %PID:%
 * %PCMS_HEADER_SUBSTITUTION_END:%
*******************************************************************************/
/** 10/27/22, 09:10:34: generated by Genecode v2.6.0.0                        */
/******************************************************************************/

#ifndef RES_CFG_H
#define RES_CFG_H

#include "Std_Types.h"

/******************************************************************************/
/* DEFINES                                                                    */
/******************************************************************************/

#define RESBSL_snDISABLE_CMD_PIN         PORT_PIN_MODE_GPIO
#define RESBSL_snENABLE_CMD_PIN          PORT_PIN_MODE_ALT1
/*#define RESBSL_snDIO_CMD_EXCITE         DioConf_DioChannel_M_RES_EXCITATION*/
#define RESBSL_udtMAXIMUM_EXCITE_DELAY  995  /* Equivalent to 99.5 μ */
#define RESBSL_udtMINIMUM_EXCITE_DELAY  15  /* Equivalent to 1.5 μ */
#define RESBSL_udtMAXIMUM_EXCITE_DUTY   100  /* 100 % */
#define RESBSL_udtMINIMUM_EXCITE_DUTY   0  /* 0 % */
#define RESBSL_snEXCITE_MCS_DELAY_PTR   MCS_pu32ResGtmPwmExciteDelay
#define RESBSL_snEXCITE_MCS_DUTY_PTR    MCS_pu32ResGtmPwmExciteDuty
/* Around 0.6 µs is time consumed in ARU (Round Trip Time) */ 
#define RESBSL_snEXCITE_ARU_ROUND_TRIP_TIME    6



#define RESBSL_snDISABLE_CMD_PIN         PORT_PIN_MODE_GPIO
#define RESBSL_snENABLE_CMD_PIN          PORT_PIN_MODE_ALT1
#define RESBSL_snDIO_CMD_SYNCPOS         DioConf_DioChannel_M_GEN_SYNCHRO_POS
#define RESBSL_udtMAXIMUM_SYNCPOS_DELAY  995  /* Equivalent to 99.5 μ */
#define RESBSL_udtMINIMUM_SYNCPOS_DELAY  15  /* Equivalent to 1.5 μ */
#define RESBSL_udtMAXIMUM_SYNCPOS_DUTY   10  /* 10 % */
#define RESBSL_udtMINIMUM_SYNCPOS_DUTY   3  /* 3 % */
#define RESBSL_udtMAXIMUM_SYNCPOS2_DELAY  995  /* Equivalent to 99.5 μ */
#define RESBSL_udtMINIMUM_SYNCPOS2_DELAY  15  /* Equivalent to 1.5 μ */
#define RESBSL_udtMAXIMUM_SYNCPOS2_DUTY   10  /* 10 % */
#define RESBSL_udtMINIMUM_SYNCPOS2_DUTY   3  /* 3 % */
#define RESBSL_snSYNCPOS_MCS_DELAY_PTR   MCS_pu32ResGtmSyncPosDelay
#define RESBSL_snSYNCPOS_MCS_DUTY_PTR    MCS_pu32ResGtmSyncPosDuty
#define RESBSL_snSYNCPOS2_MCS_DELAY_PTR   MCS_pu32ResGtmSyncPosDelay2
#define RESBSL_snSYNCPOS2_MCS_DUTY_PTR    MCS_pu32ResGtmSyncPosDuty2

/* Around 0 µs is time consumed in ARU (Round Trip Time) */ 
#define RESBSL_snSYNCPOS_ARU_ROUND_TRIP_TIME    0
#define RESBSL_snSYNCPOS2_ARU_ROUND_TRIP_TIME    0


#endif /* RES_CFG_H */

/*------------------------------ end of file ---------------------------------*/
