
/*
 **********************************************************************************************************************
 * Includes
 **********************************************************************************************************************
*/

/* <component>_MemMap.h for AUTOSAR Memory Mapping R4.0 Rev 3 */
/* MR12 DIR 4.10 VIOLATION: MemMap header concept - no protection against repeated inclusion intended */
/* ======================================================== */
#if defined BSW_START_SEC_VAR_CLEARED_8
    #undef  BSW_START_SEC_VAR_CLEARED_8

#elif defined BSW_STOP_SEC_VAR_CLEARED_8
    #undef BSW_STOP_SEC_VAR_CLEARED_8

#elif defined BSW_START_SEC_VAR_CLEARED_16
    #undef BSW_START_SEC_VAR_CLEARED_16

#elif defined BSW_STOP_SEC_VAR_CLEARED_16
    #undef BSW_STOP_SEC_VAR_CLEARED_16

#elif defined BSW_START_SEC_VAR_CLEARED_32
    #undef BSW_START_SEC_VAR_CLEARED_32

#elif defined BSW_STOP_SEC_VAR_CLEARED_32
    #undef BSW_STOP_SEC_VAR_CLEARED_32

#elif defined BSW_START_SEC_VAR_CLEARED_UNSPECIFIED
    #undef BSW_START_SEC_VAR_CLEARED_UNSPECIFIED

#elif defined BSW_STOP_SEC_VAR_CLEARED_UNSPECIFIED
    #undef BSW_STOP_SEC_VAR_CLEARED_UNSPECIFIED

#elif defined BSW_START_SEC_VAR_FAST_CLEARED_8
    #undef BSW_START_SEC_VAR_FAST_CLEARED_8

#elif defined BSW_STOP_SEC_VAR_FAST_CLEARED_8
    #undef BSW_STOP_SEC_VAR_FAST_CLEARED_8

#elif defined BSW_START_SEC_VAR_FAST_CLEARED_16
    #undef BSW_START_SEC_VAR_FAST_CLEARED_16

#elif defined BSW_STOP_SEC_VAR_FAST_CLEARED_16
    #undef BSW_STOP_SEC_VAR_FAST_CLEARED_16

#elif defined BSW_START_SEC_VAR_FAST_CLEARED_32
    #undef BSW_START_SEC_VAR_FAST_CLEARED_32

#elif defined BSW_STOP_SEC_VAR_FAST_CLEARED_32
    #undef BSW_STOP_SEC_VAR_FAST_CLEARED_32

#elif defined BSW_START_SEC_VAR_FAST_CLEARED_UNSPECIFIED
    #undef BSW_START_SEC_VAR_FAST_CLEARED_UNSPECIFIED

#elif defined BSW_STOP_SEC_VAR_FAST_CLEARED_UNSPECIFIED
    #undef BSW_STOP_SEC_VAR_FAST_CLEARED_UNSPECIFIED

#elif defined BSW_START_SEC_VAR_PBS_CLEARED_8
    #undef  BSW_START_SEC_VAR_PBS_CLEARED_8

#elif defined BSW_STOP_SEC_VAR_PBS_CLEARED_8
    #undef BSW_STOP_SEC_VAR_PBS_CLEARED_8

#elif defined BSW_START_SEC_VAR_PBS_CLEARED_16
    #undef BSW_START_SEC_VAR_PBS_CLEARED_16

#elif defined BSW_STOP_SEC_VAR_PBS_CLEARED_16
    #undef BSW_STOP_SEC_VAR_PBS_CLEARED_16

#elif defined BSW_START_SEC_VAR_PBS_CLEARED_32
    #undef BSW_START_SEC_VAR_PBS_CLEARED_32

#elif defined BSW_STOP_SEC_VAR_PBS_CLEARED_32
    #undef BSW_STOP_SEC_VAR_PBS_CLEARED_32

#elif defined BSW_START_SEC_VAR_PBS_CLEARED_UNSPECIFIED
    #undef BSW_START_SEC_VAR_PBS_CLEARED_UNSPECIFIED

#elif defined BSW_STOP_SEC_VAR_PBS_CLEARED_UNSPECIFIED
    #undef BSW_STOP_SEC_VAR_PBS_CLEARED_UNSPECIFIED


#elif defined BSW_START_SEC_RAM0_CLEARED_8
    #undef BSW_START_SEC_RAM0_CLEARED_8

#elif defined BSW_STOP_SEC_RAM0_CLEARED_8
    #undef BSW_STOP_SEC_RAM0_CLEARED_8

#elif defined BSW_START_SEC_RAM0_CLEARED_16
    #undef BSW_START_SEC_RAM0_CLEARED_16

#elif defined BSW_STOP_SEC_RAM0_CLEARED_16
    #undef BSW_STOP_SEC_RAM0_CLEARED_16

#elif defined BSW_START_SEC_RAM0_CLEARED_32
    #undef BSW_START_SEC_RAM0_CLEARED_32

#elif defined BSW_STOP_SEC_RAM0_CLEARED_32
    #undef BSW_STOP_SEC_RAM0_CLEARED_32

#elif defined BSW_START_SEC_RAM0_CLEARED_UNSPECIFIED
    #undef BSW_START_SEC_RAM0_CLEARED_UNSPECIFIED

#elif defined BSW_STOP_SEC_RAM0_CLEARED_UNSPECIFIED
    #undef BSW_STOP_SEC_RAM0_CLEARED_UNSPECIFIED

#elif defined BSW_START_SEC_RAM1_CLEARED_8
    #undef BSW_START_SEC_RAM1_CLEARED_8

#elif defined BSW_STOP_SEC_RAM1_CLEARED_8
    #undef BSW_STOP_SEC_RAM1_CLEARED_8

#elif defined BSW_START_SEC_RAM1_CLEARED_16
    #undef BSW_START_SEC_RAM1_CLEARED_16

#elif defined BSW_STOP_SEC_RAM1_CLEARED_16
    #undef BSW_STOP_SEC_RAM1_CLEARED_16

#elif defined BSW_START_SEC_RAM1_CLEARED_32
    #undef BSW_START_SEC_RAM1_CLEARED_32

#elif defined BSW_STOP_SEC_RAM1_CLEARED_32
    #undef BSW_STOP_SEC_RAM1_CLEARED_32

#elif defined BSW_START_SEC_RAM1_CLEARED_UNSPECIFIED
    #undef BSW_START_SEC_RAM1_CLEARED_UNSPECIFIED

#elif defined BSW_STOP_SEC_RAM1_CLEARED_UNSPECIFIED
    #undef BSW_STOP_SEC_RAM1_CLEARED_UNSPECIFIED

#elif defined BSW_START_SEC_RAM2_CLEARED_8
    #undef BSW_START_SEC_RAM2_CLEARED_8

#elif defined BSW_STOP_SEC_RAM2_CLEARED_8
    #undef BSW_STOP_SEC_RAM2_CLEARED_8

#elif defined BSW_START_SEC_RAM2_CLEARED_16
    #undef BSW_START_SEC_RAM2_CLEARED_16

#elif defined BSW_STOP_SEC_RAM2_CLEARED_16
    #undef BSW_STOP_SEC_RAM2_CLEARED_16

#elif defined BSW_START_SEC_RAM2_CLEARED_32
    #undef BSW_START_SEC_RAM2_CLEARED_32

#elif defined BSW_STOP_SEC_RAM2_CLEARED_32
    #undef BSW_STOP_SEC_RAM2_CLEARED_32

#elif defined BSW_START_SEC_RAM2_CLEARED_UNSPECIFIED
    #undef BSW_START_SEC_RAM2_CLEARED_UNSPECIFIED

#elif defined BSW_STOP_SEC_RAM2_CLEARED_UNSPECIFIED
    #undef BSW_STOP_SEC_RAM2_CLEARED_UNSPECIFIED

#elif defined BSW_START_SEC_SYSRAM_CLEARED_8
    #undef BSW_START_SEC_SYSRAM_CLEARED_8

#elif defined BSW_STOP_SEC_SYSRAM_CLEARED_8
    #undef BSW_STOP_SEC_SYSRAM_CLEARED_8

#elif defined BSW_START_SEC_SYSRAM_CLEARED_16
    #undef BSW_START_SEC_SYSRAM_CLEARED_16

#elif defined BSW_STOP_SEC_SYSRAM_CLEARED_16
    #undef BSW_STOP_SEC_SYSRAM_CLEARED_16

#elif defined BSW_START_SEC_SYSRAM_CLEARED_32
    #undef BSW_START_SEC_SYSRAM_CLEARED_32

#elif defined BSW_STOP_SEC_SYSRAM_CLEARED_32
    #undef BSW_STOP_SEC_SYSRAM_CLEARED_32

#elif defined BSW_START_SEC_SYSRAM_CLEARED_UNSPECIFIED
    #undef BSW_START_SEC_SYSRAM_CLEARED_UNSPECIFIED

#elif defined BSW_STOP_SEC_SYSRAM_CLEARED_UNSPECIFIED
    #undef BSW_STOP_SEC_SYSRAM_CLEARED_UNSPECIFIED
	
#elif defined BSW_START_SEC_VAR_CLEARED_SECURED_8
    #undef BSW_START_SEC_VAR_CLEARED_SECURED_8

#elif defined BSW_STOP_SEC_VAR_CLEARED_SECURED_8
    #undef BSW_STOP_SEC_VAR_CLEARED_SECURED_8

#elif defined BSW_START_SEC_VAR_CLEARED_SECURED_16
    #undef BSW_START_SEC_VAR_CLEARED_SECURED_16

#elif defined BSW_STOP_SEC_VAR_CLEARED_SECURED_16
    #undef BSW_STOP_SEC_VAR_CLEARED_SECURED_16

#elif defined BSW_START_SEC_VAR_CLEARED_SECURED_32
    #undef BSW_START_SEC_VAR_CLEARED_SECURED_32

#elif defined BSW_STOP_SEC_VAR_CLEARED_SECURED_32
    #undef BSW_STOP_SEC_VAR_CLEARED_SECURED_32

#elif defined BSW_START_SEC_VAR_CLEARED_SECURED_UNSPECIFIED
    #undef BSW_START_SEC_VAR_CLEARED_SECURED_UNSPECIFIED

#elif defined BSW_STOP_SEC_VAR_CLEARED_SECURED_UNSPECIFIED
    #undef BSW_STOP_SEC_VAR_CLEARED_SECURED_UNSPECIFIED

#elif defined BSW_START_SEC_VAR_CLEARED_SECURED_CACHE_LINE_ALIGNED_UNSPECIFIED
    #undef BSW_START_SEC_VAR_CLEARED_SECURED_CACHE_LINE_ALIGNED_UNSPECIFIED

#elif defined BSW_STOP_SEC_VAR_CLEARED_SECURED_CACHE_LINE_ALIGNED_UNSPECIFIED
    #undef BSW_STOP_SEC_VAR_CLEARED_SECURED_CACHE_LINE_ALIGNED_UNSPECIFIED

	
/* ======================================================== */
/* == Initialized Variables                              == */
/* ======================================================== */
#elif defined BSW_START_SEC_VAR_INIT_8
    #undef BSW_START_SEC_VAR_INIT_8

#elif defined BSW_STOP_SEC_VAR_INIT_8
    #undef BSW_STOP_SEC_VAR_INIT_8

#elif defined BSW_START_SEC_VAR_INIT_16
    #undef BSW_START_SEC_VAR_INIT_16

#elif defined BSW_STOP_SEC_VAR_INIT_16
    #undef BSW_STOP_SEC_VAR_INIT_16

#elif defined BSW_START_SEC_VAR_INIT_32
    #undef BSW_START_SEC_VAR_INIT_32

#elif defined BSW_STOP_SEC_VAR_INIT_32
    #undef BSW_STOP_SEC_VAR_INIT_32

#elif defined BSW_START_SEC_VAR_INIT_UNSPECIFIED
    #undef BSW_START_SEC_VAR_INIT_UNSPECIFIED

#elif defined BSW_STOP_SEC_VAR_INIT_UNSPECIFIED
    #undef BSW_STOP_SEC_VAR_INIT_UNSPECIFIED


#elif defined BSW_START_SEC_VAR_FAST_INIT_8
    #undef BSW_START_SEC_VAR_FAST_INIT_8

#elif defined BSW_STOP_SEC_VAR_FAST_INIT_8
    #undef BSW_STOP_SEC_VAR_FAST_INIT_8

#elif defined BSW_START_SEC_VAR_FAST_INIT_16
    #undef BSW_START_SEC_VAR_FAST_INIT_16

#elif defined BSW_STOP_SEC_VAR_FAST_INIT_16
    #undef BSW_STOP_SEC_VAR_FAST_INIT_16

#elif defined BSW_START_SEC_VAR_FAST_INIT_32
    #undef BSW_START_SEC_VAR_FAST_INIT_32

#elif defined BSW_STOP_SEC_VAR_FAST_INIT_32
    #undef BSW_STOP_SEC_VAR_FAST_INIT_32

#elif defined BSW_START_SEC_VAR_FAST_INIT_UNSPECIFIED
    #undef BSW_START_SEC_VAR_FAST_INIT_UNSPECIFIED

#elif defined BSW_STOP_SEC_VAR_FAST_INIT_UNSPECIFIED
    #undef BSW_STOP_SEC_VAR_FAST_INIT_UNSPECIFIED

#elif defined BSW_START_SEC_RAM0_INIT_8
    #undef BSW_START_SEC_RAM0_INIT_8

#elif defined BSW_STOP_SEC_RAM0_INIT_8
    #undef BSW_STOP_SEC_RAM0_INIT_8

#elif defined BSW_START_SEC_RAM0_INIT_16
    #undef BSW_START_SEC_RAM0_INIT_16

#elif defined BSW_STOP_SEC_RAM0_INIT_16
    #undef BSW_STOP_SEC_RAM0_INIT_16

#elif defined BSW_START_SEC_RAM0_INIT_32
    #undef BSW_START_SEC_RAM0_INIT_32

#elif defined BSW_STOP_SEC_RAM0_INIT_32
    #undef BSW_STOP_SEC_RAM0_INIT_32

#elif defined BSW_START_SEC_RAM0_INIT_UNSPECIFIED
    #undef BSW_START_SEC_RAM0_INIT_UNSPECIFIED

#elif defined BSW_STOP_SEC_RAM0_INIT_UNSPECIFIED
    #undef BSW_STOP_SEC_RAM0_INIT_UNSPECIFIED

#elif defined BSW_START_SEC_RAM1_INIT_8
    #undef BSW_START_SEC_RAM1_INIT_8

#elif defined BSW_STOP_SEC_RAM1_INIT_8
    #undef BSW_STOP_SEC_RAM1_INIT_8

#elif defined BSW_START_SEC_RAM1_INIT_16
    #undef BSW_START_SEC_RAM1_INIT_16

#elif defined BSW_STOP_SEC_RAM1_INIT_16
    #undef BSW_STOP_SEC_RAM1_INIT_16

#elif defined BSW_START_SEC_RAM1_INIT_32
    #undef BSW_START_SEC_RAM1_INIT_32

#elif defined BSW_STOP_SEC_RAM1_INIT_32
    #undef BSW_STOP_SEC_RAM1_INIT_32

#elif defined BSW_START_SEC_RAM1_INIT_UNSPECIFIED
    #undef BSW_START_SEC_RAM1_INIT_UNSPECIFIED

#elif defined BSW_STOP_SEC_RAM1_INIT_UNSPECIFIED
    #undef BSW_STOP_SEC_RAM1_INIT_UNSPECIFIED

#elif defined BSW_START_SEC_RAM2_INIT_8
    #undef BSW_START_SEC_RAM2_INIT_8

#elif defined BSW_STOP_SEC_RAM2_INIT_8
    #undef BSW_STOP_SEC_RAM2_INIT_8

#elif defined BSW_START_SEC_RAM2_INIT_16
    #undef BSW_START_SEC_RAM2_INIT_16

#elif defined BSW_STOP_SEC_RAM2_INIT_16
    #undef BSW_STOP_SEC_RAM2_INIT_16

#elif defined BSW_START_SEC_RAM2_INIT_32
    #undef BSW_START_SEC_RAM2_INIT_32

#elif defined BSW_STOP_SEC_RAM2_INIT_32
    #undef BSW_STOP_SEC_RAM2_INIT_32

#elif defined BSW_START_SEC_RAM2_INIT_UNSPECIFIED
    #undef BSW_START_SEC_RAM2_INIT_UNSPECIFIED

#elif defined BSW_STOP_SEC_RAM2_INIT_UNSPECIFIED
    #undef BSW_STOP_SEC_RAM2_INIT_UNSPECIFIED


/* ======================================================== */
/* == Reset Save Variables                               == */
/* ======================================================== */
#elif defined BSW_START_SEC_SAVED_ZONE_8
    #undef BSW_START_SEC_SAVED_ZONE_8

#elif defined BSW_STOP_SEC_SAVED_ZONE_8
    #undef BSW_STOP_SEC_SAVED_ZONE_8

#elif defined BSW_START_SEC_SAVED_ZONE_16
    #undef BSW_START_SEC_SAVED_ZONE_16

#elif defined BSW_STOP_SEC_SAVED_ZONE_16
    #undef BSW_STOP_SEC_SAVED_ZONE_16

#elif defined BSW_START_SEC_SAVED_ZONE_32
    #undef BSW_START_SEC_SAVED_ZONE_32

#elif defined BSW_STOP_SEC_SAVED_ZONE_32
    #undef BSW_STOP_SEC_SAVED_ZONE_32

#elif defined BSW_START_SEC_SAVED_ZONE_UNSPECIFIED
    #undef BSW_START_SEC_SAVED_ZONE_UNSPECIFIED

#elif defined BSW_STOP_SEC_SAVED_ZONE_UNSPECIFIED
    #undef BSW_STOP_SEC_SAVED_ZONE_UNSPECIFIED

#elif defined BSW_START_SEC_VAR_RESET_SAFE_8
    #undef BSW_START_SEC_VAR_RESET_SAFE_8

#elif defined BSW_STOP_SEC_VAR_RESET_SAFE_8
    #undef BSW_STOP_SEC_VAR_RESET_SAFE_8

#elif defined BSW_START_SEC_VAR_RESET_SAFE_16
    #undef BSW_START_SEC_VAR_RESET_SAFE_16

#elif defined BSW_STOP_SEC_VAR_RESET_SAFE_16
    #undef BSW_STOP_SEC_VAR_RESET_SAFE_16

#elif defined BSW_START_SEC_VAR_RESET_SAFE_32
    #undef BSW_START_SEC_VAR_RESET_SAFE_32

#elif defined BSW_STOP_SEC_VAR_RESET_SAFE_32
    #undef BSW_STOP_SEC_VAR_RESET_SAFE_32

#elif defined BSW_START_SEC_VAR_RESET_SAFE_UNSPECIFIED
    #undef BSW_START_SEC_VAR_RESET_SAFE_UNSPECIFIED

#elif defined BSW_STOP_SEC_VAR_RESET_SAFE_UNSPECIFIED
    #undef BSW_STOP_SEC_VAR_RESET_SAFE_UNSPECIFIED


/* ======================================================== */
/* == Constants                                          == */
/* ======================================================== */
#elif defined BSW_START_SEC_CONST_8
    #undef BSW_START_SEC_CONST_8

#elif defined BSW_STOP_SEC_CONST_8
    #undef BSW_STOP_SEC_CONST_8

#elif defined BSW_START_SEC_CONST_16
    #undef BSW_START_SEC_CONST_16

#elif defined BSW_STOP_SEC_CONST_16
    #undef BSW_STOP_SEC_CONST_16

#elif defined BSW_START_SEC_CONST_32
    #undef BSW_START_SEC_CONST_32

#elif defined BSW_STOP_SEC_CONST_32
    #undef BSW_STOP_SEC_CONST_32

#elif defined BSW_START_SEC_CONST_UNSPECIFIED
    #undef BSW_START_SEC_CONST_UNSPECIFIED

#elif defined BSW_STOP_SEC_CONST_UNSPECIFIED
    #undef BSW_STOP_SEC_CONST_UNSPECIFIED


#elif defined BSW_START_SEC_CONST_SAVED_RECOVERY_ZONE_8
    #undef BSW_START_SEC_CONST_SAVED_RECOVERY_ZONE_8

#elif defined BSW_STOP_SEC_CONST_SAVED_RECOVERY_ZONE_8
    #undef BSW_STOP_SEC_CONST_SAVED_RECOVERY_ZONE_8

#elif defined BSW_START_SEC_CONST_SAVED_RECOVERY_ZONE_16
    #undef BSW_START_SEC_CONST_SAVED_RECOVERY_ZONE_16

#elif defined BSW_STOP_SEC_CONST_SAVED_RECOVERY_ZONE_16
    #undef BSW_STOP_SEC_CONST_SAVED_RECOVERY_ZONE_16

#elif defined BSW_START_SEC_CONST_SAVED_RECOVERY_ZONE_32
    #undef BSW_START_SEC_CONST_SAVED_RECOVERY_ZONE_32

#elif defined BSW_STOP_SEC_CONST_SAVED_RECOVERY_ZONE_32
    #undef BSW_STOP_SEC_CONST_SAVED_RECOVERY_ZONE_32

#elif defined BSW_START_SEC_CONST_SAVED_RECOVERY_ZONE_UNSPECIFIED
    #undef BSW_START_SEC_CONST_SAVED_RECOVERY_ZONE_UNSPECIFIED

#elif defined BSW_STOP_SEC_CONST_SAVED_RECOVERY_ZONE_UNSPECIFIED
    #undef BSW_STOP_SEC_CONST_SAVED_RECOVERY_ZONE_UNSPECIFIED


/* ======================================================== */
/* == Calibration data                                   == */
/* ======================================================== */
#elif defined BSW_START_SEC_CALIB_8
    #undef BSW_START_SEC_CALIB_8

#elif defined BSW_STOP_SEC_CALIB_8
    #undef BSW_STOP_SEC_CALIB_8

#elif defined BSW_START_SEC_CALIB_16
    #undef BSW_START_SEC_CALIB_16

#elif defined BSW_STOP_SEC_CALIB_16
    #undef BSW_STOP_SEC_CALIB_16

#elif defined BSW_START_SEC_CALIB_32
    #undef BSW_START_SEC_CALIB_32

#elif defined BSW_STOP_SEC_CALIB_32
    #undef BSW_STOP_SEC_CALIB_32

#elif defined BSW_START_SEC_CALIB_64
    #undef BSW_START_SEC_CALIB_64

#elif defined BSW_STOP_SEC_CALIB_64
    #undef BSW_STOP_SEC_CALIB_64

#elif defined BSW_START_SEC_CALIB_UNSPECIFIED
    #undef BSW_START_SEC_CALIB_UNSPECIFIED

#elif defined BSW_STOP_SEC_CALIB_UNSPECIFIED
    #undef BSW_STOP_SEC_CALIB_UNSPECIFIED


/* ======================================================== */
/* == Code                                               == */
/* ======================================================== */
#elif defined BSW_START_SEC_CODE
    #undef BSW_START_SEC_CODE

#elif defined BSW_STOP_SEC_CODE
    #undef BSW_STOP_SEC_CODE

#elif defined BSW_START_SEC_CODE_FAST
    #undef BSW_START_SEC_CODE_FAST

#elif defined BSW_STOP_SEC_CODE_FAST
    #undef BSW_STOP_SEC_CODE_FAST

/* ========================================================= */
/* == Legacy, please keep deactivated for BSW development == */
/* ========================================================= */
#elif defined BSW_START_SEC_DEFAULT_RAM0_CLEARED_8
    #undef  BSW_START_SEC_DEFAULT_RAM0_CLEARED_8

#elif defined BSW_STOP_SEC_DEFAULT_RAM0_CLEARED_8
    #undef BSW_STOP_SEC_DEFAULT_RAM0_CLEARED_8

#elif defined BSW_START_SEC_DEFAULT_RAM0_CLEARED_16
    #undef BSW_START_SEC_DEFAULT_RAM0_CLEARED_16

#elif defined BSW_STOP_SEC_DEFAULT_RAM0_CLEARED_16
    #undef BSW_STOP_SEC_DEFAULT_RAM0_CLEARED_16

#elif defined BSW_START_SEC_DEFAULT_RAM0_CLEARED_32
    #undef BSW_START_SEC_DEFAULT_RAM0_CLEARED_32

#elif defined BSW_STOP_SEC_DEFAULT_RAM0_CLEARED_32
    #undef BSW_STOP_SEC_DEFAULT_RAM0_CLEARED_32

#elif defined BSW_START_SEC_DEFAULT_RAM0_CLEARED_UNSPECIFIED
    #undef BSW_START_SEC_DEFAULT_RAM0_CLEARED_UNSPECIFIED

#elif defined BSW_STOP_SEC_DEFAULT_RAM0_CLEARED_UNSPECIFIED
    #undef BSW_STOP_SEC_DEFAULT_RAM0_CLEARED_UNSPECIFIED

#elif defined BSW_START_SEC_DEFAULT_RAM1_CLEARED_8
    #undef BSW_START_SEC_DEFAULT_RAM1_CLEARED_8

#elif defined BSW_STOP_SEC_DEFAULT_RAM1_CLEARED_8
    #undef BSW_STOP_SEC_DEFAULT_RAM1_CLEARED_8

#elif defined BSW_START_SEC_DEFAULT_RAM1_CLEARED_16
    #undef BSW_START_SEC_DEFAULT_RAM1_CLEARED_16

#elif defined BSW_STOP_SEC_DEFAULT_RAM1_CLEARED_16
    #undef BSW_STOP_SEC_DEFAULT_RAM1_CLEARED_16

#elif defined BSW_START_SEC_DEFAULT_RAM1_CLEARED_32
    #undef BSW_START_SEC_DEFAULT_RAM1_CLEARED_32

#elif defined BSW_STOP_SEC_DEFAULT_RAM1_CLEARED_32
    #undef BSW_STOP_SEC_DEFAULT_RAM1_CLEARED_32

#elif defined BSW_START_SEC_DEFAULT_RAM1_CLEARED_UNSPECIFIED
    #undef BSW_START_SEC_DEFAULT_RAM1_CLEARED_UNSPECIFIED

#elif defined BSW_STOP_SEC_DEFAULT_RAM1_CLEARED_UNSPECIFIED
    #undef BSW_STOP_SEC_DEFAULT_RAM1_CLEARED_UNSPECIFIED

#elif defined BSW_START_SEC_DEFAULT_RAM2_CLEARED_8
    #undef BSW_START_SEC_DEFAULT_RAM2_CLEARED_8

#elif defined BSW_STOP_SEC_DEFAULT_RAM2_CLEARED_8
    #undef BSW_STOP_SEC_DEFAULT_RAM2_CLEARED_8

#elif defined BSW_START_SEC_DEFAULT_RAM2_CLEARED_16
    #undef BSW_START_SEC_DEFAULT_RAM2_CLEARED_16

#elif defined BSW_STOP_SEC_DEFAULT_RAM2_CLEARED_16
    #undef BSW_STOP_SEC_DEFAULT_RAM2_CLEARED_16

#elif defined BSW_START_SEC_DEFAULT_RAM2_CLEARED_32
    #undef BSW_START_SEC_DEFAULT_RAM2_CLEARED_32

#elif defined BSW_STOP_SEC_DEFAULT_RAM2_CLEARED_32
    #undef BSW_STOP_SEC_DEFAULT_RAM2_CLEARED_32

#elif defined BSW_START_SEC_DEFAULT_RAM2_CLEARED_UNSPECIFIED
    #undef BSW_START_SEC_DEFAULT_RAM2_CLEARED_UNSPECIFIED

#elif defined BSW_STOP_SEC_DEFAULT_RAM2_CLEARED_UNSPECIFIED
    #undef BSW_STOP_SEC_DEFAULT_RAM2_CLEARED_UNSPECIFIED

#elif defined BSW_START_SEC_DEFAULT_PBS_CLEARED_8
    #undef  BSW_START_SEC_DEFAULT_PBS_CLEARED_8

#elif defined BSW_STOP_SEC_DEFAULT_PBS_CLEARED_8
    #undef BSW_STOP_SEC_DEFAULT_PBS_CLEARED_8

#elif defined BSW_START_SEC_DEFAULT_PBS_CLEARED_16
    #undef BSW_START_SEC_DEFAULT_PBS_CLEARED_16

#elif defined BSW_STOP_SEC_DEFAULT_PBS_CLEARED_16
    #undef BSW_STOP_SEC_DEFAULT_PBS_CLEARED_16

#elif defined BSW_START_SEC_DEFAULT_PBS_CLEARED_32
    #undef BSW_START_SEC_DEFAULT_PBS_CLEARED_32

#elif defined BSW_STOP_SEC_DEFAULT_PBS_CLEARED_32
    #undef BSW_STOP_SEC_DEFAULT_PBS_CLEARED_32

#elif defined BSW_START_SEC_DEFAULT_PBS_CLEARED_UNSPECIFIED
    #undef BSW_START_SEC_DEFAULT_PBS_CLEARED_UNSPECIFIED

#elif defined BSW_STOP_SEC_DEFAULT_PBS_CLEARED_UNSPECIFIED
    #undef BSW_STOP_SEC_DEFAULT_PBS_CLEARED_UNSPECIFIED

#elif defined BSW_START_SEC_SMALL_RAM0_CLEARED_8
    #undef BSW_START_SEC_SMALL_RAM0_CLEARED_8

#elif defined BSW_STOP_SEC_SMALL_RAM0_CLEARED_8
    #undef BSW_STOP_SEC_SMALL_RAM0_CLEARED_8

#elif defined BSW_START_SEC_SMALL_RAM0_CLEARED_16
    #undef BSW_START_SEC_SMALL_RAM0_CLEARED_16

#elif defined BSW_STOP_SEC_SMALL_RAM0_CLEARED_16
    #undef BSW_STOP_SEC_SMALL_RAM0_CLEARED_16

#elif defined BSW_START_SEC_SMALL_RAM0_CLEARED_32
    #undef BSW_START_SEC_SMALL_RAM0_CLEARED_32

#elif defined BSW_STOP_SEC_SMALL_RAM0_CLEARED_32
    #undef BSW_STOP_SEC_SMALL_RAM0_CLEARED_32

#elif defined BSW_START_SEC_SMALL_RAM0_CLEARED_UNSPECIFIED
    #undef BSW_START_SEC_SMALL_RAM0_CLEARED_UNSPECIFIED

#elif defined BSW_STOP_SEC_SMALL_RAM0_CLEARED_UNSPECIFIED
    #undef BSW_STOP_SEC_SMALL_RAM0_CLEARED_UNSPECIFIED

#elif defined BSW_START_SEC_SMALL_RAM1_CLEARED_8
    #undef BSW_START_SEC_SMALL_RAM1_CLEARED_8

#elif defined BSW_STOP_SEC_SMALL_RAM1_CLEARED_8
    #undef BSW_STOP_SEC_SMALL_RAM1_CLEARED_8

#elif defined BSW_START_SEC_SMALL_RAM1_CLEARED_16
    #undef BSW_START_SEC_SMALL_RAM1_CLEARED_16

#elif defined BSW_STOP_SEC_SMALL_RAM1_CLEARED_16
    #undef BSW_STOP_SEC_SMALL_RAM1_CLEARED_16

#elif defined BSW_START_SEC_SMALL_RAM1_CLEARED_32
    #undef BSW_START_SEC_SMALL_RAM1_CLEARED_32

#elif defined BSW_STOP_SEC_SMALL_RAM1_CLEARED_32
    #undef BSW_STOP_SEC_SMALL_RAM1_CLEARED_32

#elif defined BSW_START_SEC_SMALL_RAM1_CLEARED_UNSPECIFIED
    #undef BSW_START_SEC_SMALL_RAM1_CLEARED_UNSPECIFIED

#elif defined BSW_STOP_SEC_SMALL_RAM1_CLEARED_UNSPECIFIED
    #undef BSW_STOP_SEC_SMALL_RAM1_CLEARED_UNSPECIFIED

#elif defined BSW_START_SEC_SMALL_RAM2_CLEARED_8
    #undef BSW_START_SEC_SMALL_RAM2_CLEARED_8

#elif defined BSW_STOP_SEC_SMALL_RAM2_CLEARED_8
    #undef BSW_STOP_SEC_SMALL_RAM2_CLEARED_8

#elif defined BSW_START_SEC_SMALL_RAM2_CLEARED_16
    #undef BSW_START_SEC_SMALL_RAM2_CLEARED_16

#elif defined BSW_STOP_SEC_SMALL_RAM2_CLEARED_16
    #undef BSW_STOP_SEC_SMALL_RAM2_CLEARED_16

#elif defined BSW_START_SEC_SMALL_RAM2_CLEARED_32
    #undef BSW_START_SEC_SMALL_RAM2_CLEARED_32

#elif defined BSW_STOP_SEC_SMALL_RAM2_CLEARED_32
    #undef BSW_STOP_SEC_SMALL_RAM2_CLEARED_32

#elif defined BSW_START_SEC_SMALL_RAM2_CLEARED_UNSPECIFIED
    #undef BSW_START_SEC_SMALL_RAM2_CLEARED_UNSPECIFIED

#elif defined BSW_STOP_SEC_SMALL_RAM2_CLEARED_UNSPECIFIED
    #undef BSW_STOP_SEC_SMALL_RAM2_CLEARED_UNSPECIFIED


#elif defined BSW_START_SEC_DEFAULT_RAM0_INIT_8
    #undef BSW_START_SEC_DEFAULT_RAM0_INIT_8

#elif defined BSW_STOP_SEC_DEFAULT_RAM0_INIT_8
    #undef BSW_STOP_SEC_DEFAULT_RAM0_INIT_8

#elif defined BSW_START_SEC_DEFAULT_RAM0_INIT_16
    #undef BSW_START_SEC_DEFAULT_RAM0_INIT_16

#elif defined BSW_STOP_SEC_DEFAULT_RAM0_INIT_16
    #undef BSW_STOP_SEC_DEFAULT_RAM0_INIT_16

#elif defined BSW_START_SEC_DEFAULT_RAM0_INIT_32
    #undef BSW_START_SEC_DEFAULT_RAM0_INIT_32

#elif defined BSW_STOP_SEC_DEFAULT_RAM0_INIT_32
    #undef BSW_STOP_SEC_DEFAULT_RAM0_INIT_32

#elif defined BSW_START_SEC_DEFAULT_RAM0_INIT_UNSPECIFIED
    #undef BSW_START_SEC_DEFAULT_RAM0_INIT_UNSPECIFIED

#elif defined BSW_STOP_SEC_DEFAULT_RAM0_INIT_UNSPECIFIED
    #undef BSW_STOP_SEC_DEFAULT_RAM0_INIT_UNSPECIFIED

#elif defined BSW_START_SEC_DEFAULT_RAM1_INIT_8
    #undef BSW_START_SEC_DEFAULT_RAM1_INIT_8

#elif defined BSW_STOP_SEC_DEFAULT_RAM1_INIT_8
    #undef BSW_STOP_SEC_DEFAULT_RAM1_INIT_8

#elif defined BSW_START_SEC_DEFAULT_RAM1_INIT_16
    #undef BSW_START_SEC_DEFAULT_RAM1_INIT_16

#elif defined BSW_STOP_SEC_DEFAULT_RAM1_INIT_16
    #undef BSW_STOP_SEC_DEFAULT_RAM1_INIT_16

#elif defined BSW_START_SEC_DEFAULT_RAM1_INIT_32
    #undef BSW_START_SEC_DEFAULT_RAM1_INIT_32

#elif defined BSW_STOP_SEC_DEFAULT_RAM1_INIT_32
    #undef BSW_STOP_SEC_DEFAULT_RAM1_INIT_32

#elif defined BSW_START_SEC_DEFAULT_RAM1_INIT_UNSPECIFIED
    #undef BSW_START_SEC_DEFAULT_RAM1_INIT_UNSPECIFIED

#elif defined BSW_STOP_SEC_DEFAULT_RAM1_INIT_UNSPECIFIED
    #undef BSW_STOP_SEC_DEFAULT_RAM1_INIT_UNSPECIFIED

#elif defined BSW_START_SEC_DEFAULT_RAM2_INIT_8
    #undef BSW_START_SEC_DEFAULT_RAM2_INIT_8

#elif defined BSW_STOP_SEC_DEFAULT_RAM2_INIT_8
    #undef BSW_STOP_SEC_DEFAULT_RAM2_INIT_8

#elif defined BSW_START_SEC_DEFAULT_RAM2_INIT_16
    #undef BSW_START_SEC_DEFAULT_RAM2_INIT_16

#elif defined BSW_STOP_SEC_DEFAULT_RAM2_INIT_16
    #undef BSW_STOP_SEC_DEFAULT_RAM2_INIT_16

#elif defined BSW_START_SEC_DEFAULT_RAM2_INIT_32
    #undef BSW_START_SEC_DEFAULT_RAM2_INIT_32

#elif defined BSW_STOP_SEC_DEFAULT_RAM2_INIT_32
    #undef BSW_STOP_SEC_DEFAULT_RAM2_INIT_32

#elif defined BSW_START_SEC_DEFAULT_RAM2_INIT_UNSPECIFIED
    #undef BSW_START_SEC_DEFAULT_RAM2_INIT_UNSPECIFIED

#elif defined BSW_STOP_SEC_DEFAULT_RAM2_INIT_UNSPECIFIED
    #undef BSW_STOP_SEC_DEFAULT_RAM2_INIT_UNSPECIFIED

#elif defined BSW_START_SEC_SMALL_RAM0_INIT_8
    #undef BSW_START_SEC_SMALL_RAM0_INIT_8

#elif defined BSW_STOP_SEC_SMALL_RAM0_INIT_8
    #undef BSW_STOP_SEC_SMALL_RAM0_INIT_8

#elif defined BSW_START_SEC_SMALL_RAM0_INIT_16
    #undef BSW_START_SEC_SMALL_RAM0_INIT_16

#elif defined BSW_STOP_SEC_SMALL_RAM0_INIT_16
    #undef BSW_STOP_SEC_SMALL_RAM0_INIT_16

#elif defined BSW_START_SEC_SMALL_RAM0_INIT_32
    #undef BSW_START_SEC_SMALL_RAM0_INIT_32

#elif defined BSW_STOP_SEC_SMALL_RAM0_INIT_32
    #undef BSW_STOP_SEC_SMALL_RAM0_INIT_32

#elif defined BSW_START_SEC_SMALL_RAM0_INIT_UNSPECIFIED
    #undef BSW_START_SEC_SMALL_RAM0_INIT_UNSPECIFIED

#elif defined BSW_STOP_SEC_SMALL_RAM0_INIT_UNSPECIFIED
    #undef BSW_STOP_SEC_SMALL_RAM0_INIT_UNSPECIFIED

#elif defined BSW_START_SEC_SMALL_RAM1_INIT_8
    #undef BSW_START_SEC_SMALL_RAM1_INIT_8

#elif defined BSW_STOP_SEC_SMALL_RAM1_INIT_8
    #undef BSW_STOP_SEC_SMALL_RAM1_INIT_8

#elif defined BSW_START_SEC_SMALL_RAM1_INIT_16
    #undef BSW_START_SEC_SMALL_RAM1_INIT_16

#elif defined BSW_STOP_SEC_SMALL_RAM1_INIT_16
    #undef BSW_STOP_SEC_SMALL_RAM1_INIT_16

#elif defined BSW_START_SEC_SMALL_RAM1_INIT_32
    #undef BSW_START_SEC_SMALL_RAM1_INIT_32

#elif defined BSW_STOP_SEC_SMALL_RAM1_INIT_32
    #undef BSW_STOP_SEC_SMALL_RAM1_INIT_32

#elif defined BSW_START_SEC_SMALL_RAM1_INIT_UNSPECIFIED
    #undef BSW_START_SEC_SMALL_RAM1_INIT_UNSPECIFIED

#elif defined BSW_STOP_SEC_SMALL_RAM1_INIT_UNSPECIFIED
    #undef BSW_STOP_SEC_SMALL_RAM1_INIT_UNSPECIFIED

#elif defined BSW_START_SEC_SMALL_RAM2_INIT_8
    #undef BSW_START_SEC_SMALL_RAM2_INIT_8

#elif defined BSW_STOP_SEC_SMALL_RAM2_INIT_8
    #undef BSW_STOP_SEC_SMALL_RAM2_INIT_8

#elif defined BSW_START_SEC_SMALL_RAM2_INIT_16
    #undef BSW_START_SEC_SMALL_RAM2_INIT_16

#elif defined BSW_STOP_SEC_SMALL_RAM2_INIT_16
    #undef BSW_STOP_SEC_SMALL_RAM2_INIT_16

#elif defined BSW_START_SEC_SMALL_RAM2_INIT_32
    #undef BSW_START_SEC_SMALL_RAM2_INIT_32

#elif defined BSW_STOP_SEC_SMALL_RAM2_INIT_32
    #undef BSW_STOP_SEC_SMALL_RAM2_INIT_32

#elif defined BSW_START_SEC_SMALL_RAM2_INIT_UNSPECIFIED
    #undef BSW_START_SEC_SMALL_RAM2_INIT_UNSPECIFIED

#elif defined BSW_STOP_SEC_SMALL_RAM2_INIT_UNSPECIFIED
    #undef BSW_STOP_SEC_SMALL_RAM2_INIT_UNSPECIFIED

#elif defined BSW_START_SEC_SMALL_SYSRAM_CLEARED_8
    #undef BSW_START_SEC_SMALL_SYSRAM_CLEARED_8

#elif defined BSW_STOP_SEC_SMALL_SYSRAM_CLEARED_8
    #undef BSW_STOP_SEC_SMALL_SYSRAM_CLEARED_8

#elif defined BSW_START_SEC_SMALL_SYSRAM_CLEARED_16
    #undef BSW_START_SEC_SMALL_SYSRAM_CLEARED_16

#elif defined BSW_STOP_SEC_SMALL_SYSRAM_CLEARED_16
    #undef BSW_STOP_SEC_SMALL_SYSRAM_CLEARED_16

#elif defined BSW_START_SEC_SMALL_SYSRAM_CLEARED_32
    #undef BSW_START_SEC_SMALL_SYSRAM_CLEARED_32

#elif defined BSW_STOP_SEC_SMALL_SYSRAM_CLEARED_32
    #undef BSW_STOP_SEC_SMALL_SYSRAM_CLEARED_32

#elif defined BSW_START_SEC_SMALL_SYSRAM_CLEARED_UNSPECIFIED
    #undef BSW_START_SEC_SMALL_SYSRAM_CLEARED_UNSPECIFIED

#elif defined BSW_STOP_SEC_SMALL_SYSRAM_CLEARED_UNSPECIFIED
    #undef BSW_STOP_SEC_SMALL_SYSRAM_CLEARED_UNSPECIFIED

#elif defined BSW_START_SEC_DEFAULT_SYSRAM_CLEARED_8
    #undef BSW_START_SEC_DEFAULT_SYSRAM_CLEARED_8

#elif defined BSW_STOP_SEC_DEFAULT_SYSRAM_CLEARED_8
    #undef BSW_STOP_SEC_DEFAULT_SYSRAM_CLEARED_8

#elif defined BSW_START_SEC_DEFAULT_SYSRAM_CLEARED_16
    #undef BSW_START_SEC_DEFAULT_SYSRAM_CLEARED_16

#elif defined BSW_STOP_SEC_DEFAULT_SYSRAM_CLEARED_16
    #undef BSW_STOP_SEC_DEFAULT_SYSRAM_CLEARED_16

#elif defined BSW_START_SEC_DEFAULT_SYSRAM_CLEARED_32
    #undef BSW_START_SEC_DEFAULT_SYSRAM_CLEARED_32

#elif defined BSW_STOP_SEC_DEFAULT_SYSRAM_CLEARED_32
    #undef BSW_STOP_SEC_DEFAULT_SYSRAM_CLEARED_32

#elif defined BSW_START_SEC_DEFAULT_SYSRAM_CLEARED_UNSPECIFIED
    #undef BSW_START_SEC_DEFAULT_SYSRAM_CLEARED_UNSPECIFIED

#elif defined BSW_STOP_SEC_DEFAULT_SYSRAM_CLEARED_UNSPECIFIED
    #undef BSW_STOP_SEC_DEFAULT_SYSRAM_CLEARED_UNSPECIFIED

#elif defined BSW_START_SEC_DEFAULT_RESET_SAFE_8
    #undef BSW_START_SEC_DEFAULT_RESET_SAFE_8

#elif defined BSW_STOP_SEC_DEFAULT_RESET_SAFE_8
    #undef BSW_STOP_SEC_DEFAULT_RESET_SAFE_8

#elif defined BSW_START_SEC_DEFAULT_RESET_SAFE_16
    #undef BSW_START_SEC_DEFAULT_RESET_SAFE_16

#elif defined BSW_STOP_SEC_DEFAULT_RESET_SAFE_16
    #undef BSW_STOP_SEC_DEFAULT_RESET_SAFE_16

#elif defined BSW_START_SEC_DEFAULT_RESET_SAFE_32
    #undef BSW_START_SEC_DEFAULT_RESET_SAFE_32

#elif defined BSW_STOP_SEC_DEFAULT_RESET_SAFE_32
    #undef BSW_STOP_SEC_DEFAULT_RESET_SAFE_32

#elif defined BSW_START_SEC_DEFAULT_RESET_SAFE_UNSPECIFIED
    #undef BSW_START_SEC_DEFAULT_RESET_SAFE_UNSPECIFIED

#elif defined BSW_STOP_SEC_DEFAULT_RESET_SAFE_UNSPECIFIED
    #undef BSW_STOP_SEC_DEFAULT_RESET_SAFE_UNSPECIFIED

#elif defined BSW_START_SEC_DEFAULT_RESET_SAFE_RAM0_8
    #undef BSW_START_SEC_DEFAULT_RESET_SAFE_RAM0_8

#elif defined BSW_STOP_SEC_DEFAULT_RESET_SAFE_RAM0_8
    #undef BSW_STOP_SEC_DEFAULT_RESET_SAFE_RAM0_8

#elif defined BSW_START_SEC_DEFAULT_RESET_SAFE_RAM0_16
    #undef BSW_START_SEC_DEFAULT_RESET_SAFE_RAM0_16

#elif defined BSW_STOP_SEC_DEFAULT_RESET_SAFE_RAM0_16
    #undef BSW_STOP_SEC_DEFAULT_RESET_SAFE_RAM0_16

#elif defined BSW_START_SEC_DEFAULT_RESET_SAFE_RAM0_32
    #undef BSW_START_SEC_DEFAULT_RESET_SAFE_RAM0_32

#elif defined BSW_STOP_SEC_DEFAULT_RESET_SAFE_RAM0_32
    #undef BSW_STOP_SEC_DEFAULT_RESET_SAFE_RAM0_32

#elif defined BSW_START_SEC_DEFAULT_RESET_SAFE_RAM0_UNSPECIFIED
    #undef BSW_START_SEC_DEFAULT_RESET_SAFE_RAM0_UNSPECIFIED

#elif defined BSW_STOP_SEC_DEFAULT_RESET_SAFE_RAM0_UNSPECIFIED
    #undef BSW_STOP_SEC_DEFAULT_RESET_SAFE_RAM0_UNSPECIFIED

#elif defined BSW_START_SEC_DEFAULT_RESET_SAFE_RAM1_8
    #undef BSW_START_SEC_DEFAULT_RESET_SAFE_RAM1_8

#elif defined BSW_STOP_SEC_DEFAULT_RESET_SAFE_RAM1_8
    #undef BSW_STOP_SEC_DEFAULT_RESET_SAFE_RAM1_8

#elif defined BSW_START_SEC_DEFAULT_RESET_SAFE_RAM1_16
    #undef BSW_START_SEC_DEFAULT_RESET_SAFE_RAM1_16

#elif defined BSW_STOP_SEC_DEFAULT_RESET_SAFE_RAM1_16
    #undef BSW_STOP_SEC_DEFAULT_RESET_SAFE_RAM1_16

#elif defined BSW_START_SEC_DEFAULT_RESET_SAFE_RAM1_32
    #undef BSW_START_SEC_DEFAULT_RESET_SAFE_RAM1_32

#elif defined BSW_STOP_SEC_DEFAULT_RESET_SAFE_RAM1_32
    #undef BSW_STOP_SEC_DEFAULT_RESET_SAFE_RAM1_32

#elif defined BSW_START_SEC_DEFAULT_RESET_SAFE_RAM1_UNSPECIFIED
    #undef BSW_START_SEC_DEFAULT_RESET_SAFE_RAM1_UNSPECIFIED

#elif defined BSW_STOP_SEC_DEFAULT_RESET_SAFE_RAM1_UNSPECIFIED
    #undef BSW_STOP_SEC_DEFAULT_RESET_SAFE_RAM1_UNSPECIFIED

#elif defined BSW_START_SEC_DEFAULT_RESET_SAFE_RAM2_8
    #undef BSW_START_SEC_DEFAULT_RESET_SAFE_RAM2_8

#elif defined BSW_STOP_SEC_DEFAULT_RESET_SAFE_RAM2_8
    #undef BSW_STOP_SEC_DEFAULT_RESET_SAFE_RAM2_8

#elif defined BSW_START_SEC_DEFAULT_RESET_SAFE_RAM2_16
    #undef BSW_START_SEC_DEFAULT_RESET_SAFE_RAM2_16

#elif defined BSW_STOP_SEC_DEFAULT_RESET_SAFE_RAM2_16
    #undef BSW_STOP_SEC_DEFAULT_RESET_SAFE_RAM2_16

#elif defined BSW_START_SEC_DEFAULT_RESET_SAFE_RAM2_32
    #undef BSW_START_SEC_DEFAULT_RESET_SAFE_RAM2_32

#elif defined BSW_STOP_SEC_DEFAULT_RESET_SAFE_RAM2_32
    #undef BSW_STOP_SEC_DEFAULT_RESET_SAFE_RAM2_32

#elif defined BSW_START_SEC_DEFAULT_RESET_SAFE_RAM2_UNSPECIFIED
    #undef BSW_START_SEC_DEFAULT_RESET_SAFE_RAM2_UNSPECIFIED

#elif defined BSW_STOP_SEC_DEFAULT_RESET_SAFE_RAM2_UNSPECIFIED
    #undef BSW_STOP_SEC_DEFAULT_RESET_SAFE_RAM2_UNSPECIFIED

#elif defined BSW_START_SEC_DEFAULT_CONST_8
    #undef BSW_START_SEC_DEFAULT_CONST_8

#elif defined BSW_STOP_SEC_DEFAULT_CONST_8
    #undef BSW_STOP_SEC_DEFAULT_CONST_8

#elif defined BSW_START_SEC_DEFAULT_CONST_16
    #undef BSW_START_SEC_DEFAULT_CONST_16

#elif defined BSW_STOP_SEC_DEFAULT_CONST_16
    #undef BSW_STOP_SEC_DEFAULT_CONST_16

#elif defined BSW_START_SEC_DEFAULT_CONST_32
    #undef BSW_START_SEC_DEFAULT_CONST_32

#elif defined BSW_STOP_SEC_DEFAULT_CONST_32
    #undef BSW_STOP_SEC_DEFAULT_CONST_32

#elif defined BSW_START_SEC_DEFAULT_CONST_UNSPECIFIED
    #undef BSW_START_SEC_DEFAULT_CONST_UNSPECIFIED

#elif defined BSW_STOP_SEC_DEFAULT_CONST_UNSPECIFIED
    #undef BSW_STOP_SEC_DEFAULT_CONST_UNSPECIFIED

    /* Calibration constants */
#elif defined BSW_START_SEC_DEFAULT_CALIB_8
    #undef BSW_START_SEC_DEFAULT_CALIB_8

#elif defined BSW_STOP_SEC_DEFAULT_CALIB_8
    #undef BSW_STOP_SEC_DEFAULT_CALIB_8

#elif defined BSW_START_SEC_DEFAULT_CALIB_16
    #undef BSW_START_SEC_DEFAULT_CALIB_16

#elif defined BSW_STOP_SEC_DEFAULT_CALIB_16
    #undef BSW_STOP_SEC_DEFAULT_CALIB_16

#elif defined BSW_START_SEC_DEFAULT_CALIB_32
    #undef BSW_START_SEC_DEFAULT_CALIB_32

#elif defined BSW_STOP_SEC_DEFAULT_CALIB_32
    #undef BSW_STOP_SEC_DEFAULT_CALIB_32

#elif defined BSW_START_SEC_DEFAULT_CALIB_UNSPECIFIED
    #undef BSW_START_SEC_DEFAULT_CALIB_UNSPECIFIED

#elif defined BSW_STOP_SEC_DEFAULT_CALIB_UNSPECIFIED
    #undef BSW_STOP_SEC_DEFAULT_CALIB_UNSPECIFIED

#elif defined BSW_START_SEC_SPRAM_CODE
    #undef BSW_START_SEC_SPRAM_CODE

#elif defined BSW_STOP_SEC_SPRAM_CODE
    #undef BSW_STOP_SEC_SPRAM_CODE

#elif defined BSW_STOP_SEC_DEFAULT_CODE
    #undef BSW_STOP_SEC_DEFAULT_CODE

#elif defined BSW_START_SEC_DEFAULT_CODE
    #undef BSW_START_SEC_DEFAULT_CODE

#elif defined BSW_START_SEC_VAR_CLEARED_BOOLEAN
    #undef BSW_START_SEC_VAR_CLEARED_BOOLEAN

#elif defined BSW_STOP_SEC_VAR_CLEARED_BOOLEAN
    #undef BSW_STOP_SEC_VAR_CLEARED_BOOLEAN

#elif defined BSW_START_SEC_VAR_INIT_BOOLEAN
    #undef BSW_START_SEC_VAR_INIT_BOOLEAN

#elif defined BSW_STOP_SEC_VAR_INIT_BOOLEAN
    #undef BSW_STOP_SEC_VAR_INIT_BOOLEAN

#elif defined BSW_START_SEC_VAR_SAVED_ZONE_UNSPECIFIED
    #undef BSW_START_SEC_VAR_SAVED_ZONE_UNSPECIFIED

#elif defined BSW_STOP_SEC_VAR_SAVED_ZONE_UNSPECIFIED
    #undef BSW_STOP_SEC_VAR_SAVED_ZONE_UNSPECIFIED

#elif defined BSW_START_SEC_VAR_SAVED_ZONE0_UNSPECIFIED
    #undef BSW_START_SEC_VAR_SAVED_ZONE0_UNSPECIFIED

#elif defined BSW_STOP_SEC_VAR_SAVED_ZONE0_UNSPECIFIED
    #undef BSW_STOP_SEC_VAR_SAVED_ZONE0_UNSPECIFIED

#elif defined BSW_START_SEC_CONST_BOOLEAN
    #undef BSW_START_SEC_CONST_BOOLEAN

#elif defined BSW_STOP_SEC_CONST_BOOLEAN
    #undef BSW_STOP_SEC_CONST_BOOLEAN

#elif defined BSW_START_SEC_CONFIG_DATA_8
    #undef BSW_START_SEC_CONFIG_DATA_8

#elif defined BSW_STOP_SEC_CONFIG_DATA_8
    #undef BSW_STOP_SEC_CONFIG_DATA_8

#elif defined BSW_START_SEC_CONFIG_DATA_16
    #undef BSW_START_SEC_CONFIG_DATA_16

#elif defined BSW_STOP_SEC_CONFIG_DATA_16
    #undef BSW_STOP_SEC_CONFIG_DATA_16

#elif defined BSW_START_SEC_CONFIG_DATA_32
    #undef BSW_START_SEC_CONFIG_DATA_32

#elif defined BSW_STOP_SEC_CONFIG_DATA_32
    #undef BSW_STOP_SEC_CONFIG_DATA_32

#elif defined BSW_START_SEC_CONFIG_DATA_UNSPECIFIED
    #undef BSW_START_SEC_CONFIG_DATA_UNSPECIFIED

#elif defined BSW_STOP_SEC_CONFIG_DATA_UNSPECIFIED
    #undef BSW_STOP_SEC_CONFIG_DATA_UNSPECIFIED

#elif defined BSW_START_SEC_CONFIG_DATA_POSTBUILD_HEADER
    #undef BSW_START_SEC_CONFIG_DATA_POSTBUILD_HEADER

#elif defined BSW_STOP_SEC_CONFIG_DATA_POSTBUILD_HEADER
    #undef BSW_STOP_SEC_CONFIG_DATA_POSTBUILD_HEADER

#elif defined BSW_START_SEC_CONFIG_DATA_POSTBUILD_8
    #undef BSW_START_SEC_CONFIG_DATA_POSTBUILD_8

#elif defined BSW_STOP_SEC_CONFIG_DATA_POSTBUILD_8
    #undef BSW_STOP_SEC_CONFIG_DATA_POSTBUILD_8

#elif defined BSW_START_SEC_CONFIG_DATA_POSTBUILD_16
    #undef BSW_START_SEC_CONFIG_DATA_POSTBUILD_16

#elif defined BSW_STOP_SEC_CONFIG_DATA_POSTBUILD_16
    #undef BSW_STOP_SEC_CONFIG_DATA_POSTBUILD_16

#elif defined BSW_START_SEC_CONFIG_DATA_POSTBUILD_32
    #undef BSW_START_SEC_CONFIG_DATA_POSTBUILD_32

#elif defined BSW_STOP_SEC_CONFIG_DATA_POSTBUILD_32
    #undef BSW_STOP_SEC_CONFIG_DATA_POSTBUILD_32

#elif defined BSW_START_SEC_CONFIG_DATA_POSTBUILD_UNSPECIFIED
    #undef BSW_START_SEC_CONFIG_DATA_POSTBUILD_UNSPECIFIED

#elif defined BSW_STOP_SEC_CONFIG_DATA_POSTBUILD_UNSPECIFIED
    #undef BSW_STOP_SEC_CONFIG_DATA_POSTBUILD_UNSPECIFIED

#elif defined BSW_START_SEC_VAR_CLEARED_POSTBUILD_UNSPECIFIED
    #undef BSW_START_SEC_VAR_CLEARED_POSTBUILD_UNSPECIFIED

#elif defined BSW_STOP_SEC_VAR_CLEARED_POSTBUILD_UNSPECIFIED
    #undef BSW_STOP_SEC_VAR_CLEARED_POSTBUILD_UNSPECIFIED

#elif defined BSW_START_SEC_VAR_CLEARED_POSTBUILD_8
    #undef BSW_START_SEC_VAR_CLEARED_POSTBUILD_8

#elif defined BSW_STOP_SEC_VAR_CLEARED_POSTBUILD_8
    #undef BSW_STOP_SEC_VAR_CLEARED_POSTBUILD_8

#elif defined BSW_START_SEC_VAR_CLEARED_POSTBUILD_16
    #undef BSW_START_SEC_VAR_CLEARED_POSTBUILD_16

#elif defined BSW_STOP_SEC_VAR_CLEARED_POSTBUILD_16
    #undef BSW_STOP_SEC_VAR_CLEARED_POSTBUILD_16

#elif defined BSW_START_SEC_VAR_CLEARED_POSTBUILD_32
    #undef BSW_START_SEC_VAR_CLEARED_POSTBUILD_32

#elif defined BSW_STOP_SEC_VAR_CLEARED_POSTBUILD_32
    #undef BSW_STOP_SEC_VAR_CLEARED_POSTBUILD_32

#elif defined BSW_START_SEC_CORE1_VAR_CLEARED_8
    #undef BSW_START_SEC_CORE1_VAR_CLEARED_8
	
#elif defined BSW_STOP_SEC_CORE1_VAR_CLEARED_8
    #undef BSW_STOP_SEC_CORE1_VAR_CLEARED_8
	
#elif defined BSW_START_SEC_CORE1_VAR_CLEARED_16
    #undef BSW_START_SEC_CORE1_VAR_CLEARED_16
	
#elif defined BSW_STOP_SEC_CORE1_VAR_CLEARED_16
    #undef BSW_STOP_SEC_CORE1_VAR_CLEARED_16
	
#elif defined BSW_START_SEC_CORE1_VAR_CLEARED_32
    #undef BSW_START_SEC_CORE1_VAR_CLEARED_32
	
#elif defined BSW_STOP_SEC_CORE1_VAR_CLEARED_32
    #undef BSW_STOP_SEC_CORE1_VAR_CLEARED_32
	
#elif defined BSW_START_SEC_CORE1_VAR_CLEARED_64
    #undef BSW_START_SEC_CORE1_VAR_CLEARED_64
	
#elif defined BSW_STOP_SEC_CORE1_VAR_CLEARED_64
    #undef BSW_STOP_SEC_CORE1_VAR_CLEARED_64
	
#elif defined BSW_START_SEC_CORE1_VAR_CLEARED_UNSPECIFIED
    #undef BSW_START_SEC_CORE1_VAR_CLEARED_UNSPECIFIED
	
#elif defined BSW_STOP_SEC_CORE1_VAR_CLEARED_UNSPECIFIED
    #undef BSW_STOP_SEC_CORE1_VAR_CLEARED_UNSPECIFIED
	
#elif defined BSW_START_SEC_CORE2_VAR_CLEARED_8
    #undef BSW_START_SEC_CORE2_VAR_CLEARED_8
	
#elif defined BSW_STOP_SEC_CORE2_VAR_CLEARED_8
    #undef BSW_STOP_SEC_CORE2_VAR_CLEARED_8
	
#elif defined BSW_START_SEC_CORE2_VAR_CLEARED_16
    #undef BSW_START_SEC_CORE2_VAR_CLEARED_16
	
#elif defined BSW_STOP_SEC_CORE2_VAR_CLEARED_16
    #undef BSW_STOP_SEC_CORE2_VAR_CLEARED_16
	
#elif defined BSW_START_SEC_CORE2_VAR_CLEARED_32
    #undef BSW_START_SEC_CORE2_VAR_CLEARED_32
	
#elif defined BSW_STOP_SEC_CORE2_VAR_CLEARED_32
    #undef BSW_STOP_SEC_CORE2_VAR_CLEARED_32
	
#elif defined BSW_START_SEC_CORE2_VAR_CLEARED_64
    #undef BSW_START_SEC_CORE2_VAR_CLEARED_64
	
#elif defined BSW_STOP_SEC_CORE2_VAR_CLEARED_64
    #undef BSW_STOP_SEC_CORE2_VAR_CLEARED_64
	
#elif defined BSW_START_SEC_CORE2_VAR_CLEARED_UNSPECIFIED
    #undef BSW_START_SEC_CORE2_VAR_CLEARED_UNSPECIFIED
	
#elif defined BSW_STOP_SEC_CORE2_VAR_CLEARED_UNSPECIFIED
    #undef BSW_STOP_SEC_CORE2_VAR_CLEARED_UNSPECIFIED
	
#elif defined BSW_START_SEC_CORE3_VAR_CLEARED_8
    #undef BSW_START_SEC_CORE3_VAR_CLEARED_8
	
#elif defined BSW_STOP_SEC_CORE3_VAR_CLEARED_8
    #undef BSW_STOP_SEC_CORE3_VAR_CLEARED_8
	
#elif defined BSW_START_SEC_CORE3_VAR_CLEARED_16
    #undef BSW_START_SEC_CORE3_VAR_CLEARED_16
	
#elif defined BSW_STOP_SEC_CORE3_VAR_CLEARED_16
    #undef BSW_STOP_SEC_CORE3_VAR_CLEARED_16
	
#elif defined BSW_START_SEC_CORE3_VAR_CLEARED_32
    #undef BSW_START_SEC_CORE3_VAR_CLEARED_32
	
#elif defined BSW_STOP_SEC_CORE3_VAR_CLEARED_32
    #undef BSW_STOP_SEC_CORE3_VAR_CLEARED_32
	
#elif defined BSW_START_SEC_CORE3_VAR_CLEARED_64
    #undef BSW_START_SEC_CORE3_VAR_CLEARED_64
	
#elif defined BSW_STOP_SEC_CORE3_VAR_CLEARED_64
    #undef BSW_STOP_SEC_CORE3_VAR_CLEARED_64
	
#elif defined BSW_START_SEC_CORE3_VAR_CLEARED_UNSPECIFIED
    #undef BSW_START_SEC_CORE3_VAR_CLEARED_UNSPECIFIED
	
#elif defined BSW_STOP_SEC_CORE3_VAR_CLEARED_UNSPECIFIED
    #undef BSW_STOP_SEC_CORE3_VAR_CLEARED_UNSPECIFIED
	
#elif defined BSW_START_SEC_CORE4_VAR_CLEARED_8
    #undef BSW_START_SEC_CORE4_VAR_CLEARED_8
	
#elif defined BSW_STOP_SEC_CORE4_VAR_CLEARED_8
    #undef BSW_STOP_SEC_CORE4_VAR_CLEARED_8
	
#elif defined BSW_START_SEC_CORE4_VAR_CLEARED_16
    #undef BSW_START_SEC_CORE4_VAR_CLEARED_16
	
#elif defined BSW_STOP_SEC_CORE4_VAR_CLEARED_16
    #undef BSW_STOP_SEC_CORE4_VAR_CLEARED_16
	
#elif defined BSW_START_SEC_CORE4_VAR_CLEARED_32
    #undef BSW_START_SEC_CORE4_VAR_CLEARED_32
	
#elif defined BSW_STOP_SEC_CORE4_VAR_CLEARED_32
    #undef BSW_STOP_SEC_CORE4_VAR_CLEARED_32
	
#elif defined BSW_START_SEC_CORE4_VAR_CLEARED_64
    #undef BSW_START_SEC_CORE4_VAR_CLEARED_64
	
#elif defined BSW_STOP_SEC_CORE4_VAR_CLEARED_64
    #undef BSW_STOP_SEC_CORE4_VAR_CLEARED_64
	
#elif defined BSW_START_SEC_CORE4_VAR_CLEARED_UNSPECIFIED
    #undef BSW_START_SEC_CORE4_VAR_CLEARED_UNSPECIFIED
	
#elif defined BSW_STOP_SEC_CORE4_VAR_CLEARED_UNSPECIFIED
    #undef BSW_STOP_SEC_CORE4_VAR_CLEARED_UNSPECIFIED
	
#elif defined BSW_START_SEC_CORE5_VAR_CLEARED_8
    #undef BSW_START_SEC_CORE5_VAR_CLEARED_8
	
#elif defined BSW_STOP_SEC_CORE5_VAR_CLEARED_8
    #undef BSW_STOP_SEC_CORE5_VAR_CLEARED_8
	
#elif defined BSW_START_SEC_CORE5_VAR_CLEARED_16
    #undef BSW_START_SEC_CORE5_VAR_CLEARED_16
		
#elif defined BSW_STOP_SEC_CORE5_VAR_CLEARED_16
    #undef BSW_STOP_SEC_CORE5_VAR_CLEARED_16
		
#elif defined BSW_START_SEC_CORE5_VAR_CLEARED_32
    #undef BSW_START_SEC_CORE5_VAR_CLEARED_32
		
#elif defined BSW_STOP_SEC_CORE5_VAR_CLEARED_32
    #undef BSW_STOP_SEC_CORE5_VAR_CLEARED_32
		
#elif defined BSW_START_SEC_CORE5_VAR_CLEARED_64
    #undef BSW_START_SEC_CORE5_VAR_CLEARED_64
		
#elif defined BSW_STOP_SEC_CORE5_VAR_CLEARED_64
    #undef BSW_STOP_SEC_CORE5_VAR_CLEARED_64
		
#elif defined BSW_START_SEC_CORE5_VAR_CLEARED_UNSPECIFIED
    #undef BSW_START_SEC_CORE5_VAR_CLEARED_UNSPECIFIED
		
#elif defined BSW_STOP_SEC_CORE5_VAR_CLEARED_UNSPECIFIED
    #undef BSW_STOP_SEC_CORE5_VAR_CLEARED_UNSPECIFIED
		
#elif defined BSW_START_SEC_CORE6_VAR_CLEARED_8
    #undef BSW_START_SEC_CORE6_VAR_CLEARED_8
		
#elif defined BSW_STOP_SEC_CORE6_VAR_CLEARED_8
    #undef BSW_STOP_SEC_CORE6_VAR_CLEARED_8
		
#elif defined BSW_START_SEC_CORE6_VAR_CLEARED_16
    #undef BSW_START_SEC_CORE6_VAR_CLEARED_16
		
#elif defined BSW_STOP_SEC_CORE6_VAR_CLEARED_16
    #undef BSW_STOP_SEC_CORE6_VAR_CLEARED_16
		
#elif defined BSW_START_SEC_CORE6_VAR_CLEARED_32
    #undef BSW_START_SEC_CORE6_VAR_CLEARED_32
		
#elif defined BSW_STOP_SEC_CORE6_VAR_CLEARED_32
    #undef BSW_STOP_SEC_CORE6_VAR_CLEARED_32
		
#elif defined BSW_START_SEC_CORE6_VAR_CLEARED_64
    #undef BSW_START_SEC_CORE6_VAR_CLEARED_64
		
#elif defined BSW_STOP_SEC_CORE6_VAR_CLEARED_64
    #undef BSW_STOP_SEC_CORE6_VAR_CLEARED_64
		
#elif defined BSW_START_SEC_CORE6_VAR_CLEARED_UNSPECIFIED
    #undef BSW_START_SEC_CORE6_VAR_CLEARED_UNSPECIFIED
		
#elif defined BSW_STOP_SEC_CORE6_VAR_CLEARED_UNSPECIFIED
    #undef BSW_STOP_SEC_CORE6_VAR_CLEARED_UNSPECIFIED
		
#elif defined BSW_START_SEC_VAR_CLEARED_POSTBUILD_BOOLEAN
    #undef BSW_START_SEC_VAR_CLEARED_POSTBUILD_BOOLEAN
		
#elif defined BSW_STOP_SEC_VAR_CLEARED_POSTBUILD_BOOLEAN
    #undef BSW_STOP_SEC_VAR_CLEARED_POSTBUILD_BOOLEAN
		
#elif defined BSW_START_SEC_VAR_INIT_POSTBUILD_8
    #undef BSW_START_SEC_VAR_INIT_POSTBUILD_8
		
#elif defined BSW_STOP_SEC_VAR_INIT_POSTBUILD_8
    #undef BSW_STOP_SEC_VAR_INIT_POSTBUILD_8
		
#elif defined BSW_START_SEC_VAR_SAVED_ZONE_8
    #undef BSW_START_SEC_VAR_SAVED_ZONE_8
		
#elif defined BSW_STOP_SEC_VAR_SAVED_ZONE_8
    #undef BSW_STOP_SEC_VAR_SAVED_ZONE_8
		
#elif defined BSW_START_SEC_VAR_SAVED_ZONE_16
    #undef BSW_START_SEC_VAR_SAVED_ZONE_16
		
#elif defined BSW_STOP_SEC_VAR_SAVED_ZONE_16
    #undef BSW_STOP_SEC_VAR_SAVED_ZONE_16
		
#elif defined BSW_START_SEC_VAR_SAVED_ZONE_32
    #undef BSW_START_SEC_VAR_SAVED_ZONE_32
		
#elif defined BSW_STOP_SEC_VAR_SAVED_ZONE_32
    #undef BSW_STOP_SEC_VAR_SAVED_ZONE_32
			
#elif defined BSW_START_SEC_VAR_HSM_SHARED_CLEARED_UNSPECIFIED
    #undef BSW_START_SEC_VAR_HSM_SHARED_CLEARED_UNSPECIFIED
		
#elif defined BSW_STOP_SEC_VAR_HSM_SHARED_CLEARED_UNSPECIFIED
    #undef BSW_STOP_SEC_VAR_HSM_SHARED_CLEARED_UNSPECIFIED
			
#elif defined BSW_START_SEC_VAR_HSM_SHARED_INIT_UNSPECIFIED
    #undef BSW_START_SEC_VAR_HSM_SHARED_INIT_UNSPECIFIED
		
#elif defined BSW_STOP_SEC_VAR_HSM_SHARED_INIT_UNSPECIFIED
    #undef BSW_STOP_SEC_VAR_HSM_SHARED_INIT_UNSPECIFIED
			
#elif defined BSW_START_SEC_VAR_HSM_SHARED_READONLY_CLEARED_UNSPECIFIED
    #undef BSW_START_SEC_VAR_HSM_SHARED_READONLY_CLEARED_UNSPECIFIED
		
#elif defined BSW_STOP_SEC_VAR_HSM_SHARED_READONLY_CLEARED_UNSPECIFIED
    #undef BSW_STOP_SEC_VAR_HSM_SHARED_READONLY_CLEARED_UNSPECIFIED
			
#elif defined BSW_START_SEC_VAR_HSM_SHARED_READONLY_INIT_UNSPECIFIED
    #undef BSW_START_SEC_VAR_HSM_SHARED_READONLY_INIT_UNSPECIFIED
		
#elif defined BSW_STOP_SEC_VAR_HSM_SHARED_READONLY_INIT_UNSPECIFIED
    #undef BSW_STOP_SEC_VAR_HSM_SHARED_READONLY_INIT_UNSPECIFIED
			
#else
    #error "Bsw_MemMap.h, wrong #pragma command"
#endif
/* legacy end */


