/******************************************************************************/
/*                                                                            */
/* !Layer           : STD                                                     */
/*                                                                            */
/* !Component       : MEMMAP                                                  */
/* !Description     : MEMMAP Configuration                                    */
/*                                                                            */
/* !File            : BSW_VER_MEMMAP.H                                          */
/*                                                                            */
/* !Scope           : Public                                                  */
/*                                                                            */
/* !Target          :                                                         */
/*                                                                            */
/* !Vendor          : invt                                                    */
/*                                                                            */
/* Coding language  : C                                                       */
/*                                                                            */
/* COPYRIGHT 2009 invt                                                        */
/* all rights reserved                                                        */
/*                                                                            */
/******************************************************************************/
/* SVN Information                                                           */
/* $Archive::                                                                $*/
/* $Revision::            $$Author::                  $$Date::               $*/
/******************************************************************************/
/* 02/26/24, 16:57:55: generated by Genecode  v2.6.0.0                        */
/* From Source Template : MSN_MEMMAP_H.TPL                                    */
/******************************************************************************/



/******************************************************************************/
/*          MEMMAP selected mode:  SAFE                                       */
/******************************************************************************/
#define MEMMAP_ERROR

/* The following if is used only due to automatic generation */
#if !defined MEMMAP_ERROR

/* Project section mappings */
/* !Comment: BSW_VER Section allocation */
#elif defined   BSW_VER_START_SEC_VERSION_BSW_UNSPECIFIED
   #undef  BSW_VER_START_SEC_VERSION_BSW_UNSPECIFIED
   #define START_SEC_VERSION_BSW_UNSPECIFIED_SECTION
#elif defined   BSW_VER_STOP_SEC_VERSION_BSW_UNSPECIFIED
   #undef  BSW_VER_STOP_SEC_VERSION_BSW_UNSPECIFIED
   #define STOP_SEC_VERSION_BSW_UNSPECIFIED_SECTION

#elif defined   BSW_BOOT_VER_START_SEC_VERSION_BSW_UNSPECIFIED
   #undef  BSW_BOOT_VER_START_SEC_VERSION_BSW_UNSPECIFIED
   #define START_SEC_BOOT_VERSION_BSW_UNSPECIFIED_SECTION
#elif defined   BSW_BOOT_VER_STOP_SEC_VERSION_BSW_UNSPECIFIED
   #undef  BSW_BOOT_VER_STOP_SEC_VERSION_BSW_UNSPECIFIED
   #define STOP_SEC_BOOT_VERSION_BSW_UNSPECIFIED_SECTION

#endif

/* ECU specific section mappings */
#ifndef MEMMAP_START_DONE

   /* The following if is used only due to automatic generation */

   #if FALSE
   /* !Comment: SEC_VERSION_BSW_UNSPECIFIED Start Section treatment */
   #elif defined   START_SEC_VERSION_BSW_UNSPECIFIED_SECTION
	  

      #pragma section ".version_bsw" a

      #undef  MEMMAP_ERROR
      #define MEMMAP_START_DONE

   #elif defined   START_SEC_BOOT_VERSION_BSW_UNSPECIFIED_SECTION
	  

      #pragma section ".version_boot" a

      #undef  MEMMAP_ERROR
      #define MEMMAP_START_DONE

   #endif

#else   /* if MEMMAP_START_DONE is not defined */

   /* The following if is used only due to automatic generation */

   #if FALSE
   /* !Comment: SEC_VERSION_BSW_UNSPECIFIED Stop Section treatment */
   #elif defined   STOP_SEC_VERSION_BSW_UNSPECIFIED_SECTION && defined  START_SEC_VERSION_BSW_UNSPECIFIED_SECTION
	  

      #pragma section

      #undef START_SEC_VERSION_BSW_UNSPECIFIED_SECTION
      #undef STOP_SEC_VERSION_BSW_UNSPECIFIED_SECTION
      #undef MEMMAP_ERROR
      #undef MEMMAP_START_DONE

   #elif defined   STOP_SEC_BOOT_VERSION_BSW_UNSPECIFIED_SECTION && defined  START_SEC_BOOT_VERSION_BSW_UNSPECIFIED_SECTION
	  

      #pragma section

      #undef START_SEC_BOOT_VERSION_BSW_UNSPECIFIED_SECTION
      #undef STOP_SEC_BOOT_VERSION_BSW_UNSPECIFIED_SECTION
      #undef MEMMAP_ERROR
      #undef MEMMAP_START_DONE

   #endif
#endif

#if defined MEMMAP_ERROR
   #error MEMMAP-E201 : Bad memory allocation into BSW_VER_MemMap.h
#endif


/*------------------------------- end of file --------------------------------*/

