/******************************************************************************/
/*                                                                            */
/* !Layer           : STD                                                     */
/*                                                                            */
/* !Component       : MEMMAP                                                  */
/* !Description     : MEMMAP Configuration                                    */
/*                                                                            */
/* !File            : CCP_MEMMAP.H                                          */
/*                                                                            */
/* !Scope           : Public                                                  */
/*                                                                            */
/* !Target          :                                                         */
/*                                                                            */
/* !Vendor          : invt                                                    */
/*                                                                            */
/* Coding language  : C                                                       */
/*                                                                            */
/* COPYRIGHT 2009 invt                                                        */
/* all rights reserved                                                        */
/*                                                                            */
/******************************************************************************/
/* SVN Information                                                           */
/* $Archive::                                                                $*/
/* $Revision::            $$Author::                  $$Date::               $*/
/******************************************************************************/
/* 11/09/22, 19:32:04: generated by Genecode  v2.6.0.0                        */
/* From Source Template : MSN_MEMMAP_H.TPL                                    */
/******************************************************************************/



/******************************************************************************/
/*          MEMMAP selected mode:  SAFE                                       */
/******************************************************************************/
#define MEMMAP_ERROR

/* The following if is used only due to automatic generation */
#if !defined MEMMAP_ERROR

/* Project section mappings */
/* !Comment: CCP Section allocation */
#elif defined   CCP_START_SEC_CODE
   #undef  CCP_START_SEC_CODE
   #define START_SEC_TST_CODE_SECTION
#elif defined   CCP_STOP_SEC_CODE
   #undef  CCP_STOP_SEC_CODE
   #define STOP_SEC_TST_CODE_SECTION

#elif defined   CCP_START_SEC_CONST_UNSPECIFIED
   #undef  CCP_START_SEC_CONST_UNSPECIFIED
   #define START_SEC_TST_CONST_SECTION
#elif defined   CCP_STOP_SEC_CONST_UNSPECIFIED
   #undef  CCP_STOP_SEC_CONST_UNSPECIFIED
   #define STOP_SEC_TST_CONST_SECTION

#elif defined   CCP_START_SEC_VAR_UNSPECIFIED
   #undef  CCP_START_SEC_VAR_UNSPECIFIED
   #define START_SEC_TST_VAR_SECTION
#elif defined   CCP_STOP_SEC_VAR_UNSPECIFIED
   #undef  CCP_STOP_SEC_VAR_UNSPECIFIED
   #define STOP_SEC_TST_VAR_SECTION


#endif

/* ECU specific section mappings */
#ifndef MEMMAP_START_DONE

/* The following if is used only due to automatic generation */

#if FALSE
/* !Comment: SEC_CODE Start Section treatment */
   #elif defined   START_SEC_TST_CODE_SECTION
	  

      #pragma section ".text" ax

      #undef  MEMMAP_ERROR
      #define MEMMAP_START_DONE

/* !Comment: SEC_CONST_UNSPECIFIED Start Section treatment */
   #elif defined   START_SEC_TST_CONST_SECTION
	  

      #pragma section ".const" a

      #undef  MEMMAP_ERROR
      #define MEMMAP_START_DONE

/* !Comment: SEC_VAR_UNSPECIFIED Start Section treatment */
   #elif defined   START_SEC_TST_VAR_SECTION
	  

      #pragma section ".data_cpu0" aw

      #undef  MEMMAP_ERROR
      #define MEMMAP_START_DONE


   #endif

#else   /* if MEMMAP_START_DONE is not defined */

/* The following if is used only due to automatic generation */

#if FALSE
/* !Comment: SEC_CODE Stop Section treatment */
   #elif defined   STOP_SEC_TST_CODE_SECTION && defined  START_SEC_TST_CODE_SECTION
	  

      #pragma section

      #undef START_SEC_TST_CODE_SECTION
      #undef STOP_SEC_TST_CODE_SECTION
      #undef MEMMAP_ERROR
      #undef MEMMAP_START_DONE

/* !Comment: SEC_CONST_UNSPECIFIED Stop Section treatment */
   #elif defined   STOP_SEC_TST_CONST_SECTION && defined  START_SEC_TST_CONST_SECTION
	  

      #pragma section

      #undef START_SEC_TST_CONST_SECTION
      #undef STOP_SEC_TST_CONST_SECTION
      #undef MEMMAP_ERROR
      #undef MEMMAP_START_DONE

/* !Comment: SEC_VAR_UNSPECIFIED Stop Section treatment */
   #elif defined   STOP_SEC_TST_VAR_SECTION && defined  START_SEC_TST_VAR_SECTION
	  

      #pragma section

      #undef START_SEC_TST_VAR_SECTION
      #undef STOP_SEC_TST_VAR_SECTION
      #undef MEMMAP_ERROR
      #undef MEMMAP_START_DONE


   #endif
#endif

#if defined MEMMAP_ERROR
   #error MEMMAP-E201 : Bad memory allocation into CCP_MemMap.h
#endif


/*------------------------------- end of file --------------------------------*/

