/******************************************************************************/
/*                                                                            */
/* !Layer           : STD                                                     */
/*                                                                            */
/* !Component       : MEMMAP                                                  */
/* !Description     : MEMMAP Configuration                                    */
/*                                                                            */
/* !File            : CCU6_MEMMAP.H                                          */
/*                                                                            */
/* !Scope           : Public                                                  */
/*                                                                            */
/* !Target          :                                                         */
/*                                                                            */
/* !Vendor          : invt                                                    */
/*                                                                            */
/* Coding language  : C                                                       */
/*                                                                            */
/* COPYRIGHT 2009 invt                                                        */
/* all rights reserved                                                        */
/*                                                                            */
/******************************************************************************/
/* SVN Information                                                           */
/* $Archive::                                                                $*/
/* $Revision::            $$Author::                  $$Date::               $*/
/******************************************************************************/
/* 05/20/22, 13:18:41: generated by Genecode  v2.6.0.0                        */
/* From Source Template : MSN_MEMMAP_H.TPL                                    */
/******************************************************************************/



/******************************************************************************/
/*          MEMMAP selected mode:  SAFE                                       */
/******************************************************************************/
#define MEMMAP_ERROR

/* The following if is used only due to automatic generation */
#if !defined MEMMAP_ERROR

/* Project section mappings */
/* !Comment: CCU6 Section allocation */
#elif defined   CCU6_START_SEC_CODE
   #undef  CCU6_START_SEC_CODE
   #define START_SEC_CODE_SECTION
#elif defined   CCU6_STOP_SEC_CODE
   #undef  CCU6_STOP_SEC_CODE
   #define STOP_SEC_CODE_SECTION

#elif defined   CCU6_START_CODE_FAST_CPU1
   #undef  CCU6_START_CODE_FAST_CPU1
   #define START_CODE_FAST_CPU1_SECTION
   #include "MemMap.h"
    #undef  MEMMAP_ERROR
#elif defined   CCU6_STOP_CODE_FAST_CPU1
   #undef  CCU6_STOP_CODE_FAST_CPU1
   #define STOP_CODE_FAST_CPU1_SECTION
   #include "MemMap.h"
    #undef  MEMMAP_ERROR

#elif defined   CCU6_START_SEC_VAR_UNSPECIFIED
   #undef  CCU6_START_SEC_VAR_UNSPECIFIED
   #define START_SEC_VAR_UNSPECIFIED_SECTION
#elif defined   CCU6_STOP_SEC_VAR_UNSPECIFIED
   #undef  CCU6_STOP_SEC_VAR_UNSPECIFIED
   #define STOP_SEC_VAR_UNSPECIFIED_SECTION

#elif defined   CCU6_START_SEC_CONST_UNSPECIFIED
   #undef  CCU6_START_SEC_CONST_UNSPECIFIED
   #define START_SEC_CONST_UNSPECIFIED_SECTION
#elif defined   CCU6_STOP_SEC_CONST_UNSPECIFIED
   #undef  CCU6_STOP_SEC_CONST_UNSPECIFIED
   #define STOP_SEC_CONST_UNSPECIFIED_SECTION

#elif defined   CCU6_START_SEC_CALIB_UNSPECIFIED
   #undef  CCU6_START_SEC_CALIB_UNSPECIFIED
   #define START_SEC_CALIB_UNSPECIFIED_SECTION
#elif defined   CCU6_STOP_SEC_CALIB_UNSPECIFIED
   #undef  CCU6_STOP_SEC_CALIB_UNSPECIFIED
   #define STOP_SEC_CALIB_UNSPECIFIED_SECTION

#elif defined CCU6_CALIB_START_SEC_CONST_32
  #define  CALIB_START_SEC_CONST_32
  #include "MemMap.h"
   #undef CCU6_CALIB_START_SEC_CONST_32
   #undef  MEMMAP_ERROR
#elif defined CCU6_CALIB_STOP_SEC_CONST_32
  #define  CALIB_STOP_SEC_CONST_32
  #include "MemMap.h"
   #undef CCU6_CALIB_STOP_SEC_CONST_32
   #undef  MEMMAP_ERROR
      
#elif defined CCU6_CALIB_START_SEC_CONST_16
  #define  CALIB_START_SEC_CONST_16
  #include "MemMap.h"
	#undef CCU6_CALIB_START_SEC_CONST_16
   #undef  MEMMAP_ERROR
#elif defined CCU6_CALIB_STOP_SEC_CONST_16
  #define  CALIB_STOP_SEC_CONST_16
  #include "MemMap.h"
	#undef CCU6_CALIB_STOP_SEC_CONST_16
   #undef  MEMMAP_ERROR
      
#elif defined CCU6_CALIB_START_SEC_CONST_8
  #define  CALIB_START_SEC_CONST_8
  #include "MemMap.h"
	#undef CCU6_CALIB_START_SEC_CONST_8
   #undef  MEMMAP_ERROR
#elif defined CCU6_CALIB_STOP_SEC_CONST_8
  #define  CALIB_STOP_SEC_CONST_8
  #include "MemMap.h"
	#undef CCU6_CALIB_STOP_SEC_CONST_8
   #undef  MEMMAP_ERROR
   
#elif defined   CCU6_CALIB_START_SEC_CONST_BOOL
  #define  CALIB_START_SEC_CONST_BOOL
  #include "MemMap.h"
   #undef CCU6_CALIB_START_SEC_CONST_BOOL
   #undef  MEMMAP_ERROR
#elif defined   CCU6_CALIB_STOP_SEC_CONST_BOOL
  #define  CALIB_STOP_SEC_CONST_BOOL
  #include "MemMap.h"
   #undef CCU6_CALIB_STOP_SEC_CONST_BOOL
   #undef  MEMMAP_ERROR
   
#elif defined CCU6_CALIB_START_SEC_CONST_UNSPECIFIED
  #define  CALIB_START_SEC_CONST_UNSPECIFIED
  #include "MemMap.h"
	#undef CCU6_CALIB_START_SEC_CONST_UNSPECIFIED
   #undef  MEMMAP_ERROR
#elif defined CCU6_CALIB_STOP_SEC_CONST_UNSPECIFIED
  #define  CALIB_STOP_SEC_CONST_UNSPECIFIED
  #include "MemMap.h"
	#undef CCU6_CALIB_STOP_SEC_CONST_UNSPECIFIED
   #undef  MEMMAP_ERROR



#endif

/* ECU specific section mappings */
#ifndef MEMMAP_START_DONE

/* The following if is used only due to automatic generation */

#if FALSE
/* !Comment: SEC_CODE Start Section treatment */
   #elif defined   START_SEC_CODE_SECTION
	  

      #pragma section ".text.CPU0_Code" ax 4

      #undef  MEMMAP_ERROR
      #define MEMMAP_START_DONE

/* !Comment: CODE_FAST_CPU1 Start Section treatment */
   #elif defined   START_CODE_FAST_CPU1_SECTION
	  

      #pragma section ".text.CPU0_Code" ax 4

      #undef  MEMMAP_ERROR
      #define MEMMAP_START_DONE

/* !Comment: SEC_VAR_UNSPECIFIED Start Section treatment */
   #elif defined   START_SEC_VAR_UNSPECIFIED_SECTION
	  
      #undef  MEMMAP_ERROR
      #define MEMMAP_START_DONE

/* !Comment: SEC_CONST_UNSPECIFIED Start Section treatment */
   #elif defined   START_SEC_CONST_UNSPECIFIED_SECTION
	  

      #pragma section ".rodata.DEFAULT_CONST_UNSPECIFIED" a

      #undef  MEMMAP_ERROR
      #define MEMMAP_START_DONE

/* !Comment: SEC_CALIB_UNSPECIFIED Start Section treatment */
   #elif defined   START_SEC_CALIB_UNSPECIFIED_SECTION
	  

      #pragma section ".rodata.Calib_unspec" a 4

      #undef  MEMMAP_ERROR
      #define MEMMAP_START_DONE


   #endif

#else   /* if MEMMAP_START_DONE is not defined */

/* The following if is used only due to automatic generation */

#if FALSE
/* !Comment: SEC_CODE Stop Section treatment */
   #elif defined   STOP_SEC_CODE_SECTION && defined  START_SEC_CODE_SECTION
	  

      #pragma section

      #undef START_SEC_CODE_SECTION
      #undef STOP_SEC_CODE_SECTION
      #undef MEMMAP_ERROR
      #undef MEMMAP_START_DONE

/* !Comment: SEC_VAR_UNSPECIFIED Stop Section treatment */
   #elif defined   STOP_SEC_VAR_UNSPECIFIED_SECTION && defined  START_SEC_VAR_UNSPECIFIED_SECTION
	  
      #undef START_SEC_VAR_UNSPECIFIED_SECTION
      #undef STOP_SEC_VAR_UNSPECIFIED_SECTION
      #undef MEMMAP_ERROR
      #undef MEMMAP_START_DONE

/* !Comment: SEC_CONST_UNSPECIFIED Stop Section treatment */
   #elif defined   STOP_SEC_CONST_UNSPECIFIED_SECTION && defined  START_SEC_CONST_UNSPECIFIED_SECTION
	  

      #pragma section

      #undef START_SEC_CONST_UNSPECIFIED_SECTION
      #undef STOP_SEC_CONST_UNSPECIFIED_SECTION
      #undef MEMMAP_ERROR
      #undef MEMMAP_START_DONE

/* !Comment: SEC_CALIB_UNSPECIFIED Stop Section treatment */
   #elif defined   STOP_SEC_CALIB_UNSPECIFIED_SECTION && defined  START_SEC_CALIB_UNSPECIFIED_SECTION
	  

      #pragma section

      #undef START_SEC_CALIB_UNSPECIFIED_SECTION
      #undef STOP_SEC_CALIB_UNSPECIFIED_SECTION
      #undef MEMMAP_ERROR
      #undef MEMMAP_START_DONE


   #endif
#endif

#if defined MEMMAP_ERROR
   #error MEMMAP-E201 : Bad memory allocation into CCU6_MemMap.h
#endif


/*------------------------------- end of file --------------------------------*/

