/********************************************************************************************************************/
/*                                                                                                                  */
/* TOOL-GENERATED SOURCECODE, DO NOT CHANGE                                                                         */
/*                                                                                                                  */
/********************************************************************************************************************/

#ifndef DEM_CFG_ENVDATAELEMENT_H
#define DEM_CFG_ENVDATAELEMENT_H

#include "Std_Types.h"
#include "Dem_Cfg_EnvDataElement_DataSize.h"

#define DEM_CFG_ENV_DATAELEMENTS_EXTERN_AVAILABILITY   STD_ON
#define DEM_CFG_ENV_DATAELEMENTS_INTERN_AVAILABILITY  STD_ON

#define DEM_CFG_READDEM_AGINGCTR_UPCNT_SUPPORTED                         TRUE
#define DEM_CFG_READDEM_AGINGCTR_DOWNCNT_SUPPORTED                       FALSE
#define DEM_CFG_READDEM_OCCCTR_SUPPORTED                                 TRUE
#define DEM_CFG_READDEM_OVFLIND_SUPPORTED                                FALSE
#define DEM_CFG_READDEM_SIGNIFICANCE_SUPPORTED                           FALSE
#define DEM_CFG_READDEM_DEBUG0_SUPPORTED                                 FALSE
#define DEM_CFG_READDEM_DEBUG1_SUPPORTED                                 FALSE
#define DEM_CFG_READDEM_EVENT_ID_SUPPORTED                               FALSE
#define DEM_CFG_READDEM_CURRENT_FDC_SUPPORTED                            FALSE
#define DEM_CFG_READDEM_MAX_FDC_DURING_CURRENT_CYCLE_SUPPORTED           FALSE
#define DEM_CFG_READDEM_MAX_FDC_SINCE_LAST_CLEAR_SUPPORTED               FALSE
#define DEM_CFG_READDEM_CYCLES_SINCE_FIRST_FAILED_SUPPORTED              FALSE
#define DEM_CFG_READDEM_CYCLES_SINCE_LAST_FAILED_SUPPORTED               FALSE
#define DEM_CFG_READDEM_CYCLES_SINCE_LAST_FAILED_EXCLUDING_TNC_SUPPORTED   FALSE
#define DEM_CFG_READDEM_FAILED_CYCLES_SUPPORTED                          FALSE
#define DEM_CFG_READDEM_PRJ_SPECIFIC_DATA_ON_RETRIEVE_SUPPORTED          FALSE
#define DEM_CFG_READDEM_PRJ_SPECIFIC_DATA_ON_REPORT_SUPPORTED            FALSE
#define DEM_CFG_DATAELEMENT_LASTFAILEDSINCELASTFAILEDEXCLUDINGTNC_INCLUDESFAILEDCYCLE    TRUE

#define DEM_DATAELEM_CS_EXTENDEDDATARECORD_FAULT_PENDING_COUNTER  1
#define DEM_DATAELEM_CS_EXTENDEDDATARECORD_AGED_COUNTER  2
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_D000  3
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_D001  4
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_D002  5
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_D003  6
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_D004  7
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_D005  8
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_D007  9
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_D008  10
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_D009  11
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_D010  12
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_D011  13
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_D012  14
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_D013  15
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_D014  16
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_D015  17
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_D016  18
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_D017  19
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_D018  20
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_D019  21
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_D020  22
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_D021  23
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_D022  24
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_D023  25
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_D024  26
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_D025  27
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_D026  28
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_D027  29
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_D028  30
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_D029  31
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_D030  32
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_D031  33
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_D032  34
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_D033  35
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_D034  36
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_D035  37
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_D036  38
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_D037  39
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_D038  40
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_D039  41
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_D040  42
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_D041  43
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_D042  44
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_D043  45
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_D044  46
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_D045  47
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_D046  48
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_D047  49
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_D048  50
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_D049  51
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_1D06  52
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_1D07  53
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_1D08  54
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_1D09  55
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_1D0A  56
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_1D0B  57
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_1D0C  58
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_1D0D  59
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_1D0E  60
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_1D0F  61
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_1D13  62
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_1D14  63
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_1D15  64
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_1D16  65
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_1D17  66
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_1D18  67
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_1D19  68
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_1D1A  69
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_1D1B  70
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_1D1C  71
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_1D1D  72
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_1D1E  73
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_1D1F  74
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_1D20  75
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_1D21  76
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_1D22  77
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_1D23  78
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_1D24  79
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_1D25  80
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_1D26  81
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_1D27  82
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_1D28  83
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_1D29  84
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_2D02  85
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_2D03  86
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_2D04  87
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_2D05  88
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_2D06  89
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_2D07  90
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_2D08  91
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_2D0E  92
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_2D13  93
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_2D14  94
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_2D15  95
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_2D1C  96
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_2D1D  97
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_2D1E  98
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_2D1F  99
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_2D20  100
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_2D21  101
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_2D22  102
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_2D25  103
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_2D26  104
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_3D02  105
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_3D03  106
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_3D04  107
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_3D05  108
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_3D06  109
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_3D07  110
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_3D08  111
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_3D0E  112
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_3D13  113
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_3D14  114
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_3D15  115
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_3D1C  116
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_3D1D  117
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_3D1E  118
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_3D1F  119
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_3D20  120
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_3D21  121
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_3D22  122
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_3D25  123
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_3D26  124
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_4D27  125
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_4D28  126
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_4D29  127
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_4D2A  128
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_4D2B  129
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_4D2C  130
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_4D2D  131
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_4D2E  132
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_4D2F  133
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_4D30  134
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_4D31  135
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_4D32  136
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_4D33  137
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_4D34  138
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_4D35  139
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_4D36  140
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_4D37  141
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_4D38  142
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_4D39  143
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_4D3A  144
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_4D3B  145
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_4D3C  146
#define DEM_DATAELEM_DEMDATAELEMENTCLASS_4D3D  147
#define DEM_DATAELEM_PID_02                 148
#define DEM_DATAELEM_PID_04                 149
#define DEM_DATAELEM_PID_05                 150
#define DEM_DATAELEM_PID_0C                 151
#define DEM_DATAELEM_PID_0D                 152
#define DEM_DATAELEM_PID_42                 153
#define DEM_DATAELEM_PID_49                 154
#define DEM_DATAELEM_INTER_EXTENDEDDATARECORD_FAULT_OCCURRENCE_COUNTER  155
#define DEM_DATAELEM_INTER_EXTENDEDDATARECORD_AGING_COUNTER  156

#define DEM_CFG_ENV_DATAELEMENTS \
{ \
   { DEM_ENV_DATAELEMENTS_EXTCS_INIT(NULL_PTR) DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) 0, FALSE } \
   ,{ &Rte_Call_DataServices_CS_ExtendedDataRecord_Fault_pending_counter_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR)DemConf_DemDataElementDataSize_DEM_DATAELEM_CS_EXTENDEDDATARECORD_FAULT_PENDING_COUNTER , FALSE } \
   ,{ &Rte_Call_DataServices_CS_ExtendedDataRecord_Aged_counter_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR)DemConf_DemDataElementDataSize_DEM_DATAELEM_CS_EXTENDEDDATARECORD_AGED_COUNTER , FALSE } \
   ,{ &DemDataServiceFunc_D000_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D000 , FALSE } \
   ,{ &DemDataServiceFunc_D001_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D001 , FALSE } \
   ,{ &DemDataServiceFunc_D002_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D002 , FALSE } \
   ,{ &DemDataServiceFunc_D003_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D003 , FALSE } \
   ,{ &DemDataServiceFunc_D004_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D004 , FALSE } \
   ,{ &DemDataServiceFunc_D005_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D005 , FALSE } \
   ,{ &DemDataServiceFunc_D007_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D007 , FALSE } \
   ,{ &DemDataServiceFunc_D008_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D008 , FALSE } \
   ,{ &DemDataServiceFunc_D009_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D009 , FALSE } \
   ,{ &DemDataServiceFunc_D010_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D010 , FALSE } \
   ,{ &DemDataServiceFunc_D011_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D011 , FALSE } \
   ,{ &DemDataServiceFunc_D012_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D012 , FALSE } \
   ,{ &DemDataServiceFunc_D013_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D013 , FALSE } \
   ,{ &DemDataServiceFunc_D014_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D014 , FALSE } \
   ,{ &DemDataServiceFunc_D015_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D015 , FALSE } \
   ,{ &DemDataServiceFunc_D016_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D016 , FALSE } \
   ,{ &DemDataServiceFunc_D017_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D017 , FALSE } \
   ,{ &DemDataServiceFunc_D018_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D018 , FALSE } \
   ,{ &DemDataServiceFunc_D019_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D019 , FALSE } \
   ,{ &DemDataServiceFunc_D020_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D020 , FALSE } \
   ,{ &DemDataServiceFunc_D021_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D021 , FALSE } \
   ,{ &DemDataServiceFunc_D022_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D022 , FALSE } \
   ,{ &DemDataServiceFunc_D023_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D023 , FALSE } \
   ,{ &DemDataServiceFunc_D024_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D024 , FALSE } \
   ,{ &DemDataServiceFunc_D025_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D025 , FALSE } \
   ,{ &DemDataServiceFunc_D026_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D026 , FALSE } \
   ,{ &DemDataServiceFunc_D027_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D027 , FALSE } \
   ,{ &DemDataServiceFunc_D028_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D028 , FALSE } \
   ,{ &DemDataServiceFunc_D029_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D029 , FALSE } \
   ,{ &DemDataServiceFunc_D030_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D030 , FALSE } \
   ,{ &DemDataServiceFunc_D031_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D031 , FALSE } \
   ,{ &DemDataServiceFunc_D032_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D032 , FALSE } \
   ,{ &DemDataServiceFunc_D033_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D033 , FALSE } \
   ,{ &DemDataServiceFunc_D034_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D034 , FALSE } \
   ,{ &DemDataServiceFunc_D035_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D035 , FALSE } \
   ,{ &DemDataServiceFunc_D036_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D036 , FALSE } \
   ,{ &DemDataServiceFunc_D037_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D037 , FALSE } \
   ,{ &DemDataServiceFunc_D038_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D038 , FALSE } \
   ,{ &DemDataServiceFunc_D039_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D039 , FALSE } \
   ,{ &DemDataServiceFunc_D040_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D040 , FALSE } \
   ,{ &DemDataServiceFunc_D041_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D041 , FALSE } \
   ,{ &DemDataServiceFunc_D042_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D042 , FALSE } \
   ,{ &DemDataServiceFunc_D043_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D043 , FALSE } \
   ,{ &DemDataServiceFunc_D044_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D044 , FALSE } \
   ,{ &DemDataServiceFunc_D045_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D045 , FALSE } \
   ,{ &DemDataServiceFunc_D046_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D046 , FALSE } \
   ,{ &DemDataServiceFunc_D047_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D047 , FALSE } \
   ,{ &DemDataServiceFunc_D048_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D048 , FALSE } \
   ,{ &DemDataServiceFunc_D049_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_D049 , FALSE } \
   ,{ &DemDataServiceFunc_1D06_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_1D06 , FALSE } \
   ,{ &DemDataServiceFunc_1D07_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_1D07 , FALSE } \
   ,{ &DemDataServiceFunc_1D08_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_1D08 , FALSE } \
   ,{ &DemDataServiceFunc_1D09_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_1D09 , FALSE } \
   ,{ &DemDataServiceFunc_1D0A_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_1D0A , FALSE } \
   ,{ &DemDataServiceFunc_1D0B_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_1D0B , FALSE } \
   ,{ &DemDataServiceFunc_1D0C_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_1D0C , FALSE } \
   ,{ &DemDataServiceFunc_1D0D_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_1D0D , FALSE } \
   ,{ &DemDataServiceFunc_1D0E_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_1D0E , FALSE } \
   ,{ &DemDataServiceFunc_1D0F_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_1D0F , FALSE } \
   ,{ &DemDataServiceFunc_1D13_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_1D13 , FALSE } \
   ,{ &DemDataServiceFunc_1D14_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_1D14 , FALSE } \
   ,{ &DemDataServiceFunc_1D15_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_1D15 , FALSE } \
   ,{ &DemDataServiceFunc_1D16_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_1D16 , FALSE } \
   ,{ &DemDataServiceFunc_1D17_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_1D17 , FALSE } \
   ,{ &DemDataServiceFunc_1D18_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_1D18 , FALSE } \
   ,{ &DemDataServiceFunc_1D19_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_1D19 , FALSE } \
   ,{ &DemDataServiceFunc_1D1A_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_1D1A , FALSE } \
   ,{ &DemDataServiceFunc_1D1B_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_1D1B , FALSE } \
   ,{ &DemDataServiceFunc_1D1C_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_1D1C , FALSE } \
   ,{ &DemDataServiceFunc_1D1D_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_1D1D , FALSE } \
   ,{ &DemDataServiceFunc_1D1E_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_1D1E , FALSE } \
   ,{ &DemDataServiceFunc_1D1F_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_1D1F , FALSE } \
   ,{ &DemDataServiceFunc_1D20_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_1D20 , FALSE } \
   ,{ &DemDataServiceFunc_1D21_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_1D21 , FALSE } \
   ,{ &DemDataServiceFunc_1D22_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_1D22 , FALSE } \
   ,{ &DemDataServiceFunc_1D23_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_1D23 , FALSE } \
   ,{ &DemDataServiceFunc_1D24_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_1D24 , FALSE } \
   ,{ &DemDataServiceFunc_1D25_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_1D25 , FALSE } \
   ,{ &DemDataServiceFunc_1D26_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_1D26 , FALSE } \
   ,{ &DemDataServiceFunc_1D27_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_1D27 , FALSE } \
   ,{ &DemDataServiceFunc_1D28_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_1D28 , FALSE } \
   ,{ &DemDataServiceFunc_1D29_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_1D29 , FALSE } \
   ,{ &DemDataServiceFunc_2D02_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_2D02 , FALSE } \
   ,{ &DemDataServiceFunc_2D03_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_2D03 , FALSE } \
   ,{ &DemDataServiceFunc_2D04_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_2D04 , FALSE } \
   ,{ &DemDataServiceFunc_2D05_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_2D05 , FALSE } \
   ,{ &DemDataServiceFunc_2D06_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_2D06 , FALSE } \
   ,{ &DemDataServiceFunc_2D07_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_2D07 , FALSE } \
   ,{ &DemDataServiceFunc_2D08_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_2D08 , FALSE } \
   ,{ &DemDataServiceFunc_2D0E_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_2D0E , FALSE } \
   ,{ &DemDataServiceFunc_2D13_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_2D13 , FALSE } \
   ,{ &DemDataServiceFunc_2D14_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_2D14 , FALSE } \
   ,{ &DemDataServiceFunc_2D15_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_2D15 , FALSE } \
   ,{ &DemDataServiceFunc_2D1C_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_2D1C , FALSE } \
   ,{ &DemDataServiceFunc_2D1D_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_2D1D , FALSE } \
   ,{ &DemDataServiceFunc_2D1E_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_2D1E , FALSE } \
   ,{ &DemDataServiceFunc_2D1F_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_2D1F , FALSE } \
   ,{ &DemDataServiceFunc_2D20_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_2D20 , FALSE } \
   ,{ &DemDataServiceFunc_2D21_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_2D21 , FALSE } \
   ,{ &DemDataServiceFunc_2D22_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_2D22 , FALSE } \
   ,{ &DemDataServiceFunc_2D25_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_2D25 , FALSE } \
   ,{ &DemDataServiceFunc_2D26_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_2D26 , FALSE } \
   ,{ &DemDataServiceFunc_3D02_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_3D02 , FALSE } \
   ,{ &DemDataServiceFunc_3D03_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_3D03 , FALSE } \
   ,{ &DemDataServiceFunc_3D04_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_3D04 , FALSE } \
   ,{ &DemDataServiceFunc_3D05_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_3D05 , FALSE } \
   ,{ &DemDataServiceFunc_3D06_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_3D06 , FALSE } \
   ,{ &DemDataServiceFunc_3D07_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_3D07 , FALSE } \
   ,{ &DemDataServiceFunc_3D08_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_3D08 , FALSE } \
   ,{ &DemDataServiceFunc_3D0E_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_3D0E , FALSE } \
   ,{ &DemDataServiceFunc_3D13_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_3D13 , FALSE } \
   ,{ &DemDataServiceFunc_3D14_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_3D14 , FALSE } \
   ,{ &DemDataServiceFunc_3D15_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_3D15 , FALSE } \
   ,{ &DemDataServiceFunc_3D1C_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_3D1C , FALSE } \
   ,{ &DemDataServiceFunc_3D1D_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_3D1D , FALSE } \
   ,{ &DemDataServiceFunc_3D1E_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_3D1E , FALSE } \
   ,{ &DemDataServiceFunc_3D1F_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_3D1F , FALSE } \
   ,{ &DemDataServiceFunc_3D20_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_3D20 , FALSE } \
   ,{ &DemDataServiceFunc_3D21_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_3D21 , FALSE } \
   ,{ &DemDataServiceFunc_3D22_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_3D22 , FALSE } \
   ,{ &DemDataServiceFunc_3D25_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_3D25 , FALSE } \
   ,{ &DemDataServiceFunc_3D26_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_3D26 , FALSE } \
   ,{ &DemDataServiceFunc_4D27_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_4D27 , FALSE } \
   ,{ &DemDataServiceFunc_4D28_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_4D28 , FALSE } \
   ,{ &DemDataServiceFunc_4D29_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_4D29 , FALSE } \
   ,{ &DemDataServiceFunc_4D2A_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_4D2A , FALSE } \
   ,{ &DemDataServiceFunc_4D2B_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_4D2B , FALSE } \
   ,{ &DemDataServiceFunc_4D2C_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_4D2C , FALSE } \
   ,{ &DemDataServiceFunc_4D2D_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_4D2D , FALSE } \
   ,{ &DemDataServiceFunc_4D2E_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_4D2E , FALSE } \
   ,{ &DemDataServiceFunc_4D2F_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_4D2F , FALSE } \
   ,{ &DemDataServiceFunc_4D30_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_4D30 , FALSE } \
   ,{ &DemDataServiceFunc_4D31_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_4D31 , FALSE } \
   ,{ &DemDataServiceFunc_4D32_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_4D32 , FALSE } \
   ,{ &DemDataServiceFunc_4D33_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_4D33 , FALSE } \
   ,{ &DemDataServiceFunc_4D34_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_4D34 , FALSE } \
   ,{ &DemDataServiceFunc_4D35_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_4D35 , FALSE } \
   ,{ &DemDataServiceFunc_4D36_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_4D36 , FALSE } \
   ,{ &DemDataServiceFunc_4D37_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_4D37 , FALSE } \
   ,{ &DemDataServiceFunc_4D38_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_4D38 , FALSE } \
   ,{ &DemDataServiceFunc_4D39_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_4D39 , FALSE } \
   ,{ &DemDataServiceFunc_4D3A_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_4D3A , FALSE } \
   ,{ &DemDataServiceFunc_4D3B_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_4D3B , FALSE } \
   ,{ &DemDataServiceFunc_4D3C_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_4D3C , FALSE } \
   ,{ &DemDataServiceFunc_4D3D_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR) DemConf_DemDataElementDataSize_DEM_DATAELEM_DEMDATAELEMENTCLASS_4D3D , FALSE } \
   ,{ &Rte_Call_DataServices_PID_02_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR)DemConf_DemDataElementDataSize_DEM_DATAELEM_PID_02 , FALSE } \
   ,{ &Rte_Call_DataServices_PID_04_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR)DemConf_DemDataElementDataSize_DEM_DATAELEM_PID_04 , FALSE } \
   ,{ &Rte_Call_DataServices_PID_05_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR)DemConf_DemDataElementDataSize_DEM_DATAELEM_PID_05 , FALSE } \
   ,{ &Rte_Call_DataServices_PID_0C_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR)DemConf_DemDataElementDataSize_DEM_DATAELEM_PID_0C , FALSE } \
   ,{ &Rte_Call_DataServices_PID_0D_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR)DemConf_DemDataElementDataSize_DEM_DATAELEM_PID_0D , FALSE } \
   ,{ &Rte_Call_DataServices_PID_42_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR)DemConf_DemDataElementDataSize_DEM_DATAELEM_PID_42 , FALSE } \
   ,{ &Rte_Call_DataServices_PID_49_ReadData, DEM_ENV_DATAELEMENTS_INTERN_INIT(NULL_PTR)DemConf_DemDataElementDataSize_DEM_DATAELEM_PID_49 , FALSE } \
   ,{ DEM_ENV_DATAELEMENTS_EXTCS_INIT(NULL_PTR) &Dem_ReadOccCtr, DemConf_DemDataElementDataSize_DEM_DATAELEM_INTER_EXTENDEDDATARECORD_FAULT_OCCURRENCE_COUNTER , TRUE } \
   ,{ DEM_ENV_DATAELEMENTS_EXTCS_INIT(NULL_PTR) &Dem_ReadAgingCtrUpCnt, DemConf_DemDataElementDataSize_DEM_DATAELEM_INTER_EXTENDEDDATARECORD_AGING_COUNTER , TRUE } \
}

#define DEM_CFG_ENV_DATAELEMENTS_ARRAYLENGTH      (156+1)

#endif

