/********************************************************************************************************************/
/*                                                                                                                  */
/* TOOL-GENERATED SOURCECODE, DO NOT CHANGE                                                                         */
/*                                                                                                                  */
/********************************************************************************************************************/

#ifndef DEM_CFG_EVENTID_H
#define DEM_CFG_EVENTID_H

#define DEM_EVENTID_INVALID                                          0u
#define DEM_EVENTID_COUNT         500u
#define DEM_EVENTID_ARRAYLENGTH   (DEM_EVENTID_COUNT+1u)

#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC00       1u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC01       2u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC02       3u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC03       4u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC04       5u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC05       6u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC06       7u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC07       8u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC08       9u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC09       10u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC10       11u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC11       12u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC12       13u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC13       14u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC14       15u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC15       16u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC16       17u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC17       18u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC18       19u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC19       20u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC20       21u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC21       22u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC22       23u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC23       24u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC24       25u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC25       26u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC26       27u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC27       28u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC28       29u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC29       30u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC30       31u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC31       32u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC32       33u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC33       34u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC34       35u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC35       36u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC36       37u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC37       38u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC38       39u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC39       40u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC40       41u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC41       42u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC42       43u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC43       44u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC44       45u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC45       46u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC46       47u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC47       48u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC48       49u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC49       50u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC50       51u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC51       52u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC52       53u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC53       54u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC54       55u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC55       56u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC56       57u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC57       58u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC58       59u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC59       60u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC60       61u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC61       62u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC62       63u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC63       64u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC64       65u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC65       66u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC66       67u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC67       68u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC68       69u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC69       70u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC70       71u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC71       72u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC72       73u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC73       74u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC74       75u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC75       76u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC76       77u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC77       78u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC78       79u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC79       80u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC80       81u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC81       82u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC82       83u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC83       84u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC84       85u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC85       86u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC86       87u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC87       88u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC88       89u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC89       90u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC90       91u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC91       92u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC92       93u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC93       94u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC94       95u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC95       96u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC96       97u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC97       98u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC98       99u
#define DemConf_DemEventParameter_DemEventParameter_ECU1_DTC99       100u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC00       101u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC01       102u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC02       103u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC03       104u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC04       105u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC05       106u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC06       107u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC07       108u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC08       109u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC09       110u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC10       111u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC11       112u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC12       113u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC13       114u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC14       115u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC15       116u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC16       117u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC17       118u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC18       119u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC19       120u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC20       121u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC21       122u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC22       123u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC23       124u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC24       125u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC25       126u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC26       127u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC27       128u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC28       129u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC29       130u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC30       131u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC31       132u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC32       133u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC33       134u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC34       135u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC35       136u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC36       137u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC37       138u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC38       139u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC39       140u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC40       141u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC41       142u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC42       143u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC43       144u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC44       145u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC45       146u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC46       147u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC47       148u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC48       149u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC49       150u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC50       151u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC51       152u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC52       153u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC53       154u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC54       155u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC55       156u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC56       157u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC57       158u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC58       159u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC59       160u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC60       161u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC61       162u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC62       163u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC63       164u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC64       165u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC65       166u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC66       167u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC67       168u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC68       169u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC69       170u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC70       171u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC71       172u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC72       173u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC73       174u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC74       175u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC75       176u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC76       177u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC77       178u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC78       179u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC79       180u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC80       181u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC81       182u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC82       183u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC83       184u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC84       185u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC85       186u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC86       187u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC87       188u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC88       189u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC89       190u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC90       191u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC91       192u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC92       193u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC93       194u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC94       195u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC95       196u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC96       197u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC97       198u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC98       199u
#define DemConf_DemEventParameter_DemEventParameter_ECU2_DTC99       200u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC00       201u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC01       202u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC02       203u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC03       204u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC04       205u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC05       206u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC06       207u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC07       208u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC08       209u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC09       210u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC10       211u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC11       212u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC12       213u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC13       214u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC14       215u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC15       216u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC16       217u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC17       218u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC18       219u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC19       220u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC20       221u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC21       222u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC22       223u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC23       224u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC24       225u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC25       226u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC26       227u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC27       228u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC28       229u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC29       230u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC30       231u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC31       232u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC32       233u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC33       234u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC34       235u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC35       236u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC36       237u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC37       238u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC38       239u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC39       240u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC40       241u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC41       242u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC42       243u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC43       244u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC44       245u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC45       246u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC46       247u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC47       248u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC48       249u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC49       250u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC50       251u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC51       252u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC52       253u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC53       254u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC54       255u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC55       256u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC56       257u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC57       258u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC58       259u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC59       260u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC60       261u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC61       262u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC62       263u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC63       264u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC64       265u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC65       266u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC66       267u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC67       268u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC68       269u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC69       270u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC70       271u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC71       272u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC72       273u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC73       274u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC74       275u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC75       276u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC76       277u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC77       278u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC78       279u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC79       280u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC80       281u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC81       282u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC82       283u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC83       284u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC84       285u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC85       286u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC86       287u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC87       288u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC88       289u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC89       290u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC90       291u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC91       292u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC92       293u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC93       294u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC94       295u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC95       296u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC96       297u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC97       298u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC98       299u
#define DemConf_DemEventParameter_DemEventParameter_ECU3_DTC99       300u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC00       301u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC01       302u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC02       303u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC03       304u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC04       305u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC05       306u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC06       307u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC07       308u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC08       309u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC09       310u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC10       311u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC11       312u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC12       313u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC13       314u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC14       315u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC15       316u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC16       317u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC17       318u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC18       319u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC19       320u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC20       321u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC21       322u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC22       323u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC23       324u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC24       325u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC25       326u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC26       327u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC27       328u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC28       329u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC29       330u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC30       331u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC31       332u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC32       333u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC33       334u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC34       335u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC35       336u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC36       337u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC37       338u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC38       339u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC39       340u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC40       341u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC41       342u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC42       343u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC43       344u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC44       345u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC45       346u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC46       347u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC47       348u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC48       349u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC49       350u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC50       351u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC51       352u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC52       353u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC53       354u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC54       355u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC55       356u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC56       357u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC57       358u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC58       359u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC59       360u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC60       361u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC61       362u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC62       363u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC63       364u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC64       365u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC65       366u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC66       367u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC67       368u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC68       369u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC69       370u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC70       371u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC71       372u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC72       373u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC73       374u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC74       375u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC75       376u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC76       377u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC77       378u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC78       379u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC79       380u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC80       381u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC81       382u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC82       383u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC83       384u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC84       385u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC85       386u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC86       387u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC87       388u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC88       389u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC89       390u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC90       391u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC91       392u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC92       393u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC93       394u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC94       395u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC95       396u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC96       397u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC97       398u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC98       399u
#define DemConf_DemEventParameter_DemEventParameter_ECU4_DTC99       400u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC00       401u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC01       402u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC02       403u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC03       404u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC04       405u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC05       406u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC06       407u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC07       408u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC08       409u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC09       410u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC10       411u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC11       412u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC12       413u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC13       414u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC14       415u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC15       416u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC16       417u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC17       418u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC18       419u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC19       420u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC20       421u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC21       422u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC22       423u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC23       424u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC24       425u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC25       426u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC26       427u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC27       428u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC28       429u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC29       430u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC30       431u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC31       432u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC32       433u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC33       434u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC34       435u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC35       436u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC36       437u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC37       438u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC38       439u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC39       440u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC40       441u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC41       442u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC42       443u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC43       444u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC44       445u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC45       446u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC46       447u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC47       448u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC48       449u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC49       450u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC50       451u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC51       452u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC52       453u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC53       454u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC54       455u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC55       456u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC56       457u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC57       458u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC58       459u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC59       460u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC60       461u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC61       462u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC62       463u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC63       464u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC64       465u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC65       466u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC66       467u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC67       468u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC68       469u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC69       470u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC70       471u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC71       472u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC72       473u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC73       474u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC74       475u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC75       476u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC76       477u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC77       478u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC78       479u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC79       480u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC80       481u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC81       482u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC82       483u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC83       484u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC84       485u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC85       486u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC86       487u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC87       488u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC88       489u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC89       490u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC90       491u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC91       492u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC92       493u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC93       494u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC94       495u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC95       496u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC96       497u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC97       498u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC98       499u
#define DemConf_DemEventParameter_DemEventParameter_ECU5_DTC99       500u

#endif

