/******************************************************************************/
/*                                                                            */
/* !Layer           : STD                                                     */
/*                                                                            */
/* !Component       : MEMMAP                                                  */
/* !Description     : MEMMAP Configuration                                    */
/*                                                                            */
/* !File            : FR_MEMMAP.H                                        */
/*                                                                            */
/* !Scope           : Public                                                  */
/*                                                                            */
/* !Target          :                                                         */
/*                                                                            */
/* !Vendor          : invt                                                    */
/*                                                                            */
/* Coding language  : C                                                       */
/*                                                                            */
/* COPYRIGHT 2009 invt                                                        */
/* all rights reserved                                                        */
/*                                                                            */
/******************************************************************************/
/* SVN Information                                                           */
/* $Archive::                                                                $*/
/* $Revision::            $$Author::                  $$Date::               $*/
/******************************************************************************/
/* 10/27/22, 09:10:33: generated by Genecode  v2.6.0.0                        */
/* From Source Template : MSN_MEMMAP_H.TPL                                    */
/******************************************************************************/



/******************************************************************************/
/*          MEMMAP selected mode:  SAFE                                       */
/******************************************************************************/
#define MEMMAP_ERROR

/* The following if is used only due to automatic generation */
#if !defined MEMMAP_ERROR

/* -------------------------------------------------------------------------- */
/* ROM code                                                                   */
/* -------------------------------------------------------------------------- */
/* Project section mappings */
/* !Comment: FR Section allocation */
#elif defined   FR_START_SEC_CODE
   #undef  FR_START_SEC_CODE
   #define START_SEC_CODE_SECTION
#elif defined   FR_STOP_SEC_CODE
   #undef  FR_STOP_SEC_CODE
   #define STOP_SEC_CODE_SECTION

/* -------------------------------------------------------------------------- */
/* PSRAM code initialized from ROM on reset                                   */
/* -------------------------------------------------------------------------- */
#elif defined   FR_START_CODE_FAST_CPU0_SECTION
   #define CDD_START_CODE_FAST_CPU0_SECTION
   #include "CddMemMap.h"
    #undef  FR_START_CODE_FAST_CPU0_SECTION
    #undef  MEMMAP_ERROR
#elif defined   FR_STOP_CODE_FAST_CPU0_SECTION
   #define CDD_STOP_CODE_FAST_CPU0_SECTION
   #include "CddMemMap.h"
    #undef  FR_STOP_CODE_FAST_CPU0_SECTION
    #undef  MEMMAP_ERROR

#elif defined   FR_START_CODE_FAST_CPU1_SECTION
   #define CDD_START_CODE_FAST_CPU1_SECTION
   #include "CddMemMap.h"
    #undef  FR_START_CODE_FAST_CPU1_SECTION
    #undef  MEMMAP_ERROR
#elif defined   FR_STOP_CODE_FAST_CPU1_SECTION
   #define CDD_STOP_CODE_FAST_CPU1_SECTION
   #include "CddMemMap.h"
    #undef  FR_STOP_CODE_FAST_CPU1_SECTION
    #undef  MEMMAP_ERROR

#elif defined   FR_START_CODE_FAST_CPU2_SECTION
   #define CDD_START_CODE_FAST_CPU2_SECTION
   #include "CddMemMap.h"
    #undef  FR_START_CODE_FAST_CPU2_SECTION
    #undef  MEMMAP_ERROR
#elif defined   FR_STOP_CODE_FAST_CPU2_SECTION
   #define CDD_STOP_CODE_FAST_CPU2_SECTION
   #include "CddMemMap.h"
    #undef  FR_STOP_CODE_FAST_CPU2_SECTION
    #undef  MEMMAP_ERROR

#elif defined   FR_START_CODE_FAST_CPU3_SECTION
   #define CDD_START_CODE_FAST_CPU3_SECTION
   #include "CddMemMap.h"
    #undef  FR_START_CODE_FAST_CPU3_SECTION
    #undef  MEMMAP_ERROR
#elif defined   FR_STOP_CODE_FAST_CPU3_SECTION
   #define CDD_STOP_CODE_FAST_CPU3_SECTION
   #include "CddMemMap.h"
    #undef  FR_STOP_CODE_FAST_CPU3_SECTION
    #undef  MEMMAP_ERROR

#elif defined   FR_START_CODE_FAST_CPU4_SECTION
   #define CDD_START_CODE_FAST_CPU4_SECTION
   #include "CddMemMap.h"
    #undef  FR_START_CODE_FAST_CPU4_SECTION
    #undef  MEMMAP_ERROR
#elif defined   FR_STOP_CODE_FAST_CPU4_SECTION
   #define CDD_STOP_CODE_FAST_CPU4_SECTION
   #include "CddMemMap.h"
    #undef  FR_STOP_CODE_FAST_CPU4_SECTION
    #undef  MEMMAP_ERROR

#elif defined   FR_START_CODE_FAST_CPU5_SECTION
   #define CDD_START_CODE_FAST_CPU5_SECTION
   #include "CddMemMap.h"
    #undef  FR_START_CODE_FAST_CPU5_SECTION
    #undef  MEMMAP_ERROR
#elif defined   FR_STOP_CODE_FAST_CPU5_SECTION
   #define CDD_STOP_CODE_FAST_CPU5_SECTION
   #include "CddMemMap.h"
    #undef  FR_STOP_CODE_FAST_CPU5_SECTION
    #undef  MEMMAP_ERROR

/* -------------------------------------------------------------------------- */
/* RAM variables initialized from ROM on reset                                */
/* -------------------------------------------------------------------------- */
#elif defined  FR_START_SEC_VAR_INIT_CORE0_UNSPECIFIED
   #define CDD_START_SEC_VAR_INIT_CORE0_UNSPECIFIED
   #include "CddMemMap.h"
    #undef  FR_START_SEC_VAR_INIT_CORE0_UNSPECIFIED
    #undef  MEMMAP_ERROR
#elif defined  FR_STOP_SEC_VAR_INIT_CORE0_UNSPECIFIED
   #define CDD_STOP_SEC_VAR_INIT_CORE0_UNSPECIFIED
   #include "CddMemMap.h"
    #undef  FR_STOP_SEC_VAR_INIT_CORE0_UNSPECIFIED
    #undef  MEMMAP_ERROR
      
#elif defined  FR_START_SEC_VAR_INIT_CORE0_BOOLEAN
   #define CDD_START_SEC_VAR_INIT_CORE0_BOOLEAN
   #include "CddMemMap.h"
    #undef  FR_START_SEC_VAR_INIT_CORE0_BOOLEAN
    #undef  MEMMAP_ERROR
#elif defined  FR_STOP_SEC_VAR_INIT_CORE0_BOOLEAN
   #define CDD_STOP_SEC_VAR_INIT_CORE0_BOOLEAN
   #include "CddMemMap.h"
    #undef  FR_STOP_SEC_VAR_INIT_CORE0_BOOLEAN
    #undef  MEMMAP_ERROR
      
#elif defined  FR_START_SEC_VAR_INIT_CORE0_8
   #define CDD_START_SEC_VAR_INIT_CORE0_8
   #include "CddMemMap.h"
    #undef  FR_START_SEC_VAR_INIT_CORE0_8
    #undef  MEMMAP_ERROR
#elif defined  FR_STOP_SEC_VAR_INIT_CORE0_8
   #define CDD_STOP_SEC_VAR_INIT_CORE0_8
   #include "CddMemMap.h"
    #undef  FR_STOP_SEC_VAR_INIT_CORE0_8
    #undef  MEMMAP_ERROR
      
#elif defined  FR_START_SEC_VAR_INIT_CORE0_16
   #define CDD_START_SEC_VAR_INIT_CORE0_16
   #include "CddMemMap.h"
    #undef  FR_START_SEC_VAR_INIT_CORE0_16
    #undef  MEMMAP_ERROR
#elif defined  FR_STOP_SEC_VAR_INIT_CORE0_16
   #define CDD_STOP_SEC_VAR_INIT_CORE0_16
   #include "CddMemMap.h"
    #undef  FR_STOP_SEC_VAR_INIT_CORE0_16
    #undef  MEMMAP_ERROR
      
#elif defined  FR_START_SEC_VAR_INIT_CORE0_32
   #define CDD_START_SEC_VAR_INIT_CORE0_32
   #include "CddMemMap.h"
    #undef  FR_START_SEC_VAR_INIT_CORE0_32
    #undef  MEMMAP_ERROR
#elif defined  FR_STOP_SEC_VAR_INIT_CORE0_32
   #define CDD_STOP_SEC_VAR_INIT_CORE0_32
   #include "CddMemMap.h"
    #undef  FR_STOP_SEC_VAR_INIT_CORE0_32
    #undef  MEMMAP_ERROR
      
#elif defined  FR_START_SEC_VAR_INIT_CORE1_UNSPECIFIED
   #define CDD_START_SEC_VAR_INIT_CORE1_UNSPECIFIED
   #include "CddMemMap.h"
    #undef  FR_START_SEC_VAR_INIT_CORE1_UNSPECIFIED
    #undef  MEMMAP_ERROR
#elif defined  FR_STOP_SEC_VAR_INIT_CORE1_UNSPECIFIED
   #define CDD_STOP_SEC_VAR_INIT_CORE1_UNSPECIFIED
   #include "CddMemMap.h"
    #undef  FR_STOP_SEC_VAR_INIT_CORE1_UNSPECIFIED
    #undef  MEMMAP_ERROR
      
#elif defined  FR_START_SEC_VAR_INIT_CORE1_BOOLEAN
   #define CDD_START_SEC_VAR_INIT_CORE1_BOOLEAN
   #include "CddMemMap.h"
    #undef  FR_START_SEC_VAR_INIT_CORE1_BOOLEAN
    #undef  MEMMAP_ERROR
#elif defined  FR_STOP_SEC_VAR_INIT_CORE1_BOOLEAN
   #define CDD_STOP_SEC_VAR_INIT_CORE1_BOOLEAN
   #include "CddMemMap.h"
    #undef  FR_STOP_SEC_VAR_INIT_CORE1_BOOLEAN
    #undef  MEMMAP_ERROR
      
#elif defined  FR_START_SEC_VAR_INIT_CORE1_8
   #define CDD_START_SEC_VAR_INIT_CORE1_8
   #include "CddMemMap.h"
    #undef  FR_START_SEC_VAR_INIT_CORE1_8
    #undef  MEMMAP_ERROR
#elif defined  FR_STOP_SEC_VAR_INIT_CORE1_8
   #define CDD_STOP_SEC_VAR_INIT_CORE1_8
   #include "CddMemMap.h"
    #undef  FR_STOP_SEC_VAR_INIT_CORE1_8
    #undef  MEMMAP_ERROR
      
#elif defined  FR_START_SEC_VAR_INIT_CORE1_16
   #define CDD_START_SEC_VAR_INIT_CORE1_16
   #include "CddMemMap.h"
    #undef  FR_START_SEC_VAR_INIT_CORE1_16
    #undef  MEMMAP_ERROR
#elif defined  FR_STOP_SEC_VAR_INIT_CORE1_16
   #define CDD_STOP_SEC_VAR_INIT_CORE1_16
   #include "CddMemMap.h"
    #undef  FR_STOP_SEC_VAR_INIT_CORE1_16
    #undef  MEMMAP_ERROR
      
#elif defined  FR_START_SEC_VAR_INIT_CORE1_32
   #define CDD_START_SEC_VAR_INIT_CORE1_32
   #include "CddMemMap.h"
    #undef  FR_START_SEC_VAR_INIT_CORE1_32
    #undef  MEMMAP_ERROR
#elif defined  FR_STOP_SEC_VAR_INIT_CORE1_32
   #define CDD_STOP_SEC_VAR_INIT_CORE1_32
   #include "CddMemMap.h"
    #undef  FR_STOP_SEC_VAR_INIT_CORE1_32
    #undef  MEMMAP_ERROR
      
#elif defined  FR_START_SEC_VAR_INIT_CORE2_UNSPECIFIED
   #define CDD_START_SEC_VAR_INIT_CORE2_UNSPECIFIED
   #include "CddMemMap.h"
    #undef  FR_START_SEC_VAR_INIT_CORE2_UNSPECIFIED
    #undef  MEMMAP_ERROR
#elif defined  FR_STOP_SEC_VAR_INIT_CORE2_UNSPECIFIED
   #define CDD_STOP_SEC_VAR_INIT_CORE2_UNSPECIFIED
   #include "CddMemMap.h"
    #undef  FR_STOP_SEC_VAR_INIT_CORE2_UNSPECIFIED
    #undef  MEMMAP_ERROR
      
#elif defined  FR_START_SEC_VAR_INIT_CORE2_BOOLEAN
   #define CDD_START_SEC_VAR_INIT_CORE2_BOOLEAN
   #include "CddMemMap.h"
    #undef  FR_START_SEC_VAR_INIT_CORE2_BOOLEAN
    #undef  MEMMAP_ERROR
#elif defined  FR_STOP_SEC_VAR_INIT_CORE2_BOOLEAN
   #define CDD_STOP_SEC_VAR_INIT_CORE2_BOOLEAN
   #include "CddMemMap.h"
    #undef  FR_STOP_SEC_VAR_INIT_CORE2_BOOLEAN
    #undef  MEMMAP_ERROR
      
#elif defined  FR_START_SEC_VAR_INIT_CORE2_8
   #define CDD_START_SEC_VAR_INIT_CORE2_8
   #include "CddMemMap.h"
    #undef  FR_START_SEC_VAR_INIT_CORE2_8
    #undef  MEMMAP_ERROR
#elif defined  FR_STOP_SEC_VAR_INIT_CORE2_8
   #define CDD_STOP_SEC_VAR_INIT_CORE2_8
   #include "CddMemMap.h"
    #undef  FR_STOP_SEC_VAR_INIT_CORE2_8
    #undef  MEMMAP_ERROR
      
#elif defined  FR_START_SEC_VAR_INIT_CORE2_16
   #define CDD_START_SEC_VAR_INIT_CORE2_16
   #include "CddMemMap.h"
    #undef  FR_START_SEC_VAR_INIT_CORE2_16
    #undef  MEMMAP_ERROR
#elif defined  FR_STOP_SEC_VAR_INIT_CORE2_16
   #define CDD_STOP_SEC_VAR_INIT_CORE2_16
   #include "CddMemMap.h"
    #undef  FR_STOP_SEC_VAR_INIT_CORE2_16
    #undef  MEMMAP_ERROR
      
#elif defined  FR_START_SEC_VAR_INIT_CORE2_32
   #define CDD_START_SEC_VAR_INIT_CORE2_32
   #include "CddMemMap.h"
    #undef  FR_START_SEC_VAR_INIT_CORE2_32
    #undef  MEMMAP_ERROR
#elif defined  FR_STOP_SEC_VAR_INIT_CORE2_32
   #define CDD_STOP_SEC_VAR_INIT_CORE2_32
   #include "CddMemMap.h"
    #undef  FR_STOP_SEC_VAR_INIT_CORE2_32
    #undef  MEMMAP_ERROR
      
#elif defined  FR_START_SEC_VAR_INIT_CORE3_UNSPECIFIED
   #define CDD_START_SEC_VAR_INIT_CORE3_UNSPECIFIED
   #include "CddMemMap.h"
    #undef  FR_START_SEC_VAR_INIT_CORE3_UNSPECIFIED
    #undef  MEMMAP_ERROR
#elif defined  FR_STOP_SEC_VAR_INIT_CORE3_UNSPECIFIED
   #define CDD_STOP_SEC_VAR_INIT_CORE3_UNSPECIFIED
   #include "CddMemMap.h"
    #undef  FR_STOP_SEC_VAR_INIT_CORE3_UNSPECIFIED
    #undef  MEMMAP_ERROR
      
#elif defined  FR_START_SEC_VAR_INIT_CORE3_BOOLEAN
   #define CDD_START_SEC_VAR_INIT_CORE3_BOOLEAN
   #include "CddMemMap.h"
    #undef  FR_START_SEC_VAR_INIT_CORE3_BOOLEAN
    #undef  MEMMAP_ERROR
#elif defined  FR_STOP_SEC_VAR_INIT_CORE3_BOOLEAN
   #define CDD_STOP_SEC_VAR_INIT_CORE3_BOOLEAN
   #include "CddMemMap.h"
    #undef  FR_STOP_SEC_VAR_INIT_CORE3_BOOLEAN
    #undef  MEMMAP_ERROR
      
#elif defined  FR_START_SEC_VAR_INIT_CORE3_8
   #define CDD_START_SEC_VAR_INIT_CORE3_8
   #include "CddMemMap.h"
    #undef  FR_START_SEC_VAR_INIT_CORE3_8
    #undef  MEMMAP_ERROR
#elif defined  FR_STOP_SEC_VAR_INIT_CORE3_8
   #define CDD_STOP_SEC_VAR_INIT_CORE3_8
   #include "CddMemMap.h"
    #undef  FR_STOP_SEC_VAR_INIT_CORE3_8
    #undef  MEMMAP_ERROR
      
#elif defined  FR_START_SEC_VAR_INIT_CORE3_16
   #define CDD_START_SEC_VAR_INIT_CORE3_16
   #include "CddMemMap.h"
    #undef  FR_START_SEC_VAR_INIT_CORE3_16
    #undef  MEMMAP_ERROR
#elif defined  FR_STOP_SEC_VAR_INIT_CORE3_16
   #define CDD_STOP_SEC_VAR_INIT_CORE3_16
   #include "CddMemMap.h"
    #undef  FR_STOP_SEC_VAR_INIT_CORE3_16
    #undef  MEMMAP_ERROR
      
#elif defined  FR_START_SEC_VAR_INIT_CORE3_32
   #define CDD_START_SEC_VAR_INIT_CORE3_32
   #include "CddMemMap.h"
    #undef  FR_START_SEC_VAR_INIT_CORE3_32
    #undef  MEMMAP_ERROR
#elif defined  FR_STOP_SEC_VAR_INIT_CORE3_32
   #define CDD_STOP_SEC_VAR_INIT_CORE3_32
   #include "CddMemMap.h"
    #undef  FR_STOP_SEC_VAR_INIT_CORE3_32
    #undef  MEMMAP_ERROR
      
#elif defined  FR_START_SEC_VAR_INIT_CORE4_UNSPECIFIED
   #define CDD_START_SEC_VAR_INIT_CORE4_UNSPECIFIED
   #include "CddMemMap.h"
    #undef  FR_START_SEC_VAR_INIT_CORE4_UNSPECIFIED
    #undef  MEMMAP_ERROR
#elif defined  FR_STOP_SEC_VAR_INIT_CORE4_UNSPECIFIED
   #define CDD_STOP_SEC_VAR_INIT_CORE4_UNSPECIFIED
   #include "CddMemMap.h"
    #undef  FR_STOP_SEC_VAR_INIT_CORE4_UNSPECIFIED
    #undef  MEMMAP_ERROR
      
#elif defined  FR_START_SEC_VAR_INIT_CORE4_BOOLEAN
   #define CDD_START_SEC_VAR_INIT_CORE4_BOOLEAN
   #include "CddMemMap.h"
    #undef  FR_START_SEC_VAR_INIT_CORE4_BOOLEAN
    #undef  MEMMAP_ERROR
#elif defined  FR_STOP_SEC_VAR_INIT_CORE4_BOOLEAN
   #define CDD_STOP_SEC_VAR_INIT_CORE4_BOOLEAN
   #include "CddMemMap.h"
    #undef  FR_STOP_SEC_VAR_INIT_CORE4_BOOLEAN
    #undef  MEMMAP_ERROR
      
#elif defined  FR_START_SEC_VAR_INIT_CORE4_8
   #define CDD_START_SEC_VAR_INIT_CORE4_8
   #include "CddMemMap.h"
    #undef  FR_START_SEC_VAR_INIT_CORE4_8
    #undef  MEMMAP_ERROR
#elif defined  FR_STOP_SEC_VAR_INIT_CORE4_8
   #define CDD_STOP_SEC_VAR_INIT_CORE4_8
   #include "CddMemMap.h"
    #undef  FR_STOP_SEC_VAR_INIT_CORE4_8
    #undef  MEMMAP_ERROR
      
#elif defined  FR_START_SEC_VAR_INIT_CORE4_16
   #define CDD_START_SEC_VAR_INIT_CORE4_16
   #include "CddMemMap.h"
    #undef  FR_START_SEC_VAR_INIT_CORE4_16
    #undef  MEMMAP_ERROR
#elif defined  FR_STOP_SEC_VAR_INIT_CORE4_16
   #define CDD_STOP_SEC_VAR_INIT_CORE4_16
   #include "CddMemMap.h"
    #undef  FR_STOP_SEC_VAR_INIT_CORE4_16
    #undef  MEMMAP_ERROR
      
#elif defined  FR_START_SEC_VAR_INIT_CORE4_32
   #define CDD_START_SEC_VAR_INIT_CORE4_32
   #include "CddMemMap.h"
    #undef  FR_START_SEC_VAR_INIT_CORE4_32
    #undef  MEMMAP_ERROR
#elif defined  FR_STOP_SEC_VAR_INIT_CORE4_32
   #define CDD_STOP_SEC_VAR_INIT_CORE4_32
   #include "CddMemMap.h"
    #undef  FR_STOP_SEC_VAR_INIT_CORE4_32
    #undef  MEMMAP_ERROR
      
#elif defined  FR_START_SEC_VAR_INIT_CORE5_UNSPECIFIED
   #define CDD_START_SEC_VAR_INIT_CORE5_UNSPECIFIED
   #include "CddMemMap.h"
    #undef  FR_START_SEC_VAR_INIT_CORE5_UNSPECIFIED
    #undef  MEMMAP_ERROR
#elif defined  FR_STOP_SEC_VAR_INIT_CORE5_UNSPECIFIED
   #define CDD_STOP_SEC_VAR_INIT_CORE5_UNSPECIFIED
   #include "CddMemMap.h"
    #undef  FR_STOP_SEC_VAR_INIT_CORE5_UNSPECIFIED
    #undef  MEMMAP_ERROR
      
#elif defined  FR_START_SEC_VAR_INIT_CORE5_BOOLEAN
   #define CDD_START_SEC_VAR_INIT_CORE5_BOOLEAN
   #include "CddMemMap.h"
    #undef  FR_START_SEC_VAR_INIT_CORE5_BOOLEAN
    #undef  MEMMAP_ERROR
#elif defined  FR_STOP_SEC_VAR_INIT_CORE5_BOOLEAN
   #define CDD_STOP_SEC_VAR_INIT_CORE5_BOOLEAN
   #include "CddMemMap.h"
    #undef  FR_STOP_SEC_VAR_INIT_CORE5_BOOLEAN
    #undef  MEMMAP_ERROR
      
#elif defined  FR_START_SEC_VAR_INIT_CORE5_8
   #define CDD_START_SEC_VAR_INIT_CORE5_8
   #include "CddMemMap.h"
    #undef  FR_START_SEC_VAR_INIT_CORE5_8
    #undef  MEMMAP_ERROR
#elif defined  FR_STOP_SEC_VAR_INIT_CORE5_8
   #define CDD_STOP_SEC_VAR_INIT_CORE5_8
   #include "CddMemMap.h"
    #undef  FR_STOP_SEC_VAR_INIT_CORE5_8
    #undef  MEMMAP_ERROR
      
#elif defined  FR_START_SEC_VAR_INIT_CORE5_16
   #define CDD_START_SEC_VAR_INIT_CORE5_16
   #include "CddMemMap.h"
    #undef  FR_START_SEC_VAR_INIT_CORE5_16
    #undef  MEMMAP_ERROR
#elif defined  FR_STOP_SEC_VAR_INIT_CORE5_16
   #define CDD_STOP_SEC_VAR_INIT_CORE5_16
   #include "CddMemMap.h"
    #undef  FR_STOP_SEC_VAR_INIT_CORE5_16
    #undef  MEMMAP_ERROR
      
#elif defined  FR_START_SEC_VAR_INIT_CORE5_32
   #define CDD_START_SEC_VAR_INIT_CORE5_32
   #include "CddMemMap.h"
    #undef  FR_START_SEC_VAR_INIT_CORE5_32
    #undef  MEMMAP_ERROR
#elif defined  FR_STOP_SEC_VAR_INIT_CORE5_32
   #define CDD_STOP_SEC_VAR_INIT_CORE5_32
   #include "CddMemMap.h"
    #undef  FR_STOP_SEC_VAR_INIT_CORE5_32
    #undef  MEMMAP_ERROR

/* -------------------------------------------------------------------------- */
/* RAM variables cleared on reset                                             */
/* -------------------------------------------------------------------------- */
#elif defined  FR_START_SEC_VAR_CLEARED_CORE0_UNSPECIFIED
   #define CDD_START_SEC_VAR_CLEARED_CORE0_UNSPECIFIED
   #include "CddMemMap.h"
    #undef  FR_START_SEC_VAR_CLEARED_CORE0_UNSPECIFIED
    #undef  MEMMAP_ERROR
#elif defined  FR_STOP_SEC_VAR_CLEARED_CORE0_UNSPECIFIED
   #define CDD_STOP_SEC_VAR_CLEARED_CORE0_UNSPECIFIED
   #include "CddMemMap.h"
    #undef  FR_STOP_SEC_VAR_CLEARED_CORE0_UNSPECIFIED
    #undef  MEMMAP_ERROR
      
#elif defined  FR_START_SEC_VAR_CLEARED_CORE0_BOOLEAN
   #define CDD_START_SEC_VAR_CLEARED_CORE0_BOOLEAN
   #include "CddMemMap.h"
    #undef  FR_START_SEC_VAR_CLEARED_CORE0_BOOLEAN
    #undef  MEMMAP_ERROR
#elif defined  FR_STOP_SEC_VAR_CLEARED_CORE0_BOOLEAN
   #define CDD_STOP_SEC_VAR_CLEARED_CORE0_BOOLEAN
   #include "CddMemMap.h"
    #undef  FR_STOP_SEC_VAR_CLEARED_CORE0_BOOLEAN
    #undef  MEMMAP_ERROR
      
#elif defined  FR_START_SEC_VAR_CLEARED_CORE0_8
   #define CDD_START_SEC_VAR_CLEARED_CORE0_8
   #include "CddMemMap.h"
    #undef  FR_START_SEC_VAR_CLEARED_CORE0_8
    #undef  MEMMAP_ERROR
#elif defined  FR_STOP_SEC_VAR_CLEARED_CORE0_8
   #define CDD_STOP_SEC_VAR_CLEARED_CORE0_8
   #include "CddMemMap.h"
    #undef  FR_STOP_SEC_VAR_CLEARED_CORE0_8
    #undef  MEMMAP_ERROR
      
#elif defined  FR_START_SEC_VAR_CLEARED_CORE0_16
   #define CDD_START_SEC_VAR_CLEARED_CORE0_16
   #include "CddMemMap.h"
    #undef  FR_START_SEC_VAR_CLEARED_CORE0_16
    #undef  MEMMAP_ERROR
#elif defined  FR_STOP_SEC_VAR_CLEARED_CORE0_16
   #define CDD_STOP_SEC_VAR_CLEARED_CORE0_16
   #include "CddMemMap.h"
    #undef  FR_STOP_SEC_VAR_CLEARED_CORE0_16
    #undef  MEMMAP_ERROR
      
#elif defined  FR_START_SEC_VAR_CLEARED_CORE0_32
   #define CDD_START_SEC_VAR_CLEARED_CORE0_32
   #include "CddMemMap.h"
    #undef  FR_START_SEC_VAR_CLEARED_CORE0_32
    #undef  MEMMAP_ERROR
#elif defined  FR_STOP_SEC_VAR_CLEARED_CORE0_32
   #define CDD_STOP_SEC_VAR_CLEARED_CORE0_32
   #include "CddMemMap.h"
    #undef  FR_STOP_SEC_VAR_CLEARED_CORE0_32
    #undef  MEMMAP_ERROR
      
#elif defined  FR_START_SEC_VAR_CLEARED_CORE1_UNSPECIFIED
   #define CDD_START_SEC_VAR_CLEARED_CORE1_UNSPECIFIED
   #include "CddMemMap.h"
    #undef  FR_START_SEC_VAR_CLEARED_CORE1_UNSPECIFIED
    #undef  MEMMAP_ERROR
#elif defined  FR_STOP_SEC_VAR_CLEARED_CORE1_UNSPECIFIED
   #define CDD_STOP_SEC_VAR_CLEARED_CORE1_UNSPECIFIED
   #include "CddMemMap.h"
    #undef  FR_STOP_SEC_VAR_CLEARED_CORE1_UNSPECIFIED
    #undef  MEMMAP_ERROR
      
#elif defined  FR_START_SEC_VAR_CLEARED_CORE1_BOOLEAN
   #define CDD_START_SEC_VAR_CLEARED_CORE1_BOOLEAN
   #include "CddMemMap.h"
    #undef  FR_START_SEC_VAR_CLEARED_CORE1_BOOLEAN
    #undef  MEMMAP_ERROR
#elif defined  FR_STOP_SEC_VAR_CLEARED_CORE1_BOOLEAN
   #define CDD_STOP_SEC_VAR_CLEARED_CORE1_BOOLEAN
   #include "CddMemMap.h"
    #undef  FR_STOP_SEC_VAR_CLEARED_CORE1_BOOLEAN
    #undef  MEMMAP_ERROR
      
#elif defined  FR_START_SEC_VAR_CLEARED_CORE1_8
   #define CDD_START_SEC_VAR_CLEARED_CORE1_8
   #include "CddMemMap.h"
    #undef  FR_START_SEC_VAR_CLEARED_CORE1_8
    #undef  MEMMAP_ERROR
#elif defined  FR_STOP_SEC_VAR_CLEARED_CORE1_8
   #define CDD_STOP_SEC_VAR_CLEARED_CORE1_8
   #include "CddMemMap.h"
    #undef  FR_STOP_SEC_VAR_CLEARED_CORE1_8
    #undef  MEMMAP_ERROR
      
#elif defined  FR_START_SEC_VAR_CLEARED_CORE1_16
   #define CDD_START_SEC_VAR_CLEARED_CORE1_16
   #include "CddMemMap.h"
    #undef  FR_START_SEC_VAR_CLEARED_CORE1_16
    #undef  MEMMAP_ERROR
#elif defined  FR_STOP_SEC_VAR_CLEARED_CORE1_16
   #define CDD_STOP_SEC_VAR_CLEARED_CORE1_16
   #include "CddMemMap.h"
    #undef  FR_STOP_SEC_VAR_CLEARED_CORE1_16
    #undef  MEMMAP_ERROR
      
#elif defined  FR_START_SEC_VAR_CLEARED_CORE1_32
   #define CDD_START_SEC_VAR_CLEARED_CORE1_32
   #include "CddMemMap.h"
    #undef  FR_START_SEC_VAR_CLEARED_CORE1_32
    #undef  MEMMAP_ERROR
#elif defined  FR_STOP_SEC_VAR_CLEARED_CORE1_32
   #define CDD_STOP_SEC_VAR_CLEARED_CORE1_32
   #include "CddMemMap.h"
    #undef  FR_STOP_SEC_VAR_CLEARED_CORE1_32
    #undef  MEMMAP_ERROR
      
#elif defined  FR_START_SEC_VAR_CLEARED_CORE2_UNSPECIFIED
   #define CDD_START_SEC_VAR_CLEARED_CORE2_UNSPECIFIED
   #include "CddMemMap.h"
    #undef  FR_START_SEC_VAR_CLEARED_CORE2_UNSPECIFIED
    #undef  MEMMAP_ERROR
#elif defined  FR_STOP_SEC_VAR_CLEARED_CORE2_UNSPECIFIED
   #define CDD_STOP_SEC_VAR_CLEARED_CORE2_UNSPECIFIED
   #include "CddMemMap.h"
    #undef  FR_STOP_SEC_VAR_CLEARED_CORE2_UNSPECIFIED
    #undef  MEMMAP_ERROR
      
#elif defined  FR_START_SEC_VAR_CLEARED_CORE2_BOOLEAN
   #define CDD_START_SEC_VAR_CLEARED_CORE2_BOOLEAN
   #include "CddMemMap.h"
    #undef  FR_START_SEC_VAR_CLEARED_CORE2_BOOLEAN
    #undef  MEMMAP_ERROR
#elif defined  FR_STOP_SEC_VAR_CLEARED_CORE2_BOOLEAN
   #define CDD_STOP_SEC_VAR_CLEARED_CORE2_BOOLEAN
   #include "CddMemMap.h"
    #undef  FR_STOP_SEC_VAR_CLEARED_CORE2_BOOLEAN
    #undef  MEMMAP_ERROR
      
#elif defined  FR_START_SEC_VAR_CLEARED_CORE2_8
   #define CDD_START_SEC_VAR_CLEARED_CORE2_8
   #include "CddMemMap.h"
    #undef  FR_START_SEC_VAR_CLEARED_CORE2_8
    #undef  MEMMAP_ERROR
#elif defined  FR_STOP_SEC_VAR_CLEARED_CORE2_8
   #define CDD_STOP_SEC_VAR_CLEARED_CORE2_8
   #include "CddMemMap.h"
    #undef  FR_STOP_SEC_VAR_CLEARED_CORE2_8
    #undef  MEMMAP_ERROR
      
#elif defined  FR_START_SEC_VAR_CLEARED_CORE2_16
   #define CDD_START_SEC_VAR_CLEARED_CORE2_16
   #include "CddMemMap.h"
    #undef  FR_START_SEC_VAR_CLEARED_CORE2_16
    #undef  MEMMAP_ERROR
#elif defined  FR_STOP_SEC_VAR_CLEARED_CORE2_16
   #define CDD_STOP_SEC_VAR_CLEARED_CORE2_16
   #include "CddMemMap.h"
    #undef  FR_STOP_SEC_VAR_CLEARED_CORE2_16
    #undef  MEMMAP_ERROR
      
#elif defined  FR_START_SEC_VAR_CLEARED_CORE2_32
   #define CDD_START_SEC_VAR_CLEARED_CORE2_32
   #include "CddMemMap.h"
    #undef  FR_START_SEC_VAR_CLEARED_CORE2_32
    #undef  MEMMAP_ERROR
#elif defined  FR_STOP_SEC_VAR_CLEARED_CORE2_32
   #define CDD_STOP_SEC_VAR_CLEARED_CORE2_32
   #include "CddMemMap.h"
    #undef  FR_STOP_SEC_VAR_CLEARED_CORE2_32
    #undef  MEMMAP_ERROR
      
#elif defined  FR_START_SEC_VAR_CLEARED_CORE3_UNSPECIFIED
   #define CDD_START_SEC_VAR_CLEARED_CORE3_UNSPECIFIED
   #include "CddMemMap.h"
    #undef  FR_START_SEC_VAR_CLEARED_CORE3_UNSPECIFIED
    #undef  MEMMAP_ERROR
#elif defined  FR_STOP_SEC_VAR_CLEARED_CORE3_UNSPECIFIED
   #define CDD_STOP_SEC_VAR_CLEARED_CORE3_UNSPECIFIED
   #include "CddMemMap.h"
    #undef  FR_STOP_SEC_VAR_CLEARED_CORE3_UNSPECIFIED
    #undef  MEMMAP_ERROR
      
#elif defined  FR_START_SEC_VAR_CLEARED_CORE3_BOOLEAN
   #define CDD_START_SEC_VAR_CLEARED_CORE3_BOOLEAN
   #include "CddMemMap.h"
    #undef  FR_START_SEC_VAR_CLEARED_CORE3_BOOLEAN
    #undef  MEMMAP_ERROR
#elif defined  FR_STOP_SEC_VAR_CLEARED_CORE3_BOOLEAN
   #define CDD_STOP_SEC_VAR_CLEARED_CORE3_BOOLEAN
   #include "CddMemMap.h"
    #undef  FR_STOP_SEC_VAR_CLEARED_CORE3_BOOLEAN
    #undef  MEMMAP_ERROR
      
#elif defined  FR_START_SEC_VAR_CLEARED_CORE3_8
   #define CDD_START_SEC_VAR_CLEARED_CORE3_8
   #include "CddMemMap.h"
    #undef  FR_START_SEC_VAR_CLEARED_CORE3_8
    #undef  MEMMAP_ERROR
#elif defined  FR_STOP_SEC_VAR_CLEARED_CORE3_8
   #define CDD_STOP_SEC_VAR_CLEARED_CORE3_8
   #include "CddMemMap.h"
    #undef  FR_STOP_SEC_VAR_CLEARED_CORE3_8
    #undef  MEMMAP_ERROR
      
#elif defined  FR_START_SEC_VAR_CLEARED_CORE3_16
   #define CDD_START_SEC_VAR_CLEARED_CORE3_16
   #include "CddMemMap.h"
    #undef  FR_START_SEC_VAR_CLEARED_CORE3_16
    #undef  MEMMAP_ERROR
#elif defined  FR_STOP_SEC_VAR_CLEARED_CORE3_16
   #define CDD_STOP_SEC_VAR_CLEARED_CORE3_16
   #include "CddMemMap.h"
    #undef  FR_STOP_SEC_VAR_CLEARED_CORE3_16
    #undef  MEMMAP_ERROR
      
#elif defined  FR_START_SEC_VAR_CLEARED_CORE3_32
   #define CDD_START_SEC_VAR_CLEARED_CORE3_32
   #include "CddMemMap.h"
    #undef  FR_START_SEC_VAR_CLEARED_CORE3_32
    #undef  MEMMAP_ERROR
#elif defined  FR_STOP_SEC_VAR_CLEARED_CORE3_32
   #define CDD_STOP_SEC_VAR_CLEARED_CORE3_32
   #include "CddMemMap.h"
    #undef  FR_STOP_SEC_VAR_CLEARED_CORE3_32
    #undef  MEMMAP_ERROR
      
#elif defined  FR_START_SEC_VAR_CLEARED_CORE4_UNSPECIFIED
   #define CDD_START_SEC_VAR_CLEARED_CORE4_UNSPECIFIED
   #include "CddMemMap.h"
    #undef  FR_START_SEC_VAR_CLEARED_CORE4_UNSPECIFIED
    #undef  MEMMAP_ERROR
#elif defined  FR_STOP_SEC_VAR_CLEARED_CORE4_UNSPECIFIED
   #define CDD_STOP_SEC_VAR_CLEARED_CORE4_UNSPECIFIED
   #include "CddMemMap.h"
    #undef  FR_STOP_SEC_VAR_CLEARED_CORE4_UNSPECIFIED
    #undef  MEMMAP_ERROR
      
#elif defined  FR_START_SEC_VAR_CLEARED_CORE4_BOOLEAN
   #define CDD_START_SEC_VAR_CLEARED_CORE4_BOOLEAN
   #include "CddMemMap.h"
    #undef  FR_START_SEC_VAR_CLEARED_CORE4_BOOLEAN
    #undef  MEMMAP_ERROR
#elif defined  FR_STOP_SEC_VAR_CLEARED_CORE4_BOOLEAN
   #define CDD_STOP_SEC_VAR_CLEARED_CORE4_BOOLEAN
   #include "CddMemMap.h"
    #undef  FR_STOP_SEC_VAR_CLEARED_CORE4_BOOLEAN
    #undef  MEMMAP_ERROR
      
#elif defined  FR_START_SEC_VAR_CLEARED_CORE4_8
   #define CDD_START_SEC_VAR_CLEARED_CORE4_8
   #include "CddMemMap.h"
    #undef  FR_START_SEC_VAR_CLEARED_CORE4_8
    #undef  MEMMAP_ERROR
#elif defined  FR_STOP_SEC_VAR_CLEARED_CORE4_8
   #define CDD_STOP_SEC_VAR_CLEARED_CORE4_8
   #include "CddMemMap.h"
    #undef  FR_STOP_SEC_VAR_CLEARED_CORE4_8
    #undef  MEMMAP_ERROR
      
#elif defined  FR_START_SEC_VAR_CLEARED_CORE4_16
   #define CDD_START_SEC_VAR_CLEARED_CORE4_16
   #include "CddMemMap.h"
    #undef  FR_START_SEC_VAR_CLEARED_CORE4_16
    #undef  MEMMAP_ERROR
#elif defined  FR_STOP_SEC_VAR_CLEARED_CORE4_16
   #define CDD_STOP_SEC_VAR_CLEARED_CORE4_16
   #include "CddMemMap.h"
    #undef  FR_STOP_SEC_VAR_CLEARED_CORE4_16
    #undef  MEMMAP_ERROR
      
#elif defined  FR_START_SEC_VAR_CLEARED_CORE4_32
   #define CDD_START_SEC_VAR_CLEARED_CORE4_32
   #include "CddMemMap.h"
    #undef  FR_START_SEC_VAR_CLEARED_CORE4_32
    #undef  MEMMAP_ERROR
#elif defined  FR_STOP_SEC_VAR_CLEARED_CORE4_32
   #define CDD_STOP_SEC_VAR_CLEARED_CORE4_32
   #include "CddMemMap.h"
    #undef  FR_STOP_SEC_VAR_CLEARED_CORE4_32
    #undef  MEMMAP_ERROR
      
#elif defined  FR_START_SEC_VAR_CLEARED_CORE5_UNSPECIFIED
   #define CDD_START_SEC_VAR_CLEARED_CORE5_UNSPECIFIED
   #include "CddMemMap.h"
    #undef  FR_START_SEC_VAR_CLEARED_CORE5_UNSPECIFIED
    #undef  MEMMAP_ERROR
#elif defined  FR_STOP_SEC_VAR_CLEARED_CORE5_UNSPECIFIED
   #define CDD_STOP_SEC_VAR_CLEARED_CORE5_UNSPECIFIED
   #include "CddMemMap.h"
    #undef  FR_STOP_SEC_VAR_CLEARED_CORE5_UNSPECIFIED
    #undef  MEMMAP_ERROR
      
#elif defined  FR_START_SEC_VAR_CLEARED_CORE5_BOOLEAN
   #define CDD_START_SEC_VAR_CLEARED_CORE5_BOOLEAN
   #include "CddMemMap.h"
    #undef  FR_START_SEC_VAR_CLEARED_CORE5_BOOLEAN
    #undef  MEMMAP_ERROR
#elif defined  FR_STOP_SEC_VAR_CLEARED_CORE5_BOOLEAN
   #define CDD_STOP_SEC_VAR_CLEARED_CORE5_BOOLEAN
   #include "CddMemMap.h"
    #undef  FR_STOP_SEC_VAR_CLEARED_CORE5_BOOLEAN
    #undef  MEMMAP_ERROR
      
#elif defined  FR_START_SEC_VAR_CLEARED_CORE5_8
   #define CDD_START_SEC_VAR_CLEARED_CORE5_8
   #include "CddMemMap.h"
    #undef  FR_START_SEC_VAR_CLEARED_CORE5_8
    #undef  MEMMAP_ERROR
#elif defined  FR_STOP_SEC_VAR_CLEARED_CORE5_8
   #define CDD_STOP_SEC_VAR_CLEARED_CORE5_8
   #include "CddMemMap.h"
    #undef  FR_STOP_SEC_VAR_CLEARED_CORE5_8
    #undef  MEMMAP_ERROR
      
#elif defined  FR_START_SEC_VAR_CLEARED_CORE5_16
   #define CDD_START_SEC_VAR_CLEARED_CORE5_16
   #include "CddMemMap.h"
    #undef  FR_START_SEC_VAR_CLEARED_CORE5_16
    #undef  MEMMAP_ERROR
#elif defined  FR_STOP_SEC_VAR_CLEARED_CORE5_16
   #define CDD_STOP_SEC_VAR_CLEARED_CORE5_16
   #include "CddMemMap.h"
    #undef  FR_STOP_SEC_VAR_CLEARED_CORE5_16
    #undef  MEMMAP_ERROR
      
#elif defined  FR_START_SEC_VAR_CLEARED_CORE5_32
   #define CDD_START_SEC_VAR_CLEARED_CORE5_32
   #include "CddMemMap.h"
    #undef  FR_START_SEC_VAR_CLEARED_CORE5_32
    #undef  MEMMAP_ERROR
#elif defined  FR_STOP_SEC_VAR_CLEARED_CORE5_32
   #define CDD_STOP_SEC_VAR_CLEARED_CORE5_32
   #include "CddMemMap.h"
    #undef  FR_STOP_SEC_VAR_CLEARED_CORE5_32
    #undef  MEMMAP_ERROR

/* -------------------------------------------------------------------------- */
/* Calib section initialized from ROM on reset                                */
/* -------------------------------------------------------------------------- */
#elif defined FR_CALIB_START_SEC_CONST_32
  #define  CDD_CALIB_START_SEC_CONST_32
  #include "CddMemMap.h"
   #undef FR_CALIB_START_SEC_CONST_32
   #undef  MEMMAP_ERROR
#elif defined FR_CALIB_STOP_SEC_CONST_32
  #define  CDD_CALIB_STOP_SEC_CONST_32
  #include "CddMemMap.h"
   #undef FR_CALIB_STOP_SEC_CONST_32
   #undef  MEMMAP_ERROR

#elif defined FR_CALIB_START_SEC_CONST_16
  #define  CDD_CALIB_START_SEC_CONST_16
  #include "CddMemMap.h"
	#undef FR_CALIB_START_SEC_CONST_16
   #undef  MEMMAP_ERROR
#elif defined FR_CALIB_STOP_SEC_CONST_16
  #define  CDD_CALIB_STOP_SEC_CONST_16
  #include "CddMemMap.h"
	#undef FR_CALIB_STOP_SEC_CONST_16
   #undef  MEMMAP_ERROR

#elif defined FR_CALIB_START_SEC_CONST_8
  #define  CDD_CALIB_START_SEC_CONST_8
  #include "CddMemMap.h"
	#undef FR_CALIB_START_SEC_CONST_8
   #undef  MEMMAP_ERROR
#elif defined FR_CALIB_STOP_SEC_CONST_8
  #define  CDD_CALIB_STOP_SEC_CONST_8
  #include "CddMemMap.h"
	#undef FR_CALIB_STOP_SEC_CONST_8
   #undef  MEMMAP_ERROR

#elif defined   FR_CALIB_START_SEC_CONST_BOOL
  #define  CDD_CALIB_START_SEC_CONST_BOOL
  #include "CddMemMap.h"
   #undef FR_CALIB_START_SEC_CONST_BOOL
   #undef  MEMMAP_ERROR
#elif defined   FR_CALIB_STOP_SEC_CONST_BOOL
  #define  CDD_CALIB_STOP_SEC_CONST_BOOL
  #include "CddMemMap.h"
   #undef FR_CALIB_STOP_SEC_CONST_BOOL
   #undef  MEMMAP_ERROR

#elif defined FR_CALIB_START_SEC_CONST_UNSPECIFIED
  #define  CDD_CALIB_START_SEC_CONST_UNSPECIFIED
  #include "CddMemMap.h"
	#undef FR_CALIB_START_SEC_CONST_UNSPECIFIED
   #undef  MEMMAP_ERROR
#elif defined FR_CALIB_STOP_SEC_CONST_UNSPECIFIED
  #define  CDD_CALIB_STOP_SEC_CONST_UNSPECIFIED
  #include "CddMemMap.h"
	#undef FR_CALIB_STOP_SEC_CONST_UNSPECIFIED
   #undef  MEMMAP_ERROR

/* -------------------------------------------------------------------------- */
/* ROM fix code                                                               */
/* -------------------------------------------------------------------------- */
#elif defined FR_START_SEC_FIX_CFG_CONST_32
  #pragma section  "FRConst.FixCfg" a
   #undef FR_START_SEC_FIX_CFG_CONST_32
   #undef  MEMMAP_ERROR
#elif defined FR_STOP_SEC_FIX_CFG_CONST_32
  #pragma section
   #undef FR_STOP_SEC_FIX_CFG_CONST_32
   #undef  MEMMAP_ERROR

/* -------------------------------------------------------------------------- */
/* User Config                                                                */
/* -------------------------------------------------------------------------- */



#endif


#if defined MEMMAP_ERROR
   #error MEMMAP-E201 : Bad memory allocation into FR_MemMap.h
#endif


/*------------------------------- end of file --------------------------------*/

