/******************************************************************************/
/*                                                                            */
/* !Layer           : SRVL                                                    */
/*                                                                            */
/* !Component       : GESM                                                     */
/* !Description     : StateFlow of GESM component                              */
/*                                                                            */
/* !File            : GESM_TRA.H                                               */
/*                                                                            */
/* !Scope           : Public                                                  */
/*                                                                            */
/* !Target          : All                                                     */
/*                                                                            */
/* !Vendor          : invt                                                    */
/*                                                                            */
/* Coding language  : C                                                       */
/*                                                                            */
/* COPYRIGHT 2007 invt                                                        */
/* all rights reserved                                                        */
/*                                                                            */
/******************************************************************************/
/** 10/27/22, 09:10:37: generated by Genecode v2.6.0.0                        */
/* From Source Template : GSTFSRV_TRA_H.TPL                                    */
/******************************************************************************/

#ifndef GESM_TRA_H
#define GESM_TRA_H

#include "Std_Types.h"
#include "gesm_dat.h"
#include "gstfsrv_Includes.h"


/******************************************************************************/
/* MACRO FUNCTIONS                                                            */
/******************************************************************************/

/*----------------------------------------------------------------------------*/
/* GESM Stateflow transitions definition                                       */
/*----------------------------------------------------------------------------*/

/* -------- GESM Stateflow ECU_STATE -------- */

/* SCHED_5MS Event */
/* GO2_STARTUP_I Event */


#endif /* GESM_TRA_H */

/*-------------------------------- END OF FILE -------------------------------*/
