/******************************************************************************/
/*                                                                            */
/* !Layer           : SRVL                                                    */
/*                                                                            */
/* !Component       : GESM                                                     */
/* !Description     : StateFlow of GESM component                              */
/*                                                                            */
/* !File            : GESM_DAT.H                                               */
/*                                                                            */
/* !Scope           : Public                                                  */
/*                                                                            */
/* !Target          : All                                                     */
/*                                                                            */
/* !Vendor          : invt                                                    */
/*                                                                            */
/* Coding language  : C                                                       */
/*                                                                            */
/* COPYRIGHT 2007 invt                                                        */
/* all rights reserved                                                        */
/*                                                                            */
/******************************************************************************/
/** 10/27/22, 09:10:37: generated by Genecode v2.6.0.0                        */
/* From Source Template : GSTFSRV_DAT_H.TPL                                    */
/******************************************************************************/

#ifndef GESM_DAT_H
#define GESM_DAT_H

#include "Std_Types.h"
#include "gstfsrv_Includes.h"
#include "gstfsrv_types.h"
#include "gesm.h"
#include "gesm_l.h"


/******************************************************************************/
/* DEFINES                                                                    */
/******************************************************************************/

/*----------------------------------------------------------------------------*/
/* GESM Stateflows configuration                                               */
/*----------------------------------------------------------------------------*/
/* Stateflows :  ECU_STATE <=> GESM_STF0        */
/*----------------------------------------------------------------------------*/


#define GESM_udtSTATEFLOW_NB   1

#define GESM_GSTFSRV_MAIN   GESM_STF0  /* ECU_STATE */

/* GESM_ECU_STATE */

#define GESM_GESM_STF0_VAR            GESM_EcuState
#define GESM_GESM_STF0_INIT_STATE     GESM_ST0  /* STARTUP_I_MODE */
#define GESM_GESM_STF0_NB_STATE       5




/*----------------------------------------------------------------------------*/
/* GESM States declaration                                                   */
/*----------------------------------------------------------------------------*/
#define   GESM_STARTUP_I_MODE     1
#define   GESM_STARTUP_II_MODE     2
#define   GESM_OPERATIONAL_MODE     4
#define   GESM_POWERLATCH_MODE     8
#define   GESM_POWER_OFF_MODE     16


/*----------------------------------------------------------------------------*/
/* GESM States configuration                                                   */
/*----------------------------------------------------------------------------*/

#define GESM_GESM_ST0_VAL     GESM_STARTUP_I_MODE
#define GESM_GESM_ST1_VAL     GESM_STARTUP_II_MODE
#define GESM_GESM_ST2_VAL     GESM_OPERATIONAL_MODE
#define GESM_GESM_ST3_VAL     GESM_POWERLATCH_MODE
#define GESM_GESM_ST4_VAL     GESM_POWER_OFF_MODE





/*----------------------------------------------------------------------------*/
/* GESM Events configuration                                                   */
/*----------------------------------------------------------------------------*/
#define GESM_ON_SCHED_5MS_FUNC          GESM_vidOnGESM_EV0
#define GESM_ON_GO2_STARTUP_I_FUNC          GESM_vidOnGESM_EV1

#define GO2_STARTUP_I_EVENT            (uint16)(1 << 0)
#define GO2_STARTUP_II_EVENT            (uint16)(1 << 1)
#define GO2_OPERATIONAL_EVENT            (uint16)(1 << 2)
#define GO2_POWERLATCH_EVENT            (uint16)(1 << 3)
#define GO2_POWER_OFF_EVENT            (uint16)(1 << 4)

#define GGO2_STARTUP_I_EVENT_ACTION          GESM_StpIState = GESM_SFT_STATE_1;
#define GGO2_STARTUP_II_EVENT_ACTION          GESM_StpIINfState = GESM_SFT_STATE_1; GESM_StpIIFtState = GESM_SFT_STATE_1; GESM_PwrLFtState = GESM_SFT_STATE_1;
#define GGO2_OPERATIONAL_EVENT_ACTION          GESM_OpNfState = GESM_SFT_STATE_1; GESM_OpFtState = GESM_SFT_STATE_1;
#define GGO2_POWERLATCH_EVENT_ACTION          GESM_PwrLNfState = GESM_SFT_STATE_1; GESM_PwrLFtState = GESM_SFT_STATE_1;
#define GGO2_POWER_OFF_EVENT_ACTION          GESM_PwrLNfState = GESM_SFT_STATE_15;

#define GESM_EXEC_OUT_EVENT_FUNC       GESM_vidExecOutEvent
#define GESM_OUT_EVENT_CARRIER    GESM_bfOutEventCarrier

/*----------------------------------------------------------------------------*/
/* GESM common data                                                            */
/*----------------------------------------------------------------------------*/

#define GESM_ON_EVENT_NO_ACTION   GESM_vidNoAction

/* Transition function for stateflow ECU_STATE on event SCHED_5MS */
#define GESM_GESM_STF0_ON_GESM_EV0_TRANS_PTR   GESM_pfTransGESM_STF0OnGESM_EV0Ptr


/* Transition function for stateflow ECU_STATE on event GO2_STARTUP_I */
#define GESM_GESM_STF0_ON_GESM_EV1_TRANS_PTR   GESM_pfTransGESM_STF0OnGESM_EV1Ptr


/* During function for stateflow ECU_STATE on event SCHED_5MS */
#define GESM_GESM_STF0_ON_GESM_EV0_DURING_PTR   GESM_pfDuringGESM_STF0OnGESM_EV0Ptr


/* During function for stateflow ECU_STATE on event GO2_STARTUP_I */
#define GESM_GESM_STF0_ON_GESM_EV1_DURING_PTR   GESM_pfDuringGESM_STF0OnGESM_EV1Ptr





/*----------------------------------------------------------------------------*/
/* GESM entry functions                                                        */
/*----------------------------------------------------------------------------*/

#define GESM_GESM_ST0_ENTRY             GESM_vidEntryGESM_ST0   /* GESM_STARTUP_I_MODE */
#define GESM_GESM_ST1_ENTRY             GESM_vidEntryGESM_ST1   /* GESM_STARTUP_II_MODE */
#define GESM_GESM_ST2_ENTRY             GESM_vidEntryGESM_ST2   /* GESM_OPERATIONAL_MODE */
#define GESM_GESM_ST3_ENTRY             GESM_vidEntryGESM_ST3   /* GESM_POWERLATCH_MODE */
#define GESM_GESM_ST4_ENTRY             GESM_vidEntryGESM_ST4   /* GESM_POWER_OFF_MODE */


/*----------------------------------------------------------------------------*/
/* GESM during functions                                                       */
/*----------------------------------------------------------------------------*/

#define GESM_GESM_ST0_ON_GESM_EV0_DURING             GESM_vidDuringGESM_ST0OnGESM_EV0   /* During function for STARTUP_I_MODE on event SCHED_5MS */
#define GESM_GESM_ST0_ON_GESM_EV1_DURING             GESM_vidDuringGESM_ST0OnGESM_EV1   /* During function for STARTUP_I_MODE on event GO2_STARTUP_I */

#define GESM_GESM_ST1_ON_GESM_EV0_DURING             GESM_vidDuringGESM_ST1OnGESM_EV0   /* During function for STARTUP_II_MODE on event SCHED_5MS */
#define GESM_GESM_ST1_ON_GESM_EV1_DURING             GESM_vidDuringGESM_ST1OnGESM_EV1   /* During function for STARTUP_II_MODE on event GO2_STARTUP_I */

#define GESM_GESM_ST2_ON_GESM_EV0_DURING             GESM_vidDuringGESM_ST2OnGESM_EV0   /* During function for OPERATIONAL_MODE on event SCHED_5MS */
#define GESM_GESM_ST2_ON_GESM_EV1_DURING             GESM_vidDuringGESM_ST2OnGESM_EV1   /* During function for OPERATIONAL_MODE on event GO2_STARTUP_I */

#define GESM_GESM_ST3_ON_GESM_EV0_DURING             GESM_vidDuringGESM_ST3OnGESM_EV0   /* During function for POWERLATCH_MODE on event SCHED_5MS */
#define GESM_GESM_ST3_ON_GESM_EV1_DURING             GESM_vidDuringGESM_ST3OnGESM_EV1   /* During function for POWERLATCH_MODE on event GO2_STARTUP_I */

#define GESM_GESM_ST4_ON_GESM_EV0_DURING             GESM_vidDuringGESM_ST4OnGESM_EV0   /* During function for POWER_OFF_MODE on event SCHED_5MS */
#define GESM_GESM_ST4_ON_GESM_EV1_DURING             GESM_vidDuringGESM_ST4OnGESM_EV1   /* During function for POWER_OFF_MODE on event GO2_STARTUP_I */



/*----------------------------------------------------------------------------*/
/* GESM transition functions                                                   */
/*----------------------------------------------------------------------------*/

#define GESM_GESM_ST0_ON_GESM_EV0_TRANS         GESM_vidFromGESM_ST0OnGESM_EV0/* Transition function from STARTUP_I_MODE on event SCHED_5MS */
#define GESM_GESM_ST1_ON_GESM_EV0_TRANS         GESM_vidFromGESM_ST1OnGESM_EV0/* Transition function from STARTUP_II_MODE on event SCHED_5MS */
#define GESM_GESM_ST2_ON_GESM_EV0_TRANS         GESM_vidFromGESM_ST2OnGESM_EV0/* Transition function from OPERATIONAL_MODE on event SCHED_5MS */
#define GESM_GESM_ST3_ON_GESM_EV0_TRANS         GESM_vidFromGESM_ST3OnGESM_EV0/* Transition function from POWERLATCH_MODE on event SCHED_5MS */
#define GESM_GESM_ST4_ON_GESM_EV0_TRANS         GESM_ON_EVENT_NO_ACTION      /* Transition function from POWER_OFF_MODE on event SCHED_5MS */

#define GESM_GESM_ST0_ON_GESM_EV1_TRANS         GESM_ON_EVENT_NO_ACTION      /* Transition function from STARTUP_I_MODE on event GO2_STARTUP_I */
#define GESM_GESM_ST1_ON_GESM_EV1_TRANS         GESM_vidFromGESM_ST1OnGESM_EV1/* Transition function from STARTUP_II_MODE on event GO2_STARTUP_I */
#define GESM_GESM_ST2_ON_GESM_EV1_TRANS         GESM_vidFromGESM_ST2OnGESM_EV1/* Transition function from OPERATIONAL_MODE on event GO2_STARTUP_I */
#define GESM_GESM_ST3_ON_GESM_EV1_TRANS         GESM_vidFromGESM_ST3OnGESM_EV1/* Transition function from POWERLATCH_MODE on event GO2_STARTUP_I */
#define GESM_GESM_ST4_ON_GESM_EV1_TRANS         GESM_vidFromGESM_ST4OnGESM_EV1/* Transition function from POWER_OFF_MODE on event GO2_STARTUP_I */



/*----------------------------------------------------------------------------*/
/* GESM tempo data                                                             */
/*----------------------------------------------------------------------------*/
#define GESM_TEMPO_GESM_POWERLATCH_TEMPO_VAR     GESM_u16PowerLatchTempo
#define GESM_TEMPO_GESM_POWERLATCH_TEMPO_INIT    GESM_u16PowerLatchTempoC


/******************************************************************************/
/* DATA DECLARATION                                                           */
/******************************************************************************/

#define GSTFSRV_START_SEC_CODE
#include "MemMap.h"

FUNC (void, GSTFSRV_CODE) GESM_vidOnGESM_EV0(void);
FUNC (void, GSTFSRV_CODE) GESM_vidOnGESM_EV1(void);

FUNC(void, GSTFSRV_CODE) GESM_vidExecOutEvent(uint16 bfCarrier);

FUNC (void, GSTFSRV_CODE) GESM_vidNoAction(void);

FUNC (void, GSTFSRV_CODE) GESM_vidEntryGESM_ST0(void);
FUNC (void, GSTFSRV_CODE) GESM_vidEntryGESM_ST1(void);
FUNC (void, GSTFSRV_CODE) GESM_vidEntryGESM_ST2(void);
FUNC (void, GSTFSRV_CODE) GESM_vidEntryGESM_ST3(void);
FUNC (void, GSTFSRV_CODE) GESM_vidEntryGESM_ST4(void);


FUNC (void, GSTFSRV_CODE) GESM_vidDuringGESM_ST0OnGESM_EV0(void);
FUNC (void, GSTFSRV_CODE) GESM_vidDuringGESM_ST0OnGESM_EV1(void);

FUNC (void, GSTFSRV_CODE) GESM_vidDuringGESM_ST1OnGESM_EV0(void);
FUNC (void, GSTFSRV_CODE) GESM_vidDuringGESM_ST1OnGESM_EV1(void);

FUNC (void, GSTFSRV_CODE) GESM_vidDuringGESM_ST2OnGESM_EV0(void);
FUNC (void, GSTFSRV_CODE) GESM_vidDuringGESM_ST2OnGESM_EV1(void);

FUNC (void, GSTFSRV_CODE) GESM_vidDuringGESM_ST3OnGESM_EV0(void);
FUNC (void, GSTFSRV_CODE) GESM_vidDuringGESM_ST3OnGESM_EV1(void);

FUNC (void, GSTFSRV_CODE) GESM_vidDuringGESM_ST4OnGESM_EV0(void);
FUNC (void, GSTFSRV_CODE) GESM_vidDuringGESM_ST4OnGESM_EV1(void);



FUNC (void, GSTFSRV_CODE) GESM_vidFromGESM_ST0OnGESM_EV0(void);
FUNC (void, GSTFSRV_CODE) GESM_vidFromGESM_ST1OnGESM_EV0(void);
FUNC (void, GSTFSRV_CODE) GESM_vidFromGESM_ST2OnGESM_EV0(void);
FUNC (void, GSTFSRV_CODE) GESM_vidFromGESM_ST3OnGESM_EV0(void);

FUNC (void, GSTFSRV_CODE) GESM_vidFromGESM_ST1OnGESM_EV1(void);
FUNC (void, GSTFSRV_CODE) GESM_vidFromGESM_ST2OnGESM_EV1(void);
FUNC (void, GSTFSRV_CODE) GESM_vidFromGESM_ST3OnGESM_EV1(void);
FUNC (void, GSTFSRV_CODE) GESM_vidFromGESM_ST4OnGESM_EV1(void);


#define GSTFSRV_STOP_SEC_CODE
#include "MemMap.h"


#define GSTFSRV_START_SEC_VAR_16BIT
#include "MemMap.h"

extern VAR (uint16, GSTFSRV_VAR) GESM_bfOutEventCarrier;

#define GSTFSRV_STOP_SEC_VAR_16BIT
#include "MemMap.h"


#define GSTFSRV_START_SEC_VAR_UNSPECIFIED
#include "MemMap.h"

extern VAR (GSTFSRV_tpfFunctionPointerType, GSTFSRV_VAR) GESM_pfTransGESM_STF0OnGESM_EV0Ptr;

extern VAR (GSTFSRV_tpfFunctionPointerType, GSTFSRV_VAR) GESM_pfTransGESM_STF0OnGESM_EV1Ptr;

extern VAR (GSTFSRV_tpfFunctionPointerType, GSTFSRV_VAR) GESM_pfDuringGESM_STF0OnGESM_EV0Ptr;

extern VAR (GSTFSRV_tpfFunctionPointerType, GSTFSRV_VAR) GESM_pfDuringGESM_STF0OnGESM_EV1Ptr;



#define GSTFSRV_STOP_SEC_VAR_UNSPECIFIED
#include "MemMap.h"

#endif /* GESM_DAT_H */

/*------------------------------ END OF FILE ---------------------------------*/
