/******************************************************************************/
/*                                                                            */
/* !Layer           : STD                                                     */
/*                                                                            */
/* !Component       : MEMMAP                                                  */
/* !Description     : MEMMAP Configuration                                    */
/*                                                                            */
/* !File            : HARD_MEMMAP.H                                          */
/*                                                                            */
/* !Scope           : Public                                                  */
/*                                                                            */
/* !Target          :                                                         */
/*                                                                            */
/* !Vendor          : invt                                                    */
/*                                                                            */
/* Coding language  : C                                                       */
/*                                                                            */
/* COPYRIGHT 2009 invt                                                        */
/* all rights reserved                                                        */
/*                                                                            */
/******************************************************************************/
/* SVN Information                                                           */
/* $Archive::                                                                $*/
/* $Revision::            $$Author::                  $$Date::               $*/
/******************************************************************************/
/* 10/27/22, 09:10:33: generated by Genecode  v2.6.0.0                        */
/* From Source Template : MSN_MEMMAP_H.TPL                                    */
/******************************************************************************/



/******************************************************************************/
/*          MEMMAP selected mode:  SAFE                                       */
/******************************************************************************/
#define MEMMAP_ERROR

/* The following if is used only due to automatic generation */
#if !defined MEMMAP_ERROR

/* Project section mappings */
/* !Comment: HARD Section allocation */
#elif defined   HARD_START_SEC_CODE
   #undef  HARD_START_SEC_CODE
   #define START_SEC_CODE_SECTION
#elif defined   HARD_STOP_SEC_CODE
   #undef  HARD_STOP_SEC_CODE
   #define STOP_SEC_CODE_SECTION

#elif defined   HARD_START_SEC_CALIB_UNSPECIFIED
   #undef  HARD_START_SEC_CALIB_UNSPECIFIED
   #define START_SEC_CALIB_UNSPECIFIED_SECTION
#elif defined   HARD_STOP_SEC_CALIB_UNSPECIFIED
   #undef  HARD_STOP_SEC_CALIB_UNSPECIFIED
   #define STOP_SEC_CALIB_UNSPECIFIED_SECTION

#elif defined   HARD_START_SEC_VAR_UNSPECIFIED
   #undef  HARD_START_SEC_VAR_UNSPECIFIED
   #define START_SEC_VAR_UNSPECIFIED_SECTION
#elif defined   HARD_STOP_SEC_VAR_UNSPECIFIED
   #undef  HARD_STOP_SEC_VAR_UNSPECIFIED
   #define STOP_SEC_VAR_UNSPECIFIED_SECTION

#elif defined   HARD_START_SEC_CONST_UNSPECIFIED
   #undef  HARD_START_SEC_CONST_UNSPECIFIED
   #define START_SEC_CONST_UNSPECIFIED_SECTION
#elif defined   HARD_STOP_SEC_CONST_UNSPECIFIED
   #undef  HARD_STOP_SEC_CONST_UNSPECIFIED
   #define STOP_SEC_CONST_UNSPECIFIED_SECTION

#elif defined HARD_CALIB_START_SEC_CONST_32
  #define  CALIB_START_SEC_CONST_32
  #include "MemMap.h"
   #undef HARD_CALIB_START_SEC_CONST_32
   #undef  MEMMAP_ERROR
#elif defined HARD_CALIB_STOP_SEC_CONST_32
  #define  CALIB_STOP_SEC_CONST_32
  #include "MemMap.h"
   #undef HARD_CALIB_STOP_SEC_CONST_32
   #undef  MEMMAP_ERROR
            
#elif defined HARD_CALIB_START_SEC_CONST_16
  #define  CALIB_START_SEC_CONST_16
  #include "MemMap.h"
	#undef HARD_CALIB_START_SEC_CONST_16
   #undef  MEMMAP_ERROR
#elif defined HARD_CALIB_STOP_SEC_CONST_16
  #define  CALIB_STOP_SEC_CONST_16
  #include "MemMap.h"
	#undef HARD_CALIB_STOP_SEC_CONST_16
   #undef  MEMMAP_ERROR
            
#elif defined HARD_CALIB_START_SEC_CONST_8
  #define  CALIB_START_SEC_CONST_8
  #include "MemMap.h"
	#undef HARD_CALIB_START_SEC_CONST_8
   #undef  MEMMAP_ERROR
#elif defined HARD_CALIB_STOP_SEC_CONST_8
  #define  CALIB_STOP_SEC_CONST_8
  #include "MemMap.h"
	#undef HARD_CALIB_STOP_SEC_CONST_8
   #undef  MEMMAP_ERROR
         
#elif defined   HARD_CALIB_START_SEC_CONST_BOOL
  #define  CALIB_START_SEC_CONST_BOOL
  #include "MemMap.h"
   #undef HARD_CALIB_START_SEC_CONST_BOOL
   #undef  MEMMAP_ERROR
#elif defined   HARD_CALIB_STOP_SEC_CONST_BOOL
  #define  CALIB_STOP_SEC_CONST_BOOL
  #include "MemMap.h"
   #undef HARD_CALIB_STOP_SEC_CONST_BOOL
   #undef  MEMMAP_ERROR
         
#elif defined HARD_CALIB_START_SEC_CONST_UNSPECIFIED
  #define  CALIB_START_SEC_CONST_UNSPECIFIED
  #include "MemMap.h"
	#undef HARD_CALIB_START_SEC_CONST_UNSPECIFIED
   #undef  MEMMAP_ERROR
#elif defined HARD_CALIB_STOP_SEC_CONST_UNSPECIFIED
  #define  CALIB_STOP_SEC_CONST_UNSPECIFIED
  #include "MemMap.h"
	#undef HARD_CALIB_STOP_SEC_CONST_UNSPECIFIED
   #undef  MEMMAP_ERROR


#endif

/* ECU specific section mappings */
#ifndef MEMMAP_START_DONE

/* The following if is used only due to automatic generation */

#if FALSE
/* !Comment: SEC_CODE Start Section treatment */
   #elif defined   START_SEC_CODE_SECTION
	  

      #pragma section ".text" ax

      #undef  MEMMAP_ERROR
      #define MEMMAP_START_DONE

/* !Comment: SEC_CALIB_UNSPECIFIED Start Section treatment */
   #elif defined   START_SEC_CALIB_UNSPECIFIED_SECTION
	  

      #pragma section ".calib" a

      #undef  MEMMAP_ERROR
      #define MEMMAP_START_DONE

/* !Comment: SEC_VAR_UNSPECIFIED Start Section treatment */
   #elif defined   START_SEC_VAR_UNSPECIFIED_SECTION
	  
      #undef  MEMMAP_ERROR
      #define MEMMAP_START_DONE

/* !Comment: SEC_CONST_UNSPECIFIED Start Section treatment */
   #elif defined   START_SEC_CONST_UNSPECIFIED_SECTION
	  

      #pragma section ".const" a

      #undef  MEMMAP_ERROR
      #define MEMMAP_START_DONE


   #endif

#else   /* if MEMMAP_START_DONE is not defined */

/* The following if is used only due to automatic generation */

#if FALSE
/* !Comment: SEC_CODE Stop Section treatment */
   #elif defined   STOP_SEC_CODE_SECTION && defined  START_SEC_CODE_SECTION
	  

      #pragma section

      #undef START_SEC_CODE_SECTION
      #undef STOP_SEC_CODE_SECTION
      #undef MEMMAP_ERROR
      #undef MEMMAP_START_DONE

/* !Comment: SEC_CALIB_UNSPECIFIED Stop Section treatment */
   #elif defined   STOP_SEC_CALIB_UNSPECIFIED_SECTION && defined  START_SEC_CALIB_UNSPECIFIED_SECTION
	  

      #pragma section

      #undef START_SEC_CALIB_UNSPECIFIED_SECTION
      #undef STOP_SEC_CALIB_UNSPECIFIED_SECTION
      #undef MEMMAP_ERROR
      #undef MEMMAP_START_DONE

/* !Comment: SEC_VAR_UNSPECIFIED Stop Section treatment */
   #elif defined   STOP_SEC_VAR_UNSPECIFIED_SECTION && defined  START_SEC_VAR_UNSPECIFIED_SECTION
	  
      #undef START_SEC_VAR_UNSPECIFIED_SECTION
      #undef STOP_SEC_VAR_UNSPECIFIED_SECTION
      #undef MEMMAP_ERROR
      #undef MEMMAP_START_DONE

/* !Comment: SEC_CONST_UNSPECIFIED Stop Section treatment */
   #elif defined   STOP_SEC_CONST_UNSPECIFIED_SECTION && defined  START_SEC_CONST_UNSPECIFIED_SECTION
	  

      #pragma section

      #undef START_SEC_CONST_UNSPECIFIED_SECTION
      #undef STOP_SEC_CONST_UNSPECIFIED_SECTION
      #undef MEMMAP_ERROR
      #undef MEMMAP_START_DONE


   #endif
#endif

#if defined MEMMAP_ERROR
   #error MEMMAP-E201 : Bad memory allocation into HARD_MemMap.h
#endif


/*------------------------------- end of file --------------------------------*/

