/******************************************************************************/
/*                                                                            */
/* !Layer           : SRVL                                                    */
/*                                                                            */
/* !Component       : OESM                                                     */
/* !Description     : StateFlow of OESM component                              */
/*                                                                            */
/* !File            : OESM_DAT.H                                               */
/*                                                                            */
/* !Scope           : Public                                                  */
/*                                                                            */
/* !Target          : All                                                     */
/*                                                                            */
/* !Vendor          : invt                                                    */
/*                                                                            */
/* Coding language  : C                                                       */
/*                                                                            */
/* COPYRIGHT 2007 invt                                                        */
/* all rights reserved                                                        */
/*                                                                            */
/******************************************************************************/
/** 10/27/22, 09:10:37: generated by Genecode v2.6.0.0                        */
/* From Source Template : OSTFSRV_DAT_H.TPL                                    */
/******************************************************************************/

#ifndef OESM_DAT_H
#define OESM_DAT_H

#include "Std_Types.h"
#include "ostfsrv_Includes.h"
#include "ostfsrv_types.h"
#include "oesm.h"
#include "oesm_l.h"


/******************************************************************************/
/* DEFINES                                                                    */
/******************************************************************************/

/*----------------------------------------------------------------------------*/
/* OESM Stateflows configuration                                               */
/*----------------------------------------------------------------------------*/
/* Stateflows :  ECU_STATE <=> OESM_STF0        */
/*----------------------------------------------------------------------------*/


#define OESM_udtSTATEFLOW_NB   1

#define OESM_OSTFSRV_MAIN   OESM_STF0  /* ECU_STATE */

/* OESM_ECU_STATE */

#define OESM_OESM_STF0_VAR            OESM_EcuState
#define OESM_OESM_STF0_INIT_STATE     OESM_ST0  /* STARTUP_I_MODE */
#define OESM_OESM_STF0_NB_STATE       5




/*----------------------------------------------------------------------------*/
/* OESM States declaration                                                   */
/*----------------------------------------------------------------------------*/
#define   OESM_STARTUP_I_MODE     1
#define   OESM_STARTUP_II_MODE     2
#define   OESM_OPERATIONAL_MODE     4
#define   OESM_POWERLATCH_MODE     8
#define   OESM_POWER_OFF_MODE     16


/*----------------------------------------------------------------------------*/
/* OESM States configuration                                                   */
/*----------------------------------------------------------------------------*/

#define OESM_OESM_ST0_VAL     OESM_STARTUP_I_MODE
#define OESM_OESM_ST1_VAL     OESM_STARTUP_II_MODE
#define OESM_OESM_ST2_VAL     OESM_OPERATIONAL_MODE
#define OESM_OESM_ST3_VAL     OESM_POWERLATCH_MODE
#define OESM_OESM_ST4_VAL     OESM_POWER_OFF_MODE





/*----------------------------------------------------------------------------*/
/* OESM Events configuration                                                   */
/*----------------------------------------------------------------------------*/
#define OESM_ON_SCHED_5MS_FUNC          OESM_vidOnOESM_EV0
#define OESM_ON_GO2_STARTUP_I_FUNC          OESM_vidOnOESM_EV1

#define GO2_STARTUP_I_EVENT            (uint16)(1 << 0)
#define GO2_STARTUP_II_EVENT            (uint16)(1 << 1)
#define GO2_OPERATIONAL_EVENT            (uint16)(1 << 2)
#define GO2_POWERLATCH_EVENT            (uint16)(1 << 3)
#define GO2_POWER_OFF_EVENT            (uint16)(1 << 4)

#define GGO2_STARTUP_I_EVENT_ACTION          OESM_StpIState = OESM_SFT_STATE_1;
#define GGO2_STARTUP_II_EVENT_ACTION          OESM_StpIINfState = OESM_SFT_STATE_1; OESM_StpIIFtState = OESM_SFT_STATE_1; OESM_PwrLFtState = OESM_SFT_STATE_1;
#define GGO2_OPERATIONAL_EVENT_ACTION          OESM_OpNfState = OESM_SFT_STATE_1; OESM_OpFtState = OESM_SFT_STATE_1;
#define GGO2_POWERLATCH_EVENT_ACTION          OESM_PwrLNfState = OESM_SFT_STATE_1; OESM_PwrLFtState = OESM_SFT_STATE_1;
#define GGO2_POWER_OFF_EVENT_ACTION          OESM_PwrLNfState = OESM_SFT_STATE_15;

#define OESM_EXEC_OUT_EVENT_FUNC       OESM_vidExecOutEvent
#define OESM_OUT_EVENT_CARRIER    OESM_bfOutEventCarrier

/*----------------------------------------------------------------------------*/
/* OESM common data                                                            */
/*----------------------------------------------------------------------------*/

#define OESM_ON_EVENT_NO_ACTION   OESM_vidNoAction

/* Transition function for stateflow ECU_STATE on event SCHED_5MS */
#define OESM_OESM_STF0_ON_OESM_EV0_TRANS_PTR   OESM_pfTransOESM_STF0OnOESM_EV0Ptr


/* Transition function for stateflow ECU_STATE on event GO2_STARTUP_I */
#define OESM_OESM_STF0_ON_OESM_EV1_TRANS_PTR   OESM_pfTransOESM_STF0OnOESM_EV1Ptr


/* During function for stateflow ECU_STATE on event SCHED_5MS */
#define OESM_OESM_STF0_ON_OESM_EV0_DURING_PTR   OESM_pfDuringOESM_STF0OnOESM_EV0Ptr


/* During function for stateflow ECU_STATE on event GO2_STARTUP_I */
#define OESM_OESM_STF0_ON_OESM_EV1_DURING_PTR   OESM_pfDuringOESM_STF0OnOESM_EV1Ptr





/*----------------------------------------------------------------------------*/
/* OESM entry functions                                                        */
/*----------------------------------------------------------------------------*/

#define OESM_OESM_ST0_ENTRY             OESM_vidEntryOESM_ST0   /* OESM_STARTUP_I_MODE */
#define OESM_OESM_ST1_ENTRY             OESM_vidEntryOESM_ST1   /* OESM_STARTUP_II_MODE */
#define OESM_OESM_ST2_ENTRY             OESM_vidEntryOESM_ST2   /* OESM_OPERATIONAL_MODE */
#define OESM_OESM_ST3_ENTRY             OESM_vidEntryOESM_ST3   /* OESM_POWERLATCH_MODE */
#define OESM_OESM_ST4_ENTRY             OESM_vidEntryOESM_ST4   /* OESM_POWER_OFF_MODE */


/*----------------------------------------------------------------------------*/
/* OESM during functions                                                       */
/*----------------------------------------------------------------------------*/

#define OESM_OESM_ST0_ON_OESM_EV0_DURING             OESM_vidDuringOESM_ST0OnOESM_EV0   /* During function for STARTUP_I_MODE on event SCHED_5MS */
#define OESM_OESM_ST0_ON_OESM_EV1_DURING             OESM_vidDuringOESM_ST0OnOESM_EV1   /* During function for STARTUP_I_MODE on event GO2_STARTUP_I */

#define OESM_OESM_ST1_ON_OESM_EV0_DURING             OESM_vidDuringOESM_ST1OnOESM_EV0   /* During function for STARTUP_II_MODE on event SCHED_5MS */
#define OESM_OESM_ST1_ON_OESM_EV1_DURING             OESM_vidDuringOESM_ST1OnOESM_EV1   /* During function for STARTUP_II_MODE on event GO2_STARTUP_I */

#define OESM_OESM_ST2_ON_OESM_EV0_DURING             OESM_vidDuringOESM_ST2OnOESM_EV0   /* During function for OPERATIONAL_MODE on event SCHED_5MS */
#define OESM_OESM_ST2_ON_OESM_EV1_DURING             OESM_vidDuringOESM_ST2OnOESM_EV1   /* During function for OPERATIONAL_MODE on event GO2_STARTUP_I */

#define OESM_OESM_ST3_ON_OESM_EV0_DURING             OESM_vidDuringOESM_ST3OnOESM_EV0   /* During function for POWERLATCH_MODE on event SCHED_5MS */
#define OESM_OESM_ST3_ON_OESM_EV1_DURING             OESM_vidDuringOESM_ST3OnOESM_EV1   /* During function for POWERLATCH_MODE on event GO2_STARTUP_I */

#define OESM_OESM_ST4_ON_OESM_EV0_DURING             OESM_vidDuringOESM_ST4OnOESM_EV0   /* During function for POWER_OFF_MODE on event SCHED_5MS */
#define OESM_OESM_ST4_ON_OESM_EV1_DURING             OESM_vidDuringOESM_ST4OnOESM_EV1   /* During function for POWER_OFF_MODE on event GO2_STARTUP_I */



/*----------------------------------------------------------------------------*/
/* OESM transition functions                                                   */
/*----------------------------------------------------------------------------*/

#define OESM_OESM_ST0_ON_OESM_EV0_TRANS         OESM_vidFromOESM_ST0OnOESM_EV0/* Transition function from STARTUP_I_MODE on event SCHED_5MS */
#define OESM_OESM_ST1_ON_OESM_EV0_TRANS         OESM_vidFromOESM_ST1OnOESM_EV0/* Transition function from STARTUP_II_MODE on event SCHED_5MS */
#define OESM_OESM_ST2_ON_OESM_EV0_TRANS         OESM_vidFromOESM_ST2OnOESM_EV0/* Transition function from OPERATIONAL_MODE on event SCHED_5MS */
#define OESM_OESM_ST3_ON_OESM_EV0_TRANS         OESM_vidFromOESM_ST3OnOESM_EV0/* Transition function from POWERLATCH_MODE on event SCHED_5MS */
#define OESM_OESM_ST4_ON_OESM_EV0_TRANS         OESM_ON_EVENT_NO_ACTION      /* Transition function from POWER_OFF_MODE on event SCHED_5MS */

#define OESM_OESM_ST0_ON_OESM_EV1_TRANS         OESM_ON_EVENT_NO_ACTION      /* Transition function from STARTUP_I_MODE on event GO2_STARTUP_I */
#define OESM_OESM_ST1_ON_OESM_EV1_TRANS         OESM_vidFromOESM_ST1OnOESM_EV1/* Transition function from STARTUP_II_MODE on event GO2_STARTUP_I */
#define OESM_OESM_ST2_ON_OESM_EV1_TRANS         OESM_vidFromOESM_ST2OnOESM_EV1/* Transition function from OPERATIONAL_MODE on event GO2_STARTUP_I */
#define OESM_OESM_ST3_ON_OESM_EV1_TRANS         OESM_vidFromOESM_ST3OnOESM_EV1/* Transition function from POWERLATCH_MODE on event GO2_STARTUP_I */
#define OESM_OESM_ST4_ON_OESM_EV1_TRANS         OESM_vidFromOESM_ST4OnOESM_EV1/* Transition function from POWER_OFF_MODE on event GO2_STARTUP_I */



/*----------------------------------------------------------------------------*/
/* OESM tempo data                                                             */
/*----------------------------------------------------------------------------*/
#define OESM_TEMPO_OESM_POWERLATCH_TEMPO_VAR     OESM_u16PowerLatchTempo
#define OESM_TEMPO_OESM_POWERLATCH_TEMPO_INIT    OESM_u16PowerLatchTempoC


/******************************************************************************/
/* DATA DECLARATION                                                           */
/******************************************************************************/

#define OSTFSRV_START_SEC_CODE
#include "MemMap.h"

FUNC (void, OSTFSRV_CODE) OESM_vidOnOESM_EV0(void);
FUNC (void, OSTFSRV_CODE) OESM_vidOnOESM_EV1(void);

FUNC(void, OSTFSRV_CODE) OESM_vidExecOutEvent(uint16 bfCarrier);

FUNC (void, OSTFSRV_CODE) OESM_vidNoAction(void);

FUNC (void, OSTFSRV_CODE) OESM_vidEntryOESM_ST0(void);
FUNC (void, OSTFSRV_CODE) OESM_vidEntryOESM_ST1(void);
FUNC (void, OSTFSRV_CODE) OESM_vidEntryOESM_ST2(void);
FUNC (void, OSTFSRV_CODE) OESM_vidEntryOESM_ST3(void);
FUNC (void, OSTFSRV_CODE) OESM_vidEntryOESM_ST4(void);


FUNC (void, OSTFSRV_CODE) OESM_vidDuringOESM_ST0OnOESM_EV0(void);
FUNC (void, OSTFSRV_CODE) OESM_vidDuringOESM_ST0OnOESM_EV1(void);

FUNC (void, OSTFSRV_CODE) OESM_vidDuringOESM_ST1OnOESM_EV0(void);
FUNC (void, OSTFSRV_CODE) OESM_vidDuringOESM_ST1OnOESM_EV1(void);

FUNC (void, OSTFSRV_CODE) OESM_vidDuringOESM_ST2OnOESM_EV0(void);
FUNC (void, OSTFSRV_CODE) OESM_vidDuringOESM_ST2OnOESM_EV1(void);

FUNC (void, OSTFSRV_CODE) OESM_vidDuringOESM_ST3OnOESM_EV0(void);
FUNC (void, OSTFSRV_CODE) OESM_vidDuringOESM_ST3OnOESM_EV1(void);

FUNC (void, OSTFSRV_CODE) OESM_vidDuringOESM_ST4OnOESM_EV0(void);
FUNC (void, OSTFSRV_CODE) OESM_vidDuringOESM_ST4OnOESM_EV1(void);



FUNC (void, OSTFSRV_CODE) OESM_vidFromOESM_ST0OnOESM_EV0(void);
FUNC (void, OSTFSRV_CODE) OESM_vidFromOESM_ST1OnOESM_EV0(void);
FUNC (void, OSTFSRV_CODE) OESM_vidFromOESM_ST2OnOESM_EV0(void);
FUNC (void, OSTFSRV_CODE) OESM_vidFromOESM_ST3OnOESM_EV0(void);

FUNC (void, OSTFSRV_CODE) OESM_vidFromOESM_ST1OnOESM_EV1(void);
FUNC (void, OSTFSRV_CODE) OESM_vidFromOESM_ST2OnOESM_EV1(void);
FUNC (void, OSTFSRV_CODE) OESM_vidFromOESM_ST3OnOESM_EV1(void);
FUNC (void, OSTFSRV_CODE) OESM_vidFromOESM_ST4OnOESM_EV1(void);


#define OSTFSRV_STOP_SEC_CODE
#include "MemMap.h"


#define OSTFSRV_START_SEC_VAR_16BIT
#include "MemMap.h"

extern VAR (uint16, OSTFSRV_VAR) OESM_bfOutEventCarrier;

#define OSTFSRV_STOP_SEC_VAR_16BIT
#include "MemMap.h"


#define OSTFSRV_START_SEC_VAR_UNSPECIFIED
#include "MemMap.h"

extern VAR (OSTFSRV_tpfFunctionPointerType, OSTFSRV_VAR) OESM_pfTransOESM_STF0OnOESM_EV0Ptr;

extern VAR (OSTFSRV_tpfFunctionPointerType, OSTFSRV_VAR) OESM_pfTransOESM_STF0OnOESM_EV1Ptr;

extern VAR (OSTFSRV_tpfFunctionPointerType, OSTFSRV_VAR) OESM_pfDuringOESM_STF0OnOESM_EV0Ptr;

extern VAR (OSTFSRV_tpfFunctionPointerType, OSTFSRV_VAR) OESM_pfDuringOESM_STF0OnOESM_EV1Ptr;



#define OSTFSRV_STOP_SEC_VAR_UNSPECIFIED
#include "MemMap.h"

#endif /* OESM_DAT_H */

/*------------------------------ END OF FILE ---------------------------------*/
