/* BSW-13093 */
#ifndef RBA_DEMOBDBASIC_DISTANCETIMEPID_H
#define RBA_DEMOBDBASIC_DISTANCETIMEPID_H

#define DEM_START_SEC_CODE
#include "Dem_MemMap.h"

#if((DEM_CFG_OBD_SUPPORT == DEM_OBD_MASTER_ECU) && (DEM_CFG_OBD_PID21_CENTRAL != DEM_CFG_OBD_PID21_CENTRAL_OFF))
/**
 **********************************************************************************************************************
 * Dem_GetDataOfPID21
 * 
 * \brief Service to get the value of PID $21 from the Dem by a software component.
 * API is needed in OBD-relevant ECUs only.
 * \note The value received in the input buffer is expected to be in Km units and is converted to m units 
 * for internal storage.
 *
 * \param[in]   uint8*          PID21value          Content of PID $21 as raw hex value.
 * 
 * \return      Std_ReturnType                      Always E_OK is returned, E_NOT_OK will only be returned if a NULL_PTR
 *                                                  is passed
 */
/*MR12 RULE 8.5 VIOLATION: the function declaration is also generated by the RTE if it is configured, this does not cause any issues*/
/* [$DD_BSWCODE 30818] */
Std_ReturnType Dem_GetDataOfPID21(uint8* PID21value);

#endif

#if((DEM_CFG_OBD_PID31_CENTRAL != DEM_CFG_OBD_PID31_CENTRAL_OFF) && (DEM_CFG_OBD_SUPPORT == DEM_OBD_MASTER_ECU))
/**
 **********************************************************************************************************************
 * Dem_GetDataOfPID31
 * 
 * \brief Service to get the value of PID $31 from the Dem by a software component.
 * API is needed in OBD-relevant ECUs only.
 * \note The value received in the input buffer is expected to be in Km units and is converted to m units 
 * for internal storage.
 *
 * \param[in]   uint8*          PID31value          Content of PID $31 as raw hex value.
 * 
 * \return      Std_ReturnType                      Always E_OK is returned, E_NOT_OK will only be returned if a NULL_PTR
 *                                                  is passed
 */
/*MR12 RULE 8.5 VIOLATION: the function declaration is also generated by the RTE if it is configured, this does not cause any issues*/
/* [$DD_BSWCODE 30819] */
Std_ReturnType Dem_GetDataOfPID31(uint8* PID31value);

#endif

#if((DEM_CFG_OBD_SUPPORT == DEM_OBD_MASTER_ECU) && (DEM_CFG_OBD_PID4D_CENTRAL != DEM_CFG_OBD_PID4D_CENTRAL_OFF))
/**
 **********************************************************************************************************************
 * Dem_GetDataOfPID4D
 * 
 * \brief Service to get the value of PID $4D from the Dem by a software component.
 * API is needed in OBD-relevant ECUs only.
 * \note The value received in the input buffer is expected to be in 100ms units and is converted to hour units 
 * for internal storage.
 *
 * \param[in]   uint8*          PID4Dvalue          Content of PID $4D as raw hex value.
 * 
 * \return      Std_ReturnType                      Always E_OK is returned, E_NOT_OK will only be returned if a NULL_PTR
 *                                                  is passed
 */
/*MR12 RULE 8.5 VIOLATION: the function declaration is also generated by the RTE if it is configured, this does not cause any issues*/ 
/* [$DD_BSWCODE 30816] */
Std_ReturnType Dem_GetDataOfPID4D(uint8* PID4Dvalue);

#endif

#if((DEM_CFG_OBD_SUPPORT == DEM_OBD_MASTER_ECU) && (DEM_CFG_OBD_PID4E_CENTRAL != DEM_CFG_OBD_PID4E_CENTRAL_OFF))
/**
 **********************************************************************************************************************
 * Dem_GetDataOfPID4E
 * 
 * \brief Service to get the value of PID $4E from the Dem by a software component.
 * API is needed in OBD-relevant ECUs only.
 * \note The value received in the input buffer is expected to be in 100ms units and is converted to hour units 
 * for internal storage.
 *
 * \param[in]   uint8*          PID4Evalue          Content of PID $4E as raw hex value.
 * 
 * \return      Std_ReturnType                      Always E_OK is returned, E_NOT_OK will only be returned if a NULL_PTR
 *                                                  is passed
 */
/*MR12 RULE 8.5 VIOLATION: the function declaration is also generated by the RTE if it is configured, this does not cause any issues*/ 
/* [$DD_BSWCODE 30817] */
Std_ReturnType Dem_GetDataOfPID4E(uint8* PID4Evalue);

#endif


#if ((DEM_CFG_OBD_PID21_CENTRAL != DEM_CFG_OBD_PID21_CENTRAL_OFF) && (DEM_CFG_OBD_SUPPORT == DEM_OBD_PRIMARY_ECU))
/**
 **********************************************************************************************************************
 * Dem_SetDataOfPID21
 * 
 * \brief Interface to set the value stored in the internal PID $21 counter.
 * \note The value received in the input buffer is expected to be in Km units and is converted to m units 
 * for internal storage. Caller should ensure buffer referenced by PID21value is of the correct size.
 *
 * \param[in]   const uint8*    PID21value          Input buffer with expected size of at least 2 bytes
 * 
 * \return      Std_ReturnType                      Internal PID $21 counter set status
 */
/*MR12 RULE 8.5 VIOLATION: the function declaration is also generated by the RTE if it is configured, this does not cause any issues*/ 
/* [$DD_BSWCODE 30822] */
Std_ReturnType Dem_SetDataOfPID21(const uint8* PID21value);

#endif

#if ((DEM_CFG_OBD_PID31_CENTRAL != DEM_CFG_OBD_PID31_CENTRAL_OFF) && (DEM_CFG_OBD_SUPPORT == DEM_OBD_PRIMARY_ECU))
/**
 **********************************************************************************************************************
 * Dem_SetDataOfPID31
 * 
 * \brief Service to set the value of PID $31 in the Dem by a software component.
 * API is needed in OBD-relevant ECUs only..
 * \note The value received in the input buffer is expected to be in Km units and is converted to m units 
 * for internal storage.
 *
 * \param[in]   const uint8*    PID31value          Buffer containing the contents of PID $31.
 *                                                  The buffer is provided by the Dcm with the appropriate
 *                                                  size, i.e. during configuration, the Dcm identifies
 *                                                  the required size from the largest PID in order to
 *                                                  configure a PIDBuffer.
 * 
 * \return      Std_ReturnType                      Always E_OK is returned, E_NOT_OK will only be returned if a NULL_PTR
 *                                                  is passed
 */
/*MR12 RULE 8.5 VIOLATION: the function declaration is also generated by the RTE if it is configured, this does not cause any issues*/ 
/* [$DD_BSWCODE 30823] */
Std_ReturnType Dem_SetDataOfPID31(const uint8* PID31value);

#endif

#if ((DEM_CFG_OBD_PID4D_CENTRAL != DEM_CFG_OBD_PID4D_CENTRAL_OFF) && (DEM_CFG_OBD_SUPPORT == DEM_OBD_PRIMARY_ECU))
/**
 **********************************************************************************************************************
 * Dem_SetDataOfPID4D
 * 
 * \brief Interface to set the value stored in the internal PID $4D counter.
 * \note The value received in the input buffer is expected to be in hour units and is converted to 100ms units 
 * for internal storage. Caller should ensure buffer referenced by PID4Dvalue is of the correct size.
 *
 * \param[in]   const uint8*    PID4Dvalue          Input buffer with expected size of at least 2 bytes
 * 
 * \return      Std_ReturnType                      Internal PID $4D counter set status
 */
/*MR12 RULE 8.5 VIOLATION: the function declaration is also generated by the RTE if it is configured, this does not cause any issues*/ 
/* [$DD_BSWCODE 31774] */
Std_ReturnType Dem_SetDataOfPID4D(const uint8* PID4Dvalue);

#endif

#if ((DEM_CFG_OBD_PID4E_CENTRAL != DEM_CFG_OBD_PID4E_CENTRAL_OFF) && (DEM_CFG_OBD_SUPPORT == DEM_OBD_PRIMARY_ECU))
/**
 **********************************************************************************************************************
 * Dem_SetDataOfPID4E
 * 
 * \brief Interface to set the value stored in the internal PID $4E counter.
 * \note The value received in the input buffer is expected to be in hour units and is converted to 100ms units 
 * for internal storage. Caller should ensure buffer referenced by PID4Dvalue is of the correct size.
 *
 * \param[in]   const uint8*    PID4Evalue          Input buffer with expected size of at least 2 bytes
 * 
 * \return      Std_ReturnType                      Internal PID $4E counter set status
 */
/*MR12 RULE 8.5 VIOLATION: the function declaration is also generated by the RTE if it is configured, this does not cause any issues*/ 
/* [$DD_BSWCODE 31775] */
Std_ReturnType Dem_SetDataOfPID4E(const uint8* PID4Evalue);

#endif

#define DEM_STOP_SEC_CODE
#include "Dem_MemMap.h"

#endif
/* END BSW-13093 */

