/******************************************************************************/
/*                                                                            */
/* !Layer           : STD                                                     */
/*                                                                            */
/* !Component       : MEMMAP                                                  */
/* !Description     : MEMMAP Configuration                                    */
/*                                                                            */
/* !File            : SBC_MEMMAP.H                                          */
/*                                                                            */
/* !Scope           : Public                                                  */
/*                                                                            */
/* !Target          :                                                         */
/*                                                                            */
/* !Vendor          : invt                                                    */
/*                                                                            */
/* Coding language  : C                                                       */
/*                                                                            */
/* COPYRIGHT 2009 invt                                                        */
/* all rights reserved                                                        */
/*                                                                            */
/******************************************************************************/
/* SVN Information                                                           */
/* $Archive::                                                                $*/
/* $Revision::            $$Author::                  $$Date::               $*/
/******************************************************************************/
/* 08/23/22, 15:34:08: generated by Genecode  v2.6.0.0                        */
/* From Source Template : MSN_MEMMAP_H.TPL                                    */
/******************************************************************************/



/******************************************************************************/
/*          MEMMAP selected mode:  SAFE                                       */
/******************************************************************************/
#define MEMMAP_ERROR

/* The following if is used only due to automatic generation */
#if !defined MEMMAP_ERROR

/* Project section mappings */
/* !Comment: SBC Section allocation */
#elif defined   SBC_START_SEC_CODE
   #undef  SBC_START_SEC_CODE
   #define START_SEC_CODE_SECTION
#elif defined   SBC_STOP_SEC_CODE
   #undef  SBC_STOP_SEC_CODE
   #define STOP_SEC_CODE_SECTION

#elif defined   SBC_START_SEC_VAR_UNSPECIFIED
   #undef  SBC_START_SEC_VAR_UNSPECIFIED
   #define START_SEC_VAR_UNSPECIFIED_SECTION
#elif defined   SBC_STOP_SEC_VAR_UNSPECIFIED
   #undef  SBC_STOP_SEC_VAR_UNSPECIFIED
   #define STOP_SEC_VAR_UNSPECIFIED_SECTION

#elif defined   SBC_START_SEC_VAR_CLEARED_8BIT
   #undef  SBC_START_SEC_VAR_CLEARED_8BIT
   #define START_SEC_VAR_CLEARED_8BIT_SECTION
#elif defined   SBC_STOP_SEC_VAR_CLEARED_8BIT
   #undef  SBC_STOP_SEC_VAR_CLEARED_8BIT
   #define STOP_SEC_VAR_CLEARED_8BIT_SECTION

#elif defined   SBC_START_SEC_VAR_CLEARED_16BIT
   #undef  SBC_START_SEC_VAR_CLEARED_16BIT
   #define START_SEC_VAR_CLEARED_16BIT_SECTION
#elif defined   SBC_STOP_SEC_VAR_CLEARED_16BIT
   #undef  SBC_STOP_SEC_VAR_CLEARED_16BIT
   #define STOP_SEC_VAR_CLEARED_16BIT_SECTION
   
#elif defined SBC_CALIB_START_SEC_CONST_32
  #define  CALIB_START_SEC_CONST_32
  #include "MemMap.h"
   #undef SBC_CALIB_START_SEC_CONST_32
   #undef  MEMMAP_ERROR
#elif defined SBC_CALIB_STOP_SEC_CONST_32
  #define  CALIB_STOP_SEC_CONST_32
  #include "MemMap.h"
   #undef SBC_CALIB_STOP_SEC_CONST_32
   #undef  MEMMAP_ERROR


#endif

/* ECU specific section mappings */
#ifndef MEMMAP_START_DONE

/* The following if is used only due to automatic generation */

#if FALSE
/* !Comment: SEC_CODE Start Section treatment */
   #elif defined   START_SEC_CODE_SECTION
	  

      #pragma section ".text" ax

      #undef  MEMMAP_ERROR
      #define MEMMAP_START_DONE

/* !Comment: SEC_VAR_UNSPECIFIED Start Section treatment */
   #elif defined   START_SEC_VAR_UNSPECIFIED_SECTION
	  
      #undef  MEMMAP_ERROR
      #define MEMMAP_START_DONE

/* !Comment: SEC_VAR_CLEARED_8BIT Start Section treatment */
   #elif defined   START_SEC_VAR_CLEARED_8BIT_SECTION
	  

      #pragma section ".bss" awB

      #undef  MEMMAP_ERROR
      #define MEMMAP_START_DONE

/* !Comment: SEC_VAR_CLEARED_16BIT Start Section treatment */
   #elif defined   START_SEC_VAR_CLEARED_16BIT_SECTION
	  

      #pragma section ".bss" awB

      #undef  MEMMAP_ERROR
      #define MEMMAP_START_DONE


   #endif

#else   /* if MEMMAP_START_DONE is not defined */

/* The following if is used only due to automatic generation */

#if FALSE
/* !Comment: SEC_CODE Stop Section treatment */
   #elif defined   STOP_SEC_CODE_SECTION && defined  START_SEC_CODE_SECTION
	  

      #pragma section

      #undef START_SEC_CODE_SECTION
      #undef STOP_SEC_CODE_SECTION
      #undef MEMMAP_ERROR
      #undef MEMMAP_START_DONE

/* !Comment: SEC_VAR_UNSPECIFIED Stop Section treatment */
   #elif defined   STOP_SEC_VAR_UNSPECIFIED_SECTION && defined  START_SEC_VAR_UNSPECIFIED_SECTION
	  
      #undef START_SEC_VAR_UNSPECIFIED_SECTION
      #undef STOP_SEC_VAR_UNSPECIFIED_SECTION
      #undef MEMMAP_ERROR
      #undef MEMMAP_START_DONE

/* !Comment: SEC_VAR_CLEARED_8BIT Stop Section treatment */
   #elif defined   STOP_SEC_VAR_CLEARED_8BIT_SECTION && defined  START_SEC_VAR_CLEARED_8BIT_SECTION
	  

      #pragma section

      #undef START_SEC_VAR_CLEARED_8BIT_SECTION
      #undef STOP_SEC_VAR_CLEARED_8BIT_SECTION
      #undef MEMMAP_ERROR
      #undef MEMMAP_START_DONE

/* !Comment: SEC_VAR_CLEARED_16BIT Stop Section treatment */
   #elif defined   STOP_SEC_VAR_CLEARED_16BIT_SECTION && defined  START_SEC_VAR_CLEARED_16BIT_SECTION
	  

      #pragma section

      #undef START_SEC_VAR_CLEARED_16BIT_SECTION
      #undef STOP_SEC_VAR_CLEARED_16BIT_SECTION
      #undef MEMMAP_ERROR
      #undef MEMMAP_START_DONE


   #endif
#endif

#if defined MEMMAP_ERROR
   #error MEMMAP-E201 : Bad memory allocation into SBC_MemMap.h
#endif


/*------------------------------- end of file --------------------------------*/

